// Taháky ke kapitolám – Bc. 2.–3. ročník: Mapování 1 a 2, Katastr 1 a 2, Pozemkové úpravy,
// Matematická kartografie, Kartografie 1, GIS 1, Inženýrská geodézie 1, Výuka v terénu.

export default {
  bea011: {
    intro: 'Mapování velkých měřítek od bodového pole přes podrobné měření a náčrt až po hotovou mapu. Je to každodenní chleba geodeta – účelové mapy, podklady pro projekty i DTM kraje.',
    points: [
      'Referenční systémy a státní mapová díla stanoví nařízení vlády 430/2006 Sb. (S-JTSK, Bpv, ETRS89).',
      'Mapa velkého měřítka má měřítko 1 : 5 000 a větší.',
      'Vrstevnice se interpolují lineárně jen mezi body se stálým sklonem terénu.',
      'Spádnice protíná vrstevnice kolmo ve směru největšího spádu.',
      'Měřický náčrt vzniká v terénu současně s měřením a neobsahuje souřadnice.',
      'Opravy délky: atmosférická → na vodorovnou → do nulového horizontu → do zobrazení S-JTSK.',
      'Délkové zkreslení S-JTSK je v ČR zhruba −10 až +14 cm/km.',
      'ČSN 01 3410 má 5 tříd přesnosti; nejběžnější je 3. třída s m_xy = 0,14 m.',
      'Kódy kvality 3–5 mají body určené měřením, 6–8 body z grafické mapy.',
      'DTM kraje vedou kraje (zákon 47/2020 Sb.), data se předávají ve formátu JVF DTM.',
    ],
    formulas: [
      ['Sklon v procentech', 'i = Δh / d · 100 %'],
      ['Interpolace vrstevnice', 'x = (H_v − H_A) / (H_B − H_A) · D'],
      ['Vodorovná délka', 'd = s · sin z'],
      ['Redukce do nulového horizontu', 'Δd = −d · H / R'],
      ['Polární metoda', 'Y_P = Y_A + d · sin σ;  X_P = X_A + d · cos σ'],
    ],
    terms: [
      ['Oměrná míra', 'Měřená vzdálenost sousedních podrobných bodů pro kontrolu.'],
      ['Údolnice', 'Spojnice nejnižších bodů údolí.'],
      ['Sedlo', 'Snížení hřbetu mezi dvěma vrcholy; stýkají se v něm dvě hřbetnice a dvě údolnice.'],
      ['ZABAGED', 'Digitální topografický model území ČR (spravuje ZÚ).'],
      ['DMR 5G', 'Model holého terénu z leteckého laserového skenování, m_H ≈ 0,18 m.'],
      ['m_xy', 'Střední souřadnicová chyba bodu.'],
    ],
    tip: 'Toti radí: čísla bodů v náčrtu a v přístroji kontroluj průběžně – záměnu bodů výpočet neodhalí, oměrná míra ano.',
  },

  bea017: {
    intro: 'Obnova katastrálního operátu a dějiny mapování a pozemkových evidencí od stabilního katastru po KN. Bez znalosti historie nepochopíš, proč má dnešní katastrální mapa tak různou kvalitu.',
    points: [
      'Obnova KO: novým mapováním, na podkladě výsledků PÚ, nebo přepracováním SGI.',
      'Novým mapováním nebo z PÚ vzniká DKM; přepracováním analogové mapy vzniká KMD.',
      'KMD přebírá přesnost původní grafické mapy (kódy kvality 6–8).',
      'Body PPBP se určují s m_xy ≤ 0,06 m, podrobné body při obnově zpravidla s kódem kvality 3.',
      'Obnovený operát se před vyhlášením platnosti vyloží k veřejnému nahlédnutí.',
      'Číslo podrobného bodu = číslo ZPMZ + pořadové číslo (např. 245-12).',
      'Stabilní katastr: patent 1817, mapy 1 : 2 880, měřický stůl, účel daňový.',
      'Soustavy stabilního katastru: Gusterberg (Čechy) a Svatý Štěpán (Morava a Slezsko).',
      'Evidence: stabilní k. 1817 → evidenční 1883 → pozemkový 1927 → JEP 1956 → EN 1964 → KN 1993.',
    ],
    formulas: [
      ['Polární metoda – Y', 'Y_P = Y_A + d · sin σ_AP'],
      ['Polární metoda – X', 'X_P = X_A + d · cos σ_AP'],
      ['Měřítko sáhové mapy', '1″ = 40 sáhů → 40 · 72 = 2 880'],
    ],
    terms: [
      ['DKM', 'Digitální katastrální mapa s body určenými měřením v S-JTSK.'],
      ['KMD', 'Katastrální mapa digitalizovaná z analogové mapy.'],
      ['PPBP', 'Podrobné polohové bodové pole.'],
      ['ZPMZ', 'Záznam podrobného měření změn; číslován průběžně v k. ú.'],
      ['VFK', 'Výměnný formát katastru – textový, s daty SGI i SPI.'],
      ['Reambulance', 'Revize a doplnění map stabilního katastru (1869–1881).'],
      ['JEP', 'Jednotná evidence půdy – evidovala užívání, ne vlastnictví.'],
    ],
    tip: 'Toti radí: než se připojíš na bod PPBP, udělej revizi – zničený nebo pohnutý bod ti pokazí celé měření.',
  },

  bea016: {
    intro: 'Základy katastru nemovitostí: pojmy, historické míry a pozemkové knihy, organizace resortu a obsah katastrálního operátu. Na tom stojí každý geometrický plán i každý dotaz klienta.',
    points: [
      'Katastr rozlišuje 10 druhů pozemků; způsob využití druh jen upřesňuje.',
      'Stavební parcela je v druhu zastavěná plocha a nádvoří; na LV má zkratku „st.“.',
      'Od 2014 platí superficies solo cedit – stavba bývá součástí pozemku.',
      'KO tvoří SGI, SPI, dokumentace výsledků šetření a měření, souhrnné přehledy o půdním fondu a sbírka listin.',
      'SGI = katastrální mapa a souřadnice; SPI = popisné údaje (vlastníci, práva).',
      'Katastrálních úřadů je 14 (jeden v kraji), ZKI je odvolacím a dozorovým orgánem.',
      'Údaje z KN poskytuje vyhláška 358/2013 Sb.; výpis z LV získá kdokoli.',
      'Pozemkové knihy vedly soudy, deskové statky se zapisovaly do zemských desek.',
      'Geometrický plán je technický podklad k listině – sám vlastnictví nemění.',
    ],
    formulas: [
      ['Vídeňský sáh', '1 sáh = 6 stop = 72 palců ≈ 1,896 484 m'],
      ['Čtvereční sáh', '1 čtv. sáh ≈ 3,5966 m²'],
      ['Katastrální jitro', '1 jitro = 1 600 čtv. sáhů ≈ 5 754,6 m²'],
      ['Převod výměry', 'P [m²] = (jitra · 1 600 + čtv. sáhy) · 3,5966'],
    ],
    terms: [
      ['Katastrální území', 'Místopisně uzavřený soubor nemovitostí.'],
      ['ÚOZI', 'Úředně oprávněný zeměměřický inženýr.'],
      ['ISKN', 'Informační systém katastru nemovitostí.'],
      ['ČÚZK', 'Ústřední orgán státní správy zeměměřictví a katastru.'],
      ['ZÚ', 'Zeměměřický úřad – ZABAGED, bodová pole, ZM ČR.'],
      ['WSDP', 'Webová služba pro podporu GP – podklady i předložení plánu.'],
      ['Intabulace', 'Vznik věcného práva zápisem do veřejné knihy.'],
    ],
    tip: 'Toti radí: Nahlížení do KN je jen informativní – pro úřední účely vždy ověřený výpis z LV.',
  },

  bea022: {
    intro: 'Pokročilá agenda katastru: druhy geometrických plánů, zjednodušená evidence, zápisy práv, opravy chyb a vytyčení hranic. Přesně s tím se ÚOZI potkává denně.',
    points: [
      'GP se vyhotovuje např. pro rozdělení pozemku, vyznačení budovy, věcné břemeno k části pozemku nebo doplnění parcely ZE.',
      'Výměra se počítá ze souřadnic lomových bodů a eviduje se v celých m².',
      'Parcely ZE nejsou v katastrální mapě; vycházejí z map PK nebo EN.',
      'Vklad (ze smlouvy) je konstitutivní a působí k okamžiku podání návrhu.',
      'Vklad lze povolit nejdříve po 20 dnech od vyrozumění vlastníka.',
      'Záznam zapisuje práva vzniklá ze zákona či rozhodnutím; poznámka má informativní význam.',
      'Opravou chyby nelze měnit právní vztahy; řízení se zahajuje na návrh i z moci úřední.',
      'Vytyčení hranice vlastnictví nemění; výsledkem je protokol s vytyčovacím náčrtem.',
      'GP ověřuje ÚOZI, potvrzuje katastrální úřad; znalce jmenuje Ministerstvo spravedlnosti.',
    ],
    formulas: [
      ['Výměra ze souřadnic', '2P = Σ X_i · (Y_i+1 − Y_i−1)'],
      ['Vytyčovací úhel', 'ω = σ_SP − σ_SO'],
      ['Vytyčovací délka', 'd = √(ΔY² + ΔX²)'],
    ],
    terms: [
      ['Vklad', 'Zápis práva ze smlouvy; právo vzniká až zápisem.'],
      ['Záznam', 'Deklaratorní zápis práva, které už vzniklo (např. dědictví).'],
      ['Poznámka', 'Upozornění, např. na exekuci nebo spornost zápisu.'],
      ['Plomba', 'Vyznačení, že práva jsou dotčena probíhající změnou.'],
      ['ZE', 'Zjednodušená evidence – parcely nezobrazené v katastrální mapě.'],
      ['Identifikace parcel', 'Porovnání parcel KN s parcelami dřívějších evidencí.'],
      ['Nezbytná cesta', 'Přístup přes cizí pozemek povolený soudem podle OZ.'],
    ],
    tip: 'Toti radí: před vytyčením si ověř orientaci na druhý známý bod – pootočená osnova posune všechny lomové body.',
  },

  bpu: {
    intro: 'Pozemkové úpravy podle zákona 139/2002 Sb. nově uspořádají, scelí a zpřístupní pozemky a zároveň řeší erozi, vodu a ekologickou stabilitu. Výsledkem je nová DKM bez parcel ZE.',
    points: [
      'PÚ řídí Státní pozemkový úřad, řízení vede krajský pozemkový úřad.',
      'KoPÚ řeší zpravidla celé k. ú., JPÚ jen část území nebo dílčí problém.',
      'Sbor zástupců zastupuje vlastníky a spolupracuje na návrhu.',
      'Plán společných zařízení se navrhuje před novým uspořádáním pozemků.',
      'Návrh se schválí při souhlasu vlastníků alespoň 60 % výměry pozemků v PÚ.',
      'Přiměřenost: cena ±4 %, výměra ±10 %, vzdálenost ±20 %; jinak jen se souhlasem vlastníka.',
      'Pozemky pro společná zařízení se berou přednostně ze státní a obecní půdy.',
      'Nový stav se zapisuje záznamem na základě rozhodnutí o výměně vlastnických práv.',
      'Geodetické práce pro PÚ ověřuje ÚOZI; odvolání řeší ústředí SPÚ.',
    ],
    formulas: [
      ['Nejmenší přiměřená výměra', 'P_min = P_nárok · (1 − 0,10)'],
      ['Rozsah přiměřené ceny', 'C_nový = C_nárok · (1 ± 0,04)'],
    ],
    terms: [
      ['KoPÚ', 'Komplexní pozemková úprava.'],
      ['JPÚ', 'Jednoduchá pozemková úprava.'],
      ['PSZ', 'Plán společných zařízení (cesty, protierozní a vodohospodářská opatření, ÚSES).'],
      ['BPEJ', '5místný kód: klimatický region, HPJ, sklonitost a expozice, skeletovitost a hloubka.'],
      ['Nárokový list', 'Původní pozemky vlastníka s výměrou, cenou a vzdáleností.'],
      ['Biokoridor', 'Propojení biocenter umožňující migraci.'],
      ['Bilancování', 'Porovnání nároků se stavem po návrhu.'],
    ],
    tip: 'Toti radí: nejdřív cesty a společná zařízení, potom pozemky – každý nový pozemek musí mít přístup.',
  },

  mkart: {
    intro: 'Jak převést zakřivenou Zemi do roviny a co přitom zkreslíme. Bez toho nepochopíš Křovákovo zobrazení ani UTM, se kterými denně pracuješ.',
    points: [
      'Referenční plochy: elipsoid → koule → rovina (případně přes kužel či válec).',
      'Ortodroma leží na hlavní kružnici, loxodroma protíná poledníky pod stálým úhlem.',
      'V Mercatorově zobrazení je loxodroma přímka, v gnómonickém ortodroma.',
      'Konformní zobrazení zachovává úhly, ekvivalentní plochy; obojí současně nelze.',
      'Tissotova indikatrix je elipsa; u konformního zobrazení kružnice (a = b).',
      'Sečné zobrazení má dvě nezkreslené linie a menší extrémy zkreslení.',
      'Křovák: dvojité kuželové konformní zobrazení v obecné poloze, X k jihu, Y k západu.',
      'Zmenšení poloměru koeficientem 0,9999 dává v ČR zkreslení asi −10 až +14 cm/km.',
      'UTM má na středním poledníku 0,9996; ČR leží v pásech 33 a 34.',
    ],
    formulas: [
      ['Sférický exces', 'ε = P / R² · ρ″  (ρ″ ≈ 206 265″)'],
      ['Legendreova věta', 'α′ = α − ε/3'],
      ['Délka oblouku 1°', 'd = 2πR / 360'],
      ['Délkové zkreslení', 'm = ds′ / ds'],
      ['Zkreslení v cm/km', '(m − 1) · 100 000 cm/km'],
      ['Plošné zkreslení', 'P = a · b'],
      ['Mercator na kouli', 'm = 1 / cos φ;  P = m²'],
    ],
    terms: [
      ['Ortodroma', 'Nejkratší spojnice dvou bodů po hlavní kružnici.'],
      ['Loxodroma', 'Křivka se stálým azimutem.'],
      ['Tissotova indikatrix', 'Elipsa – obraz nekonečně malé kružnice.'],
      ['Ekvidistantní', 'Nezkresluje délky v jedné soustavě směrů.'],
      ['Nepravé zobrazení', 'Poledníky jsou obecné křivky (Sanson, Mollweide, Bonne).'],
      ['Gaussova koule', 'Konformní obraz elipsoidu, v Křovákovi s nezkreslenou rovnoběžkou 49°30′.'],
    ],
    tip: 'Toti radí: pamatuj si „konformní = kružnice, ekvivalentní = a · b = 1“ – polovina zkouškových otázek je vyřešená.',
  },

  kart1: {
    intro: 'Kartografie jako tvorba a čtení map: obsah, kompozice, znakový jazyk, generalizace a kartometrie. Dobrá mapa musí být přesná a zároveň čitelná.',
    points: [
      'Mapa je zmenšený, generalizovaný obraz Země v rovině podle matematického zákona.',
      'Plán zobrazuje malé území a zakřivení Země zanedbává.',
      'Topografický obsah mapy tvoří polohopis, výškopis a popis.',
      'Vnitřní rám ohraničuje mapové pole; tiráž, legenda a nomenklatura jsou mimorámové údaje.',
      'Grafické měřítko platí i po zmenšení kopie, číselné ne.',
      'Kartogram vyjadřuje relativní hodnoty vztažené k ploše, kartodiagram absolutní hodnoty.',
      'Generalizace: výběr, zjednodušení, slučování, posun, zveličení; příčinou je měřítko a účel.',
      'Stínování je plastické, ale neměřitelné; výšky nesou vrstevnice a kóty.',
      'Nejpodrobnější ZM ČR má 1 : 10 000; SMO-5 je Státní mapa 1 : 5 000 odvozená.',
      'Klaudyán – mapa Čech 1518; Komenský – mapa Moravy 1627; Müller – Morava 1716, Čechy 1720.',
    ],
    formulas: [
      ['Skutečná délka z mapy', 'D = l_mapa · M'],
      ['Délka na mapě', 'l = D / M'],
      ['Töpferův zákon výběru', 'n_F = n_A · √(M_A / M_F)'],
      ['Grafická přesnost', 'D_min = 0,1 mm · M'],
      ['Hustota zalidnění', 'h = počet obyvatel / plocha [obyv./km²]'],
    ],
    terms: [
      ['Tiráž', 'Údaje o vydání (vydavatel, rok).'],
      ['Nomenklatura', 'Jednoznačné označení listu v kladu.'],
      ['Kilometrová síť', 'Síť rovinných pravoúhlých souřadnic.'],
      ['Kartodiagram', 'Absolutní hodnoty diagramy v územních jednotkách.'],
      ['Zveličení', 'Zvětšení malého, ale významného objektu.'],
      ['Srážka mapy', 'Změna rozměru mapového listu (papíru).'],
      ['Kartometrie', 'Měření délek, ploch a úhlů na mapách.'],
    ],
    tip: 'Toti radí: u převodu měřítka si nejdřív převeď jednotky – mm · M = mm, teprve pak dělíš tisícem na metry.',
  },

  bea020: {
    intro: 'Geografické informační systémy: datové modely, prostorové databáze, topologie, webové služby a analýzy. GIS propojuje geodetická data s atributy a otázkami „kde a proč“.',
    points: [
      'GIS tvoří hardware, software, data, lidé a metody; objekt má geometrii a atributy.',
      'Otcem GIS je Roger Tomlinson (CGIS), ranou prostorovou analýzou je mapa Johna Snowa.',
      'Základní registry jsou 4; RÚIAN i ISKN spravuje ČÚZK.',
      'INSPIRE (2007/2/ES) buduje evropskou infrastrukturu prostorových informací.',
      'EPSG:5514 je S-JTSK / Krovak East North, EPSG:4326 je WGS 84.',
      'Vektor pro diskrétní objekty, rastr pro spojité jevy; přesnost rastru dává velikost buňky.',
      'Špagetový model neukládá vztahy, topologický ano (sousednost, spojitost, obsažení).',
      'WMS vrací obrázek, WMTS dlaždice, WFS vektory, WCS rastrová data, CSW metadata.',
      'Delaunayova triangulace: kružnice opsaná trojúhelníku neobsahuje jiný bod.',
      'IDW váží hodnoty tak, že vliv klesá se vzdáleností.',
    ],
    formulas: [
      ['Sklon svahu', 'α = arctg(Δh / d)'],
      ['Sklon v procentech', 'i = Δh / d · 100 %'],
      ['Pořadí SQL', 'SELECT … FROM … WHERE … GROUP BY … ORDER BY'],
    ],
    terms: [
      ['PostGIS', 'Prostorové rozšíření PostgreSQL (funkce ST_*).'],
      ['ST_Buffer', 'Vytvoří obalovou zónu kolem geometrie.'],
      ['WKT', 'Textový zápis geometrie, např. POINT(16.6 49.2).'],
      ['R-strom', 'Prostorový index nad ohraničujícími obdélníky (MBR).'],
      ['Nedotah', 'Linie končí těsně před tou, se kterou se má spojit.'],
      ['DE-9IM', 'Matice 3 × 3 popisující topologický vztah dvou geometrií.'],
      ['Fokální funkce', 'Hodnota buňky z okolí (klouzavé okno).'],
      ['Metadata', 'Data o datech – původ, přesnost, aktuálnost.'],
    ],
    tip: 'Toti radí: než spustíš prostorový dotaz, zkontroluj, že obě vrstvy mají stejný EPSG – jinak se nic neprotne.',
  },

  bea021: {
    intro: 'Inženýrská geodézie ve výstavbě: rozbory přesnosti, vytyčení úhlů, délek a výšek, metody polohového vytyčení a vytyčovací sítě. Tady se projekt mění ve skutečnost.',
    points: [
      'Rozbor a priori se dělá před měřením – od požadované přesnosti k volbě metody a přístroje.',
      'Náhodné chyby zmenší průměrování, systematické jen metoda nebo opravy.',
      'U polárního vytyčení roste příčná chyba lineárně se vzdáleností.',
      'Chyba podkladu se promítne do vytyčeného bodu, proto musí být síť přesnější.',
      'Ideální úhel protnutí je kolem 100 gon; protínání z délek má dvě řešení.',
      'Dvě polohy dalekohledu vyloučí kolimační chybu, dálkoměr potřebuje teplotu a tlak.',
      'Přesnost vytyčování staveb řeší ČSN 73 0420.',
      'Primární systém tvoří hlavní body a osy stavby; osy se zajišťují na lavičkách.',
      'Přechodnice (klotoida) má křivost rostoucí lineárně s délkou.',
    ],
    formulas: [
      ['Chyba průměru', 'σ_x̄ = σ / √n'],
      ['Mezní odchylka', 'δ = u_p · σ'],
      ['Polohová chyba polárního vytyčení', 'm_p = √(m_d² + (d · m_ω)²),  m_ω v rad'],
      ['Posun při zpřesněném vytyčení úhlu', 'q = d · Δω'],
      ['Čtení na lati při vytyčení výšky', 'l = H_R + l_R − H_P'],
      ['Šikmá délka ve svahu', 's = d / cos α'],
      ['Délka tečny oblouku', 't = R · tg(α / 2)'],
      ['Protínání vpřed', 'd_AP = d_AB · sin β / sin(α + β)'],
    ],
    terms: [
      ['Vytyčovací prvky', 'Úhel ω = σ_SP − σ_SO a vodorovná délka d.'],
      ['Volné stanovisko', 'Stanovisko určené měřením na aspoň dva známé body.'],
      ['Provažovač', 'Přístroj pro vytyčení svislice.'],
      ['Stavební lavička', 'Zajištění os mimo prostor výkopu.'],
      ['Staničení', 'Vzdálenost bodu od začátku trasy po ose.'],
      ['Hlavní body oblouku', 'ZO, SO a KO; pomocí vrcholu tečen VB.'],
      ['Mikrosíť', 'Velmi přesná síť pro most nebo tunel.'],
    ],
    tip: 'Toti radí: úhlovou chybu převeď na radiány (cc · π / 2 000 000) a vynásob délkou – hned vidíš, kolik milimetrů tě stojí dlouhá záměra.',
  },

  vyuka: {
    intro: 'Praktické postupy z terénních cvičení: rekognoskace, postavení přístroje, polygon, nivelace, mapování a vytyčení stavby. Co se naučíš tady, uplatníš hned první den v práci.',
    points: [
      'Rekognoskace ověří stav bodů a viditelnost; zničený bod se neobnovuje odhadem.',
      'Stanovisko musí vidět na všechny body, mít je v dosahu a stát na pevném místě.',
      'Bublina libely putuje k nejvyššímu místu; při točení dvěma šrouby platí pravidlo levého palce.',
      'Osnova směrů: I. poloha vzad → vpřed, II. poloha vpřed → vzad.',
      'Překročený uzávěr se nerozděluje – najdi chybu a přeměř.',
      'Nivelační přístroj stojí uprostřed, ne nutně na spojnici latí; sudý počet sestav vyloučí rozdíl nul latí.',
      'Pohnutá nivelační podložka = měř znovu od posledního pevného bodu.',
      'Na novém stanovisku nejprve kontrolně zaměř známý bod.',
      'Vytyčený bod ověř nezávisle, ideálně z jiného stanoviska; u obdélníka porovnej úhlopříčky.',
    ],
    formulas: [
      ['Úhlový uzávěr (vnitřní úhly)', 'u = Σω − (n − 2) · 200 gon'],
      ['Převýšení na sestavě', 'Δh = vzad − vpřed'],
      ['Výška koncového bodu', 'H_K = H_Z + ΣΔh'],
      ['Kontrola zápisníku', 'ΣΔh = Σvzad − Σvpřed'],
      ['Mezní odchylka technické nivelace', 'Δ = 40 mm · √R [km]'],
      ['Vytyčovací úhel', 'ω = σ_SP − σ_SO'],
    ],
    terms: [
      ['Rekognoskace', 'Průzkum území, vyhledání bodů a ověření viditelnosti.'],
      ['Nucená centrace', 'Výměna přístroje a terčů v trojnožkách na místě.'],
      ['Přestavový bod', 'Dočasný bod mezi nivelačními sestavami.'],
      ['Oddíl', 'Úsek nivelace mezi dvěma nivelačními body.'],
      ['Excentrické vytyčení', 'Posunutý bod s popsaným směrem a vzdáleností.'],
      ['Výška ±0,000', 'Projektová výška podlahy přízemí v Bpv.'],
    ],
    tip: 'Toti radí: figurant je tvoje druhá polovina – dohodni si znamení a každou jeho hlášku (posunutá podložka, jiná výška tyče) hned zapiš.',
  },
};
