// Taháky ke kapitolám u11–u16 a VUT Bc. 1 (Geodézie 1–3, TCVP 1, Geodetické programy).

export default {
  u11: {
    intro: 'Elipsoid jako matematický model Země, jeho poloměry křivosti, geodetické a pravoúhlé souřadnice a zobrazení do roviny. Bez toho nelze převádět GNSS souřadnice do S-JTSK ani správně redukovat měření.',
    points: [
      'GRS80 i WGS84 mají a = 6 378 137 m, liší se jen nepatrně zploštěním (1/f = 298,257 222 101 vs. 298,257 223 563).',
      'Besselův elipsoid (a = 6 377 397,155 m, 1/f ≈ 299,152 812 8) je lokálně uložený a je základem S-JTSK.',
      'Geocentrický GRS80 je elipsoidem ETRS89, Krasovského elipsoid patří k S-42.',
      'Vždy platí M ≤ N; na rovníku N = a a M = b²/a, na pólu M = N = a²/b.',
      'Geodetická šířka φ je úhel normály k elipsoidu s rovinou rovníku; elipsoidická výška h se měří po normále.',
      'Mezi dvěma datumy se transformuje v pravoúhlých X, Y, Z sedmiprvkovou Helmertovou transformací.',
      'Sférický exces 1″ odpovídá trojúhelníku o ploše asi 200 km²; podle Legendra se každý úhel zmenší o ε/3.',
      'Křovákovo zobrazení je dvojité konformní kuželové: Bessel → Gaussova koule → šikmý kužel → rovina.',
      'Na základní rovnoběžce Křováka je m = 0,9999, tedy zkreslení −10 cm/km.',
      'V S-JTSK míří +X k jihu a +Y k západu, v ČR platí Y < X; UTM má m₀ = 0,9996 a ČR leží v pásech 33 a 34.',
    ],
    formulas: [
      ['Zploštění', 'f = (a − b) / a'],
      ['První excentricita', 'e² = (a² − b²) / a² = 2f − f²'],
      ['Meridiánový poloměr', 'M = a(1 − e²) / W³,  W = √(1 − e² sin² φ)'],
      ['Příčný poloměr', 'N = a / W'],
      ['Gaussův poloměr', 'R = √(M · N)'],
      ['φ, λ, h → ECEF', 'X = (N + h) cos φ cos λ,  Y = (N + h) cos φ sin λ,  Z = (N(1 − e²) + h) sin φ'],
      ['Sférický exces', 'ε″ = ρ″ · P / R²'],
      ['Zakřivení Země a refrakce', 'Δ = (1 − k) · d² / (2R),  k = 0,13'],
    ],
    terms: [
      ['Geodetika', 'nejkratší spojnice dvou bodů na ploše elipsoidu'],
      ['1. geodetická úloha', 'z bodu, délky a azimutu určit druhý bod a azimut α₂'],
      ['2. geodetická úloha', 'ze dvou bodů určit délku a oba azimuty'],
      ['Gaussova koule', 'náhradní koule, na kterou se elipsoid zobrazí konformně'],
      ['Konformní zobrazení', 'zachovává úhly, délky a plochy zkresluje'],
      ['ECEF', 'geocentrická pravoúhlá soustava pevně spojená se Zemí'],
      ['Soldnerovy souřadnice', 'x po osovém meridiánu, y po kolmé geodetice'],
    ],
    tip: 'Kontrola poloměrů GRS80: pro φ = 50° vychází M ≈ 6 373 km a N ≈ 6 391 km. Když ti vyjde něco jiného, máš kalkulačku v gonech místo ve stupních.',
  },

  u12: {
    intro: 'Tíhové pole Země, geoid a kvazigeoid, výškové systémy a gravimetrie. Díky nim lze z elipsoidické výšky z GNSS získat nadmořskou výšku v Bpv.',
    points: [
      'Tíže je výslednicí gravitace a odstředivého zrychlení z rotace Země; slapy se opravují zvlášť.',
      'Na hladinové ploše je konstantní potenciál W, ne tíže g; hladinové plochy nejsou rovnoběžné a sbíhají se k pólům.',
      'Normální tíže je na rovníku ≈ 9,780 m/s², na pólu ≈ 9,832 m/s²; s výškou klesá asi o 0,3086 mGal/m.',
      'Normální pole budí hladinový elipsoid (GRS80); poruchový potenciál je T = W − U.',
      'Undulace N je výška geoidu nad elipsoidem, výšková anomálie ζ výška kvazigeoidu nad elipsoidem.',
      'Kvazigeoid leží v ČR asi 42–48 m nad GRS80; převod GNSS výšek na Bpv se dělá modelem CR2005.',
      'Bpv používá normální výšky s počátkem v Kronštadtu; EVRS normální výšky s datem NAP (rámec EVRF2007).',
      'Součet převýšení v uzavřeném nivelačním polygonu není nulový ani bez chyb, protože hladinové plochy nejsou rovnoběžné.',
      'Absolutní balistický gravimetr měří volný pád ve vakuu, relativní pružinový jen rozdíly tíže s opravou o chod a slapy.',
      'Tížnicové odchylky dosahují v ČR jednotek úhlových vteřin a odpovídají sklonu geoidu vůči elipsoidu.',
    ],
    formulas: [
      ['Elipsoidická a normální výška', 'h = Hⁿ + ζ'],
      ['Elipsoidická a ortometrická výška', 'h = H + N'],
      ['Geopotenciální kóta', 'C = W₀ − W'],
      ['Výšky z geopotenciální kóty', 'H = C / ḡ,  Hⁿ = C / γ̄,  H_dyn = C / γ₄₅'],
      ['Fayeova anomálie (mGal, H v m)', 'Δg_F = g + 0,3086 · H − γ'],
      ['Bouguerova anomálie', 'Δg_B = Δg_F − 0,1119 · H  (ρ = 2 670 kg/m³)'],
      ['Složky tížnicové odchylky', 'ξ = Φ − φ,  η = (Λ − λ) cos φ'],
      ['Laplaceova rovnice', 'A − α = (Λ − λ) sin φ'],
    ],
    terms: [
      ['Tížnice', 'křivka kolmá ke všem hladinovým plochám'],
      ['Geoid', 'hladinová plocha nejlépe přimknutá ke střední hladině moří'],
      ['Kvazigeoid', 'pomocná plocha pro normální výšky, není hladinovou plochou'],
      ['Geopotenciální kóta', 'rozdíl potenciálu W₀ − W, nezávisí na dráze nivelace'],
      ['Tížnicová odchylka', 'úhel mezi tížnicí a normálou k elipsoidu'],
      ['Chod gravimetru', 'časová změna údaje, určená opakovaným měřením na výchozím bodě'],
      ['1 mGal', '10⁻⁵ m/s²'],
    ],
    tip: 'Z GNSS do Bpv: Hⁿ = h − ζ. Znaménko ověř selským rozumem – v ČR je výška z GNSS vždy asi o 45 m větší než nadmořská.',
  },

  u13: {
    intro: 'Chyby měření, zákon hromadění chyb a metoda nejmenších čtverců včetně hodnocení přesnosti a spolehlivosti. Je to matematický základ každého vyrovnání sítě.',
    points: [
      'Chyby jsou hrubé, systematické a náhodné; systematické se odstraňují kalibrací, opravami a metodou měření, ne průměrem.',
      'V intervalu ±1σ, ±2σ, ±3σ leží 68 %, 95 % a 99,7 % hodnot; chyba nad 3σ je podezřelá z hrubé chyby.',
      'Kovarianční matice je symetrická, na diagonále má rozptyly, mimo ni kovariance.',
      'Nelineární funkce se před použitím zákona hromadění linearizuje Taylorovým rozvojem (členy 1. řádu).',
      'Součet i rozdíl dvou nekorelovaných měření mají stejnou σ = √(σ₁² + σ₂²); n sestav dává σ₀ · √n.',
      'MNČ minimalizuje vᵀPv; počet nadbytečných měření je r = n − k.',
      'Kovarianční matice neznámých je Σ_x = m₀² · N⁻¹, kde Q_xx = N⁻¹.',
      'Volná síť má singulární matici N (defekt datumu), řeší se pseudoinverzí nebo podmínkami na datum.',
      'Podmínkových rovnic je n − k; vynásobení všech vah stejnou konstantou výsledek vyrovnání nezmění.',
      'Poloosy chybové elipsy jsou odmocniny vlastních čísel kovarianční matice bodu; standardní elipsa pokrývá jen asi 39 %.',
    ],
    formulas: [
      ['Směrodatná odchylka průměru', 'σ_x̄ = σ / √n'],
      ['Korelační koeficient', 'ρ = σ_xy / (σ_x · σ_y)'],
      ['Hromadění chyb (lineární funkce)', 'σ_f² = a₁²σ₁² + a₂²σ₂²'],
      ['Hromadění chyb maticově', 'Σ_f = J · Σ_x · Jᵀ'],
      ['Váha měření', 'p = c / m²,  c = m₀²'],
      ['Vážený průměr', 'x̄ = Σ(p · x) / Σp'],
      ['Zprostředkující vyrovnání', 'N = AᵀPA,  x = N⁻¹AᵀPl,  v = Ax − l'],
      ['Jednotková střední chyba', 'm₀ = √(vᵀPv / (n − k))'],
    ],
    terms: [
      ['Matice plánu A', 'derivace měření podle neznámých'],
      ['Nadbytečnost', 'n − k, počet měření nad nutný počet'],
      ['Korelát', 'Lagrangeův multiplikátor v podmínkovém vyrovnání'],
      ['Číslo nadbytečnosti r_i', 'podíl měření na nadbytečnosti, 0 až 1'],
      ['Test χ²', 'shoda aposteriorní m₀ s apriorní σ₀, n − k stupňů volnosti'],
      ['Data snooping', 'Baardův test normovaných oprav, kritická hodnota 3,29'],
      ['Vnitřní spolehlivost', 'nejmenší ještě zjistitelná hrubá chyba'],
    ],
    tip: 'U m₀ děl počtem nadbytečných měření n − k, ne n. A pamatuj: sčítají se rozptyly, směrodatné odchylky nikdy.',
  },

  u14: {
    intro: 'Geometrie leteckého a UAV snímku, orientace snímků, stereofotogrammetrie, zpracování metodou SfM a laserové skenování. Tak vznikají ortofota, mračna bodů a digitální modely terénu.',
    points: [
      'Konstanta komory c je vzdálenost projekčního centra od roviny snímku, prakticky ohnisková vzdálenost.',
      'Snímek je středový průmět: u členitého terénu se měřítko mění, konstantní měřítko má až ortofoto.',
      'Vnitřní orientaci tvoří c, hlavní bod a distorze; vnější orientaci 6 prvků X₀, Y₀, Z₀, ω, φ, κ.',
      'Pro protínání zpět jednoho snímku teoreticky stačí 3 vlícovací body, v praxi se volí víc.',
      'Klasický podélný překryt je 60 %, příčný 20–30 %; u UAV a SfM se volí výrazně vyšší.',
      'Výška bodu ve stereodvojici se určuje z x-paralaxy; větší poměr B/h dává přesnější výšky.',
      'Vlícovací body (GCP) vstupují do výpočtu, kontrolní body slouží jen k nezávislému ověření.',
      'SfM: klíčové body → orientace a řídké mračno → GCP → husté mračno → DMP a ortofoto; bez textury (voda, sníh) selhává.',
      'DMR je holý terén, DMP zahrnuje i budovy a vegetaci.',
      'ALS potřebuje k dálkoměru GNSS a IMU; vícenásobné odrazy umožní proniknout vegetací k terénu.',
    ],
    formulas: [
      ['Měřítkové číslo snímku', 'm_s = h / c'],
      ['GSD', 'GSD = velikost pixelu · h / c'],
      ['Základna', 'B = s · m_s · (1 − p)'],
      ['Normální případ stereo', 'Z = B · c / p_x'],
      ['Pulzní dálkoměr / skener', 'd = c · t / 2'],
    ],
    terms: [
      ['GSD', 'velikost pixelu promítnutá na terén'],
      ['Kolinearita', 'obrazový bod, centrum a předmětový bod leží na přímce'],
      ['Aerotriangulace', 'orientace bloku snímků s minimem vlícovacích bodů'],
      ['Vyrovnání svazků', 'současné vyrovnání všech snímků a bodů'],
      ['Ortofoto', 'snímek překreslený do ortogonálního průmětu'],
      ['ICP', 'iterativní registrace překrývajících se mračen'],
      ['Klasifikace mračna', 'třídění bodů na terén, vegetaci, budovy'],
    ],
    tip: 'Trik pro GSD: pixel v µm krát výška v m děleno ohniskem v mm vyjde rovnou v milimetrech. U m_s a Z dej c do stejných jednotek jako h a p.',
  },

  u15: {
    intro: 'Referenční systémy a rámce, signály a pozorování GNSS, zdroje chyb, metody měření a oběžné dráhy. Bez toho nelze posoudit, kdy je RTK bod opravdu centimetrový.',
    points: [
      'Referenční systém je definice, rámec jeho realizace souřadnicemi bodů (ITRS → ITRF2020).',
      'ETRS89 je spojen s euroasijskou deskou; v ČR se používá realizace ETRF2000 v epoše 2000,0.',
      'S-JTSK je na Besselově elipsoidu, ETRS89 na GRS80 – nutná je transformace i Křovákovo zobrazení.',
      'Frekvence GPS: L1 = 1575,42 MHz, L2 = 1227,60 MHz, L5 = 1176,45 MHz.',
      'Pseudovzdálenost obsahuje chybu hodin přijímače, proto jsou potřeba nejméně 4 družice.',
      'Ionosféra je disperzní (∼ 1/f²): kód zpožďuje, fázi urychluje; troposféra je nedisperzní a nejhůř se modeluje mokrá složka.',
      'Jednoduchá diference vyloučí hodiny družice, dvojitá hodiny přijímačů, trojitá ambiguitu.',
      'Float znamená nevyřešené ambiguity (decimetry), centimetry dává až fixed řešení.',
      'Čas GPS nemá přestupné sekundy a je o 18 s napřed před UTC.',
      'Výšky drah: GPS ≈ 20 200 km (oběžná doba ≈ 11 h 58 min), GLONASS ≈ 19 100 km, Galileo ≈ 23 222 km.',
    ],
    formulas: [
      ['Elipsoidická výška', 'h = H + ζ'],
      ['Prostorová Helmertova transformace', 'X₂ = T + (1 + m) · R · X₁  (3 posuny, 3 rotace, 1 měřítko)'],
      ['Vlnová délka', 'λ = c / f,  L1: λ ≈ 19,03 cm'],
      ['Nosná L1', 'f_L1 = 154 · 10,23 MHz = 1575,42 MHz'],
      ['Délka základny', 's = √(ΔX² + ΔY² + ΔZ²)'],
      ['Přesnost a + b ppm', 'm = a + b · d  (d v km, 1 ppm = 1 mm/km)'],
      ['Vliv geometrie', 'σ_poloha ≈ PDOP · σ_měření'],
    ],
    terms: [
      ['Ambiguita', 'neznámý celý počet cyklů fázového měření'],
      ['Cycle slip', 'skok v celém počtu cyklů po ztrátě zámku'],
      ['Multipath', 'vícecestné šíření odrazem od okolních ploch'],
      ['PCO / PCV', 'poloha a proměnlivost fázového centra antény'],
      ['VRS', 'virtuální referenční stanice vypočtená poblíž roveru'],
      ['PPP', 'přesná poloha jedním přijímačem z přesných drah a hodin'],
      ['CZEPOS', 'síť permanentních stanic ČÚZK'],
      ['Epocha', 'okamžik, ke kterému platí souřadnice v ITRF'],
    ],
    tip: 'RTK bod ber jako hotový až po fixu a nezávislém přeměření po nové inicializaci. Float s decimetry vypadá na displeji stejně nevinně jako fix.',
  },

  u16: {
    intro: 'Návrh a vyrovnání geodetických sítí, vytyčení staveb, měření posunů a monitoring konstrukcí. Právě tady geodet přebírá odpovědnost za přesnost na stavbě.',
    points: [
      'Volná síť nemá datum dané pevnými body; defekt polohové sítě s délkami a směry je 3, jen se směry 4, nivelační sítě 1.',
      'Ve vázané síti se chyby daných bodů přenášejí do vyrovnaných souřadnic a mohou síť deformovat.',
      'Optimalizace sítě: nultý stupeň datum, první konfigurace, druhý váhy měření, třetí zhuštění.',
      'Čísla nadbytečnosti r_i leží mezi 0 a 1 a jejich součet je n − k.',
      'Přesnost vytyčování řeší ČSN 73 0420, měření posunů ČSN 73 0405.',
      'Vytyčení postupuje od vytyčovací sítě přes hlavní a podrobné body ke kontrole a protokolu.',
      'Kontrolu vytyčení dělej z jiného stanoviska nebo jinou metodou.',
      'Vztažné body jsou stabilní mimo oblast deformací, pozorované body leží na sledovaném objektu.',
      'Posun je významný, až když překročí kritickou hodnotu danou jeho přesností; test kongruence ověřuje, zda se tvar sítě nezměnil.',
      'InSAR měří posun ve směru záměry radaru (LOS); v tunelu GNSS nefunguje.',
    ],
    formulas: [
      ['Jednotková střední chyba', 'm₀ = √([vv] / (n − k))'],
      ['Polární metoda', 'Y_P = Y_A + d · sin σ,  X_P = X_A + d · cos σ'],
      ['Směrník', 'σ_AB = arctg(ΔY / ΔX) + úprava podle kvadrantu'],
      ['Délka ze souřadnic', 'd = √(ΔY² + ΔX²)'],
      ['Přesnost posunu', 'σ_d = √(σ₁² + σ₂²)'],
      ['Významnost posunu', '|d| > t · σ_d'],
      ['Polohová chyba polárního vytyčení', 'm_p = √(m_d² + (d · m_ω)²),  m_ω v rad'],
    ],
    terms: [
      ['Defekt sítě', 'počet chybějících parametrů datumu'],
      ['Vytyčovací síť', 'stabilní síť pro vytyčení a kontrolu stavby'],
      ['Mezní vytyčovací odchylka', 'největší dovolená odchylka vytyčení'],
      ['Nultá etapa', 'výchozí měření, ke kterému se vztahují posuny'],
      ['Test kongruence', 'test, zda se tvar sítě mezi etapami nezměnil'],
      ['Průrazová chyba', 'odchylka setkání dvou protilehlých ražeb tunelu'],
      ['PS-InSAR', 'radarová interferometrie na stabilních odražečích'],
    ],
    tip: 'Při vytyčení nastav nulu na orientační bod, otoč o vytyčovací úhel po směru hodinových ručiček a délku měř podél záměry. Pak bod zkontroluj z jiného stanoviska.',
  },

  bea003: {
    intro: 'Základy práce s teodolitem a totální stanicí: libely, osové podmínky, měření vodorovných směrů, zenitových úhlů a délek včetně redukcí. Na tom stojí veškeré další měření.',
    points: [
      'Citlivost libely je úhel náklonu na jeden dílek; bublina putuje vždy k výše položenému konci.',
      'Libelu urovnáš nejprve rovnoběžně se spojnicí dvou šroubů, pak otočíš alhidádu o 100 gon a urovnáš třetím šroubem.',
      'Osové podmínky teodolitu: L ⊥ V, Z ⊥ H, H ⊥ V.',
      'Měření ve dvou polohách vyloučí kolimační, úklonnou i indexovou chybu; nesvislost osy V ne, tu hlídá kompenzátor.',
      'Nejdřív okulárem zaostři ryskový kříž, potom zaostřovacím šroubem cíl – odstraníš paralaxu.',
      'Ve skupinové metodě se v II. poloze cílí v opačném pořadí a mezi skupinami se mění počáteční čtení kruhu.',
      'Zenitový úhel: 0 gon zenit, 100 gon vodorovná záměra, 200 gon nadir; výškový úhel α = 100 gon − z.',
      'Atmosférická korekce EDM závisí hlavně na teplotě a tlaku; při vyšší teplotě je kladná.',
      'Pásmo se opravuje o komparaci, teplotu a sklon.',
      'Postup redukce délky: šikmá → atmosféra → vodorovná → nulový horizont → kartografické zkreslení.',
    ],
    formulas: [
      ['Vodorovný úhel', 'ω = čtení vpravo − čtení vlevo  (+ 400 gon, je-li záporný)'],
      ['Průměrný směr', 'ψ = (ψ_I + ψ_II ± 200 gon) / 2'],
      ['Indexová chyba', 'i = (z_I + z_II − 400 gon) / 2'],
      ['Opravený zenitový úhel', 'z = (z_I − z_II + 400 gon) / 2'],
      ['Vodorovná délka', 'd = s · sin z'],
      ['Přesnost dálkoměru', 'm = a + b · d  (d v km, 1 ppm = 1 mm/km)'],
      ['Redukce do S-JTSK', 'd₀ = d · (1 − H/R),  d_S = d₀ · m'],
      ['Paralaktická metoda', 'd = (b / 2) · cotg(γ / 2)'],
    ],
    terms: [
      ['Alhidáda', 'otočná horní část nesoucí dalekohled a libelu'],
      ['Limbus', 'vodorovný dělený kruh'],
      ['Kolimační chyba', 'záměrná přímka není kolmá k točné ose'],
      ['Indexová chyba', 'nula svislého kruhu nesměřuje do zenitu'],
      ['Kompenzátor', 'měří sklon osy V a opravuje čtení'],
      ['Pentagonální hranol', 'pomůcka pro vytyčení pravého úhlu'],
      ['Redukce osnovy', 'odečtení prvního směru od všech směrů'],
    ],
    tip: 'Stanovisko vybírej tak, abys viděl na všechny body a stativ stál pevně. Po jemném urovnání vždy znovu zkontroluj centraci – obě se navzájem ovlivňují.',
  },

  bea004: {
    intro: 'Nivelační přístroje a technická nivelace, bodová pole, trigonometrické výšky a podrobné měření s výpočty ploch a kubatur. Typická každodenní práce na stavbě i v katastru.',
    points: [
      'Kompenzátor po hrubém urovnání krabicovou libelou automaticky urovná záměrnou přímku.',
      'i-chyba je sklon záměrné přímky; vyloučí ji nivelace ze středu se stejně dlouhými záměrami.',
      'Přístroj nemusí stát na spojnici latí, stačí stejné délky záměr vzad a vpřed.',
      'Menší čtení na lati znamená výše položený bod.',
      'Vetknutý pořad je připojen na začátku i na konci; v uzavřeném pořadu má být ΣΔh = 0.',
      'Uzávěr se rozděluje s opačným znaménkem úměrně délkám nebo počtu sestav, jen pokud nepřekročí mezní odchylku.',
      'ZPBP a PPBP jsou polohová bodová pole, ZNBP nivelační; výšky jsou v Bpv.',
      'Čepová značka se osazuje do svislé zdi, hřebová do vodorovné plochy; trig. bod má i podzemní značku na téže svislici.',
      'Oprava ze zakřivení a refrakce (k = 0,13) dělá na 1 km asi 68 mm; refrakci omezí oboustranné současné měření.',
      'Tachymetrie určuje polohu i výšku, ortogonální metoda staničení a kolmice.',
    ],
    formulas: [
      ['Převýšení na sestavě', 'Δh = vzad − vpřed'],
      ['Výška koncového bodu', 'H_K = H_Z + ΣΔh,  kontrola ΣΔh = Σvzad − Σvpřed'],
      ['Uzávěr pořadu', 'u = ΣΔh − (H_K − H_Z)'],
      ['Mezní odchylka technické nivelace', 'Δ = 40 mm · √R  (R v km)'],
      ['Plošná nivelace', 'H_i = H_A + vzad,  H_B = H_i − čtení'],
      ['Trigonometrické převýšení', 'Δh = s · cos z + (1 − k) · d² / (2R)'],
      ['Plocha ze souřadnic (L’Huilier)', '2P = Σ Xᵢ · (Yᵢ₊₁ − Yᵢ₋₁)'],
      ['Objem mezi profily', 'V = (A₁ + A₂) / 2 · L'],
    ],
    terms: [
      ['Přestavový bod', 'bod, na kterém se čte vpřed i vzad'],
      ['Nivelační podložka', 'stabilní podložka pro lať na přestavovém bodě'],
      ['Horizont přístroje', 'výška záměrné přímky nad srovnávací plochou'],
      ['Vetknutý pořad', 'pořad připojený na začátku i na konci'],
      ['Refrakční koeficient', 'k = 0,13, poměr poloměru Země a poloměru křivosti paprsku'],
      ['Tachymetrie', 'prostorová polární metoda: směr, délka, zenitový úhel'],
      ['Podélný profil', 'výšky terénu podél osy trasy'],
    ],
    tip: 'V zápisníku vždy proveď kontrolu Σvzad − Σvpřed = ΣΔh. Než začneš rozdělovat uzávěr, porovnej ho s 40 mm · √R.',
  },

  bea006: {
    intro: 'Pravděpodobnost, rozdělení náhodných veličin, chyby měření, přenášení chyb a vyrovnání přímých měření. Bez toho nelze říct, jak přesný je naměřený výsledek.',
    points: [
      'Pravděpodobnost leží v ⟨0; 1⟩; pro nezávislé jevy P(A ∩ B) = P(A) · P(B), opačný jev má 1 − P(A).',
      'Normální rozdělení N(μ, σ²): v ±1σ, ±2σ, ±3σ leží 68,3 %, 95,4 % a 99,7 % hodnot.',
      'Oboustranný 95% kvantil je 1,96, jednostranný 1,64, oboustranný 99% 2,58.',
      'Mezní odchylka se volí jako dvoj- až trojnásobek σ.',
      'Skutečná chyba je měření minus skutečná hodnota; oprava v = x̄ − l a součet oprav [v] = 0.',
      'Správnost kazí systematické chyby, přesnost (rozptyl) nahodilé chyby.',
      'Korelační koeficient leží od −1 do 1; kovarianční matice je symetrická.',
      'Součet n veličin se stejnou m má chybu m√n, úhel ze dvou směrů m_ψ√2, funkce k · x chybu |k| · m.',
      'Váha je nepřímo úměrná kvadrátu střední chyby; průměr z n měření s vahou 1 má váhu n.',
      'Studentovo t se používá při malém počtu měření, χ² k testu rozptylu.',
    ],
    formulas: [
      ['Kombinace', 'C(n, k) = n! / (k! · (n − k)!)'],
      ['Binomické rozdělení', 'P(k) = C(n, k) · pᵏ · (1 − p)ⁿ⁻ᵏ'],
      ['Normování', 'u = (x − μ) / σ'],
      ['Výběrová směrodatná odchylka', 's = √([vv] / (n − 1))'],
      ['Střední chyba průměru', 'm_x̄ = m / √n'],
      ['Zákon přenášení chyb', 'm_f² = Σ (∂f/∂xᵢ)² · mᵢ²'],
      ['Vážený průměr', 'x̄ = [pl] / [p],  m = m₀ / √p'],
      ['Střední chyba ze dvojic', 'm = √([dd] / (2n))'],
    ],
    terms: [
      ['Permutace', 'počet uspořádání n prvků je n!'],
      ['Distribuční funkce', 'F(x) = P(X ≤ x)'],
      ['Rozptyl', 'σ², druhá mocnina směrodatné odchylky'],
      ['Oprava', 'rozdíl průměru a měřené hodnoty'],
      ['Hrubá chyba', 'omyl, odhalí ji kontrolní měření'],
      ['Jednotková střední chyba', 'střední chyba měření s vahou 1'],
      ['Nadbytečné měření', 'měření nad nutný počet, umožní kontrolu'],
    ],
    tip: 'Po výpočtu oprav vždy sečti [v] – musí vyjít nula (až na zaokrouhlení). Když nevyjde, máš chybu v průměru dřív, než začneš počítat s.',
  },

  bea010: {
    intro: 'Přesná nivelace, transformace souřadnic, centrace a orientace osnov, gyroskopická a magnetická orientace a úvod do GNSS. Nástroje pro připojení měření do státních systémů.',
    points: [
      'Přesná nivelace používá invarové latě, měří se tam a zpět s krátkými a stejnými záměrami.',
      'Pořadí čtení vzad – vpřed – vpřed – vzad omezuje vliv sedání přístroje.',
      'Refrakce škodí nejvíc těsně nad terénem, proto je předepsaná minimální výška záměry.',
      'Rovinné transformace: shodnostní 3, podobnostní 4, afinní 6, projektivní 8 parametrů; prostorová podobnostní 7.',
      'Pro podobnostní transformaci stačí 2 identické body; při nadbytku se klíč určí MNČ a posoudí z oprav.',
      'Shodnostní zachovává délky i úhly, podobnostní úhly, afinní rovnoběžnost, projektivní přímky.',
      'Centrace je nutná, když přístroj nebo cíl stojí mimo bod; nucená centrace ji na pilířích prakticky odstraní.',
      'Gyroteodolit určuje astronomický azimut; od směrníku v S-JTSK se liší hlavně o meridiánovou konvergenci.',
      'Kovová vedení hledá lokátor, nekovová georadar; nové vedení se zaměřuje v otevřeném výkopu.',
      'GNSS dává elipsoidickou výšku; pro 3D polohu a hodiny jsou potřeba 4 družice.',
    ],
    formulas: [
      ['Helmertova transformace – Y', 'Y = Y₀ + q · (y · cos ω + x · sin ω)'],
      ['Helmertova transformace – X', 'X = X₀ + q · (x · cos ω − y · sin ω)'],
      ['Oprava z excentricity', 'δ = ρ · e · sin φ / d,  ρ = 200/π gon'],
      ['Příčná odchylka', 'δ[rad] = q / d,  1 cm na 1 km ≈ 0,64 mgon'],
      ['Orientační posun', 'O = σ − ψ'],
      ['Mezní odchylka technické nivelace', 'Δ = 40 mm · √R  (R v km)'],
    ],
    terms: [
      ['Invar', 'slitina s velmi malou teplotní roztažností'],
      ['Identický bod', 'bod se souřadnicemi v obou soustavách'],
      ['Transformační klíč', 'parametry transformace mezi soustavami'],
      ['Nucená centrace', 'přesné stavění přístroje i cíle na pilíři'],
      ['Meridiánová konvergence', 'úhel mezi průmětem poledníku a osou X'],
      ['Magnetická deklinace', 'úhel mezi magnetickým a zeměpisným severem, mění se v čase'],
      ['PDOP', 'vliv geometrie družic na přesnost polohy'],
    ],
    tip: 'U Helmertovy transformace přepni kalkulačku na gony (GRAD), spočti cos ω a sin ω jednou a pak dosazuj. Výsledek ověř na identickém bodě.',
  },

  bea009: {
    intro: 'Práce s geodetickými daty v CAD a GIS: formáty, kontroly, konverze a mapové služby. Správně odevzdaná data jsou stejně důležitá jako přesné měření.',
    points: [
      'DGN je formát MicroStationu (Bentley), DWG AutoCADu (Autodesk), DXF výměnný formát Autodesku; Kokeš je od firmy Gepro.',
      'Vrstvy (hladiny) tematicky člení kresbu, mapové značky se vkládají jako buňky nebo bloky.',
      'Souřadnice S-JTSK se v CAD zadávají se záporným znaménkem, aby byl sever nahoře a východ vpravo.',
      'VFK je výměnný formát katastru nemovitostí od ČÚZK; GML je XML pro geodata (INSPIRE, RÚIAN).',
      'Shapefile tvoří .shp (geometrie), .shx (index), .dbf (atributy) a .prj (souřadnicový systém); má jediný typ geometrie.',
      'Topologická kontrola hlídá napojení, překryvy a uzavřenost ploch, atributová kontrola vlastnosti prvků.',
      'Hranice sousedních ploch má být uložena jednou a sdílena.',
      'Konverze může ztratit atributy či styly; u českých dat hlídej kódování Windows-1250 vs. UTF-8.',
      'S-JTSK ↔ ETRS89 se převádí zpřesněnou globální transformací ČÚZK s opravnou tabulkou.',
      'WMS dává obrázek, WFS vektorové prvky, WMTS dlaždice; standardy vydává OGC.',
    ],
    formulas: [],
    terms: [
      ['Georeferencování', 'přiřazení souřadnic rastru podle identických bodů'],
      ['Snap', 'tolerance přichycení koncových bodů'],
      ['Uzel', 'bod, kde se stýkají linie'],
      ['Převodní tabulka', 'určuje, kam se při konverzi převedou vrstvy a atributy'],
      ['GetCapabilities', 'požadavek vracející popis služby a vrstev'],
      ['Kartogram', 'relativní hodnoty vyjádřené barvou ploch'],
      ['Kartodiagram', 'absolutní hodnoty vyjádřené diagramy'],
    ],
    tip: 'Po každé konverzi otevři výsledek a zkontroluj diakritiku, vrstvy i souřadnicový systém. Topologické kontroly po opravách vždy spusť znovu.',
  },
};
