// Taháky ke kapitolám 1–10 (u1–u10).

export default {
  u1: {
    intro: 'Geodézie určuje tvar a rozměry Země a polohu bodů na jejím povrchu. Bez úhlových jednotek, měřítka a bodových polí se neobejde žádné měření.',
    points: [
      'Geodézie = zeměměřictví; zeměměřictví a katastr v ČR řídí ČÚZK.',
      'Vyšší geodézie řeší Zemi jako celek, inženýrská geodézie měření pro stavby a průmysl.',
      'Plný úhel = 400 gon = 360° = 2π rad, pravý úhel = 100 gon.',
      '1 gon = 0,9° = 1000 mgon; 1° = 60′ = 3600″; 1 mgon ≈ 3,24″.',
      'Větší měřítko = menší číslo ve jmenovateli = podrobnější mapa (1 : 500 > 1 : 5 000).',
      'Geoid je hladinová plocha tíhového pole, elipsoid je matematická plocha pro výpočty.',
      'S-JTSK používá Besselův elipsoid, ETRS89 elipsoid GRS80 (prakticky shodný s WGS84).',
      'Střední poloměr Země je asi 6 371 km; zakřivení se ve výšce projeví asi 8 cm na 1 km.',
      'Polohu dávají trigonometrické a zhušťovací body, výšku nivelační body, korekce GNSS síť CZEPOS.',
    ],
    formulas: [
      ['Gony na stupně', '° = gon · 0,9'],
      ['Stupně na gony', 'gon = ° / 0,9'],
      ['Gony na radiány', 'rad = gon · π / 200'],
      ['Stupně, minuty, vteřiny', '° = d + m / 60 + s / 3600'],
      ['Skutečná délka z mapy', 'D = d_mapa · M'],
      ['Délka na mapě', 'd_mapa = D / M'],
      ['Plocha z mapy', 'P = p_mapa · M²'],
      ['Vliv zakřivení Země na výšku', 'Δ ≈ d² / (2R)'],
    ],
    terms: [
      ['Geoid', 'Hladinová plocha tíhového pole blízká klidné střední hladině moří.'],
      ['Rotační elipsoid', 'Matematická plocha daná poloosami a zploštěním.'],
      ['Tížnicová odchylka', 'Úhel mezi tížnicí a normálou k elipsoidu.'],
      ['Měřítko mapy', 'Poměr délky na mapě ke skutečné délce, např. 1 : 1 000.'],
      ['Grafické měřítko', 'Dělená úsečka na mapě, platí i po zvětšení kopie.'],
      ['ÚOZI', 'Úředně oprávněný zeměměřický inženýr, ověřuje výsledky pro katastr.'],
      ['CZEPOS', 'Síť permanentních stanic GNSS provozovaná ČÚZK.'],
    ],
    tip: 'Na kalkulačce si vždycky nejdřív zkontroluj, jestli máš přepnuto na gony (GRAD). Kvůli špatnému režimu padá u zkoušek nejvíc bodů.',
  },

  u2: {
    intro: 'Souřadnicové a výškové systémy říkají, k čemu se souřadnice a výšky vztahují. Bez nich nejde spojit měření z totální stanice, GNSS a katastru.',
    points: [
      'S-JTSK používá Křovákovo dvojité konformní kuželové zobrazení na Besselově elipsoidu.',
      'V S-JTSK míří kladná osa X k jihu a kladná osa Y k západu, v ČR jsou obě souřadnice kladné.',
      'V ČR platí Y < X; souřadnice se zapisují v pořadí Y, X.',
      'Délkové zkreslení Křovákova zobrazení je v ČR asi −10 až +14 cm/km.',
      'GPS pracuje ve WGS84, evropský závazný systém je ETRS89 (elipsoid GRS80).',
      'UTM má pásy široké 6°, Česko leží v pásech 33 a 34.',
      'Závazný výškový systém je Bpv, výšky jsou normální a vztažené k nule vodočtu v Kronštadtu.',
      'Elipsoidická výška z GNSS se od výšky v Bpv liší v ČR zhruba o 40 až 47 m.',
      'Směrník se měří od kladné osy +X po směru hodinových ručiček, 0 až 400 gon.',
      'Opačný směrník se liší o 200 gon.',
    ],
    formulas: [
      ['Pomocný úhel', 'φ = arctg |ΔY / ΔX|'],
      ['Směrník podle kvadrantu', 'I: σ = φ; II: σ = 200 − φ; III: σ = 200 + φ; IV: σ = 400 − φ (gon)'],
      ['Opačný směrník', 'σ_BA = σ_AB ± 200 gon'],
      ['Souřadnicové rozdíly', 'ΔY = Y_B − Y_A, ΔX = X_B − X_A'],
      ['Elipsoidická výška', 'h = H + ζ'],
      ['Helmertova transformace – Y', 'Y = Y₀ + q · (y · cos ω + x · sin ω)'],
      ['Helmertova transformace – X', 'X = X₀ + q · (x · cos ω − y · sin ω)'],
    ],
    terms: [
      ['Kvadrant I', 'ΔY > 0, ΔX > 0 → σ v rozsahu 0–100 gon.'],
      ['Kvadrant II', 'ΔY > 0, ΔX < 0 → σ v rozsahu 100–200 gon.'],
      ['Kvadrant III', 'ΔY < 0, ΔX < 0 → σ v rozsahu 200–300 gon.'],
      ['Kvadrant IV', 'ΔY < 0, ΔX > 0 → σ v rozsahu 300–400 gon.'],
      ['Konformní zobrazení', 'Zobrazení, které zachovává úhly (úhlojevné).'],
      ['S-JTSK/05', 'Zpřesněná realizace S-JTSK navázaná na ETRS89.'],
      ['Identický bod', 'Bod se známými souřadnicemi v obou systémech.'],
      ['Transformace', 'Rovinná Helmertova má 4 parametry, afinní 6, prostorová Helmertova 7.'],
    ],
    tip: 'Než začneš počítat směrník, načrtni si ΔY a ΔX do kříže os. Kvadrant pak poznáš na první pohled a arkustangens z kalkulačky nepřevezmeš naslepo.',
  },

  u3: {
    intro: 'Přístroje jsou hlavní nástroj geodeta: totální stanice, nivelační přístroj a GNSS přijímač. Kdo zná jejich osy a chyby, měří rychle a bez zbytečných opakování.',
    points: [
      'Totální stanice spojuje elektronický teodolit a dálkoměr, měří úhly i délky.',
      'Osy teodolitu: V svislá (točná), H klopná, Z záměrná přímka, L osa alhidádové libely.',
      'Osové podmínky: L ⟂ V, Z ⟂ H, H ⟂ V.',
      'Porušení Z ⟂ H je kolimační chyba; nepřesné čtení svislého kruhu je indexová chyba.',
      'Měření ve dvou polohách dalekohledu odstraní kolimační a indexovou chybu, ne sklon svislé osy.',
      'Čtení kruhu = číslo gonové rysky + poloha na stupnici po 0,01 gon, tisíciny se odhadují.',
      'Nivelační přístroj musí mít vodorovnou záměru, automatický ji drží kompenzátorem.',
      'Digitální nivelační přístroj čte čárový kód na lati, lať s E-dělením má dílky po 1 cm.',
      'Pro 3D polohu z GNSS jsou potřeba aspoň 4 družice (X, Y, Z a chyba hodin).',
      'Výška antény GNSS se měří k referenčnímu bodu antény (ARP).',
    ],
    formulas: [
      ['Indexová chyba', 'i = (z_I + z_II − 400 gon) / 2'],
      ['Kontrola zenitových úhlů', 'z_I + z_II = 400 gon (bez indexové chyby)'],
      ['Dálka z dálkoměrných rysek', 'D = 100 · (horní − dolní čtení)'],
    ],
    terms: [
      ['Alhidáda', 'Otočná horní část přístroje nesoucí dalekohled.'],
      ['Limbus', 'Vodorovný dělený kruh, čte se z něj vodorovný směr.'],
      ['Ustanovka', 'Šroub pro jemné natočení na cíl.'],
      ['Stavěcí šrouby', 'Tři šrouby trojnožky pro horizontaci.'],
      ['Kolimátor', 'Hledáček pro hrubé zamíření na cíl.'],
      ['Kompenzátor', 'Automaticky opravuje malý zbytkový sklon přístroje.'],
      ['Centrovač', 'Optický nebo laserový, staví přístroj přesně nad bod.'],
      ['Nivelační podložka', 'Žabka, stabilní přestavový bod pod lať.'],
    ],
    tip: 'Než vyrazíš do terénu, zkontroluj baterie, nastavenou konstantu hranolu a vodorovnost záměry nivelačního přístroje. Doma to trvá minutu, v terénu to stojí celý den.',
  },

  u4: {
    intro: 'Úhly a délky jsou základní měřené veličiny, ze kterých se počítají souřadnice i výšky. Kapitola ukazuje, jak přístroj postavit a jak z měření dostat vodorovné délky a převýšení.',
    points: [
      'Centrace staví svislou osu nad bod, horizontace ji uvádí do svislé polohy.',
      'Při horizontaci dvěma šrouby jde bublina ve směru levého palce.',
      'Výška přístroje se měří od bodu ke klopné ose dalekohledu.',
      'Vodorovný úhel je průmět úhlu do vodorovné roviny, nezávisí na sklonu záměr.',
      'Skupina = měření osnovy v I. i II. poloze, čtení se liší asi o 200 gon.',
      'Zenitový úhel se měří od zenitu: zenit 0 gon, vodorovná záměra 100 gon, z > 100 gon je záměra dolů.',
      'Přesnost dálkoměru se udává jako a mm + b ppm; 1 ppm na 1 km = 1 mm.',
      'Atmosférická korekce délky závisí hlavně na teplotě a tlaku vzduchu.',
      'Na dlouhých záměrách se převýšení opravuje o zakřivení Země a refrakci.',
    ],
    formulas: [
      ['Vodorovný úhel', 'ω = čtení vpravo − čtení vlevo (záporné + 400 gon)'],
      ['Výškový úhel', 'ε = 100 gon − z'],
      ['Indexová chyba', 'i = (z_I + z_II − 400 gon) / 2'],
      ['Vodorovná délka', 'd = s · sin z'],
      ['Střední chyba délky', 'm_d = a + b · D [km] (mm)'],
      ['Trigonometrické převýšení', 'Δh = s · cos z + v_p − v_c'],
      ['Zakřivení a refrakce', 'Δ = (1 − k) · d² / (2R), k ≈ 0,13'],
    ],
    terms: [
      ['Centrace', 'Postavení svislé osy přístroje nad měřený bod.'],
      ['Horizontace', 'Urovnání svislé osy do svislé polohy.'],
      ['Orientace osnovy', 'Určení směrníku nulového směru limbu.'],
      ['Zenitový úhel', 'Úhel od svislice vzhůru k záměře.'],
      ['ppm', 'Milióntina délky, 1 mm na 1 km.'],
      ['Součtová konstanta', 'Oprava délky podle typu hranolu, např. 0 nebo −30 mm.'],
      ['Refrakce', 'Zakřivení paprsku v atmosféře, obvykle vydutý k Zemi.'],
    ],
    tip: 'Orientuj se na co nejvzdálenější body. Chyba centrace na krátké záměře rozhodí úhel víc, než si myslíš.',
  },

  u5: {
    intro: 'Výpočty v rovině převádějí měřené úhly a délky na souřadnice v S-JTSK a zpět. Je to každodenní práce při podrobném měření, vytyčování i v katastru.',
    points: [
      'První základní úloha: ze souřadnic bodu, směrníku a délky určíme nový bod.',
      'Druhá základní úloha: ze souřadnic dvou bodů určíme směrník a délku.',
      'Polární metoda určuje bod směrem a délkou ze stanoviska.',
      'Orientační posun převádí čtení limbu na směrníky.',
      'Protínání zpět potřebuje aspoň 3 známé body a selže na nebezpečné kružnici.',
      'Úhlový uzávěr pořadu se rozdělí rovnoměrně na úhly, souřadnicové uzávěry úměrně délkám stran.',
      'Vetknutý pořad je připojený souřadnicově, ale bez orientací, takže chybí úhlová kontrola.',
      'Výměra parcely se v katastru uvádí v celých m²; 1 a = 100 m², 1 ha = 10 000 m².',
    ],
    formulas: [
      ['Délka ze souřadnic', 'd = √(ΔY² + ΔX²)'],
      ['Směrník', 'tg σ = ΔY / ΔX'],
      ['Polární metoda – Y', 'Y_P = Y_A + d · sin σ'],
      ['Polární metoda – X', 'X_P = X_A + d · cos σ'],
      ['Orientační posun', 'O = σ_SO − ψ_O, pak σ_SP = O + ψ_P'],
      ['Součet vnitřních úhlů', 'Σω = (n − 2) · 200 gon'],
      ['Výměra (L\'Huilier)', '2P = Σ X_i · (Y_i+1 − Y_i−1)'],
    ],
    terms: [
      ['Polární metoda', 'Určení bodu směrem a délkou ze stanoviska.'],
      ['Protínání vpřed', 'Bod z úhlů měřených na dvou známých bodech.'],
      ['Protínání zpět', 'Poloha stanoviska z úhlů na známé body.'],
      ['Protínání z délek', 'Bod ze dvou délek měřených ze dvou známých bodů.'],
      ['Volné stanovisko', 'Stanovisko ze směrů a délek na známé body, vyrovnané.'],
      ['Polygonový pořad', 'Lomená čára sloužící ke zhuštění bodového pole.'],
      ['Uzávěr', 'Rozdíl mezi naměřenou a danou hodnotou.'],
    ],
    tip: 'U výměry ze souřadnic musíš body číslovat postupně po obvodu. Když je přeházíš, vyjde nesmysl, a ten se v protokolu hledá hodně špatně.',
  },

  u6: {
    intro: 'Geometrická nivelace je nejpřesnější běžná metoda určování výšek. Používá se pro výškové bodové pole, stavby i terénní úpravy.',
    points: [
      'Při nivelaci ze středu stojí přístroj stejně daleko od obou latí, nemusí stát na jejich spojnici.',
      'Stejné záměry vyloučí vliv nevodorovnosti záměry a zakřivení Země.',
      'Čtení vzad je na bod se známou výškou, čtení vpřed na určovaný bod.',
      'Je-li čtení vzad větší než vpřed, bod vpředu leží výše.',
      'Přestavový bod se čte vpřed a po přestavení přístroje vzad.',
      'Pořad se měří tam a zpět, uzávěr se porovná s mezní odchylkou.',
      'Oprava má opačné znaménko než uzávěr a rozděluje se úměrně délkám (počtu sestav).',
      'Čtení na lati se udává v metrech na milimetry: číslo = dm, dílky = cm, mm se odhadují.',
      'Plošná nivelace dává výšky bodů ve čtvercové síti z jednoho horizontu přístroje.',
    ],
    formulas: [
      ['Převýšení', 'Δh = čtení vzad − čtení vpřed'],
      ['Výška bodu', 'H_B = H_A + vzad − vpřed'],
      ['Kontrola zápisníku', 'ΣΔh = Σvzad − Σvpřed'],
      ['Výškový uzávěr', 'u = ΣΔh − (H_K − H_Z)'],
      ['Mezní odchylka technické nivelace', 'Δ_M = 40 mm · √R (R v km)'],
      ['Dálka z rysek', 'D = 100 · (horní − dolní čtení)'],
      ['Horizont přístroje', 'H_i = H_A + čtení vzad'],
      ['Výška z horizontu', 'H_B = H_i − čtení na bodě'],
    ],
    terms: [
      ['Nivelační sestava', 'Jedno postavení přístroje se čtením vzad a vpřed.'],
      ['Přestavový bod', 'Spojuje dvě sestavy, lať stojí na žabce.'],
      ['Uzávěr', 'Rozdíl naměřeného a daného převýšení pořadu.'],
      ['Mezní odchylka', 'Nejvyšší přípustný uzávěr, při překročení se měří znovu.'],
      ['Horizont přístroje', 'Výška vodorovné záměrné roviny.'],
      ['Plošná nivelace', 'Výšky bodů v síti pro terénní úpravy a kubatury.'],
    ],
    tip: 'Délky záměr vzad a vpřed odkrokuj. Když se liší jen o pár metrů, chyba ze sklonu záměry se ti sama vyruší.',
  },

  u7: {
    intro: 'GNSS a moderní metody jako RTK, laserové skenování a drony dnes tvoří velkou část měření. Rychle dávají polohu, mračna bodů i ortofota, ale mají svá úskalí.',
    points: [
      'Přijímač určuje polohu z pseudovzdáleností k družicím, čtvrtá družice řeší chybu hodin.',
      'Kódová měření dávají přesnost v metrech, fázová v centimetrech až milimetrech.',
      'GNSS dává elipsoidickou výšku, nadmořskou získáme až modelem kvazigeoidu.',
      'Menší PDOP znamená lepší geometrii družic a vyšší přesnost.',
      'Multipath vzniká odrazy signálu, zhoršuje přesnost u budov a pod stromy.',
      'Ionosférické zpoždění se omezuje měřením na více frekvencích.',
      'Elevační maska (10–15°) vyřadí družice nízko nad obzorem.',
      'RTK Fixed = vyřešené ambiguity, centimetrová přesnost; Float jen decimetrová.',
      'Korekce se přenášejí přes internet protokolem NTRIP, např. ze sítě CZEPOS.',
      'Statická metoda s dlouhou observací je přesnější než rychlé RTK.',
    ],
    formulas: [
      ['Pseudovzdálenost', 'ρ = c · Δt'],
      ['Vliv chyby hodin', '1 µs ≈ 300 m'],
      ['Normální výška z GNSS', 'H = h − ζ'],
    ],
    terms: [
      ['PDOP', 'Vliv geometrie družic na přesnost polohy.'],
      ['Multipath', 'Chyba z odrazů signálu od okolních ploch.'],
      ['RTK', 'Měření v reálném čase s korekcemi z referenční stanice.'],
      ['VRS', 'Virtuální referenční stanice vytvořená sítí u roveru.'],
      ['Mračno bodů', 'Výstup laserového skeneru, miliony bodů se souřadnicemi.'],
      ['ALS', 'Letecké laserové skenování (LiDAR), z něj vznikl DMR 5G.'],
      ['Vlícovací bod', 'GCP, geodeticky změřený bod pro georeferencování snímků.'],
      ['Vektor a rastr', 'Vektor: body, linie, polygony; rastr: mřížka pixelů.'],
    ],
    tip: 'Dokud nesvítí Fixed, neměř. A když jsi pod stromy nebo u fasády, radši přidej druhé nezávislé měření po chvíli, až se změní konstelace.',
  },

  u8: {
    intro: 'Každé měření má chybu. Kapitola učí chyby rozlišit, spočítat jejich velikost a pomocí nadbytečných měření a vyrovnání dojít k nejlepšímu výsledku.',
    points: [
      'Hrubá chyba je omyl, systematická má stálé znaménko a lze ji opravit, nahodilá je náhodná.',
      'Oprava má opačné znaménko než chyba.',
      'Nahodilé chyby mají přibližně normální (Gaussovo) rozdělení a nelze je úplně vyloučit.',
      'Nejpravděpodobnější hodnota stejně přesných měření je aritmetický průměr; součet oprav je 0.',
      'Pro poloviční chybu průměru je potřeba měřit 4× víc.',
      'Nezávislé chyby se sčítají kvadraticky.',
      'Metoda nejmenších čtverců minimalizuje součet čtverců vážených oprav [pvv].',
      'Bez nadbytečných měření nelze odhalit hrubou chybu.',
      'Kód kvality 3 znamená 0,14 m; nižší kód = přesnější bod.',
      'Mezní odchylka je obvykle dvojnásobek střední chyby.',
    ],
    formulas: [
      ['Aritmetický průměr', 'x̄ = Σx / n'],
      ['Střední chyba měření', 'm = √([vv] / (n − 1))'],
      ['Střední chyba průměru', 'm_x̄ = m / √n'],
      ['Součet dvou veličin', 'm_s = √(m₁² + m₂²)'],
      ['Součet n stejně přesných', 'm = m₀ · √n'],
      ['Násobek konstantou', 'm = k · m_x'],
      ['Váha měření', 'p = c / m²'],
      ['Souřadnicová střední chyba', 'm_xy = √((m_x² + m_y²) / 2)'],
    ],
    terms: [
      ['Hrubá chyba', 'Omyl nebo přehlédnutí, odhalí se kontrolou.'],
      ['Systematická chyba', 'Působí stále stejně, lze ji opravit kalibrací.'],
      ['Nahodilá chyba', 'Náhodná, lze ji jen zmenšit opakováním.'],
      ['Střední chyba', 'Míra přesnosti měření.'],
      ['Nadbytečná měření', 'r = n − k, měření navíc nad nutný počet.'],
      ['Váha', 'Nepřímo úměrná čtverci střední chyby.'],
      ['Kód kvality', 'Udává přesnost souřadnic bodu v katastru.'],
    ],
    tip: 'Každou veličinu změř aspoň jednou navíc. Jediné měření nic nekontroluje, dvě už odhalí překlep.',
  },

  u9: {
    intro: 'Katastr nemovitostí eviduje pozemky, stavby a práva k nim. Geodet do něj dodává geometrické plány a vytyčuje hranice.',
    points: [
      'Katastr spravují katastrální úřady řízené ČÚZK, základní jednotkou je katastrální území.',
      'Katastrální zákon je č. 256/2013 Sb., katastrální vyhláška č. 357/2013 Sb.',
      'Zákon o zeměměřictví je č. 200/1994 Sb.',
      'SGI obsahuje katastrální mapu, SPI popisné údaje o parcelách, stavbách a vlastnících.',
      'List vlastnictví uvádí vlastníky a jejich nemovitosti.',
      'Geometrický plán ověřuje ÚOZI a potvrzuje katastrální úřad.',
      'Geometrický plán obsahuje grafické znázornění a výkaz výměr dosavadního a nového stavu.',
      'Při vytyčení hranice se zvou vlastníci sousedních pozemků a sepisuje se protokol.',
      'Vytyčovací prvky se počítají ze souřadnic lomových bodů v S-JTSK.',
      'Oprávnění ÚOZI uděluje ČÚZK po VŠ vzdělání, praxi a zkoušce.',
    ],
    formulas: [
      ['Vytyčovací úhel', 'ω = σ_SP − σ_SO'],
      ['Vytyčovací délka', 'd = √(ΔY² + ΔX²)'],
    ],
    terms: [
      ['Parcela', 'Pozemek geometricky určený a zobrazený v katastrální mapě.'],
      ['SGI', 'Soubor geodetických informací, katastrální mapa.'],
      ['SPI', 'Soubor popisných informací.'],
      ['LV', 'List vlastnictví.'],
      ['KMD', 'Katastrální mapa digitalizovaná z analogové mapy.'],
      ['ZPMZ', 'Záznam podrobného měření změn: náčrty, zápisníky, výpočty.'],
      ['Geometrický plán', 'Podklad např. pro rozdělení pozemku nebo vyznačení budovy.'],
    ],
    tip: 'Než začneš vytyčovat, zjisti kód kvality bodů. U bodů z digitalizované mapy počítej s tím, že realita může být o decimetry jinde.',
  },

  u10: {
    intro: 'Mapování zachycuje polohopis a výškopis terénu, inženýrská geodézie přenáší projekt do terénu a hlídá posuny staveb. Tady se geodet potkává se stavbou.',
    points: [
      'Tachymetrie určuje současně polohu i výšku bodů ze směru, délky a zenitového úhlu.',
      'Polohopis zobrazuje předměty v půdorysu, výškopis tvar terénu.',
      'Vrstevnice spojuje body stejné výšky; hustě u sebe znamenají strmý terén.',
      'Základní interval je výškový rozdíl sousedních vrstevnic, každá pátá je zdůrazněná.',
      'Stanovisko vol tak, aby byly vidět všechny body a byly v dosahu dálkoměru.',
      'Při polárním vytyčení se zacílí na orientační bod, nastaví 0 a otočí o vytyčovací úhel.',
      'Lavičky zajišťují osy stavby mimo výkop; vytyčení se kontroluje nezávislým měřením.',
      'Posun je rozdíl souřadnic nebo výšek pozorovacích bodů mezi etapami.',
      'Vztažné body musí být stabilní a mimo oblast deformací.',
      'Přechodnice (nejčastěji klotoida) plynule mění křivost mezi přímou a obloukem.',
    ],
    formulas: [
      ['Vodorovná délka', 'd = s · sin z'],
      ['Převýšení', 'Δh = s · cos z + v_p − v_c'],
      ['Sklon v procentech', 'sklon = Δh / d · 100 %'],
      ['Vytyčovací úhel', 'ω = σ_SP − σ_SO'],
      ['Délka oblouku', 'o = R · α (α v radiánech)'],
      ['Převod úhlu oblouku', 'α_rad = α_gon · π / 200'],
      ['Délka tečny oblouku', 'T = R · tg(α / 2)'],
    ],
    terms: [
      ['Tachymetrie', 'Současné měření polohy a výšky podrobných bodů.'],
      ['Měřický náčrt', 'Kresba měřených bodů a jejich čísel v terénu.'],
      ['Vrstevnice', 'Čára spojující body se stejnou nadmořskou výškou.'],
      ['Vytyčovací síť', 'Síť bodů pro přesné vytyčení velkých staveb.'],
      ['Lavička', 'Zajištění os stavby mimo výkop, osy se přenášejí provázky.'],
      ['Pozorovací bod', 'Bod osazený na sledovaném objektu.'],
      ['Staničení', 'Vzdálenost podél osy trasy od počátku, např. km 1,250 00.'],
    ],
    tip: 'Každý vytyčený bod ověř oměrnou mírou nebo z jiného stanoviska. Chybu, kterou najdeš ty, nemusí na stavbě bourat nikdo jiný.',
  },
};
