// Taháky ke kapitolám Ing. (VUT FAST): NEA030, NEA033, NEA034, NEA031, NEA035,
// NEA041, NEA042, NEA046, NEA047, NEB045, NEB039, NZA018, NEA043.
export default {
  nea030: {
    intro: 'Inženýrská geodézie provází stavbu od podkladů pro projekt přes vytyčení až po zaměření skutečného provedení. Rozbor přesnosti rozhoduje, jakou metodou a přístrojem se vytyčuje.',
    points: [
      'Apriorní rozbor přesnosti se dělá před měřením a slouží k návrhu metody a přístrojů.',
      'Relativní přesnost se týká vzájemné polohy bodů, celková i chyby podkladu (sítě).',
      'Mezní odchylka se obvykle bere jako 2σ (asi 95 %), pro vyšší spolehlivost 2,5σ až 3σ.',
      'Příčná chyba polárního vytyčení roste lineárně s délkou záměry.',
      'Prostorová poloha stavby se vytyčuje z vytyčovací sítě, podrobné body od hlavních os.',
      'Vytyčovací síť se stabilizuje trvale mimo stavbu a často se vyrovnává jako volná.',
      'Přechodnice (klotoida) zajistí plynulou změnu křivosti mezi přímou a obloukem.',
      'Normální rozchod koleje je 1 435 mm; převýšení koleje kompenzuje odstředivé zrychlení.',
      'Přesná měření ocelových mostů se plánují ráno nebo za zatažené oblohy.',
      'ČSN 73 0420-1 dává základní požadavky na přesnost vytyčování, ČSN 73 0420-2 vytyčovací odchylky.',
    ],
    formulas: [
      ['Polohová chyba bodu', 'm_p = √(m_x² + m_y²),  m_xy = m_p / √2'],
      ['Celková přesnost vytyčení', 'm_celk = √(m_podkladu² + m_vytyčení²)'],
      ['Příčná chyba polární metody', 'q = d · m_ω (rad)'],
      ['Polohová chyba polárního vytyčení', 'm_p = √(m_d² + (d · m_ω)²)'],
      ['Převod cc na radiány', 'm_ω (rad) = m_ω (cc) · π / 2 000 000'],
      ['Chyba součtu úseků', 'm = √(m₁² + m₂²)'],
      ['Klotoida', 'A² = R · L,  křivost 1/r = l / A²'],
      ['Délka kruhového oblouku', 'o = R · α (rad)'],
    ],
    terms: [
      ['Vytyčovací síť', 'Primární systém bodů pro vytyčení stavby.'],
      ['Stavební síť', 'Pravoúhlá síť rovnoběžná s osami objektů.'],
      ['Staničení', 'Vzdálenost od počátku trasy měřená podél osy.'],
      ['Přechodnice', 'Úsek s plynule rostoucí křivostí, obvykle klotoida.'],
      ['Rektifikace', 'Uvedení strojního zařízení do předepsané polohy.'],
      ['SMR', 'Kulový reflektor laserového trackeru.'],
      ['DSPS', 'Dokumentace skutečného provedení stavby.'],
    ],
    tip: 'Toti radí: úhel v cc převeď na radiány hned na začátku. 10 cc na 100 m dává příčnou chybu asi 1,6 mm, na 200 m už dvojnásobek.',
  },

  nea033: {
    intro: 'Geodézie v podzemí řeší orientaci a připojení důlních děl a tunelů bez GNSS a sleduje vliv poddolování na povrch. Chyby se tu kumulují, proto jsou klíčové kontroly.',
    points: [
      'V podzemí nelze použít GNSS, magnetickou orientaci ruší ocel a rudy.',
      'Body se často stabilizují ve stropě a přístroj se na ně centruje olovnicí.',
      'Gyroteodolit určí astronomický azimut z rotace Země bez viditelnosti na povrch.',
      'Směrující moment gyroskopu klesá s cos φ, u pólů je nepoužitelný.',
      'Gyroteodolit se kalibruje na základně se známým azimutem před i po měření.',
      'Orientace jednou jámou má slabinu ve velmi krátké spojnici olovnic.',
      'Orientace dvěma jámami je přesnější, spojnice olovnic má stovky metrů.',
      'Nad vyrubaným prostorem vzniká poklesová kotlina, hranici vymezuje úhel vlivu.',
      'U tunelu je nejméně kritická podélná složka průrazové chyby.',
      'Hornickou činnost upravuje zákon č. 61/1988 Sb., odpovídá hlavní důlní měřič.',
    ],
    formulas: [
      ['Směrující moment gyroskopu', 'M ∼ ω · cos φ'],
      ['Součinitel poklesu', 'a = s_max / m (mocnost sloje)'],
      ['Náklon', 'i = Δs / l'],
      ['Poměrné přetvoření', 'ε = Δl / l'],
    ],
    terms: [
      ['Počva', 'Spodní plocha důlního díla.'],
      ['Jáma', 'Svislé důlní dílo z povrchu.'],
      ['Štola', 'Vodorovné dílo s ústím na povrch.'],
      ['Připojovací trojúhelník', 'Stanovisko a dvě olovnice, velmi štíhlý.'],
      ['Metoda reverzních bodů', 'Vyhodnocení kmitů gyroskopu z obratů.'],
      ['Úhel vlivu', 'Vymezuje hranici poklesové kotliny na povrchu.'],
      ['NRTM', 'Ražba využívající nosnost horniny, řízená monitoringem.'],
      ['TBM', 'Plnoprofilový razicí stroj.'],
    ],
    tip: 'Toti radí: azimut z gyroteodolitu není směrník. Nezapomeň na meridiánovou konvergenci, u přesných prací i na tížnicovou odchylku.',
  },

  nea034: {
    intro: 'Kapitola o geometrických plánech, poskytování údajů z katastru, digitálních katastrálních mapách a vytyčení hranic. Je to každodenní práce ÚOZI v katastru.',
    points: [
      'GP ověřuje ÚOZI (náležitosti a přesnost), potvrzuje katastrální úřad.',
      'Úřední oprávnění uděluje Český úřad zeměměřický a katastrální.',
      'Před zpracováním GP se u KÚ vyžádá číslo ZPMZ a podklady.',
      'GP sám nemění vlastnictví, je technickou přílohou listiny.',
      'GP pro vymezení věcného břemene k části pozemku novou parcelu nevytváří.',
      'Výměra nové parcely se počítá ze souřadnic lomových bodů.',
      'DKM vzniká z přesného měření, KMD přepracováním analogových map.',
      'Mapy stabilního katastru jsou v sáhovém měřítku 1 : 2 880.',
      'Vytyčením hranice se vlastnické právo nemění, nesouhlas se zapíše do protokolu.',
      'Opravu chyby v katastru provádí katastrální úřad, i z moci úřední.',
    ],
    formulas: [
      ['Výměra ze souřadnic', '2P = Σ X_i · (Y_i+1 − Y_i−1)'],
      ['Délka ze souřadnic', 'd = √(ΔY² + ΔX²)'],
      ['Směrník', 'σ = arctg(ΔY / ΔX), kvadrant podle znamének'],
      ['Polární vytyčení', 'σ_SP = σ_SO + ω,  Y_P = Y_S + d · sin σ_SP,  X_P = X_S + d · cos σ_SP'],
      ['Kódy kvality (m_xy)', 'KK 3: 0,14 m · KK 4: 0,26 m · KK 5: 0,50 m'],
    ],
    terms: [
      ['ZPMZ', 'Záznam podrobného měření změn.'],
      ['SGI / SPI', 'Soubor geodetických / popisných informací.'],
      ['ISKN', 'Informační systém katastru nemovitostí.'],
      ['VFK', 'Výměnný formát dat katastru.'],
      ['RÚIAN', 'Základní registr přebírající parcely a budovy z ISKN.'],
      ['LV část A–E', 'A vlastník, B nemovitosti, C omezení, E nabývací tituly.'],
      ['KMD', 'Katastrální mapa digitalizovaná z analogové mapy.'],
    ],
    tip: 'Toti radí: při vytyčení hranice vždy změř nezávislou kontrolu a zapiš ji do protokolu. Soused nesouhlasí? Nehádej se, jen to uveď v protokolu.',
  },

  nea031: {
    intro: 'Tematická kartografie ukazuje vybraný jev na potlačeném topografickém podkladu. Správná metoda, klasifikace a barvy rozhodují, zda mapa neklame.',
    points: [
      'Základní kompoziční prvky: mapové pole, název, legenda, měřítko.',
      'Legenda musí být úplná a shodná se znaky v mapě.',
      'Generalizace je výběr a zjednodušení obsahu podle měřítka a účelu.',
      'Kvantitu vyjadřuje velikost, kategorie barevný tón nebo tvar, pořadí světlost.',
      'Kartogram je pro relativní hodnoty, absolutní hodnoty patří do kartodiagramu.',
      'Izolinie se hodí pro spojité jevy, např. teplotu či srážky.',
      'Dasymetrická metoda vyloučí neobydlené plochy a zpřesní kartogram.',
      'Kartogram mívá 4 až 7 tříd, sekvenční stupnice jde od světlé k tmavé.',
      'Pro přírůstek a úbytek se hodí divergentní dvoubarevná stupnice.',
      'Popis bodového objektu se přednostně dává vpravo nahoru od znaku.',
    ],
    formulas: [
      ['Hustota zalidnění', 'hustota = počet obyvatel / plocha [obyv./km²]'],
      ['Ekvidistantní intervaly', 'šířka třídy = (max − min) / počet tříd'],
    ],
    terms: [
      ['Kartogram', 'Relativní hodnoty v plošných jednotkách.'],
      ['Kartodiagram', 'Absolutní hodnoty diagramy v jednotkách.'],
      ['Bodová metoda', 'Tečky s pevnou vahou v místě výskytu.'],
      ['Anamorfóza', 'Velikost území změněná podle hodnoty.'],
      ['Kvantily', 'Třídy se stejným počtem jednotek.'],
      ['Přirozené zlomy', 'Jenksova metoda, minimalizuje rozptyl uvnitř tříd.'],
      ['Tiráž', 'Autor, vydavatel, zdroje dat a datum vydání.'],
    ],
    tip: 'Toti radí: než vybarvíš kartogram, zkontroluj, že hodnoty jsou poměrné. Počet obyvatel obcí do kartogramu nepatří, hustota ano.',
  },

  nea035: {
    intro: 'Kosmická geodézie spojuje nebeské souřadnice, čas a rotaci Země s technikami VLBI, SLR, DORIS, gravitačními misemi a InSAR. Z nich vznikají referenční rámce ITRF a ICRF.',
    points: [
      'Rektascenze se měří od jarního bodu, hvězdný čas je hodinový úhel jarního bodu.',
      'Výška světového pólu nad obzorem je rovna astronomické šířce.',
      'Hvězdný den je o 3 min 56 s kratší než střední sluneční den.',
      'TAI − UTC = 37 s, GPS − UTC = 18 s; přestupná sekunda drží |UT1 − UTC| < 0,9 s.',
      'Precese má periodu asi 25 800 let, hlavní člen nutace 18,6 roku, Chandler asi 433 dní.',
      'Refrakce zvětšuje zdánlivou výšku hvězdy, konstanta roční aberace je asi 20,5″.',
      'Jen VLBI (kvasary) spolehlivě určuje UT1, SLR je klíčová pro geocentrum ITRF.',
      'DORIS měří Dopplerův posun signálu pozemních majáků přijímačem na družici.',
      'GRACE měřila změny vzdálenosti dvou družic, GOCE nesla gradiometr.',
      'Diferenční InSAR měří posun ve směru záměry radaru (LOS).',
    ],
    formulas: [
      ['Hodinový úhel', 't = s − α'],
      ['Zenitová vzdálenost', 'z = 90° − h'],
      ['Šířka z kulminace jižně od zenitu', 'φ = δ + z'],
      ['Vzdálenost z paralaxy', 'd [pc] = 1 / π [″],  1 pc ≈ 206 265 au ≈ 3,26 ly'],
      ['SLR vzdálenost', 'd = c · t / 2'],
      ['Pseudovzdálenost GNSS', 'ρ = c · Δt'],
      ['Oběžná doba (3. Keplerův zákon)', 'T = 2π · √(a³ / GM),  a = R + h'],
    ],
    terms: [
      ['Parsek', 'Vzdálenost, z níž je roční paralaxa 1″.'],
      ['UT1', 'Čas odvozený ze skutečné rotace Země.'],
      ['IERS', 'Služba pro rotaci Země a referenční rámce.'],
      ['VLBI', 'Rádiová interferometrie kvasarů na dlouhých základnách.'],
      ['LAGEOS', 'Pasivní koule s koutovými odražeči pro SLR.'],
      ['LOS', 'Směr záměry radaru, ve kterém InSAR měří posun.'],
      ['Zenitová kamera', 'Digitální přístroj pro astronomické Φ a Λ.'],
    ],
    tip: 'Toti radí: u SLR nezapomeň dělit dvěma, pulz letí tam i zpět. U GNSS se dvěma nedělí, signál letí jen jedním směrem.',
  },

  nea041: {
    intro: 'Digitální model terénu je základ pro projekty, objemy, hydrologii i viditelnost. Kvalitu určuje sběr dat, reprezentace, interpolace a lomové linie.',
    points: [
      'DMR 4G a DMR 5G vznikly z celostátního leteckého laserového skenování.',
      'LLS proniká korunami k terénu, obrazová korelace vidí jen povrch (DMP).',
      'Při tachymetrii se měří hlavně terénní hrany a lomy sklonu.',
      'GRID je pravidelná mřížka, TIN přizpůsobí hustotu členitosti terénu.',
      'Delaunayova triangulace má prázdné opsané kružnice a maximalizuje nejmenší úhel.',
      'IDW je vážený průměr, nikdy nepřekročí rozsah vstupních výšek.',
      'Kriging vychází z variogramu a dává i odhad přesnosti interpolace.',
      'Lomové linie se do TIN zavádějí jako povinné hrany.',
      'Přesnost DMT se udává RMSE na nezávislých kontrolních bodech.',
      'Před hydrologickou analýzou se odstraní bezodtokové deprese, odtok řídí D8.',
    ],
    formulas: [
      ['Sklon ve stupních', 'α = arctg(Δh / d)'],
      ['Sklon v procentech', 's = Δh / d · 100 %'],
      ['Sklon z gradientu', 'α = arctg √(p² + q²),  p = ∂z/∂x, q = ∂z/∂y'],
      ['IDW', 'z = Σ wᵢ · zᵢ / Σ wᵢ,  wᵢ = 1 / dᵢᵖ'],
      ['Normalizovaný model povrchu', 'nDSM = DMP − DMR'],
      ['Přesnost modelu', 'RMSE = √(Σ Δh² / n)'],
    ],
    terms: [
      ['DMR 4G', 'GRID 5 × 5 m.'],
      ['DMR 5G', 'TIN holého terénu.'],
      ['DMP 1G', 'Povrch s budovami a vegetací.'],
      ['Nugget', 'Nespojitost variogramu v počátku.'],
      ['Dosah (range)', 'Vzdálenost, kde končí korelace.'],
      ['Aspect', 'Azimut směru největšího spádu.'],
      ['Viewshed', 'Území viditelné ze stanoviska.'],
    ],
    tip: 'Toti radí: sklon 45° je 100 %, ne 45 %. A při tachymetrii nestav stativ naslepo, vyber místo, odkud vidíš všechny hrany svahu.',
  },

  nea042: {
    intro: 'GIS 2 prohlubuje teorii informace, registry, relační a prostorové SQL, grafové algoritmy, topologii a kvalitu dat až po webové služby. Jde o nástroje pro práci s geodaty ve velkém.',
    points: [
      'Shannonova entropie je střední množství informace zdroje.',
      'Základní registry ČR: ROB, ROS, RÚIAN a RPP; RÚIAN spravuje ČÚZK.',
      'Selekci odpovídá WHERE, projekci výčet sloupců za SELECT.',
      'ST_Intersects je opak ST_Disjoint; ST_Distance v EPSG:4326 vrací stupně.',
      'Prostorový index v PostGIS je GiST nad obalovými obdélníky.',
      'Minimální kostru hledá Kruskal a Prim, nejkratší cestu Dijkstra (bez záporných hran).',
      'Uzavřený eulerovský tah existuje, když mají všechny uzly sudý stupeň.',
      'Topologické predikáty vycházejí z modelu DE-9IM.',
      'Metadata popisuje ISO 19115, kvalitu dat ISO 19157.',
      'WMS vrací obrázek, WFS vektory, WMTS dlaždice, CSW metadata.',
    ],
    formulas: [
      ['Shannonova entropie', 'H = −Σ pᵢ · log₂ pᵢ'],
      ['Informace jevu', 'I = log₂ N (N stejně pravděpodobných jevů)'],
    ],
    terms: [
      ['Primární klíč', 'Jednoznačně identifikuje řádek tabulky.'],
      ['Cizí klíč', 'Odkaz do jiné tabulky.'],
      ['Čínský pošťák', 'Nejkratší uzavřený sled přes všechny hrany.'],
      ['Hamiltonovská cesta', 'Prochází každým uzlem právě jednou.'],
      ['k-means', 'Shlukování s předem zvoleným počtem shluků.'],
      ['AHP', 'Saatyho párové srovnání pro váhy kritérií.'],
      ['Fokální operace', 'Výpočet z okolí buňky, např. sklon z okna 3 × 3.'],
      ['Ontologie', 'Formální popis pojmů a vztahů v oboru.'],
    ],
    tip: 'Toti radí: počítáš vzdálenosti v PostGIS? Nejdřív zkontroluj souřadnicový systém. Ve WGS 84 dostaneš stupně, ne metry.',
  },

  nea046: {
    intro: 'Fotogrammetrie rekonstruuje prostor ze snímků, DPZ vyhodnocuje spektrální odraz povrchu z družic. Výstupem jsou ortofota, modely i mapy krajinného pokryvu.',
    points: [
      'Relativní orientace má 5 prvků, absolutní 7 (3 posuny, 3 rotace, měřítko).',
      'Minimum pro absolutní orientaci: dva polohově-výškové a jeden výškový bod.',
      'Chyba hloubky roste s druhou mocninou vzdálenosti Z.',
      'U leteckých snímků je výška určena hůř než poloha, poměr zhruba h / B.',
      'Diferenciální překreslení potřebuje orientovaný snímek a DMT.',
      'True ortofoto používá DMP a odstraní sklápění budov.',
      'Chybné korespondence odstraňuje RANSAC, SIFT je invariantní k měřítku a rotaci.',
      'Zdravá vegetace má nízkou odrazivost v červené a vysokou v blízké IR.',
      'Sentinel-2 má nejlepší rozlišení 10 m, Landsat 8 a 9 multispektrálně 30 m.',
      'Sentinel-1 nese radar SAR v pásmu C, snímkuje přes mraky i v noci.',
    ],
    formulas: [
      ['Měřítkové číslo snímku', 'm_s = h / c'],
      ['GSD', 'GSD = velikost pixelu · h / c'],
      ['Hloubka v normálním případě', 'Z = B · c / p'],
      ['Chyba hloubky', 'σ_Z = Z² / (B · c) · σ_p'],
      ['Reliéfní posun', 'Δr = r · Δh / h'],
      ['Radiální distorze', 'Δr = k₁r³ + k₂r⁵ + k₃r⁷'],
      ['NDVI', 'NDVI = (NIR − R) / (NIR + R)'],
      ['Wienův zákon', 'λ_max ≈ 2 898 µm·K / T'],
    ],
    terms: [
      ['Koplanarita', 'Základna a oba paprsky leží v jedné rovině.'],
      ['Gruberovy body', 'Šest bodů pro relativní orientaci.'],
      ['Boresight', 'Úhly mezi IMU a kamerou.'],
      ['NCC', 'Normovaný korelační koeficient pro obrazovou korelaci.'],
      ['Atmosférické okno', 'Část spektra propouštěná atmosférou.'],
      ['ISODATA', 'Algoritmus neřízené klasifikace.'],
      ['Chybová matice', 'Hodnocení přesnosti klasifikace, koeficient kappa.'],
      ['L2A', 'Sentinel-2 po atmosférické korekci (BOA).'],
    ],
    tip: 'Toti radí: hlídej jednotky. Pixel v µm, c v mm a výšku v m převeď dřív, než je dosadíš, jinak ti GSD vyjde o řády vedle.',
  },

  nea047: {
    intro: 'Fyzikální geodézie popisuje tíhové pole Země, slapy a pohyby kůry, inerciální systémy určují polohu z gyroskopů a akcelerometrů. Obojí se dnes kombinuje s GNSS.',
    points: [
      'Geopotenciální modely jsou rozvojem do sférických harmonických funkcí.',
      'EGM2008 je úplný do stupně a řádu 2159 (asi 5′).',
      'Koeficient C₂₀ (J₂ ≈ 1,08 · 10⁻³) popisuje zploštění Země.',
      'Koeficienty stupně 1 jsou nulové, je-li počátek v těžišti Země.',
      'Slapový účinek Měsíce je asi dvakrát silnější než Slunce, hlavní vlna je M2.',
      'Svislé slapy pevné Země dosahují několika decimetrů.',
      'Euroasijská deska se v ITRF pohybuje asi 2–3 cm za rok, ETRS89 je s ní spojen.',
      'RLG a FOG využívají Sagnacův jev, MEMS gyroskop Coriolisovu sílu.',
      'Akcelerometr měří specifickou sílu, ve volném pádu ukazuje nulu.',
      'Chyba samostatného INS roste s časem, proto se podpírá GNSS Kalmanovým filtrem.',
    ],
    formulas: [
      ['Rozlišení modelu stupně n', 'λ/2 ≈ 20 000 km / n'],
      ['Oběžná doba družice', 'T = 2π · √(a³ / GM),  a = R + h'],
      ['Schulerova perioda', 'T = 2π · √(R / g) ≈ 84,4 min'],
      ['Výška hladiny z altimetrie', 'h_hladiny = h_dráhy − měřená vzdálenost'],
    ],
    terms: [
      ['Zonální koeficienty', 'Řád m = 0, nezávisí na délce.'],
      ['Loveova čísla', 'Pružná odezva Země na slapy (h, k, l).'],
      ['Dynamická topografie', 'Rozdíl střední hladiny moře a geoidu.'],
      ['GGOS', 'Globální geodetický pozorovací systém IAG.'],
      ['Strapdown', 'Senzory pevně spojené s nosičem.'],
      ['Lock-in', 'Necitlivost RLG při malé rotaci, řeší se ditherem.'],
      ['Těsná integrace', 'INS využije pseudovzdálenosti i z méně než 4 družic.'],
    ],
    tip: 'Toti radí: u oběžné doby počítej s poloosou a = R + h, ne jen s výškou nad povrchem. GPS ve 20 200 km oběhne Zemi asi za 12 hodin.',
  },

  neb045: {
    intro: 'BIM je správa informací o stavbě v celém životním cyklu. Geodet do něj dodává zaměření skutečného stavu, georeferenci modelu a kontrolu provedení.',
    points: [
      'OpenBIM je spolupráce přes otevřené formáty, hlavně IFC.',
      '4D BIM přidává čas, 5D náklady.',
      'Zavádění BIM v ČR koordinuje Česká agentura pro standardizaci.',
      'IFC je normou ISO 16739, spravuje ho buildingSMART International.',
      'IFC 4.3 přidalo dopravní infrastrukturu včetně IfcAlignment.',
      'ČSN EN ISO 19650 řeší správu informací, role a CDE.',
      'Stavy v CDE: rozpracované, sdílené, publikované, archivované.',
      'IFC popisuje objemy, CityGML (OGC) povrchy.',
      'Model se georeferencuje do S-JTSK a Bpv, v IFC 4 např. IfcMapConversion.',
      'Přesnost scan-to-BIM se ověřuje mapou odchylek model–mračno.',
    ],
    formulas: [],
    terms: [
      ['CIM', 'Informační model na úrovni města.'],
      ['Digitální dvojče', 'Průběžně aktualizovaný obraz reálné stavby.'],
      ['EIR', 'Informační požadavky objednatele.'],
      ['BEP', 'Plán realizace BIM od dodavatele.'],
      ['bSDD', 'Online slovník pojmů a vlastností (IFD).'],
      ['Federovaný model', 'Spojení samostatných profesních modelů.'],
      ['LOD 500', 'Ověřený model skutečného provedení.'],
      ['LOIN', 'Potřebná úroveň informací pro účel a milník.'],
    ],
    tip: 'Toti radí: terče pro skenování zaměř i totální stanicí v S-JTSK a Bpv. Bez toho model nebude georeferencovaný a registraci nebudeš mít čím zkontrolovat.',
  },

  neb039: {
    intro: 'Geomatika propojuje software, databáze, formáty a standardy geodat s prostorovými analýzami a publikací ve 3D a na webu. Je to praktická výbava pro každý GIS projekt.',
    points: [
      'QGIS je open source (OSGeo), GRASS GIS je silný v rastrových analýzách.',
      'Formáty čte a zapisuje hlavně knihovna GDAL/OGR.',
      'PostGIS přidává do PostgreSQL geometrie, prostorové indexy a funkce ST_*.',
      'GeoPackage ukládá vektory i rastry do jednoho souboru SQLite.',
      'GeoJSON podle RFC 7946 používá WGS 84 v pořadí délka, šířka.',
      'Shapefile tvoří více souborů, názvy atributů mají max. 10 znaků.',
      'Standardy WMS, WFS a GeoPackage vydává OGC, metadata popisuje ISO 19115.',
      'Úplnost řeší chybějící a nadbytečné objekty, mezery a překryvy jsou chybou topologie.',
      'Interpolace IDW nevytvoří hodnotu mimo rozsah vstupů, kriging dává i rozptyl.',
      'CityGML popisuje 3D modely měst v úrovních detailu LOD.',
    ],
    formulas: [
      ['Sklon ve stupních', 'α = arctg(Δh / d)'],
      ['IDW', 'z = Σ wᵢ · zᵢ / Σ wᵢ,  wᵢ = 1 / dᵢᵖ'],
      ['Normalizovaný model povrchu', 'nDSM = DMP − DMR'],
    ],
    terms: [
      ['LAZ', 'Bezeztrátově komprimovaný LAS.'],
      ['GeoTIFF', 'Rastr TIFF s georeferenčními značkami.'],
      ['MMS', 'Mobilní mapovací systém na vozidle.'],
      ['INSPIRE', 'Infrastruktura prostorových informací v EU.'],
      ['WCS', 'Služba pro rastrová data (coverage).'],
      ['Reklasifikace', 'Nové hodnoty rastru podle intervalů.'],
      ['Intersect', 'Jen části společné oběma vrstvám.'],
    ],
    tip: 'Toti radí: před analýzou ověř, že všechny vrstvy mají stejný souřadnicový systém. Buffer 50 m ve stupních dopadne hodně divně.',
  },

  nza018: {
    intro: 'Kapitola spojuje občanské právo k nemovitostem, katastrální a správní řízení s oceňováním. Geodet díky tomu ví, k čemu slouží jeho GP a vytyčení.',
    points: [
      'Občanský zákoník je zákon č. 89/2012 Sb., účinný od 1. 1. 2014.',
      'Platí zásada superficies solo cedit, stavba je součástí pozemku, kromě staveb dočasných.',
      'Vlastnické právo zapisované do KN se nabývá až vkladem.',
      'Vklad lze provést nejdříve po 20 dnech od odeslání vyrozumění.',
      'Účinky vkladu nastávají ke dni podání návrhu.',
      'Věcná břemena se dělí na služebnosti a reálná břemena.',
      'Právo stavby lze zřídit nejdéle na 99 let.',
      'Řádné vydržení nemovitosti trvá 10 let, mimořádné 20 let.',
      'Odvolání podle správního řádu se podává do 15 dnů od oznámení.',
      'Cena obvyklá je tržní, cena zjištěná se určuje podle zákona č. 151/1997 Sb. a vyhlášky.',
    ],
    formulas: [
      ['Výnosová hodnota (věčná renta)', 'C = V / i'],
      ['Nákladová (věcná) hodnota', 'C = RC · (1 − opotřebení)'],
    ],
    terms: [
      ['Služebnost', 'Vlastník musí něco trpět nebo se zdržet.'],
      ['Reálné břemeno', 'Vlastník musí něco dávat nebo konat.'],
      ['Vklad, záznam, poznámka', 'Tři způsoby zápisu práv do KN.'],
      ['SJM', 'Společné jmění manželů.'],
      ['Právní moc', 'Rozhodnutí oznámeno a nelze se již odvolat.'],
      ['Povolení záměru', 'Jedno řízení podle zákona č. 283/2021 Sb.'],
      ['Nezbytná cesta', 'Přístup přes cizí pozemek povolený soudem.'],
    ],
    tip: 'Toti radí: u výnosové metody převeď procenta na desetinné číslo. 240 000 Kč při 6 % znamená dělit 0,06, ne šesti.',
  },

  nea043: {
    intro: 'Komplexní projekt prochází celou zakázku od zadání a rekognoskace přes síť, sběr dat a vytyčení po vyrovnání a technickou zprávu. Učí plánovat, kontrolovat a obhájit výsledek.',
    points: [
      'Před volbou metod musí být jasná požadovaná přesnost a forma výstupu.',
      'Rekognoskace ověřuje body, přístupnost, viditelnost a zákryty obzoru pro GNSS.',
      'Zničený bod bodového pole se ohlásí a síť se připojí na jiné body.',
      'Pro opakované přesné měření posunů je nejlepší pilíř s nucenou centrací.',
      'Vlícovací body UAV se rozmístí rovnoměrně po obvodu i uvnitř bloku.',
      'Kontrolní body se do výpočtu nezavádějí, slouží jen k ověření přesnosti.',
      'Síť s mm přesností se měří statickou GNSS, výška antény se měří k ARP.',
      'Primární systém stavby tvoří vytyčovací síť, sekundární hlavní a podrobné osy.',
      'Vytyčený bod se kontroluje nezávislým měřením, např. z jiného stanoviska.',
      'Při nivelaci ze středu jsou záměry vzad a vpřed stejně dlouhé.',
    ],
    formulas: [
      ['Délka GNSS základny', 's = √(ΔX² + ΔY² + ΔZ²)'],
      ['Polohová chyba polárního vytyčení', 'm_p = √(m_d² + (d · m_ω)²)'],
      ['Převod cc na radiány', 'm_ω (rad) = m_ω (cc) · π / 2 000 000'],
      ['Polární vytyčení', 'σ_SP = σ_SO + ω,  Y_P = Y_S + d · sin σ_SP,  X_P = X_S + d · cos σ_SP'],
      ['Převýšení v nivelaci', 'Δh = čtení vzad − čtení vpřed'],
      ['Empirická přesnost', 'RMSE = √(Σ Δ² / n)'],
    ],
    terms: [
      ['Rekognoskace', 'Ověření podkladů a podmínek přímo v terénu.'],
      ['Nucená centrace', 'Centrace na pilíři s chybou v desetinách mm.'],
      ['GCP', 'Vlícovací bod pro georeferencování snímků.'],
      ['ARP', 'Referenční bod antény GNSS.'],
      ['RINEX', 'Výměnný formát GNSS observací.'],
      ['CZEPOS', 'Síť permanentních stanic GNSS ČÚZK.'],
      ['Provažovač', 'Přenáší svislou osu do vyšších podlaží.'],
    ],
    tip: 'Toti radí: stav nivelační přístroj tak, aby záměry vzad a vpřed byly stejně dlouhé. Nemusíš stát na spojnici latí, a když je tam strom, klidně ho obejdi.',
  },
};
