// Kapitoly podle osnov VUT FAST (Bc., 1.–2. ročník): Geodézie 1–3, TCVP 1, Geodetické programy.
// Formát otázek viz js/content/u01-03.js.

export default [
  {
    id: 'bea003', title: 'Geodézie 1', color: '#2563eb', level: 'Bc.', course: 'BEA003', sem: '1. ročník · ZS',
    desc: 'Měřické pomůcky, teodolit a totální stanice, měření směrů, svislých úhlů a délek včetně redukcí.',
    lessons: [
      {
        id: 'bea003l1', title: 'Pomůcky, libely, olovnice', icon: '🧰', gens: ['bubble'],
        items: [
          { t: 'c', q: 'Citlivost trubicové libely je dána…', a: 'úhlem náklonu na 1 dílek stupnice', w: ['délkou celé trubice libely', 'počtem dílků na stupnici', 'velikostí vzduchové bubliny'], e: 'Citlivost je úhlová hodnota dílku (obvykle 2 mm) – čím menší úhel, tím citlivější libela.' },
          { t: 'c', q: 'Osa trubicové libely je…', a: 'tečna k výbrusu v nulovém bodě', w: ['spojnice obou konců trubice', 'osa symetrie pouzdra libely', 'kolmice k výbrusu v nulovém bodě'], e: 'Je-li bublina uprostřed, je tečna k výbrusu v nulovém bodě vodorovná.' },
          { t: 'c', q: 'Krabicová libela slouží hlavně k…', a: 'hrubé horizontaci přístroje', w: ['jemné horizontaci teodolitu', 'měření svislých úhlů', 'kontrole zaostření'], e: 'Krabicová libela je řádově méně citlivá než trubicová; stačí na hrubé urovnání.' },
          { t: 'c', q: 'Při urovnání alhidádové libely třemi šrouby natočíte libelu nejprve…', a: 'rovnoběžně se spojnicí dvou šroubů', w: ['kolmo ke spojnici dvou šroubů', 'přímo nad třetí šroub', 'libovolně, na směru nezáleží'], e: 'Dva šrouby se točí proti sobě, pak se alhidáda otočí o 100 gon a urovná se třetím šroubem.' },
          { t: 'tf', q: 'Bublina libely se pohybuje vždy k výše položenému konci.', a: true, e: 'Bublina je lehčí než kapalina, proto „stoupá“ k vyššímu konci trubice.' },
          { t: 'c', q: 'Olovnice vytyčuje…', a: 'svislici (směr tíže)', w: ['vodorovnou rovinu', 'normálu k elipsoidu', 'směr k severu'], e: 'Olovnice se ustálí ve směru tížnice – ne normály k elipsoidu.' },
          { t: 'c', q: 'Pravý úhel se v terénu jednoduše vytyčí…', a: 'pentagonálním hranolem', w: ['krabicovou libelou', 'šňůrovou olovnicí', 'nivelační latí'], e: 'Pentagon odchyluje paprsek o 100 gon; kolmice se pak vyznačí výtyčkou.' },
          { t: 'm', q: 'Spojte pomůcku s účelem', p: [['Výtyčka', 'Označení bodu a směru'], ['Pentagonální hranol', 'Vytyčení pravého úhlu'], ['Olovnice', 'Svislice nad bodem'], ['Krabicová libela', 'Hrubé urovnání'], ['Pásmo', 'Měření délek']] },
        ],
      },
      {
        id: 'bea003l2', title: 'Teodolit a totální stanice', icon: '🔭', gens: ['station'],
        items: [
          { t: 'c', q: 'Kolem které osy se otáčí dalekohled teodolitu?', a: 'Točné (klopné) osy H', w: ['Svislé (vertikální) osy V', 'Záměrné osy Z', 'Osy alhidádové libely L'], e: 'Dalekohled se klopí kolem točné osy H, alhidáda se otáčí kolem svislé osy V.' },
          { t: 'c', q: 'Osa alhidádové libely L musí být kolmá k…', a: 'svislé ose V', w: ['záměrné ose Z', 'točné ose H', 'ose optického dostřeďovače'], e: 'Podmínka L ⊥ V: po urovnání libely je svislá osa ve svislici.' },
          { t: 'c', q: 'Kolimační chyba je nesplnění podmínky…', a: 'Z ⊥ H', w: ['L ⊥ V', 'H ⊥ V', 'Z ∥ L'], e: 'Záměrná přímka není kolmá k točné ose; vyloučí se měřením ve dvou polohách.' },
          { t: 'tf', q: 'Vliv nesvislosti osy V nelze odstranit měřením ve dvou polohách dalekohledu.', a: true, e: 'Sklon svislé osy se v obou polohách nemění – řeší se pečlivou horizontací a dvouosým kompenzátorem.' },
          { t: 'c', q: 'Dvouosý kompenzátor totální stanice opravuje čtení o…', a: 'vliv malého sklonu svislé osy', w: ['kolimační chybu dalekohledu', 'chybu z excentricity kruhu', 'refrakci záměrné přímky'], e: 'Kompenzátor měří podélný i příčný sklon osy V a opravuje vodorovné i svislé čtení.' },
          { t: 'c', q: 'Alhidáda je…', a: 'otočná horní část nesoucí dalekohled', w: ['trojnožka se stavěcími šrouby', 'hlava stativu s upínacím šroubem', 'dělený kruh pro svislé úhly'], e: 'Alhidáda nese dalekohled, libelu a čtecí zařízení; limbus je vodorovný dělený kruh.' },
          { t: 'c', q: 'Ostrost ryskového kříže nastavíte…', a: 'otáčením okuláru', w: ['zaostřovacím šroubem dalekohledu', 'stavěcími šrouby trojnožky', 'jemnou ustanovkou alhidády'], e: 'Nejdřív okulárem ostrý kříž, pak zaostřovacím šroubem cíl – tím se odstraní paralaxa.' },
          { t: 'm', q: 'Spojte chybu s osovou podmínkou', p: [['Kolimační chyba', 'Z ⊥ H'], ['Úklonná chyba', 'H ⊥ V'], ['Nesvislost osy V', 'L ⊥ V'], ['Indexová chyba', 'Nula svislého kruhu v zenitu']] },
          { t: 'o', q: 'Seřaďte postavení přístroje nad bod', s: ['Postavit stativ zhruba nad bod', 'Upevnit přístroj a zacílit dostřeďovač na bod', 'Urovnat krabicovou libelu nohami stativu', 'Jemně urovnat alhidádovou libelu šrouby', 'Zkontrolovat centraci a posunout přístroj na hlavě stativu'], e: 'Centrace a horizontace se navzájem ovlivňují, proto se na konci obě kontrolují.' },
        ],
      },
      {
        id: 'bea003l3', title: 'Vodorovné směry', icon: '📐', gens: ['angleDiff'],
        items: [
          { t: 'c', q: 'Vodorovný úhel se určí jako rozdíl čtení na cíle…', a: 'vpravo minus vlevo', w: ['vlevo minus vpravo', 'I. poloha minus II. poloha', 'na cíl minus na zenit'], e: 'ω = čtení vpravo − čtení vlevo (+ 400 gon, vyjde-li záporné).' },
          { t: 'c', q: 'Měření ve dvou polohách dalekohledu vyloučí…', a: 'kolimační a úklonnou chybu', w: ['chybu ze sklonu svislé osy', 'chybu z centrace přístroje', 'chybu z cílení na signál'], e: 'Tyto chyby mění v II. poloze znaménko, průměr je tedy odstraní.' },
          { t: 'c', q: 'Čtení na tentýž cíl se v I. a II. poloze liší přibližně o…', a: '200 gon', w: ['100 gon', '400 gon', '0 gon'], e: 'Alhidáda se otočí o 200 gon a dalekohled se proloží.' },
          { t: 'c', q: 'Jednu skupinu ve skupinové metodě tvoří…', a: 'všechny směry měřené v obou polohách', w: ['jeden směr měřený v jedné poloze', 'jeden úhel měřený ze dvou stanovisek', 'opakované čtení na tentýž cíl'], e: 'I. poloha postupně na všechny cíle, II. poloha v opačném pořadí, pak redukce na první směr.' },
          { t: 'tf', q: 'Ve II. poloze se cíle ve skupinové metodě obvykle cílí v opačném pořadí než v I. poloze.', a: true, e: 'Symetrie v čase omezuje vliv pomalého stáčení stativu.' },
          { t: 'c', q: 'Proč se mezi skupinami mění počáteční čtení na kruhu?', a: 'omezí se vliv chyb dělení kruhu', w: ['vyloučí se kolimační chyba', 'zkrátí se doba měření', 'vyloučí se boční refrakce'], e: 'Směry se čtou na různých místech kruhu a chyby dělení se zprůměrují.' },
          { t: 'n', q: 'Čtení na cíl v I. poloze 52,3418 gon, ve II. poloze 252,3426 gon. Jaký je průměrný směr?', a: 52.3422, tol: 0.00006, dec: 4, unit: 'gon', e: '(52,3418 + 252,3426 − 200) / 2 = 52,3422 gon; rozdíl 0,8 mgon je ≈ dvojnásobek kolimační chyby.' },
          { t: 'c', q: 'Redukce osnovy směrů znamená…', a: 'odečtení prvního směru od všech', w: ['přičtení 200 gon ke II. poloze', 'převod směrů na směrníky', 'oprava směrů o refrakci'], e: 'Redukovaná osnova začíná nulou, takže skupiny lze průměrovat.' },
          { t: 'o', q: 'Seřaďte měření jedné skupiny', s: ['I. poloha: cílit na první cíl', 'I. poloha: další cíle po směru hodinových ručiček', 'Proložit dalekohled do II. polohy', 'II. poloha: cíle v opačném pořadí', 'Spočítat průměry a redukovat na první směr'], e: 'Tak se měří osnova směrů skupinovou metodou.' },
        ],
      },
      {
        id: 'bea003l4', title: 'Svislé úhly', icon: '📏', gens: ['hdFromSd'],
        items: [
          { t: 'c', q: 'Zenitový úhel vodorovné záměry je…', a: '100 gon', w: ['0 gon', '200 gon', '400 gon'], e: 'Zenitový úhel se měří od zenitu (0) přes horizont (100) k nadiru (200).' },
          { t: 'c', q: 'Výškový úhel α souvisí se zenitovým úhlem z vztahem…', a: 'α = 100 gon − z', w: ['α = z − 100 gon', 'α = 200 gon − z', 'α = z + 100 gon'], e: 'Záměra nad horizont má z < 100 gon a kladný výškový úhel.' },
          { t: 'c', q: 'Součet zenitových úhlů v I. a II. poloze je bez indexové chyby…', a: '400 gon', w: ['200 gon', '100 gon', '0 gon'], e: 'z_I + z_II = 400 gon + 2i, odtud indexová chyba i.' },
          { t: 'n', q: 'z_I = 96,1234 gon, z_II = 303,8790 gon. Jaká je indexová chyba v mgon?', a: 1.2, tol: 0.05, dec: 1, unit: 'mgon', e: 'i = (z_I + z_II − 400) / 2 = 0,0024 / 2 gon = 1,2 mgon.' },
          { t: 'n', q: 'z_I = 96,1234 gon, z_II = 303,8790 gon. Jaký je opravený zenitový úhel?', a: 96.1222, tol: 0.00006, dec: 4, unit: 'gon', e: 'z = (z_I − z_II + 400) / 2 = 96,1222 gon.' },
          { t: 'tf', q: 'Indexovou chybu vyloučí měření ve dvou polohách dalekohledu.', a: true, e: 'Průměr z obou poloh je na indexové chybě nezávislý.' },
          { t: 'c', q: 'Vodorovná délka ze šikmé délky s a zenitového úhlu z je…', a: 'd = s · sin z', w: ['d = s · cos z', 'd = s · tg z', 'd = s / sin z'], e: 'Pro z = 100 gon je sin z = 1 a d = s.' },
          { t: 'm', q: 'Spojte zenitový úhel se záměrou', p: [['z = 0 gon', 'Zenit'], ['z = 100 gon', 'Vodorovná záměra'], ['z = 200 gon', 'Nadir'], ['z = 80 gon', 'Záměra 20 gon vzhůru']] },
        ],
      },
      {
        id: 'bea003l5', title: 'Měření délek', icon: '📡', gens: ['ppmError', 'lengthReduction'],
        items: [
          { t: 'c', q: 'Paralaktická metoda určuje délku z úhlu na…', a: 'vodorovnou lať známé délky', w: ['svislou nivelační lať', 'odrazný hranol', 'pásmo napnuté siloměrem'], e: 'd = (b/2) · cotg(γ/2), kde b je délka základnové latě (typicky 2 m).' },
          { t: 'c', q: 'Fázový dálkoměr určuje délku z…', a: 'fázového rozdílu vyslané a přijaté vlny', w: ['doby letu jednoho impulsu', 'Dopplerova posunu frekvence', 'úhlu mezi dvěma paprsky'], e: 'Počet celých vlnových délek se řeší několika modulačními frekvencemi.' },
          { t: 'c', q: 'Impulsní dálkoměr měří…', a: 'dobu letu impulsu tam a zpět', w: ['fázi modulované vlny', 'intenzitu odraženého světla', 'frekvenci nosné vlny'], e: 'd = c · t / 2; hodí se pro měření bez hranolu a na velké vzdálenosti.' },
          { t: 'c', q: 'U přesnosti 2 mm + 2 ppm je složka úměrná délce na 1 km…', a: '2 mm', w: ['0,2 mm', '20 mm', '0,02 mm'], e: '1 ppm = 1 mm na 1 km; k tomu se připočte konstantní složka.' },
          { t: 'c', q: 'Atmosférická korekce EDM závisí hlavně na…', a: 'teplotě a tlaku vzduchu', w: ['zeměpisné délce stanoviska', 'barvě odrazného hranolu', 'výšce přístroje nad bodem'], e: 'Teplota a tlak (méně vlhkost) mění index lomu a tím rychlost šíření vlny.' },
          { t: 'tf', q: 'Při vyšší teplotě vzduchu je atmosférická korekce záporná.', a: false, e: 'Vyšší teplota → menší index lomu → korekce je kladná; neopravená délka je kratší.' },
          { t: 'c', q: 'Délku měřenou ocelovým pásmem opravujeme o…', a: 'komparaci, teplotu a sklon', w: ['refrakci a zakřivení Země', 'konstantu odrazného hranolu', 'indexovou chybu kruhu'], e: 'Komparace = skutečná délka pásma, teplotní roztažnost oceli, převod na vodorovnou délku.' },
          { t: 'c', q: 'Redukce délky do nulového horizontu (výška H) je…', a: 'd₀ = d · (1 − H/R)', w: ['d₀ = d · (1 + H/R)', 'd₀ = d · H/R', 'd₀ = d − R/H'], e: 'Ve výšce 500 m se 1 km zkrátí asi o 7,8 cm (R ≈ 6 380 km).' },
          { t: 'o', q: 'Seřaďte převod měřené délky do roviny S-JTSK', s: ['Šikmá délka z dálkoměru', 'Oprava o atmosférickou korekci', 'Převod na vodorovnou délku', 'Redukce do nulového horizontu', 'Oprava z kartografického zkreslení'], e: 'Nejdřív fyzikální korekce, pak matematické redukce na referenční plochu a do zobrazení.' },
        ],
      },
    ],
  },

  {
    id: 'bea004', title: 'Geodézie 2', color: '#059669', level: 'Bc.', course: 'BEA004', sem: '1. ročník · LS',
    desc: 'Nivelační přístroje a nivelace, bodová pole, trigonometrické výšky, podrobné měření a výpočty ploch a objemů.',
    lessons: [
      {
        id: 'bea004l1', title: 'Nivelační přístroje', icon: '🎯', gens: ['levelSetup'],
        items: [
          { t: 'c', q: 'Kompenzátor nivelačního přístroje automaticky…', a: 'urovná záměrnou přímku do vodorovné', w: ['vypočte převýšení mezi latěmi', 'odečte čtení na lati', 'změří vzdálenost k lati'], e: 'Po hrubém urovnání krabicovou libelou zajistí kompenzátor vodorovnou záměru.' },
          { t: 'c', q: 'Digitální nivelační přístroj odečítá…', a: 'čárový kód na lati', w: ['centimetrové dělení latě', 'stopu laserového paprsku', 'odraz od hranolu'], e: 'Obraz kódu se porovná s referenčním vzorem; zároveň se určí vzdálenost k lati.' },
          { t: 'c', q: 'i-chyba nivelačního přístroje je…', a: 'sklon záměrné přímky od vodorovné', w: ['sklon svislé osy od tížnice', 'chyba v dělení nivelační latě', 'rozdíl délek záměr vzad a vpřed'], e: 'Nesplnění podmínky, že záměrná přímka je vodorovná, když kompenzátor pracuje.' },
          { t: 'c', q: 'Vliv i-chyby se při nivelaci ze středu…', a: 'vyloučí při stejně dlouhých záměrách', w: ['zdvojnásobí na každé sestavě', 'nedá se nijak odstranit', 'vyloučí jen u digitálních přístrojů'], e: 'Chyba čtení je úměrná délce záměry – při stejných délkách se v převýšení odečte.' },
          { t: 'n', q: 'Zkouška: převýšení ze středu je 0,412 m. U lati A čtete A = 1,532 m, na vzdálené lati B = 1,108 m. Jaké má být správné čtení na B?', a: 1.120, tol: 0.0005, dec: 3, unit: 'm', e: 'B_správně = A − Δh = 1,532 − 0,412 = 1,120 m; záměra je skloněna dolů o 12 mm.' },
          { t: 'tf', q: 'Při zkoušce ze středu a z konce je převýšení měřené ze středu správné i s i-chybou.', a: true, e: 'Ze středu jsou záměry stejně dlouhé, i-chyba se v převýšení vyruší.' },
          { t: 'c', q: 'Nivelační podložka („žabka“) slouží jako…', a: 'stabilní přestavový bod pro lať', w: ['stojan pro nivelační přístroj', 'závaží pro napnutí pásma', 'značka bodového pole'], e: 'Na přestavovém bodě se čte vpřed i vzad, lať proto nesmí sednout.' },
          { t: 'o', q: 'Seřaďte zkoušku nivelačního přístroje ze středu a z konce', s: ['Postavit přístroj uprostřed mezi latě A a B', 'Změřit správné převýšení ze středu', 'Přestavit přístroj těsně k lati A', 'Přečíst lať A a vzdálenou lať B', 'Vypočítat správné čtení na B', 'Rektifikovat záměrnou přímku'], e: 'Z konce vliv i-chyby působí jen na vzdálenou lať, proto ji lze přímo určit.' },
        ],
      },
      {
        id: 'bea004l2', title: 'Bodová pole a stabilizace', icon: '📍',
        items: [
          { t: 'c', q: 'Zkratka ZPBP znamená…', a: 'základní polohové bodové pole', w: ['zhušťovací polohové bodové pole', 'závazné podrobné bodové pole', 'zeměměřické pomocné body'], e: 'Nosnou kostru tvoří body referenční sítě a České státní trigonometrické sítě.' },
          { t: 'c', q: 'Zhušťovací body patří do…', a: 'podrobného polohového bodového pole', w: ['základního nivelačního pole', 'základního polohového pole', 'pomocné měřické sítě'], e: 'PPBP tvoří zhušťovací body a ostatní body podrobného polohového bodového pole.' },
          { t: 'c', q: 'Výšky bodů nivelačních sítí ČR jsou v systému…', a: 'Bpv', w: ['S-JTSK', 'WGS84', 'S-42'], e: 'Baltský výškový systém – po vyrovnání; S-JTSK je polohový systém.' },
          { t: 'c', q: 'Nivelační značka osazená ve svislé zdi budovy je…', a: 'čepová značka', w: ['hřebová značka', 'ochranný tyčový znak', 'kamenný hranol'], e: 'Hřebové značky se osazují do vodorovných ploch (skála, práh, patka).' },
          { t: 'c', q: 'Trigonometrický bod bývá stabilizován…', a: 'kamenem s křížkem a podzemní značkou', w: ['dřevěným kolíkem s hřebíkem', 'barevnou značkou na asfaltu', 'čepovou značkou ve zdi'], e: 'Podzemní značka umožní obnovu bodu, pokud je povrchová zničena.' },
          { t: 'tf', q: 'Podzemní značka trigonometrického bodu leží na téže svislici jako povrchová značka.', a: true, e: 'Obě značky určují tentýž bod; při obnově se povrchová značka centruje nad podzemní.' },
          { t: 'c', q: 'Body pomocné měřické sítě se obvykle stabilizují…', a: 'dočasně, např. hřebem nebo kolíkem', w: ['vždy žulovým hranolem', 'čepovou značkou ve zdi', 'pilířem s nucenou centrací'], e: 'Slouží jen pro konkrétní zakázku, proto stačí dočasná stabilizace.' },
          { t: 'm', q: 'Spojte zkratku s významem', p: [['ZPBP', 'Základní polohové bodové pole'], ['PPBP', 'Podrobné polohové bodové pole'], ['ZNBP', 'Základní nivelační bodové pole'], ['Bpv', 'Baltský výškový systém po vyrovnání']] },
        ],
      },
      {
        id: 'bea004l3', title: 'Technická nivelace', icon: '📒', gens: ['fieldbook', 'levelClosure', 'levelLimit'],
        items: [
          { t: 'c', q: 'Mezní odchylka technické nivelace pro pořad délky R km je…', a: '40 mm · √R', w: ['4 mm · √R', '40 mm · R', '0,4 mm · √R'], e: 'Mezní odchylka roste s odmocninou délky, protože se sčítají nahodilé chyby sestav.' },
          { t: 'c', q: 'Vetknutý nivelační pořad je…', a: 'připojený na začátku i na konci', w: ['uzavřený do výchozího bodu', 'připojený jen na začátku', 'měřený bez přestavových bodů'], e: 'Začíná i končí na bodech se známou výškou, takže má kontrolu (uzávěr).' },
          { t: 'c', q: 'Převýšení na sestavě je…', a: 'čtení vzad − čtení vpřed', w: ['čtení vpřed − čtení vzad', 'čtení vzad + čtení vpřed', 'průměr čtení vzad a vpřed'], e: 'Menší čtení znamená vyšší bod.' },
          { t: 'tf', q: 'V uzavřeném nivelačním pořadu má být součet převýšení teoreticky nulový.', a: true, e: 'Pořad začíná i končí na tomtéž bodě.' },
          { t: 'c', q: 'Uzávěr pořadu se rozdělí…', a: 'úměrně délkám nebo počtu sestav', w: ['celý do první sestavy', 'do největšího převýšení', 'vůbec, jen se zapíše'], e: 'Opravy mají opačné znaménko než uzávěr.' },
          { t: 'c', q: 'Přestavový bod je bod, na kterém…', a: 'se čte vpřed i vzad', w: ['stojí nivelační přístroj', 'je známá výška předem', 'se měří jen vpřed'], e: 'Přenáší výšku z jedné sestavy do další.' },
          { t: 'c', q: 'Proč mají být záměry vzad a vpřed stejně dlouhé?', a: 'vyloučí se i-chyba a zakřivení', w: ['lať se méně prohýbá', 'zkrátí se doba měření', 'lépe se čte čárový kód'], e: 'Vyruší se i-chyba, vliv zakřivení Země a z velké části i refrakce.' },
          { t: 'o', q: 'Seřaďte výpočet nivelačního pořadu', s: ['Sečíst převýšení všech sestav', 'Určit uzávěr vůči daným bodům', 'Porovnat uzávěr s mezní odchylkou', 'Rozdělit opravy do sestav', 'Vypočítat výšky bodů'], e: 'Opravy se rozdělují, jen pokud uzávěr nepřekročí mezní odchylku.' },
        ],
      },
      {
        id: 'bea004l4', title: 'Plošná nivelace a trig. výšky', icon: '⛰️', gens: ['trigHeightLong'],
        items: [
          { t: 'c', q: 'Plošná nivelace se používá hlavně k…', a: 'výškovému zaměření rovinatých ploch', w: ['určení polohy trig. bodů', 'kontrole svislosti budov', 'měření délek dlouhých stran'], e: 'Výsledkem je síť výškových bodů pro vrstevnice nebo výpočet kubatur.' },
          { t: 'c', q: 'Při plošné nivelaci je výška bodu…', a: 'horizont přístroje minus čtení', w: ['čtení minus výška přístroje', 'součet čtení vzad a vpřed', 'horizont přístroje plus čtení'], e: 'Horizont = výška bodu vzad + čtení vzad; z jednoho stanoviska se určí mnoho bodů.' },
          { t: 'c', q: 'Body plošné nivelace se často volí…', a: 've čtvercové síti', w: ['jen na jedné přímce', 'jen na hranách budov', 'náhodně bez náčrtu'], e: 'Pravidelná síť usnadní interpolaci vrstevnic i výpočet objemů.' },
          { t: 'c', q: 'Oprava převýšení ze zakřivení Země pro vzdálenost d je…', a: 'd² / (2R)', w: ['d / (2R)', '2R / d²', 'd² · 2R'], e: 'Na 1 km asi 7,8 cm – u dlouhých trigonometrických záměr ji nelze zanedbat.' },
          { t: 'c', q: 'Refrakční koeficient k se v ČR běžně uvažuje…', a: '0,13', w: ['1,3', '0,013', '−1,3'], e: 'Paprsek se zakřivuje s poloměrem R/k; hodnota se mění s počasím a denní dobou.' },
          { t: 'tf', q: 'Refrakce zmenšuje vliv zakřivení Země na trigonometrické převýšení.', a: true, e: 'Společná oprava je (1 − k) · d² / (2R).' },
          { t: 'c', q: 'Nejistý vliv refrakce u dlouhých záměr omezíte…', a: 'oboustranným současným měřením', w: ['měřením jen v poledne', 'delší záměrou', 'vyšším stativem'], e: 'Při současném měření z obou konců se vliv refrakce v průměru převýšení vyruší.' },
          { t: 'n', q: 'Jaká je oprava ze zakřivení a refrakce pro d = 1 000 m (k = 0,13; R = 6 381 km)?', a: 68, tol: 1, dec: 0, unit: 'mm', e: '(1 − 0,13) · 1 000² / (2 · 6 381 000) = 0,068 m = 68 mm.' },
        ],
      },
      {
        id: 'bea004l5', title: 'Podrobné měření a kubatury', icon: '🗺️', gens: ['cutVolume', 'areaQuad'],
        items: [
          { t: 'c', q: 'Ortogonální (pravoúhlá) metoda měří…', a: 'staničení a kolmice k měřické přímce', w: ['směr a délku ze stanoviska', 'dva směry ze dvou bodů', 'jen převýšení na lati'], e: 'Kolmice se vytyčí pentagonem, staničení i kolmice se měří pásmem.' },
          { t: 'c', q: 'Tachymetrie určuje současně…', a: 'polohu i výšku podrobných bodů', w: ['jen polohu lomových bodů', 'jen výšku bodů na lati', 'plochu parcel bez měření'], e: 'Prostorová polární metoda: směr, délka a zenitový úhel.' },
          { t: 'c', q: 'Nepřístupný bod (vrchol věže) se prostorově určí…', a: 'protínáním vpřed ze základny', w: ['nivelací ze středu', 'ortogonální metodou', 'měřením ocelovým pásmem'], e: 'Z obou konců základny se měří vodorovné i zenitové úhly; výška se tak určí dvakrát.' },
          { t: 'c', q: 'Plocha ze souřadnic vrcholů se počítá…', a: 'L’Huilierovými vzorci', w: ['Pythagorovou větou', 'metodou nejmenších čtverců', 'Heronovým vzorcem z úhlů'], e: '2P = Σ xᵢ (yᵢ₊₁ − yᵢ₋₁); kontrola druhým vzorcem.' },
          { t: 'tf', q: 'Objem zemních prací lze určit metodou průměrných ploch mezi příčnými profily.', a: true, e: 'V = (A₁ + A₂) / 2 · L – přesnost roste s hustotou profilů.' },
          { t: 'c', q: 'Podélný profil trasy zobrazuje…', a: 'výšky terénu podél osy trasy', w: ['výšky terénu napříč trasou', 'půdorys osy trasy', 'hranice dotčených pozemků'], e: 'Napříč osou se měří příčné profily.' },
          { t: 'c', q: 'Při výpočtu kubatur z plošné nivelace se objem hranolu počítá…', a: 'průměrnou výškou krát plocha', w: ['součtem výšek rohů', 'nejvyšší výškou krát plocha', 'plochou děleno výškou'], e: 'Objem nad srovnávací rovinou = plocha čtverce × průměr výšek jeho rohů.' },
          { t: 'm', q: 'Spojte metodu s měřenými veličinami', p: [['Polární metoda', 'Směr a délka'], ['Ortogonální metoda', 'Staničení a kolmice'], ['Plošná nivelace', 'Čtení na lati v síti bodů'], ['Protínání vpřed', 'Dva směry ze dvou bodů']] },
        ],
      },
    ],
  },

  {
    id: 'bea006', title: 'Teorie chyb a vyrovnávací počet 1', color: '#b45309', level: 'Bc.', course: 'BEA006', sem: '1. ročník · LS',
    desc: 'Pravděpodobnost, rozdělení náhodných veličin, chyby měření, přenášení chyb, váhy a vyrovnání přímých měření.',
    lessons: [
      {
        id: 'bea006l1', title: 'Kombinatorika a pravděpodobnost', icon: '🎲',
        items: [
          { t: 'c', q: 'Kolik je permutací 5 prvků?', a: '120', w: ['25', '60', '720'], e: '5! = 5 · 4 · 3 · 2 · 1 = 120.' },
          { t: 'c', q: 'Kombinační číslo C(5, 2) je…', a: '10', w: ['20', '5', '25'], e: '5! / (2! · 3!) = 10.' },
          { t: 'c', q: 'Kolik je variací 2. třídy ze 4 prvků bez opakování?', a: '12', w: ['6', '16', '8'], e: '4 · 3 = 12; záleží na pořadí.' },
          { t: 'c', q: 'Pravděpodobnost jevu leží v intervalu…', a: '⟨0; 1⟩', w: ['⟨−1; 1⟩', '⟨0; 100⟩', '⟨1; ∞)'], e: '0 = jev nemožný, 1 = jev jistý.' },
          { t: 'c', q: 'Pro nezávislé jevy A a B platí P(A ∩ B) =', a: 'P(A) · P(B)', w: ['P(A) + P(B)', 'P(A) − P(B)', 'P(A) / P(B)'], e: 'Součin platí jen pro nezávislé jevy.' },
          { t: 'tf', q: 'Pravděpodobnost opačného jevu k A je 1 − P(A).', a: true, e: 'Jev a jeho opak dohromady tvoří jev jistý.' },
          { t: 'n', q: 'Dvakrát hodíte kostkou. Jaká je pravděpodobnost dvou šestek?', a: 0.0278, tol: 0.0005, dec: 4, unit: '', e: '1/6 · 1/6 = 1/36 ≈ 0,0278.' },
          { t: 'c', q: 'Počet úspěchů v n opakovaných nezávislých pokusech má rozdělení…', a: 'binomické', w: ['normální', 'Studentovo', 'rovnoměrné'], e: 'P(k) = C(n, k) · pᵏ · (1 − p)ⁿ⁻ᵏ.' },
          { t: 'm', q: 'Spojte pojem se vzorcem', p: [['Permutace', 'n!'], ['Kombinace', 'n! / (k! (n − k)!)'], ['Variace', 'n! / (n − k)!'], ['Variace s opakováním', 'nᵏ']] },
        ],
      },
      {
        id: 'bea006l2', title: 'Náhodné veličiny a rozdělení', icon: '🔔',
        items: [
          { t: 'c', q: 'Normální rozdělení je určeno…', a: 'střední hodnotou μ a odchylkou σ', w: ['jen střední hodnotou μ', 'mediánem a modusem', 'počtem měření n a vahou p'], e: 'Zápis N(μ, σ²); hustota je symetrická kolem μ.' },
          { t: 'c', q: 'V intervalu μ ± 2σ leží přibližně…', a: '95 % hodnot', w: ['68 % hodnot', '99,7 % hodnot', '50 % hodnot'], e: 'Přesněji 95,4 %; pro ±1σ je to 68,3 %, pro ±3σ 99,7 %.' },
          { t: 'c', q: 'Kvantil pro oboustranný 95% interval normovaného normálního rozdělení je…', a: '1,96', w: ['1,64', '2,58', '3,00'], e: '1,64 je jednostranný 95% kvantil, 2,58 oboustranný 99%.' },
          { t: 'c', q: 'Mezní odchylka se v geodézii obvykle volí jako…', a: 'dvoj- až trojnásobek σ', w: ['polovina σ', 'přesně jedno σ', 'desetinásobek σ'], e: 'Běžně u_p = 2 (≈ 95 %), přísněji 2,5 nebo 3.' },
          { t: 'c', q: 'Normované normální rozdělení N(0, 1) má…', a: 'μ = 0 a σ = 1', w: ['μ = 1 a σ = 0', 'μ = 0 a σ = 0', 'μ = 1 a σ = 1'], e: 'Normování: u = (x − μ) / σ.' },
          { t: 'tf', q: 'Spojitá náhodná veličina nabývá každé konkrétní hodnoty s pravděpodobností 0.', a: true, e: 'Nenulovou pravděpodobnost mají jen intervaly – plocha pod hustotou.' },
          { t: 'c', q: 'Distribuční funkce F(x) udává…', a: 'P(X ≤ x)', w: ['P(X = x)', 'hustotu v bodě x', 'střední hodnotu X'], e: 'F je neklesající, od 0 do 1; hustota je její derivace.' },
          { t: 'c', q: 'Rozptyl náhodné veličiny je…', a: 'druhá mocnina směrodatné odchylky', w: ['odmocnina směrodatné odchylky', 'střední hodnota veličiny', 'největší odchylka od průměru'], e: 'D(X) = σ² = E[(X − μ)²].' },
          { t: 'm', q: 'Spojte rozdělení s použitím', p: [['Normální', 'Nahodilé chyby měření'], ['Studentovo t', 'Interval při malém počtu měření'], ['χ²', 'Test rozptylu'], ['Binomické', 'Počet úspěchů v n pokusech']] },
        ],
      },
      {
        id: 'bea006l3', title: 'Chyby měření', icon: '🎯', gens: ['meanValue', 'meanError'],
        items: [
          { t: 'c', q: 'Skutečná chyba ε je…', a: 'rozdíl měřené a skutečné hodnoty', w: ['rozdíl dvou opakovaných měření', 'rozdíl průměru a měření', 'mezní odchylka měření'], e: 'Skutečnou hodnotu obvykle neznáme, proto se pracuje s opravami od průměru.' },
          { t: 'c', q: 'Oprava v od aritmetického průměru je…', a: 'průměr minus měřená hodnota', w: ['měřená hodnota minus průměr', 'průměr děleno počtem měření', 'rozdíl dvou sousedních měření'], e: 'l + v = x̄ – oprava se k měření přičítá.' },
          { t: 'c', q: 'Součet oprav od aritmetického průměru je…', a: 'nulový', w: ['minimální, ale kladný', 'roven počtu měření', 'roven směrodatné odchylce'], e: '[v] = 0 slouží jako výpočetní kontrola.' },
          { t: 'c', q: 'Výběrová směrodatná odchylka z oprav je…', a: 's = √([vv] / (n − 1))', w: ['s = √([vv] / n)', 's = [vv] / (n − 1)', 's = [v] / n'], e: 'Besselův vzorec; n − 1, protože průměr byl určen ze stejných dat.' },
          { t: 'c', q: 'Hrubou chybu (omyl) odhalíte…', a: 'kontrolním nebo opakovaným měřením', w: ['výpočtem aritmetického průměru', 'zvětšením počtu desetinných míst', 'měřením ve stejné poloze'], e: 'Hrubé chyby se nesmí dostat do vyrovnání – měření se vyřadí a opakuje.' },
          { t: 'tf', q: 'Nahodilé chyby mají stejnou pravděpodobnost kladného i záporného znaménka.', a: true, e: 'Proto se jejich vliv s rostoucím počtem měření zmenšuje.' },
          { t: 'c', q: 'Správnost měření vypovídá o…', a: 'blízkosti průměru ke skutečné hodnotě', w: ['rozptylu opakovaných měření', 'počtu platných číslic', 'rozlišení displeje přístroje'], e: 'Správnost kazí systematické chyby, přesnost (rozptyl) nahodilé chyby.' },
          { t: 'n', q: 'Délka změřena 3×: 12,31; 12,35; 12,33 m. Jaká je výběrová směrodatná odchylka v mm?', a: 20, tol: 0.1, dec: 1, unit: 'mm', e: 'x̄ = 12,33; v = 20, −20, 0 mm; s = √(800 / 2) = 20 mm.' },
          { t: 'm', q: 'Spojte pojem s popisem', p: [['Skutečná chyba', 'Odchylka od pravé hodnoty'], ['Oprava', 'Rozdíl průměru a měření'], ['Systematická chyba', 'Stálý vliv s určitým znaménkem'], ['Hrubá chyba', 'Omyl nebo selhání měřiče']] },
        ],
      },
      {
        id: 'bea006l4', title: 'Kovariance a přenášení chyb', icon: '🔗', gens: ['errorPropagation'],
        items: [
          { t: 'c', q: 'Korelační koeficient nabývá hodnot…', a: 'od −1 do 1', w: ['od 0 do 1', 'od 0 do ∞', 'od −∞ do ∞'], e: '±1 = úplná lineární závislost, 0 = nekorelované veličiny.' },
          { t: 'c', q: 'Mimo diagonálu kovarianční matice jsou…', a: 'kovariance dvojic veličin', w: ['rozptyly jednotlivých veličin', 'váhy jednotlivých měření', 'korelační koeficienty rovné 1'], e: 'Matice je symetrická: σ_xy = σ_yx.' },
          { t: 'c', q: 'Plocha obdélníku P = a · b (a, b nekorelované). Její střední chyba je…', a: 'm_P = √(b²m_a² + a²m_b²)', w: ['m_P = m_a · m_b', 'm_P = a·m_a + b·m_b', 'm_P = √(m_a² + m_b²)'], e: 'Parciální derivace: ∂P/∂a = b, ∂P/∂b = a.' },
          { t: 'n', q: 'Obdélník a = 40 m, b = 25 m, m_a = m_b = 10 mm. Jaká je střední chyba plochy?', a: 0.47, tol: 0.006, dec: 2, unit: 'm²', e: '√((25 · 0,01)² + (40 · 0,01)²) = √0,2225 ≈ 0,47 m².' },
          { t: 'c', q: 'Funkce f = k · x (k konstanta) má střední chybu…', a: '|k| · m_x', w: ['k² · m_x', 'm_x / k', '√k · m_x'], e: 'Konstanta se přenáší lineárně, ve variancích jako k².' },
          { t: 'tf', q: 'Součet n nekorelovaných veličin se stejnou střední chybou m má střední chybu m · √n.', a: true, e: 'm² + m² + … = n · m², odmocnina dává m√n.' },
          { t: 'c', q: 'Úhel jako rozdíl dvou směrů se střední chybou m_ψ má střední chybu…', a: 'm_ψ · √2', w: ['2 · m_ψ', 'm_ψ / √2', 'm_ψ'], e: 'ω = ψ₂ − ψ₁, variance se sčítají: 2m_ψ².' },
          { t: 'c', q: 'Kladná korelace dvou veličin znamená, že…', a: 'mají tendenci růst společně', w: ['jsou na sobě nezávislé', 'jedna roste, druhá klesá', 'mají stejný rozptyl'], e: 'Kovariance je kladná, korelační koeficient leží mezi 0 a 1.' },
          { t: 'm', q: 'Spojte funkci se střední chybou', p: [['x + y + z', '√(m_x² + m_y² + m_z²)'], ['3x', '3 · m_x'], ['x / 2', 'm_x / 2'], ['x²', '2|x| · m_x']] },
        ],
      },
      {
        id: 'bea006l5', title: 'Váhy a vyrovnání přímých měření', icon: '⚖️', gens: ['weightedMean', 'meanValue'],
        items: [
          { t: 'c', q: 'Vyrovnaná hodnota přímých měření stejné přesnosti je…', a: 'aritmetický průměr', w: ['medián', 'modus', 'geometrický průměr'], e: 'Aritmetický průměr minimalizuje [vv] – je to výsledek MNČ.' },
          { t: 'c', q: 'Pro měření různé přesnosti je nejlepším odhadem…', a: 'vážený (obecný) průměr', w: ['prostý aritmetický průměr', 'nejpřesnější měření samo', 'průměr krajních hodnot'], e: 'x̄ = [pl] / [p]; přesnější měření mají větší váhu.' },
          { t: 'c', q: 'Váha aritmetického průměru z n měření s váhou 1 je…', a: 'n', w: ['1/n', '√n', 'n²'], e: 'Váha je nepřímo úměrná varianci: m² / n → p = n.' },
          { t: 'c', q: 'Jednotková střední chyba m₀ je střední chyba měření…', a: 's váhou rovnou jedné', w: ['s největší vahou', 'jednoho metru délky', 'po vyloučení hrubých chyb'], e: 'Pro měření s vahou p platí m = m₀ / √p.' },
          { t: 'n', q: 'Délka: 100,012 m (váha 1) a 100,018 m (váha 2). Jaký je vážený průměr?', a: 100.016, tol: 0.0005, dec: 3, unit: 'm', e: '(1 · 100,012 + 2 · 100,018) / 3 = 100,016 m.' },
          { t: 'c', q: 'Z rozdílů d n dvojic měření stejné přesnosti je střední chyba jednoho měření…', a: 'm = √([dd] / (2n))', w: ['m = √([dd] / n)', 'm = √([dd] / (n − 1))', 'm = [dd] / (2n)'], e: 'Rozdíl dvojice má varianci 2m², proto dělíme 2n.' },
          { t: 'tf', q: 'MNČ pro přímá měření stejné přesnosti vede na aritmetický průměr.', a: true, e: 'Minimum [vv] nastává právě pro x̄ = [l] / n.' },
          { t: 'c', q: 'Nadbytečná měření jsou…', a: 'měření nad nutný počet', w: ['měření s hrubou chybou', 'měření bez kontroly', 'měření s nulovou váhou'], e: 'Umožňují kontrolu, vyrovnání a odhad přesnosti.' },
          { t: 'o', q: 'Seřaďte vyrovnání přímých měření', s: ['Vypočítat aritmetický průměr', 'Vypočítat opravy v = x̄ − l', 'Zkontrolovat, že [v] = 0', 'Vypočítat s = √([vv] / (n − 1))', 'Vypočítat střední chybu průměru s / √n'], e: 'Kontrola [v] = 0 odhalí početní chybu dřív, než se spočte přesnost.' },
        ],
      },
    ],
  },

  {
    id: 'bea010', title: 'Geodézie 3', color: '#9333ea', level: 'Bc.', course: 'BEA010', sem: '2. ročník · ZS',
    desc: 'Přesná nivelace, transformace souřadnic, centrace a orientace, gyroskopická a magnetická měření a úvod do GNSS.',
    lessons: [
      {
        id: 'bea010l1', title: 'Přesná nivelace', icon: '🎚️', gens: ['levelLimit'],
        items: [
          { t: 'c', q: 'Při přesné a velmi přesné nivelaci se používají latě…', a: 's invarovým pásem', w: ['dřevěné skládací', 'hliníkové teleskopické', 'sklolaminátové zasouvací'], e: 'Invar má velmi malou teplotní roztažnost.' },
          { t: 'c', q: 'Pořad přesné nivelace se měří tam a zpět, aby…', a: 'byla kontrola a omezily se systematické vlivy', w: ['se zkrátila doba měření', 'nebylo nutné měřit ze středu', 'se vyloučila chyba dělení latě'], e: 'Rozdíl tam–zpět se porovnává s mezním rozdílem.' },
          { t: 'c', q: 'Pořadí čtení vzad – vpřed – vpřed – vzad omezuje…', a: 'vliv svislého pohybu přístroje', w: ['vliv kolimační chyby', 'vliv zakřivení Země', 'vliv chyby invarového pásu'], e: 'Sedání nebo zvedání stativu v čase se v průměru vyruší.' },
          { t: 'c', q: 'Záměry ve velmi přesné nivelaci jsou oproti technické…', a: 'kratší, vzad a vpřed stejné', w: ['delší, na délce nezáleží', 'kratší jen vzad', 'stejné jako u technické'], e: 'Krátké a vyrovnané záměry omezují i-chybu i refrakci.' },
          { t: 'tf', q: 'Refrakce při nivelaci škodí nejvíc u záměr těsně nad terénem.', a: true, e: 'U země je největší teplotní gradient; proto se předepisuje minimální výška záměry.' },
          { t: 'c', q: 'Nivelační síť I. a II. řádu se měří…', a: 'velmi přesnou nivelací', w: ['technickou nivelací', 'trigonometricky', 'metodou GNSS RTK'], e: 'Nižší řády a plošné sítě se měří přesnou nebo technickou nivelací.' },
          { t: 'c', q: 'Mezní rozdíl měření tam a zpět závisí na…', a: 'odmocnině z délky oddílu', w: ['nadmořské výšce pořadu', 'teplotě vzduchu při měření', 'počtu měřičů ve skupině'], e: 'Nahodilé chyby sestav se sčítají kvadraticky, tedy s √R.' },
          { t: 'm', q: 'Spojte opatření s účelem', p: [['Invarový pás', 'Malá teplotní roztažnost'], ['Střídání pořadí čtení', 'Omezení sedání přístroje'], ['Stejné záměry', 'Vyloučení i-chyby'], ['Měření tam a zpět', 'Kontrola měření']] },
        ],
      },
      {
        id: 'bea010l2', title: 'Transformace souřadnic', icon: '🔄', gens: ['helmertY', 'helmertX'],
        items: [
          { t: 'c', q: 'Kolik parametrů má podobnostní (Helmertova) transformace v rovině?', a: '4', w: ['3', '6', '8'], e: 'Dva posuny, rotace a měřítko.' },
          { t: 'c', q: 'Shodnostní transformace v rovině má…', a: '3 parametry', w: ['4 parametry', '6 parametrů', '2 parametry'], e: 'Dva posuny a rotace, měřítko je 1.' },
          { t: 'c', q: 'Afinní transformace v rovině má…', a: '6 parametrů', w: ['4 parametry', '8 parametrů', '3 parametry'], e: 'Umožňuje různé měřítko v osách a zkosení.' },
          { t: 'c', q: 'Projektivní transformace v rovině má…', a: '8 parametrů', w: ['6 parametrů', '4 parametry', '12 parametrů'], e: 'Používá se např. pro překreslení fotografie rovinného objektu.' },
          { t: 'c', q: 'Minimální počet identických bodů pro podobnostní transformaci je…', a: '2', w: ['1', '3', '4'], e: 'Každý bod dá dvě rovnice, 4 neznámé → 2 body; další body umožní kontrolu.' },
          { t: 'tf', q: 'Při nadbytečném počtu identických bodů se transformační klíč určí vyrovnáním MNČ.', a: true, e: 'Z oprav na identických bodech se posoudí kvalita transformace.' },
          { t: 'c', q: 'Prostorová podobnostní transformace se 7 parametry obsahuje…', a: '3 posuny, 3 rotace, 1 měřítko', w: ['3 posuny a 4 rotace', '2 posuny, 1 rotace, 4 měřítka', '6 posunů a 1 měřítko'], e: 'Používá se např. mezi 3D kartézskými souřadnicemi různých systémů.' },
          { t: 'c', q: 'Co zachovává afinní transformace?', a: 'rovnoběžnost přímek', w: ['velikost všech úhlů', 'délky všech úseček', 'tvar kružnic'], e: 'Čtverec se může změnit na kosodélník, ale strany zůstanou rovnoběžné.' },
          { t: 'm', q: 'Spojte transformaci s tím, co zachovává', p: [['Shodnostní', 'Délky i úhly'], ['Podobnostní', 'Úhly (tvar)'], ['Afinní', 'Rovnoběžnost'], ['Projektivní', 'Přímky (kolinearitu)']] },
        ],
      },
      {
        id: 'bea010l3', title: 'Centrace a orientace', icon: '🧭',
        items: [
          { t: 'c', q: 'Centrace směrů je nutná, když…', a: 'přístroj nebo cíl stojí mimo bod', w: ['přístroj není urovnán', 'měříme jen v jedné poloze', 'cíl je dál než 1 km'], e: 'Excentrická měření se převádějí na centrum výpočtem.' },
          { t: 'c', q: 'Oprava směru z excentricity e na vzdálenost d je přibližně…', a: 'ρ · e · sin φ / d', w: ['ρ · d · sin φ / e', 'e · d · sin φ', 'ρ · e · cos φ · d'], e: 'φ je úhel mezi směrem k excentru a směrem k cíli, ρ převádí radiány na gony.' },
          { t: 'n', q: 'Excentricita e = 0,050 m, úhel φ = 100 gon, délka d = 500 m. Jaká je oprava směru v mgon?', a: 6.37, tol: 0.02, dec: 2, unit: 'mgon', e: '0,05 / 500 = 1·10⁻⁴ rad · 200/π = 0,006 37 gon = 6,37 mgon.' },
          { t: 'c', q: 'Orientace osnovy směrů na stanovisku znamená…', a: 'určení orientačního posunu z daných bodů', w: ['urovnání přístroje nad bodem', 'redukci směrů na první cíl', 'výpočet délek k cílům'], e: 'O = σ − ψ; průměr z více daných bodů převede osnovu na směrníky.' },
          { t: 'tf', q: 'Příčná odchylka 1 cm na vzdálenost 1 km odpovídá asi 0,64 mgon.', a: true, e: '0,01 / 1000 = 10⁻⁵ rad ≈ 0,64 mgon.' },
          { t: 'c', q: 'Excentricita cíle vzniká typicky při cílení na…', a: 'signál mimo svislici bodu', w: ['hranol na výtyčce nad bodem', 'lať na nivelační značce', 'terč s nucenou centrací'], e: 'Např. věž kostela nebo signál, který nestojí přesně nad značkou.' },
          { t: 'c', q: 'Nucená centrace se používá, aby…', a: 'přístroj i cíl stály přesně na témže místě', w: ['nebylo nutné urovnávat přístroj', 'se vyloučila indexová chyba', 'šlo měřit bez hranolu'], e: 'Na pilířích a v mikrosítích; chyba centrace klesne na desetiny mm.' },
          { t: 'm', q: 'Spojte pojem s popisem', p: [['Excentrické stanovisko', 'Přístroj mimo bod'], ['Excentrický cíl', 'Signál mimo bod'], ['Orientační posun', 'Převod osnovy na směrníky'], ['Nucená centrace', 'Přesné stavění na pilíři']] },
        ],
      },
      {
        id: 'bea010l4', title: 'Gyroskop, magnetika, podzemní sítě', icon: '🧲',
        items: [
          { t: 'c', q: 'Gyroteodolit určuje…', a: 'astronomický azimut směru', w: ['magnetický azimut směru', 'nadmořskou výšku bodu', 'délku záměry'], e: 'Gyroskop se vlivem rotace Země ustaluje k zeměpisnému severu.' },
          { t: 'c', q: 'Gyroskop je důležitý v tunelech a dolech, protože…', a: 'orientuje sítě bez výhledu na povrch', w: ['měří délky bez hranolu', 'nahrazuje nivelaci', 'nepotřebuje urovnání'], e: 'Podzemní polygonové pořady jsou dlouhé a orientace z povrchu je obtížná.' },
          { t: 'c', q: 'Magnetická deklinace je úhel mezi…', a: 'magnetickým a zeměpisným severem', w: ['zeměpisným severem a osou X', 'tížnicí a normálou elipsoidu', 'dvěma magnetickými póly'], e: 'Mění se místně i v čase – pro přesnou orientaci je buzola nevhodná.' },
          { t: 'tf', q: 'Magnetická deklinace je v čase neměnná.', a: false, e: 'Mění se sekulárně (roky) i denně a při magnetických bouřích.' },
          { t: 'c', q: 'Astronomický azimut a směrník v S-JTSK se liší hlavně o…', a: 'meridiánovou konvergenci', w: ['magnetickou deklinaci', 'indexovou chybu', 'refrakční koeficient'], e: 'Konvergence je úhel mezi průmětem poledníku a osou X zobrazení.' },
          { t: 'c', q: 'Kovové podzemní vedení se vyhledává…', a: 'elektromagnetickým lokátorem', w: ['nivelačním přístrojem', 'přijímačem GNSS', 'optickým dostřeďovačem'], e: 'Lokátor zachytí pole vybuzené v kabelu nebo potrubí.' },
          { t: 'c', q: 'Nekovové (plastové) potrubí se hledá nejlépe…', a: 'georadarem', w: ['magnetometrem', 'buzolou', 'fázovým dálkoměrem'], e: 'Georadar zachytí rozhraní materiálů; lze také zavést do potrubí sondu.' },
          { t: 'c', q: 'Nové podzemní vedení se nejspolehlivěji zaměří…', a: 'v otevřeném výkopu před zasypáním', w: ['z ortofota po dokončení', 'podle projektové dokumentace', 'lokátorem po zasypání'], e: 'Přímé zaměření dává polohu i výšku bez nejistoty detekce.' },
          { t: 'm', q: 'Spojte přístroj s určovanou veličinou', p: [['Gyroteodolit', 'Astronomický azimut'], ['Buzola', 'Magnetický azimut'], ['Georadar', 'Nekovové vedení'], ['Lokátor vedení', 'Kovové kabely a potrubí']] },
        ],
      },
      {
        id: 'bea010l5', title: 'Úvod do GNSS', icon: '🛰️',
        items: [
          { t: 'c', q: 'Kolik družic je minimálně potřeba pro 3D polohu a opravu hodin přijímače?', a: '4', w: ['3', '2', '6'], e: 'Neznámé X, Y, Z a chyba hodin přijímače.' },
          { t: 'c', q: 'Evropský globální navigační systém je…', a: 'Galileo', w: ['GLONASS', 'BeiDou', 'NAVSTAR GPS'], e: 'GLONASS je ruský, BeiDou čínský, GPS americký.' },
          { t: 'c', q: 'Kódové měření určuje…', a: 'pseudovzdálenost', w: ['azimut družice', 'výšku geoidu', 'rychlost větru'], e: '„Pseudo“, protože obsahuje chybu hodin přijímače.' },
          { t: 'c', q: 'Metoda RTK poskytuje…', a: 'centimetrovou polohu v reálném čase', w: ['metrovou polohu bez korekcí', 'milimetrovou výšku bez modelu', 'polohu až po týdnu zpracování'], e: 'Fázová měření s korekcemi z referenční stanice nebo sítě (např. CZEPOS).' },
          { t: 'tf', q: 'Fázové měření je přesnější než kódové, ale obsahuje neznámý počet celých cyklů.', a: true, e: 'Určení této ambiguity (fixace) je klíčem k přesnosti RTK.' },
          { t: 'c', q: 'GNSS dává přímo výšku…', a: 'elipsoidickou', w: ['normální v Bpv', 'ortometrickou', 'dynamickou'], e: 'Pro Bpv se odečte výšková anomálie z modelu kvazigeoidu.' },
          { t: 'c', q: 'Hodnota PDOP vyjadřuje…', a: 'vliv geometrie družic na přesnost', w: ['sílu signálu družic', 'počet viditelných družic', 'chybu hodin přijímače'], e: 'Čím menší PDOP, tím lepší rozložení družic na obloze.' },
          { t: 'c', q: 'Diferenční GNSS zpřesňuje polohu díky…', a: 'korekcím z referenční stanice', w: ['delší anténě přijímače', 'vyššímu počtu kanálů', 'měření ve dvou polohách'], e: 'Chyby společné blízkým přijímačům (atmosféra, dráhy) se odečtou.' },
          { t: 'm', q: 'Spojte systém se státem nebo regionem', p: [['GPS', 'USA'], ['GLONASS', 'Rusko'], ['Galileo', 'Evropská unie'], ['BeiDou', 'Čína']] },
        ],
      },
    ],
  },

  {
    id: 'bea009', title: 'Geodetické programy a data', color: '#475569', level: 'Bc.', course: 'BEA009', sem: '2. ročník · ZS',
    desc: 'Digitální mapa v CAD, datové formáty, kontroly dat, konverze a mapové služby.',
    lessons: [
      {
        id: 'bea009l1', title: 'Digitální mapa v CAD', icon: '🖥️',
        items: [
          { t: 'c', q: 'Nativní formát programu MicroStation je…', a: 'DGN', w: ['DWG', 'SHP', 'VFK'], e: 'DGN (design file) od firmy Bentley.' },
          { t: 'c', q: 'Nativní formát programu AutoCAD je…', a: 'DWG', w: ['DGN', 'GML', 'VFK'], e: 'Pro výměnu dat Autodesk nabízí textový DXF.' },
          { t: 'c', q: 'Kokeš je…', a: 'český geodetický program (Gepro)', w: ['kreslicí program Autodesku', 'formát katastrálních dat', 'webová služba ČÚZK'], e: 'Používá se pro výpočty, kresbu map a geometrické plány.' },
          { t: 'c', q: 'Vrstvy (hladiny) v CAD slouží…', a: 'k tematickému členění kresby', w: ['k ukládání souřadnic bodů', 'k tisku v barvě', 'k šifrování výkresu'], e: 'Např. budovy, komunikace, popis – každý obsah ve své vrstvě.' },
          { t: 'c', q: 'Buňka (MicroStation) nebo blok (AutoCAD) je…', a: 'pojmenovaná skupina prvků', w: ['samostatný výkresový soubor', 'rastrový podklad mapy', 'jedna vrstva výkresu'], e: 'Opakovaně se vkládá, typicky jako mapová značka.' },
          { t: 'tf', q: 'Mapové značky se v digitální mapě obvykle vkládají jako buňky nebo bloky.', a: true, e: 'Změna definice se pak projeví u všech výskytů.' },
          { t: 'c', q: 'Souřadnice S-JTSK se v CAD často zadávají se záporným znaménkem, protože…', a: 'osy S-JTSK míří k jihu a západu', w: ['CAD nepodporuje velká čísla', 'to vyžaduje formát DXF', 'body leží pod hladinou moře'], e: 'Se znaménkem minus je sever nahoře a východ vpravo jako v běžném CAD.' },
          { t: 'm', q: 'Spojte program s výrobcem', p: [['MicroStation', 'Bentley'], ['AutoCAD', 'Autodesk'], ['Kokeš', 'Gepro'], ['ArcGIS', 'Esri']] },
          { t: 'o', q: 'Seřaďte tvorbu digitální mapy z měření', s: ['Importovat seznam souřadnic', 'Vykreslit body s čísly', 'Spojit body liniemi podle náčrtu', 'Vložit mapové značky a popis', 'Zkontrolovat a exportovat výkres'], e: 'Měřický náčrt určuje, které body se spojují.' },
        ],
      },
      {
        id: 'bea009l2', title: 'Datové formáty', icon: '📂',
        items: [
          { t: 'c', q: 'VFK je…', a: 'výměnný formát katastru nemovitostí', w: ['nativní formát MicroStationu', 'formát rastrových ortofot', 'protokol webových služeb'], e: 'Obsahuje grafická i popisná data KN; vydává ho ČÚZK.' },
          { t: 'c', q: 'Formát DXF je…', a: 'výměnný formát CAD od Autodesku', w: ['formát katastru nemovitostí', 'databázový formát Esri', 'standard OGC pro služby'], e: 'Umí ho číst a zapisovat prakticky všechny CAD a GIS programy.' },
          { t: 'c', q: 'Atributy prvků shapefilu jsou uloženy v souboru…', a: '.dbf', w: ['.shx', '.prj', '.dxf'], e: '.shp geometrie, .shx index, .prj souřadnicový systém.' },
          { t: 'c', q: 'GML je…', a: 'jazyk na bázi XML pro geodata', w: ['binární formát CAD', 'rastrový obrazový formát', 'nativní formát Kokeše'], e: 'Standard OGC; používá se např. pro data INSPIRE a RÚIAN.' },
          { t: 'tf', q: 'Jeden shapefile může obsahovat body, linie i polygony současně.', a: false, e: 'Každý shapefile má jediný typ geometrie.' },
          { t: 'c', q: 'Soubor .prj u shapefilu obsahuje…', a: 'definici souřadnicového systému', w: ['atributovou tabulku', 'prostorový index', 'styly zobrazení'], e: 'Bez něj program neví, v jakém systému jsou souřadnice.' },
          { t: 'c', q: 'Rastrová data na rozdíl od vektorových…', a: 'ukládají hodnoty v mřížce buněk', w: ['ukládají body, linie a plochy', 'nemají žádné rozlišení', 'nelze georeferencovat'], e: 'Typicky ortofoto, skenované mapy nebo DMR v mřížce.' },
          { t: 'c', q: 'Georeferencování rastru znamená…', a: 'přiřazení souřadnic obrazu', w: ['převod rastru na vektor', 'zmenšení velikosti souboru', 'změnu barevné palety'], e: 'Obvykle transformací podle identických (vlícovacích) bodů.' },
          { t: 'm', q: 'Spojte formát s původem', p: [['DGN', 'MicroStation'], ['DWG', 'AutoCAD'], ['SHP', 'Esri'], ['VFK', 'Katastr nemovitostí'], ['GML', 'XML pro geodata']] },
        ],
      },
      {
        id: 'bea009l3', title: 'Atributové a topologické kontroly', icon: '✅',
        items: [
          { t: 'c', q: 'Atributová kontrola ověřuje…', a: 'správnost a úplnost vlastností prvků', w: ['vzájemné napojení linií', 'přesnost měření v terénu', 'velikost souboru výkresu'], e: 'Např. správnou vrstvu, kód, typ čáry nebo vyplněné povinné atributy.' },
          { t: 'c', q: 'Topologická kontrola odhalí například…', a: 'nedotažené nebo přetažené linie', w: ['chybný název souboru', 'špatnou barvu popisu', 'chybějící legendu mapy'], e: 'Kontroluje geometrické vztahy – napojení, překryvy, uzavřenost.' },
          { t: 'c', q: 'Plocha (polygon) musí mít…', a: 'shodný počáteční a koncový bod', w: ['alespoň pět vrcholů', 'všechny strany stejné', 'nulovou výměru'], e: 'Neuzavřená hranice neumožní určit plochu ani přiřadit atributy.' },
          { t: 'tf', q: 'Duplicitní linie ležící přes sebe jsou topologická chyba.', a: true, e: 'Způsobují chyby při tvorbě ploch a zdvojené délky.' },
          { t: 'c', q: 'Tolerance přichycení (snap) slouží k…', a: 'spojení koncových bodů v dané vzdálenosti', w: ['zaokrouhlení souřadnic na metry', 'zvětšení tloušťky čar', 'posunu celé mapy'], e: 'Příliš velká tolerance ale může spojit prvky, které k sobě nepatří.' },
          { t: 'c', q: 'Hranice sousedních parcel má být v topologicky čisté mapě…', a: 'uložena jednou a sdílena', w: ['nakreslena dvakrát přes sebe', 'posunuta o toleranci', 'uložena jen jako text'], e: 'Sdílená hranice vylučuje mezery a překryvy mezi plochami.' },
          { t: 'c', q: 'Uzel (node) v topologii je…', a: 'bod, kde se stýkají linie', w: ['střed každé plochy', 'popis bodu v mapě', 'libovolný lomový bod'], e: 'Lomové body mezi uzly se nazývají vrcholy (vertexy).' },
          { t: 'o', q: 'Seřaďte kontrolu dat před odevzdáním', s: ['Ověřit souřadnicový systém dat', 'Spustit atributové kontroly', 'Spustit topologické kontroly', 'Opravit nalezené chyby', 'Kontroly zopakovat a data exportovat'], e: 'Po opravách je nutné kontrolu opakovat – oprava může vytvořit novou chybu.' },
        ],
      },
      {
        id: 'bea009l4', title: 'Datové modely a konverze', icon: '🔀',
        items: [
          { t: 'c', q: 'Datový model popisuje…', a: 'objekty, jejich atributy a vztahy', w: ['jen barvy a styly čar', 'jen souřadnicový systém', 'jen formát souboru'], e: 'Určuje, jaké třídy objektů existují a jak jsou uloženy.' },
          { t: 'c', q: 'Vektorový model reprezentuje objekty jako…', a: 'body, linie a plochy', w: ['mřížku stejných buněk', 'sadu fotografií', 'tabulku bez geometrie'], e: 'Geometrie je dána souřadnicemi vrcholů.' },
          { t: 'c', q: 'Při konverzi DGN → DWG se převádějí…', a: 'hladiny a buňky na vrstvy a bloky', w: ['vrstvy na samostatné soubory', 'body na rastrové buňky', 'atributy na barvy čar'], e: 'Obsah je podobný, liší se terminologie a uložení stylů.' },
          { t: 'c', q: 'Převodní tabulka při konverzi určuje…', a: 'kam se převedou vrstvy a atributy', w: ['měřítko tisku výkresu', 'heslo k souboru', 'rychlost konverze'], e: 'Zajistí, aby např. budovy skončily ve správné vrstvě cílového modelu.' },
          { t: 'tf', q: 'Konverze mezi formáty může způsobit ztrátu atributů nebo stylů.', a: true, e: 'Proto se výsledek konverze vždy kontroluje.' },
          { t: 'c', q: 'U českých dat je při konverzi důležité kódování znaků, jinak…', a: 'se poškodí diakritika', w: ['se posunou souřadnice', 'se ztratí geometrie', 'se změní měřítko'], e: 'Starší data bývají ve Windows-1250, novější v UTF-8.' },
          { t: 'c', q: 'Převod mezi S-JTSK a ETRS89 se v ČR oficiálně provádí…', a: 'zpřesněnou globální transformací ČÚZK', w: ['posunem o konstantní hodnotu', 'Helmertovou transformací ze 2 bodů', 'přepočtem stupňů na metry'], e: 'Globální klíč doplňuje opravná tabulka, která zohlední deformace S-JTSK.' },
          { t: 'm', q: 'Spojte prvek s dimenzí', p: [['Bod', 'Bezrozměrný prvek'], ['Linie', 'Jednorozměrný prvek'], ['Plocha', 'Dvourozměrný prvek'], ['Těleso', 'Trojrozměrný prvek']] },
        ],
      },
      {
        id: 'bea009l5', title: 'Mapové služby a výstupy', icon: '🌐',
        items: [
          { t: 'c', q: 'Služba WMS poskytuje…', a: 'mapu jako obrázek (rastr)', w: ['vektorové prvky s atributy', 'seznam souřadnic bodů', 'surová data měření GNSS'], e: 'Server vykreslí mapu podle požadavku a pošle obrázek.' },
          { t: 'c', q: 'Služba WFS poskytuje…', a: 'vektorové prvky s atributy', w: ['předgenerované dlaždice', 'mapu jako obrázek', 'metadata bez dat'], e: 'Data lze stáhnout a dál analyzovat.' },
          { t: 'c', q: 'Standardy WMS a WFS vydává…', a: 'OGC', w: ['Esri', 'Bentley', 'ČSÚ'], e: 'Open Geospatial Consortium – otevřené standardy pro geodata.' },
          { t: 'c', q: 'Požadavek GetCapabilities vrací…', a: 'popis služby a dostupných vrstev', w: ['obrázek mapy výřezu', 'atributy jednoho prvku', 'souřadnice kurzoru'], e: 'Klient z něj zjistí vrstvy, formáty a souřadnicové systémy.' },
          { t: 'c', q: 'Katastrální mapu jako WMS poskytuje…', a: 'ČÚZK', w: ['Český statistický úřad', 'ČHMÚ', 'Ministerstvo vnitra'], e: 'Služby jsou dostupné přes Geoportál ČÚZK.' },
          { t: 'tf', q: 'Vrstvu WMS lze v CAD přímo editovat jako vektorovou kresbu.', a: false, e: 'WMS je jen obrázek – slouží jako podklad; pro editaci je třeba vektorová data.' },
          { t: 'c', q: 'Tematická mapa znázorňuje…', a: 'vybraný jev nad topografickým podkladem', w: ['jen polohopis bez obsahu', 'výhradně výškopis', 'pouze hranice parcel'], e: 'Např. hustotu obyvatel, využití území nebo hluk.' },
          { t: 'c', q: 'Kartogram vyjadřuje…', a: 'relativní hodnoty barvou ploch', w: ['absolutní hodnoty diagramy', 'polohu bodů značkami', 'výšky vrstevnicemi'], e: 'Absolutní hodnoty se zobrazují kartodiagramem.' },
          { t: 'm', q: 'Spojte službu nebo požadavek s obsahem', p: [['WMS', 'Rastrový obraz mapy'], ['WFS', 'Vektorové prvky'], ['WMTS', 'Předgenerované dlaždice'], ['GetCapabilities', 'Popis služby']] },
        ],
      },
    ],
  },
];
