// Kapitoly podle osnov VUT FAST (Ing., 2. ročník): Digitální model terénu, GIS 2,
// Fotogrammetrie a DPZ, Fyzikální geodézie a inerciální systémy, Geodézie pro BIM.
// Formát otázek viz js/content/u01-03.js.

export default [
  {
    id: 'nea041', title: 'Digitální model terénu', color: '#15803d', level: 'Ing.', course: 'NEA041', sem: '2. ročník · ZS',
    desc: 'Sběr dat, reprezentace a interpolace terénu, lomové linie, přesnost a analýzy nad DMT včetně produktů ČÚZK.',
    lessons: [
      {
        id: 'nea041l1', title: 'Sběr dat pro DMT', icon: '🛩️', gens: ['station'],
        items: [
          { t: 'c', q: 'Z jakých dat vznikly modely DMR 4G a DMR 5G ČÚZK?', a: 'Z leteckého laserového skenování', w: ['Ze stereofotogrammetrie ortofot', 'Z radarové interferometrie SRTM', 'Z digitalizace vrstevnic ZM 10'], e: 'DMR 4G a 5G vznikly z celostátního LLS, provedeného v letech 2009–2013.' },
          { t: 'c', q: 'Proč je LLS vhodnější než obrazová korelace pro terén v lese?', a: 'Část impulsů pronikne korunami k zemi', w: ['Laser vidí skrz hustou vegetaci', 'Snímky z lesa nelze orientovat', 'LLS nepotřebuje GNSS ani IMU'], e: 'Vícenásobné odrazy zachytí i terén pod korunami. Korelace vidí jen povrch, který je na snímcích viditelný.' },
          { t: 'c', q: 'Pro jaké zakázky je tachymetrie jako zdroj dat pro DMT vhodná hlavně?', a: 'Menší území s vysokou přesností', w: ['Mapování celého státu', 'Rozsáhlé zalesněné oblasti', 'Rychlé plošné snímkování'], e: 'Tachymetrie je pomalá, ale měřič volí charakteristické body a hrany přímo v terénu.' },
          { t: 'c', q: 'Při tachymetrii terénu je nejdůležitější zaměřit body…', a: 'na terénních hranách a lomech sklonu', w: ['v pravidelné síti bez ohledu na tvar', 'jen v místech s dobrým výhledem', 'hlavně na bodech bodového pole'], e: 'Kvalitu DMT určuje správná kostra terénu – hrany, údolnice, hřbetnice a lomy sklonu.' },
          { t: 'c', q: 'Fotogrammetrie z UAV dává přímo model…', a: 'povrchu (DMP) včetně vegetace', w: ['holého terénu pod vegetací', 'pouze vodních ploch', 'podzemních inženýrských sítí'], e: 'Obrazová korelace zachytí jen viditelný povrch – střechy a koruny. DMR se získá až filtrací.' },
          { t: 'c', q: 'Globální DMT z radarové interferometrie z raketoplánu (2000) se jmenuje…', a: 'SRTM', w: ['EGM2008', 'DMR 5G', 'CORINE'], e: 'Shuttle Radar Topography Mission pokryla pevninu mezi 60° s. š. a 56° j. š.' },
          { t: 'tf', q: 'Mračno z LLS se musí před tvorbou DMR klasifikovat a odfiltrovat body vegetace a budov.', a: true, e: 'DMR tvoří jen body klasifikované jako terén; ostatní třídy slouží např. pro DMP.' },
          { t: 'm', q: 'Spojte metodu sběru s její charakteristikou', p: [['LLS', 'Mračno s vícenásobnými odrazy'], ['Letecká fotogrammetrie', 'Obrazová korelace snímků'], ['Tachymetrie', 'Body volené měřičem'], ['UAV', 'Lokální data s malým GSD']], e: 'LLS jako aktivní metoda díky vícenásobným odrazům pronikne vegetací až na terén, zatímco fotogrammetrie zachytí jen viditelný povrch.' },
        ],
      },
      {
        id: 'nea041l2', title: 'Reprezentace terénu', icon: '🔺', gens: ['contour'],
        items: [
          { t: 'c', q: 'GRID reprezentuje terén jako…', a: 'pravidelnou mřížku výšek', w: ['síť nepravidelných trojúhelníků', 'soubor vrstevnic', 'seznam lomových linií'], e: 'Výška je v uzlech (nebo buňkách) matice s konstantním krokem.' },
          { t: 'c', q: 'Hlavní výhoda TIN proti GRID je, že…', a: 'hustota bodů odpovídá členitosti terénu', w: ['všechny trojúhelníky mají stejnou plochu', 'se ukládá jako obyčejná matice', 'nepotřebuje žádné vstupní body'], e: 'V rovině stačí velké trojúhelníky, v členitém terénu jsou menší. TIN navíc zachová měřené body.' },
          { t: 'c', q: 'Delaunayova triangulace splňuje podmínku, že…', a: 'v kružnici opsané trojúhelníku neleží jiný bod', w: ['všechny trojúhelníky jsou rovnostranné', 'součet délek hran je nejmenší', 'každý bod má právě šest sousedů'], e: 'Podmínka prázdné opsané kružnice vede k „co nejpravidelnějším“ trojúhelníkům.' },
          { t: 'c', q: 'Delaunayova triangulace ze všech triangulací maximalizuje…', a: 'nejmenší vnitřní úhel', w: ['součet ploch trojúhelníků', 'délku nejdelší hrany', 'počet trojúhelníků'], e: 'Vyhýbá se protáhlým, ostroúhlým trojúhelníkům, které zhoršují interpolaci.' },
          { t: 'c', q: 'Duální strukturou k Delaunayově triangulaci je…', a: 'Voroného diagram', w: ['minimální kostra', 'kvadrantový strom', 'Hilbertova křivka'], e: 'Spojením bodů, jejichž Voroného buňky sousedí, vznikne Delaunayova triangulace.' },
          { t: 'c', q: 'Hlavní výhoda GRID je…', a: 'snadné maticové výpočty a mapová algebra', w: ['přesné zachování lomových linií', 'proměnná hustota podle terénu', 'uložení jen měřených bodů'], e: 'Sousedství je dáno indexy řádků a sloupců, proto jsou analýzy (sklon, odtok) jednoduché.' },
          { t: 'tf', q: 'Vrstevnice jsou nejvhodnější primární datovou strukturou pro výpočetní analýzy DMT.', a: false, e: 'Vrstevnice jsou hlavně vizualizační výstup; analýzy se počítají nad GRID nebo TIN.' },
          { t: 'm', q: 'Spojte reprezentaci s popisem', p: [['GRID', 'Pravidelná matice výšek'], ['TIN', 'Nepravidelné trojúhelníky'], ['Vrstevnice', 'Izolinie stejné výšky'], ['Mračno bodů', 'Neuspořádané body XYZ']], e: 'GRID je výpočetně jednoduchý, ale nepřizpůsobí se členitosti terénu; TIN zahušťuje body tam, kde je terén členitější, a respektuje povinné hrany.' },
        ],
      },
      {
        id: 'nea041l3', title: 'Interpolace', icon: '📈',
        items: [
          { t: 'c', q: 'Metoda IDW přiřazuje bodům váhu…', a: 'nepřímo úměrnou mocnině vzdálenosti', w: ['přímo úměrnou vzdálenosti', 'podle variogramu dat', 'stejnou pro všechny body'], e: 'IDW = Inverse Distance Weighting, obvykle w = 1 / dᵖ s p = 2.' },
          { t: 'c', q: 'Kriging vychází z…', a: 'variogramu prostorové autokorelace', w: ['Delaunayovy triangulace', 'minimální křivosti plochy', 'nejbližšího měřeného bodu'], e: 'Váhy se určí tak, aby odhad byl nestranný a měl nejmenší rozptyl (BLUE).' },
          { t: 'c', q: 'Výhodou krigingu proti IDW je, že…', a: 'dává i odhad přesnosti interpolace', w: ['nepotřebuje žádný model dat', 'je výpočetně nejrychlejší', 'vždy prochází lomovými liniemi'], e: 'Z modelu variogramu vychází i rozptyl krigingu v každém interpolovaném bodě.' },
          { t: 'c', q: 'Interpolace metodou nejbližšího souseda vytvoří povrch…', a: 'schodovitý po Voroného buňkách', w: ['dokonale hladký', 'rovinný v trojúhelnících', 's minimální křivostí'], e: 'Každý bod přebírá výšku nejbližšího vstupního bodu, takže na hranicích buněk vznikají skoky.' },
          { t: 'c', q: 'Spline typu „tenká deska“ vytváří…', a: 'hladký povrch s minimální křivostí', w: ['schodovitý povrch po buňkách', 'rovinné trojúhelníkové plošky', 'povrch jen z nejbližšího bodu'], e: 'Minimalizuje ohybovou energii; může ale překmitnout mimo rozsah vstupních výšek.' },
          { t: 'tf', q: 'IDW nikdy nevytvoří výšku vyšší, než je maximum vstupních bodů.', a: true, e: 'IDW je vážený průměr, proto nevytvoří vrcholy ani dna mezi body – typické jsou „ploché vrcholy“.' },
          { t: 'c', q: 'Lineární interpolace v TIN určí výšku bodu…', a: 'z roviny trojúhelníku, v němž leží', w: ['průměrem všech bodů modelu', 'z nejbližšího vrcholu sítě', 'z variogramu okolních bodů'], e: 'Povrch je spojitý, ale na hranách trojúhelníků se skokově mění sklon.' },
          { t: 'm', q: 'Spojte pojem variogramu s významem', p: [['Nugget', 'Nespojitost v počátku'], ['Práh (sill)', 'Hodnota, kde se variogram ustálí'], ['Dosah (range)', 'Vzdálenost konce korelace'], ['Anizotropie', 'Závislost na směru']], e: 'Nugget zahrnuje chybu měření a variabilitu na kratších vzdálenostech, než je krok vzorkování; za dosahem už hodnoty nejsou prostorově korelované.' },
        ],
      },
      {
        id: 'nea041l4', title: 'Lomové linie a přesnost', icon: '📐',
        items: [
          { t: 'c', q: 'Povinná hrana (breakline) v TIN zajistí, že…', a: 'žádný trojúhelník hranu nepřekříží', w: ['všechny trojúhelníky jsou stejné', 'hrana se z modelu vypustí', 'výšky se na hraně zprůměrují'], e: 'Hrany trojúhelníků musí ležet podél lomové linie – vznikne omezená Delaunayova triangulace.' },
          { t: 'c', q: 'Typickou lomovou linií je…', a: 'horní hrana výkopu nebo břeh', w: ['hranice katastrálního území', 'osa vrstevnice 10 m', 'okraj mapového listu'], e: 'Lomové linie oddělují plochy s různým sklonem: hrany svahů, obruby, břehy, zdi.' },
          { t: 'c', q: 'Co se stane při triangulaci hrany svahu bez lomové linie?', a: 'Trojúhelníky hranu přemostí a zkreslí', w: ['Model bude přesnější než s linií', 'Triangulace skončí chybou', 'Vznikne automaticky GRID'], e: 'Hrany trojúhelníků spojí body nad a pod hranou – hrana se „useká“ a objemy budou chybné.' },
          { t: 'c', q: 'Ploché trojúhelníky (všechny vrcholy stejné výšky) vznikají typicky při triangulaci…', a: 'bodů digitalizovaných z vrstevnic', w: ['mračna z laserového skenování', 'pravidelné mřížky bodů', 'tachymetricky měřených bodů'], e: 'Tři vrcholy na jedné vrstevnici dávají vodorovnou plošku, např. v údolnicích a na hřbetech.' },
          { t: 'c', q: 'Přesnost DMT se obvykle vyjadřuje…', a: 'střední chybou výšky na kontrolních bodech', w: ['počtem trojúhelníků modelu', 'velikostí souboru v MB', 'rozdílem nejvyšší a nejnižší výšky'], e: 'RMSE rozdílů výšek modelu a nezávisle zaměřených kontrolních bodů.' },
          { t: 'c', q: 'Kde bývá přesnost DMR z LLS nejhorší?', a: 'Ve strmém a zarostlém terénu', w: ['Na rovinaté louce', 'Na asfaltové ploše', 'Na střechách budov'], e: 'Chybu zvyšuje malý počet odrazů od terénu pod vegetací a vliv polohové chyby na strmém svahu.' },
          { t: 'tf', q: 'Jemnější krok GRIDu, než odpovídá hustotě vstupních bodů, sám zvýší přesnost modelu.', a: false, e: 'Nová informace nevznikne – jen se interpoluje mezi stejnými body a roste objem dat.' },
          { t: 'o', q: 'Seřaďte kroky tvorby DMR z LLS', s: ['Kontrola a vyrovnání pásů LLS', 'Klasifikace bodů mračna', 'Výběr bodů terénu', 'Triangulace s lomovými liniemi', 'Kontrola přesnosti na kontrolních bodech'], e: 'Nejdřív geometrie pásů, pak klasifikace, model a nakonec nezávislá kontrola.' },
        ],
      },
      {
        id: 'nea041l5', title: 'Analýzy a produkty ČÚZK', icon: '🏔️', gens: ['slopeDeg', 'slopePercent'],
        items: [
          { t: 'c', q: 'Sklon v buňce GRIDu se obvykle počítá…', a: 'z gradientu v okně 3 × 3 buňky', w: ['z jediné sousední buňky', 'z průměru celé vrstvy', 'z nejvyššího bodu okolí'], e: 'Např. Hornova metoda odhadne ∂z/∂x a ∂z/∂y z osmi sousedů; sklon = arctg √(p² + q²).' },
          { t: 'c', q: 'Orientace svahu (aspect) udává…', a: 'azimut směru největšího spádu', w: ['výšku nad mořem', 'křivost svahu', 'délku svahu po spádnici'], e: 'Používá se např. pro oslunění, vegetaci a lavinová nebezpečí.' },
          { t: 'c', q: 'Sklon 45° odpovídá v procentech…', a: '100 %', w: ['45 %', '50 %', '90 %'], e: 'tg 45° = 1, tedy převýšení 1 m na 1 m vodorovně = 100 %.' },
          { t: 'c', q: 'Analýza viditelnosti (viewshed) určuje…', a: 'území viditelné ze stanoviska', w: ['odtokové cesty vody', 'sklon každé buňky', 'objem výkopů'], e: 'Pro každou buňku se testuje, zda paprsek od pozorovatele neprotne terén.' },
          { t: 'c', q: 'Algoritmus D8 v hydrologických analýzách…', a: 'pošle odtok do souseda s největším spádem', w: ['rozdělí odtok rovnoměrně do 8 buněk', 'počítá výšky z 8 nejbližších bodů', 'vyhlazuje terén 8× za sebou'], e: 'Z mapy směrů odtoku se dále počítá akumulace odtoku a povodí.' },
          { t: 'c', q: 'Před hydrologickou analýzou se v DMT musí odstranit…', a: 'bezodtokové deprese', w: ['lomové linie', 'kontrolní body', 'vrstevnice'], e: 'Umělé „jámy“ (sinks) by zastavily tok; vyplní se nebo se proříznou.' },
          { t: 'm', q: 'Spojte produkt ČÚZK s popisem', p: [['DMR 4G', 'GRID 5 × 5 m'], ['DMR 5G', 'TIN holého terénu'], ['DMP 1G', 'Povrch s budovami a vegetací']], e: 'Všechny produkty vznikly z leteckého laserového skenování území ČR; DMR popisuje holý terén, DMP i objekty nad ním.' },
          { t: 'tf', q: 'Rozdíl DMP − DMR (normalizovaný model povrchu) udává výšky budov a stromů nad terénem.', a: true, e: 'nDSM je základ pro modelování budov a pro odhad výšky a zásoby porostů.' },
        ],
      },
    ],
  },

  {
    id: 'nea042', title: 'GIS 2', color: '#0369a1', level: 'Ing.', course: 'NEA042', sem: '2. ročník · ZS',
    desc: 'Teorie informace a registry, relační a prostorové SQL, grafové algoritmy, topologie, kvalita dat a Web-GIS.',
    lessons: [
      {
        id: 'nea042l1', title: 'Informace a registry', icon: 'ℹ️',
        items: [
          { t: 'c', q: 'Shannonova entropie vyjadřuje…', a: 'střední množství informace zdroje', w: ['rychlost přenosu dat', 'velikost databáze', 'počet chyb v datech'], e: 'H = −Σ pᵢ log₂ pᵢ; čím méně předvídatelná zpráva, tím více informace nese.' },
          { t: 'n', q: 'Kolik bitů informace nese zpráva o jednom z 8 stejně pravděpodobných jevů?', a: 3, tol: 0, dec: 0, unit: 'bit', e: 'I = log₂ 8 = 3 bity.' },
          { t: 'c', q: 'Který UML diagram popisuje třídy, jejich atributy a vazby?', a: 'Diagram tříd', w: ['Diagram aktivit', 'Diagram případů užití', 'Sekvenční diagram'], e: 'Diagram tříd je základem návrhu datového modelu, např. v normách ISO 191xx.' },
          { t: 'c', q: 'Který z registrů patří mezi čtyři základní registry ČR?', a: 'RÚIAN', w: ['ISKN', 'Centrální registr vozidel', 'Obchodní rejstřík'], e: 'Základní registry: ROB, ROS, RÚIAN a RPP. ISKN a obchodní rejstřík jsou jejich zdroje.' },
          { t: 'm', q: 'Spojte zkratku základního registru s názvem', p: [['ROB', 'Registr obyvatel'], ['ROS', 'Registr osob'], ['RÚIAN', 'Územní identifikace, adresy a nemovitosti'], ['RPP', 'Registr práv a povinností']], e: 'Základní registry zřizuje zákon č. 111/2009 Sb.; RÚIAN spravuje ČÚZK a část jeho údajů se přebírá z katastru nemovitostí.' },
          { t: 'c', q: 'Kdo je správcem RÚIAN?', a: 'ČÚZK', w: ['Ministerstvo vnitra', 'Český statistický úřad', 'Ministerstvo pro místní rozvoj'], e: 'Údaje o parcelách a budovách se do RÚIAN editují přes ISKN, adresy a obce přes ISÚI.' },
          { t: 'tf', q: 'Údaje RÚIAN o parcelách se editují v informačním systému katastru nemovitostí.', a: true, e: 'ISKN je editačním systémem RÚIAN pro parcely, stavební objekty a katastrální území.' },
          { t: 'c', q: 'GeoInfoStrategie je…', a: 'strategie rozvoje prostorových informací v ČR', w: ['software pro správu katastru', 'norma pro metadata', 'evropská síť stanic GNSS'], e: 'Strategie rozvoje infrastruktury pro prostorové informace v ČR schválená vládou.' },
        ],
      },
      {
        id: 'nea042l2', title: 'Relační a prostorové SQL', icon: '🗄️',
        items: [
          { t: 'm', q: 'Spojte operaci relační algebry s významem', p: [['Selekce', 'Výběr řádků podle podmínky'], ['Projekce', 'Výběr sloupců'], ['Spojení', 'Kombinace relací podle atributu'], ['Sjednocení', 'N-tice obou relací']], e: 'V SQL odpovídá selekce klauzuli WHERE, projekce výčtu sloupců v SELECT, spojení klauzuli JOIN a sjednocení operátoru UNION.' },
          { t: 'c', q: 'Primární klíč tabulky…', a: 'jednoznačně identifikuje každý řádek', w: ['určuje pořadí sloupců', 'šifruje data v tabulce', 'odkazuje do jiné tabulky'], e: 'Odkaz do jiné tabulky je cizí klíč.' },
          { t: 'c', q: 'Která klauzule SQL odpovídá selekci relační algebry?', a: 'WHERE', w: ['SELECT', 'ORDER BY', 'GROUP BY'], e: 'Seznam sloupců za SELECT odpovídá projekci, podmínka WHERE selekci.' },
          { t: 'c', q: 'Funkce PostGIS ST_Intersects(a, b) vrátí true, když…', a: 'geometrie mají aspoň jeden společný bod', w: ['a leží celá uvnitř b', 'geometrie se jen dotýkají hranicí', 'geometrie jsou totožné'], e: 'Je to opak ST_Disjoint. „Leží uvnitř“ testuje ST_Within, dotyk ST_Touches.' },
          { t: 'c', q: 'Co vrátí ST_Buffer(geom, 50)?', a: 'Obalovou zónu 50 jednotek kolem geometrie', w: ['Seznam objektů do vzdálenosti 50 jednotek', 'Geometrii posunutou o 50 jednotek', 'Plochu geometrie zvětšenou o 50 %'], e: 'Jednotky jsou jednotkami souřadnicového systému geometrie, v S-JTSK tedy metry.' },
          { t: 'c', q: 'Jaký index se v PostGIS používá pro geometrie?', a: 'GiST (R-strom nad obdélníky)', w: ['B-strom nad souřadnicí X', 'Hash index nad ID', 'Bitmapový index'], e: 'Index filtruje podle obalových obdélníků (MBR), přesný test proběhne až poté.' },
          { t: 'tf', q: 'ST_Distance nad typem geometry v EPSG:4326 vrací vzdálenost v metrech.', a: false, e: 'Vrací ji ve stupních. Pro metry je nutné použít typ geography nebo projekci.' },
          { t: 'c', q: 'Deduktivní databáze rozšiřuje relační model o…', a: 'odvozovací pravidla', w: ['rastrová data', 'prostorové indexy', 'šifrování záznamů'], e: 'Nová fakta se odvozují logickými pravidly (např. Datalog) z uložených faktů.' },
        ],
      },
      {
        id: 'nea042l3', title: 'Grafy a data mining', icon: '🕸️',
        items: [
          { t: 'c', q: 'Minimální kostra grafu je…', a: 'strom přes všechny uzly s nejmenší vahou', w: ['nejkratší cesta mezi dvěma uzly', 'cyklus přes všechny hrany', 'podgraf s nejvíce hranami'], e: 'Využití např. pro návrh nejlevnější sítě vedení mezi objekty.' },
          { t: 'c', q: 'Které algoritmy hledají minimální kostru?', a: 'Kruskalův a Primův', w: ['Dijkstrův a A*', 'k-means a DBSCAN', 'RANSAC a ICP'], e: 'Kruskal přidává nejlehčí hrany netvořící cyklus, Prim rozšiřuje strom z jednoho uzlu.' },
          { t: 'c', q: 'Dijkstrův algoritmus nelze obecně použít, když…', a: 'graf má záporně ohodnocené hrany', w: ['graf je orientovaný', 'graf má více než 1000 uzlů', 'hrany mají různou délku'], e: 'Pro záporné hrany se používá např. Bellmanův–Fordův algoritmus.' },
          { t: 'c', q: 'Úloha čínského pošťáka hledá…', a: 'nejkratší uzavřený sled přes všechny hrany', w: ['nejkratší cestu přes všechny uzly', 'minimální kostru grafu', 'nejbližší uzel k danému bodu'], e: 'Typicky trasa úklidu ulic nebo roznášky pošty – každou ulici projet aspoň jednou.' },
          { t: 'c', q: 'Hamiltonovská cesta prochází…', a: 'každým uzlem právě jednou', w: ['každou hranou právě jednou', 'jen uzly se sudým stupněm', 'nejkratší hranou grafu'], e: 'Hledání nejkratší hamiltonovské kružnice je úloha obchodního cestujícího.' },
          { t: 'tf', q: 'Souvislý graf má uzavřený eulerovský tah, právě když mají všechny uzly sudý stupeň.', a: true, e: 'Když tomu tak není, úloha čínského pošťáka zdvojí hrany mezi uzly lichého stupně.' },
          { t: 'c', q: 'Shlukovací metoda k-means…', a: 'vyžaduje předem zvolit počet shluků', w: ['nepotřebuje žádné parametry', 'vždy najde globální optimum', 'pracuje jen s rastrovými daty'], e: 'Výsledek závisí na volbě k i na počátečních středech shluků.' },
          { t: 'm', q: 'Spojte úlohu s typickou metodou', p: [['Nejkratší cesta', 'Dijkstrův algoritmus'], ['Minimální kostra', 'Kruskalův algoritmus'], ['Shlukování bodů', 'k-means'], ['Optimalizace evolucí', 'Genetický algoritmus']], e: 'Dijkstrův algoritmus vyžaduje nezáporné ohodnocení hran; Kruskalův přidává hrany od nejlevnější, pokud nevytvoří cyklus.' },
        ],
      },
      {
        id: 'nea042l4', title: 'Topologie a kvalita dat', icon: '🧩',
        items: [
          { t: 'c', q: 'Topologické vztahy objektů se zachovávají při…', a: 'spojitých deformacích (homeomorfismu)', w: ['jakékoli změně dat', 'převzorkování rastru', 'změně atributů'], e: 'Sousednost, incidence a obsažení nezávisí na měřítku, posunu ani spojitém „natažení“.' },
          { t: 'c', q: 'Topologické predikáty (Touches, Within, Crosses…) vycházejí z modelu…', a: 'DE-9IM', w: ['UML', 'EPSG', 'IFC'], e: 'Dimensionally Extended 9-Intersection Model porovnává vnitřek, hranici a vnějšek geometrií.' },
          { t: 'c', q: 'Typickou topologickou chybou polygonové vrstvy parcel jsou…', a: 'překryty a mezery mezi sousedy', w: ['chybějící metadata vrstvy', 'nevhodně zvolené barvy', 'příliš dlouhé názvy'], e: 'Topologická pravidla (např. „nesmí se překrývat“) je automaticky odhalí.' },
          { t: 'c', q: 'Která norma popisuje metadata geografických informací?', a: 'ISO 19115', w: ['ISO 9001', 'ISO 19650', 'ISO 14001'], e: 'ISO 19115 je základ i pro metadata INSPIRE. Kvalitu dat popisuje ISO 19157.' },
          { t: 'm', q: 'Spojte prvek kvality dat s obsahem', p: [['Úplnost', 'Chybějící nebo nadbytečné objekty'], ['Logická konzistence', 'Dodržení pravidel modelu'], ['Polohová přesnost', 'Shoda souřadnic se skutečností'], ['Časová kvalita', 'Aktuálnost a platnost'], ['Tematická přesnost', 'Správnost atributů a tříd']], e: 'Prvky kvality prostorových dat definuje norma ISO 19157, podle níž se kvalita datové sady hodnotí i dokumentuje v metadatech.' },
          { t: 'tf', q: 'Směrnice INSPIRE ukládá poskytovatelům prostorových dat povinnost popsat data metadaty.', a: true, e: 'Metadata jsou vyhledatelná přes katalogové služby, v ČR přes Národní geoportál INSPIRE.' },
          { t: 'c', q: 'Ontologie v geoinformatice je…', a: 'formální popis pojmů a vztahů v oboru', w: ['typ prostorového indexu', 'metoda interpolace', 'formát rastrových dat'], e: 'Zajišťuje sémantickou interoperabilitu – stejný pojem znamená pro systémy totéž.' },
          { t: 'c', q: 'Rozdíl mezi přesností a správností dat je, že přesnost popisuje…', a: 'rozptyl hodnot, správnost blízkost pravdě', w: ['jen polohu, správnost jen atributy', 'totéž, jde o synonyma', 'aktuálnost, správnost úplnost'], e: 'Data mohou být přesná (málo rozptýlená), ale nesprávná kvůli systematické chybě.' },
        ],
      },
      {
        id: 'nea042l5', title: 'Analýzy, Web-GIS a BIM', icon: '🌐',
        items: [
          { t: 'c', q: 'Big data se charakterizují především…', a: 'objemem, rychlostí a různorodostí', w: ['přesností, cenou a licencí', 'měřítkem, zobrazením a legendou', 'počtem uživatelů a serverů'], e: 'Tzv. 3V: volume, velocity, variety; často se přidává i věrohodnost (veracity).' },
          { t: 'c', q: 'Váhy kritérií v multikriteriální analýze lze určit…', a: 'Saatyho párovým srovnáním (AHP)', w: ['Dijkstrovým algoritmem', 'Delaunayovou triangulací', 'metodou nejbližšího souseda'], e: 'AHP porovná každou dvojici kritérií a z matice vypočte váhy i míru konzistence.' },
          { t: 'c', q: 'Před sečtením kritérií v multikriteriální analýze je nutné je…', a: 'normalizovat na společnou škálu', w: ['převést do vektoru', 'seřadit podle abecedy', 'zaokrouhlit na celá čísla'], e: 'Kritéria mají různé jednotky (m, %, Kč), proto se převádějí např. na škálu 0–1.' },
          { t: 'c', q: 'Výpočet sklonu z okna 3 × 3 je v mapové algebře operace…', a: 'fokální', w: ['lokální', 'zonální', 'globální'], e: 'Lokální pracuje s jednou buňkou, fokální s okolím, zonální se zónami, globální s celou vrstvou.' },
          { t: 'm', q: 'Spojte webovou službu OGC s tím, co vrací', p: [['WMS', 'Obraz mapy'], ['WFS', 'Vektorové prvky'], ['WMTS', 'Předgenerované dlaždice'], ['CSW', 'Záznamy metadat']], e: 'WMS a WMTS vracejí jen obraz mapy, kdežto WFS vrací geometrii s atributy vhodnou k další analýze; CSW slouží k vyhledávání v katalogu metadat.' },
          { t: 'tf', q: 'Služba WMS poskytuje klientovi vektorová data s atributy k další analýze.', a: false, e: 'WMS vrací jen obrázek (PNG, JPEG). Vektorová data poskytuje WFS.' },
          { t: 'c', q: 'Čím se BIM liší od GIS nejvíce?', a: 'Detailem stavby v jejím životním cyklu', w: ['Neumí pracovat s geometrií', 'Pracuje jen s rastrovými daty', 'Nepoužívá žádné atributy'], e: 'GIS pracuje s územím, BIM s podrobným objektovým modelem jedné stavby.' },
          { t: 'c', q: 'Reverzní inženýrství v GIS znamená…', a: 'odvození modelu z existujících dat', w: ['návrh databáze od nuly', 'tisk mapy v opačném pořadí', 'převod rastru na obraz'], e: 'Např. rekonstrukce datového modelu z existující databáze nebo modelu objektu z mračna bodů.' },
        ],
      },
    ],
  },

  {
    id: 'nea046', title: 'Fotogrammetrie a DPZ', color: '#b45309', level: 'Ing.', course: 'NEA046', sem: '2. ročník · LS',
    desc: 'Orientace snímků, chyby a přesnost, ortofoto a obrazová korelace, fyzikální základy DPZ a klasifikace.',
    lessons: [
      {
        id: 'nea046l1', title: 'Relativní a absolutní orientace', icon: '🧭', gens: ['photoScale'],
        items: [
          { t: 'c', q: 'Kolik prvků má relativní orientace stereodvojice?', a: '5', w: ['3', '6', '7'], e: 'Ze 12 prvků vnější orientace dvou snímků zbude po odečtení 7 prvků absolutní orientace 5.' },
          { t: 'c', q: 'Kolik prvků má absolutní orientace modelu?', a: '7', w: ['5', '6', '12'], e: 'Prostorová podobnostní transformace: 3 posuny, 3 rotace a měřítko.' },
          { t: 'c', q: 'Podmínka koplanarity říká, že…', a: 'základna a oba paprsky leží v rovině', w: ['oba snímky leží v jedné rovině', 'paprsky jsou rovnoběžné', 'základna je vodorovná'], e: 'Při splnění se odpovídající paprsky protnou a zmizí y-paralaxa.' },
          { t: 'c', q: 'Minimální sada vlícovacích bodů pro absolutní orientaci je…', a: 'dva polohově-výškové a jeden výškový', w: ['jeden polohově-výškový bod', 'tři výškové body', 'dva výškové body'], e: '2 × 3 + 1 = 7 rovnic pro 7 neznámých; v praxi se volí nadbytečné body.' },
          { t: 'c', q: 'Klasické rozmístění šesti bodů pro relativní orientaci se nazývá…', a: 'Gruberovy body', w: ['Laplaceovy body', 'Helmertovy body', 'Voroného body'], e: 'Šest bodů rozložených ve třech řadách přes stereomodel; minimum je pět.' },
          { t: 'c', q: 'Vnitřní orientace analogového snímku se obnovuje pomocí…', a: 'rámových značek komory', w: ['vlícovacích bodů v terénu', 'antény GNSS', 'spojovacích bodů'], e: 'Rámové značky mají z kalibrace známé snímkové souřadnice.' },
          { t: 'tf', q: 'Přímé georeferencování z GNSS/IMU určí vnější orientaci i bez vlícovacích bodů.', a: true, e: 'Je nutná kalibrace excentricity (lever-arm) a úhlů mezi IMU a kamerou (boresight).' },
          { t: 'o', q: 'Seřaďte kroky dvoustupňové orientace stereodvojice', s: ['Vnitřní orientace', 'Relativní orientace', 'Absolutní orientace', 'Vyhodnocení modelu'], e: 'Nejprve se obnoví svazky paprsků, pak se vytvoří model a ten se umístí do terénu.' },
        ],
      },
      {
        id: 'nea046l2', title: 'Chyby a přesnost rekonstrukce', icon: '🎯', gens: ['stereoDepth'],
        items: [
          { t: 'c', q: 'Radiální distorze se modeluje…', a: 'polynomem radiální vzdálenosti (k₁, k₂, k₃)', w: ['posunem celého snímku', 'jedinou konstantou komory', 'rotací kolem osy κ'], e: 'Δr = k₁r³ + k₂r⁵ + k₃r⁷ (Brownův model); r je vzdálenost od hlavního bodu.' },
          { t: 'c', q: 'Tangenciální (decentrační) distorze vzniká…', a: 'necentrováním čoček objektivu', w: ['zakřivením Země', 'pohybem letadla', 'atmosférickou refrakcí'], e: 'Modeluje se koeficienty p₁, p₂; bývá menší než radiální distorze.' },
          { t: 'c', q: 'Zakřivení Země posouvá obraz bodu na svislém snímku…', a: 'radiálně směrem k nadiru', w: ['radiálně od nadiru', 've směru letu', 'kolmo ke směru letu'], e: 'Body se jeví níže, než jsou. Refrakce naopak posouvá obraz radiálně ven.' },
          { t: 'c', q: 'Radiální posun obrazu vlivem převýšení Δh na svislém snímku je…', a: 'r · Δh / h', w: ['h · Δh / r', 'c · Δh / h', 'r · h / Δh'], e: 'r je vzdálenost od nadiru, h výška letu. Tento posun odstraňuje až ortofoto.' },
          { t: 'c', q: 'Střední chyba hloubky v normálním případě je…', a: 'Z² / (B · c) · σ_p', w: ['Z / (B · c) · σ_p', 'B · c / Z² · σ_p', 'Z · B / c · σ_p'], e: 'Derivací Z = B · c / p podle p. Chyba roste s druhou mocninou vzdálenosti.' },
          { t: 'c', q: 'Jak se změní chyba hloubky, když se vzdálenost Z zdvojnásobí (B, c stejné)?', a: 'Zvětší se čtyřikrát', w: ['Zvětší se dvakrát', 'Nezmění se', 'Zmenší se na polovinu'], e: 'σ_Z je úměrná Z², proto se při větší vzdálenosti zvětšuje základna.' },
          { t: 'tf', q: 'U leteckého snímkování je poloha (X, Y) obvykle určena přesněji než výška Z.', a: true, e: 'Poměr σ_Z / σ_XY je přibližně h / B, a ten je větší než 1.' },
          { t: 'm', q: 'Spojte vliv s jeho příčinou', p: [['Radiální distorze', 'Vada objektivu'], ['Refrakce', 'Ohyb paprsku v atmosféře'], ['Zakřivení Země', 'Referenční plocha není rovina'], ['Reliéfní posun', 'Převýšení terénu']], e: 'Všechny čtyři vlivy posouvají obraz bodu radiálně vůči středu snímku; reliéfní posun roste s převýšením a se vzdáleností od nadiru.' },
        ],
      },
      {
        id: 'nea046l3', title: 'Ortofoto a obrazová korelace', icon: '🔍', gens: ['gsd'],
        items: [
          { t: 'c', q: 'Diferenciální překreslení snímku potřebuje…', a: 'orientovaný snímek a DMT', w: ['jen konstantu komory', 'dva snímky bez orientace', 'pouze vlícovací body'], e: 'Každý pixel ortofota se přes výšku z DMT promítne do snímku (nepřímá metoda).' },
          { t: 'c', q: 'Která metoda převzorkování zachová původní hodnoty pixelů?', a: 'Nejbližší soused', w: ['Bilineární', 'Bikubická', 'Lanczos'], e: 'Ostatní metody hodnoty průměrují – hodí se pro obraz, ne pro klasifikované rastry.' },
          { t: 'c', q: 'True ortofoto se od běžného liší tím, že…', a: 'používá DMP a odstraní sklápění budov', w: ['má vždy menší GSD', 'je jen černobílé', 'nepotřebuje orientaci snímků'], e: 'Běžné ortofoto s DMR ponechá střechy posunuté; true ortofoto doplní zakrytá místa z jiných snímků.' },
          { t: 'tf', q: 'Na běžném ortofotu vytvořeném s DMR jsou střechy budov posunuty od nadiru.', a: true, e: 'DMR nezná výšku budov, takže se jejich radiální posun neopraví.' },
          { t: 'c', q: 'Plošná obrazová korelace porovnává okna snímků pomocí…', a: 'normovaného korelačního koeficientu', w: ['konstanty komory', 'Kalmanova filtru', 'variogramu'], e: 'NCC je necitlivý na lineární změny jasu a kontrastu; maximum udává nejlepší shodu.' },
          { t: 'c', q: 'Deskriptor SIFT je invariantní hlavně vůči…', a: 'změně měřítka a rotaci', w: ['změně perspektivy o 90°', 'zakrytí objektu', 'rozmazání pohybem'], e: 'Scale-Invariant Feature Transform hledá extrémy v měřítkovém prostoru (DoG).' },
          { t: 'c', q: 'Detektor ORB kombinuje…', a: 'detektor FAST a deskriptor BRIEF', w: ['SIFT a RANSAC', 'Harrisův detektor a NCC', 'SURF a kriging'], e: 'Binární deskriptor se porovnává Hammingovou vzdáleností – je velmi rychlý.' },
          { t: 'c', q: 'Chybné korespondence při párování bodů se odstraňují metodou…', a: 'RANSAC', w: ['IDW', 'Kruskal', 'Kriging'], e: 'RANSAC opakovaně odhaduje model z náhodných vzorků a ponechá body, které s ním souhlasí.' },
          { t: 'o', q: 'Seřaďte kroky tvorby ortofota', s: ['Aerotriangulace', 'Tvorba nebo převzetí DMT', 'Diferenciální překreslení', 'Vyrovnání barev a mozaikování', 'Kontrola na kontrolních bodech'], e: 'Nejdřív geometrie snímků a terénu, pak překreslení a nakonec radiometrie a kontrola.' },
        ],
      },
      {
        id: 'nea046l4', title: 'Fyzikální základy DPZ a družice', icon: '🛰️',
        items: [
          { t: 'c', q: 'Vlastní tepelné záření zemského povrchu má maximum kolem…', a: '10 µm', w: ['0,5 µm', '0,1 µm', '1 mm'], e: 'Wienův zákon: λ_max ≈ 2898 µm·K / T; pro 300 K ≈ 10 µm, pro Slunce (≈ 5 800 K) ≈ 0,5 µm.' },
          { t: 'c', q: 'Atmosférické okno je…', a: 'část spektra, kterou atmosféra propouští', w: ['otvor v ozonové vrstvě', 'období bez oblačnosti', 'zorné pole družice'], e: 'Např. viditelné pásmo, termální okno 8–14 µm nebo mikrovlny.' },
          { t: 'c', q: 'Zdravá vegetace má odrazivost…', a: 'nízkou v červené, vysokou v blízké IR', w: ['vysokou v červené, nízkou v blízké IR', 'stejnou ve všech pásmech', 'nejvyšší v termální IR'], e: 'Chlorofyl pohlcuje červené světlo, buněčná struktura listu silně odráží blízké IR.' },
          { t: 'c', q: 'Družice Sentinel-1 nese…', a: 'radar SAR v pásmu C', w: ['multispektrální skener', 'laserový výškoměr', 'termální kameru'], e: 'Jde o aktivní senzor – vlastní zdroj mikrovlnného záření.' },
          { t: 'c', q: 'Nejlepší prostorové rozlišení multispektrálních pásem Sentinel-2 je…', a: '10 m', w: ['30 m', '1 m', '60 m'], e: '10 m mají modré, zelené, červené a blízké IR pásmo; ostatní 20 m nebo 60 m.' },
          { t: 'c', q: 'Multispektrální pásma družic Landsat 8 a 9 mají rozlišení…', a: '30 m', w: ['10 m', '2 m', '250 m'], e: 'Panchromatické pásmo má 15 m, termální pásma se převzorkovávají na 30 m.' },
          { t: 'tf', q: 'Radar SAR může snímkovat i přes oblačnost a v noci.', a: true, e: 'Mikrovlny pronikají mraky a senzor si scénu sám osvětluje.' },
          { t: 'm', q: 'Spojte druh rozlišení s významem', p: [['Prostorové', 'Velikost pixelu na zemi'], ['Spektrální', 'Počet a šířka pásem'], ['Radiometrické', 'Počet úrovní jasu'], ['Časové', 'Interval opakování snímků']], e: 'Druhy rozlišení jsou ve vzájemném kompromisu: menší pixel nebo užší pásma znamenají méně zachycené energie na detektor.' },
          { t: 'c', q: 'Družice Sentinel patří do programu…', a: 'Copernicus', w: ['Landsat', 'Galileo', 'GRACE'], e: 'Copernicus je program EU pro pozorování Země, data jsou volně dostupná.' },
        ],
      },
      {
        id: 'nea046l5', title: 'Indexy a klasifikace', icon: '🗺️',
        items: [
          { t: 'c', q: 'NDVI se vypočte jako…', a: '(NIR − R) / (NIR + R)', w: ['(R − NIR) / (R + NIR)', '(NIR − G) / (NIR + G)', 'NIR / (R · G)'], e: 'Normalizovaný vegetační index; R = červené pásmo, NIR = blízké infračervené.' },
          { t: 'n', q: 'Odrazivost v NIR je 0,50, v červeném pásmu 0,10. Jaký je NDVI?', a: 0.667, tol: 0.002, dec: 3, unit: '', e: 'NDVI = (0,50 − 0,10) / (0,50 + 0,10) = 0,40 / 0,60 = 0,667 – hustá vegetace.' },
          { t: 'c', q: 'Vodní plochy mají NDVI obvykle…', a: 'záporné nebo blízké nule', w: ['blízké +1', 'kolem 0,8', 'vždy přesně 0,5'], e: 'Voda silně pohlcuje blízké IR, proto je NIR < R.' },
          { t: 'c', q: 'Řízená klasifikace vyžaduje…', a: 'trénovací plochy se známou třídou', w: ['předem daný počet shluků', 'jen jedno spektrální pásmo', 'radarová data'], e: 'Z trénovacích ploch se určí spektrální příznaky tříd, podle nich se zařadí ostatní pixely.' },
          { t: 'c', q: 'Který algoritmus patří k neřízené klasifikaci?', a: 'ISODATA', w: ['Maximální věrohodnost', 'Minimální vzdálenost', 'Support Vector Machine'], e: 'ISODATA (podobně k-means) shlukuje pixely bez trénovacích dat.' },
          { t: 'c', q: 'Přesnost klasifikace se hodnotí pomocí…', a: 'chybové (konfuzní) matice', w: ['Delaunayovy triangulace', 'variogramu', 'matice rotace'], e: 'Z ní se počítá celková přesnost, přesnost zpracovatele a uživatele a koeficient kappa.' },
          { t: 'tf', q: 'Po neřízené klasifikaci musí analytik vzniklým shlukům přiřadit význam.', a: true, e: 'Algoritmus vytvoří jen spektrálně podobné skupiny, ne třídy jako „les“ nebo „orná půda“.' },
          { t: 'c', q: 'Produkt Sentinel-2 úrovně L2A obsahuje…', a: 'odrazivost na zemském povrchu (BOA)', w: ['odrazivost nad atmosférou (TOA)', 'surová data bez georeference', 'radarovou koherenci'], e: 'L1C je odrazivost TOA; L2A je po atmosférické korekci.' },
          { t: 'o', q: 'Seřaďte kroky řízené klasifikace', s: ['Předzpracování a korekce dat', 'Výběr trénovacích ploch', 'Výpočet signatur tříd', 'Klasifikace pixelů', 'Hodnocení chybovou maticí'], e: 'Hodnotí se na nezávislých testovacích plochách, ne na trénovacích.' },
        ],
      },
    ],
  },

  {
    id: 'nea047', title: 'Fyzikální geodézie a inerciální systémy', color: '#a21caf', level: 'Ing.', course: 'NEA047', sem: '2. ročník · LS',
    desc: 'Geopotenciální modely, slapy a altimetrie, pohyby zemské kůry, gyroskopy, akcelerometry a integrace INS/GNSS.',
    lessons: [
      {
        id: 'nea047l1', title: 'Geopotenciální modely', icon: '🌐',
        items: [
          { t: 'c', q: 'Globální geopotenciální modely vyjadřují potenciál rozvojem do…', a: 'sférických harmonických funkcí', w: ['Fourierovy řady v čase', 'polynomů v souřadnicích S-JTSK', 'Taylorovy řady výšky'], e: 'Model je dán koeficienty C̄ₙₘ a S̄ₙₘ do určitého stupně n a řádu m.' },
          { t: 'c', q: 'Model EGM2008 je úplný do stupně a řádu…', a: '2159', w: ['360', '70', '10 000'], e: 'To odpovídá rozlišení asi 5′ (≈ 9 km); vybrané koeficienty sahají až do stupně 2190.' },
          { t: 'c', q: 'Nejkratší rozlišená polovina vlnové délky pro stupeň n je přibližně…', a: '20 000 km / n', w: ['40 000 km · n', '6 371 km / n²', '1 000 km · n'], e: 'Polovina obvodu Země dělená stupněm; pro n = 360 asi 55 km.' },
          { t: 'c', q: 'Zonální koeficient C₂₀ (J₂) popisuje hlavně…', a: 'zploštění Země', w: ['rotaci Země', 'polohu těžiště', 'slapové deformace'], e: 'J₂ ≈ 1,08 · 10⁻³ je zdaleka největší koeficient; ovlivňuje i stáčení drah družic.' },
          { t: 'c', q: 'Koeficienty s řádem m = 0 se nazývají…', a: 'zonální', w: ['sektorové', 'teserální', 'normální'], e: 'Zonální nezávisí na délce; pro m = n jsou sektorové, ostatní teserální.' },
          { t: 'tf', q: 'Koeficienty stupně 1 jsou nulové, pokud je počátek souřadnic v těžišti Země.', a: true, e: 'Stupeň 1 popisuje polohu těžiště vůči počátku soustavy.' },
          { t: 'm', q: 'Spojte družicovou misi s principem', p: [['GRACE', 'Časové změny tíhového pole'], ['GOCE', 'Družicová gradiometrie'], ['CHAMP', 'Sledování dráhy pomocí GPS'], ['LAGEOS', 'Laserové měření vzdáleností (SLR)']], e: 'GRACE měřila změny vzdálenosti mezi dvojicí družic (low-low), CHAMP využíval sledování dráhy pomocí GPS (high-low) a LAGEOS je pasivní koule s koutovými odražeči.' },
          { t: 'c', q: 'Krátkovlnnou část EGM2008 určují hlavně…', a: 'pozemní a altimetrická tíhová data', w: ['jen data mise GRACE', 'nivelační pořady', 'astronomická měření'], e: 'Družice (GRACE) určují dlouhé vlny, detail dodávají tíhová data s rozlišením 5′.' },
        ],
      },
      {
        id: 'nea047l2', title: 'Slapy a družicová altimetrie', icon: '🌊', gens: ['orbitPeriod'],
        items: [
          { t: 'c', q: 'Slapové zrychlení je dáno…', a: 'rozdílem přitažlivosti v bodě a v těžišti', w: ['rotací Země kolem osy', 'odstředivou silou Měsíce', 'tlakem atmosféry na oceány'], e: 'Země jako celek volně „padá“ k Měsíci; slapy působí jen rozdíl přitažlivosti.' },
          { t: 'c', q: 'Slapový účinek Měsíce je proti Slunci…', a: 'přibližně dvakrát silnější', w: ['asi desetkrát slabší', 'přibližně stejně silný', 'asi stokrát silnější'], e: 'Slapy klesají s třetí mocninou vzdálenosti, proto blízký Měsíc převažuje (poměr ≈ 2,2).' },
          { t: 'c', q: 'Hlavní půldenní měsíční slapová vlna se označuje…', a: 'M2', w: ['K1', 'S2', 'O1'], e: 'M2 má periodu asi 12,42 h; S2 je sluneční půldenní vlna, K1 a O1 denní.' },
          { t: 'c', q: 'Loveova čísla popisují…', a: 'pružnou odezvu Země na slapy', w: ['rychlost rotace Země', 'tvar oběžné dráhy Měsíce', 'hustotu zemského jádra'], e: 'h a l popisují deformaci povrchu, k změnu potenciálu vlivem přerozdělení hmot.' },
          { t: 'c', q: 'Svislé slapové deformace pevné Země dosahují…', a: 'několika decimetrů', w: ['několika mikrometrů', 'desítek metrů', 'jednotek milimetrů'], e: 'Radiální posun je až asi 30–40 cm, proto se opravuje v GNSS, VLBI i SLR.' },
          { t: 'tf', q: 'Družicová altimetrie měří radarem vzdálenost družice od mořské hladiny.', a: true, e: 'Výška hladiny = výška dráhy − měřená vzdálenost (s korekcemi atmosféry a stavu moře).' },
          { t: 'c', q: 'Rozdíl střední hladiny moře a geoidu se nazývá…', a: 'dynamická topografie oceánu', w: ['undulace geoidu', 'výšková anomálie', 'tížnicová odchylka'], e: 'Dosahuje až asi ±1 m a souvisí s mořskými proudy.' },
          { t: 'm', q: 'Spojte misi s typem altimetrie', p: [['Jason-3', 'Radarová altimetrie oceánů'], ['ICESat-2', 'Laserová altimetrie ledu'], ['CryoSat-2', 'Radarová altimetrie ledu']], e: 'Radarová altimetrie pracuje s mikrovlnami a proniká oblačností, laserová má malou stopu a přesně mapuje povrch ledu i výšku vegetace.' },
        ],
      },
      {
        id: 'nea047l3', title: 'Pohyby kůry a mezinárodní programy', icon: '🌋',
        items: [
          { t: 'c', q: 'Euroasijská deska se v ITRF pohybuje rychlostí asi…', a: '2–3 cm za rok', w: ['2–3 mm za rok', '2–3 m za rok', '20–30 cm za rok'], e: 'Proto se souřadnice v ITRF mění a pro Evropu se zavedl ETRS89.' },
          { t: 'c', q: 'Proč jsou souřadnice v ETRS89 v Evropě téměř stálé?', a: 'Systém je spojen se stabilní částí desky', w: ['Evropa se vůbec nepohybuje', 'ETRS89 nepoužívá GNSS', 'Souřadnice se každý rok mění'], e: 'ETRS89 se pohybuje spolu s Euroasijskou deskou, zůstávají jen malé vnitrodeskové pohyby.' },
          { t: 'c', q: 'Která metoda umí plošně mapovat posuny terénu v mm z družic?', a: 'Radarová interferometrie (InSAR)', w: ['Relativní gravimetrie', 'Geometrická nivelace', 'Astronomická nivelace'], e: 'Z fázových rozdílů opakovaných snímků SAR se určí posuny ve směru pohledu družice.' },
          { t: 'c', q: 'Kde se v Evropě nejvýrazněji projevuje postglaciální výzdvih?', a: 've Fennoskandii', w: ['v Panonské pánvi', 'na Pyrenejském poloostrově', 'v Českém masivu'], e: 'Kůra se po roztátí ledovce stále zvedá, v centru až asi 1 cm za rok.' },
          { t: 'c', q: 'GGOS je…', a: 'globální geodetický pozorovací systém IAG', w: ['evropská síť stanic GNSS', 'model geoidu pro ČR', 'družice pro altimetrii'], e: 'Global Geodetic Observing System propojuje geometrii, rotaci a tíhové pole Země.' },
          { t: 'm', q: 'Spojte službu IAG s technikou', p: [['IGS', 'GNSS'], ['IVS', 'VLBI'], ['ILRS', 'Laserové měření k družicím'], ['IERS', 'Rotace Země a ITRF']], e: 'IERS kombinuje výsledky služeb IGS, IVS, ILRS a IDS (DORIS) do rámce ITRF a parametrů orientace Země.' },
          { t: 'tf', q: 'ITRF vzniká kombinací technik VLBI, SLR, GNSS a DORIS.', a: true, e: 'VLBI přispívá hlavně k orientaci a měřítku, SLR k poloze těžiště, GNSS k hustotě sítě.' },
          { t: 'c', q: 'Gravimetrie se v užité geofyzice využívá k…', a: 'hledání hustotních nehomogenit pod povrchem', w: ['měření vzdáleností k družicím', 'určování času GPS', 'mapování vegetace'], e: 'Tíhové anomálie prozradí např. dutiny, ložiska nebo zlomy.' },
        ],
      },
      {
        id: 'nea047l4', title: 'Gyroskopy a akcelerometry', icon: '🌀',
        items: [
          { t: 'c', q: 'Mechanický gyroskop využívá…', a: 'moment hybnosti rotujícího rotoru', w: ['interferenci laserového světla', 'Hallův jev v polovodiči', 'tlak kapaliny v trubici'], e: 'Rychle rotující rotor si zachovává směr osy v inerciálním prostoru.' },
          { t: 'c', q: 'Laserový kruhový gyroskop (RLG) je založen na…', a: 'Sagnacově jevu', w: ['Dopplerově jevu', 'Hallově jevu', 'Faradayově jevu'], e: 'Při otáčení se liší dráha dvou protiběžných paprsků – vznikne rozdíl frekvencí.' },
          { t: 'c', q: 'Vláknový gyroskop FOG zvyšuje citlivost…', a: 'mnoha závity optického vlákna', w: ['rychlejším otáčením rotoru', 'větší hmotností senzoru', 'chlazením na nízkou teplotu'], e: 'Sagnacův fázový posun roste s plochou uzavřenou dráhou světla, tedy s počtem závitů.' },
          { t: 'c', q: 'Jev lock-in u RLG se potlačuje…', a: 'mechanickým rozkmitáváním (dither)', w: ['zahřátím rezonátoru', 'vypnutím laseru', 'měřením GNSS'], e: 'Při malých rychlostech rotace se frekvence obou vln „svážou“ a senzor rotaci nevidí.' },
          { t: 'c', q: 'MEMS gyroskop měří úhlovou rychlost pomocí…', a: 'Coriolisovy síly na kmitající hmotě', w: ['Sagnacova jevu ve vlákně', 'rotujícího rotoru', 'magnetického pole Země'], e: 'Levné a malé senzory, ale s větším driftem než optické gyroskopy.' },
          { t: 'c', q: 'Akcelerometr měří…', a: 'specifickou (negravitační) sílu', w: ['přímo gravitační zrychlení', 'úhlovou rychlost', 'polohu v prostoru'], e: 'V klidu na stole ukazuje 1 g vzhůru; gravitaci je nutné do navigace doplnit modelem.' },
          { t: 'tf', q: 'Akcelerometr ve volném pádu ukazuje nulové zrychlení.', a: true, e: 'Na těleso působí jen gravitace, kterou akcelerometr nevidí (princip ekvivalence).' },
          { t: 'm', q: 'Spojte senzor s principem', p: [['RLG', 'Sagnacův jev v laserovém rezonátoru'], ['FOG', 'Sagnacův jev ve vláknové cívce'], ['MEMS gyroskop', 'Coriolisova síla'], ['Gyrokompas', 'Hledání severu z rotace Země']], e: 'RLG a FOG měří rozdíl frekvence či fáze dvou protiběžných paprsků (Sagnacův jev), MEMS gyroskop kmitající hmotu vychylovanou Coriolisovou silou.' },
        ],
      },
      {
        id: 'nea047l5', title: 'INS a integrace s GNSS', icon: '🧭',
        items: [
          { t: 'c', q: 'Inerciální jednotka IMU obsahuje typicky…', a: 'tři gyroskopy a tři akcelerometry', w: ['jeden gyroskop a GNSS anténu', 'tři magnetometry a barometr', 'dva akcelerometry a kompas'], e: 'Měří úhlové rychlosti a specifické síly ve třech osách.' },
          { t: 'c', q: 'INS určí polohu z měření akcelerometrů…', a: 'dvojnásobnou integrací zrychlení', w: ['jedinou derivací rychlosti', 'triangulací z družic', 'porovnáním s mapou'], e: 'Nejprve se zrychlení převede do navigačního systému podle orientace z gyroskopů.' },
          { t: 'c', q: 'Chyba polohy samostatného INS…', a: 'roste s časem bez vnější opory', w: ['je konstantní', 'se s časem zmenšuje', 'závisí jen na počtu družic'], e: 'Integrací se malé chyby senzorů kumulují – proto se INS podpírá GNSS.' },
          { t: 'c', q: 'Systém strapdown znamená, že…', a: 'senzory jsou pevně spojeny s nosičem', w: ['senzory jsou na stabilizované plošině', 'INS funguje jen se GNSS', 'měří se jen v jedné ose'], e: 'Orientace se počítá numericky z gyroskopů, nepotřebuje mechanickou plošinu.' },
          { t: 'c', q: 'Kalmanův filtr…', a: 'kombinuje predikci modelu s měřením', w: ['vyhlazuje obraz snímku', 'hledá nejkratší cestu v grafu', 'počítá sférické harmonické'], e: 'Váhy obou složek určují jejich kovarianční matice; filtr je rekurzivní.' },
          { t: 'c', q: 'Těsná (tightly coupled) integrace INS/GNSS…', a: 'využije pseudovzdálenosti i z méně než 4 družic', w: ['používá jen hotovou polohu GNSS', 'vůbec nepotřebuje IMU', 'funguje jen bez signálu GNSS'], e: 'Volná integrace kombinuje až výsledné polohy GNSS, těsná přímo surová měření.' },
          { t: 'tf', q: 'Schulerova perioda horizontálních chyb INS je asi 84 minut.', a: true, e: 'T = 2π √(R / g) ≈ 84,4 min – chyby polohy kmitají s touto periodou.' },
          { t: 'o', q: 'Seřaďte kroky jednoho cyklu Kalmanova filtru', s: ['Predikce stavu z modelu INS', 'Predikce kovarianční matice', 'Výpočet Kalmanova zisku', 'Oprava stavu měřením GNSS', 'Aktualizace kovarianční matice'], e: 'Cyklus se opakuje s každým novým měřením GNSS.' },
        ],
      },
    ],
  },

  {
    id: 'neb045', title: 'Geodézie pro BIM', color: '#4338ca', level: 'Ing.', course: 'NEB045', sem: '2. ročník · ZS',
    desc: 'BIM a CIM, standardy IDM/IFC/IFD a ISO 19650, CDE a role v týmu, IFC a CityGML a scan-to-BIM.',
    lessons: [
      {
        id: 'neb045l1', title: 'BIM a CIM', icon: '🏗️',
        items: [
          { t: 'c', q: 'BIM je nejlépe popsán jako…', a: 'správa informací o stavbě v životním cyklu', w: ['3D výkres budovy v CAD', 'software jednoho výrobce', 'formát souboru pro mapy'], e: 'Building Information Modelling – model je nosičem informací od návrhu po provoz a demolici.' },
          { t: 'c', q: 'CIM (City Information Modelling) rozšiřuje BIM na…', a: 'úroveň celého města', w: ['jednotlivé místnosti', 'strojní součásti', 'podzemní vody'], e: 'Propojuje modely budov, infrastruktury a území – blízko ke GIS a 3D modelům měst.' },
          { t: 'c', q: '4D BIM přidává k 3D modelu…', a: 'čas (harmonogram)', w: ['náklady', 'barvy materiálů', 'souřadnicový systém'], e: '5D pak přidává náklady; další „dimenze“ nejsou definovány jednotně.' },
          { t: 'm', q: 'Spojte pojem s charakteristikou', p: [['CAD', 'Výkresová geometrie bez sémantiky'], ['GIS', 'Prostorová data území'], ['BIM', 'Objektový model stavby'], ['CIM', 'Informační model města']], e: 'Klíčový rozdíl je sémantika: BIM i CIM nesou objekty s vlastnostmi a vztahy, zatímco CAD pracuje jen s geometrií výkresu.' },
          { t: 'tf', q: 'OpenBIM znamená spolupráci přes otevřené formáty (např. IFC) nezávislé na výrobci softwaru.', a: true, e: 'Každý účastník může pracovat ve svém programu a vyměňovat data přes IFC.' },
          { t: 'c', q: 'Která instituce z pověření MPO realizuje Koncepci zavádění metody BIM v ČR?', a: 'Česká agentura pro standardizaci', w: ['Český úřad zeměměřický a katastrální', 'Ministerstvo zemědělství', 'Česká komora architektů'], e: 'ČAS realizuje Koncepci zavádění metody BIM a spravuje web koncepcebim.cz.' },
          { t: 'c', q: 'Digitální dvojče stavby je…', a: 'průběžně aktualizovaný obraz reálné stavby', w: ['záložní kopie projektu', 'dva shodné modely IFC', 'výkres v měřítku 1 : 1'], e: 'Propojuje model s daty z provozu (senzory, údržba) v téměř reálném čase.' },
          { t: 'c', q: 'Hlavní přínos geodeta v BIM projektu je…', a: 'přesné zaměření stavu a georeference modelu', w: ['návrh statiky konstrukce', 'výběr materiálů fasády', 'cenová kalkulace stavby'], e: 'Geodet dodává vstupní data, vytyčuje z modelu a kontroluje skutečné provedení.' },
        ],
      },
      {
        id: 'neb045l2', title: 'IDM, IFC, IFD a normy', icon: '📚',
        items: [
          { t: 'm', q: 'Spojte standard buildingSMART s rolí', p: [['IDM', 'Procesy a výměny informací'], ['IFC', 'Datový model pro výměnu'], ['IFD (bSDD)', 'Slovník pojmů a vlastností'], ['MVD', 'Podmnožina IFC pro určitou výměnu']], e: 'IDM popisuje, kdo a kdy potřebuje jaké informace, MVD z toho vymezí potřebnou část IFC; IFC je normalizován jako ISO 16739.' },
          { t: 'c', q: 'Datový model IFC je normalizován jako…', a: 'ISO 16739', w: ['ISO 19115', 'ISO 9001', 'ISO 19157'], e: 'Poslední verze IFC 4.3 vyšla jako ISO 16739-1:2024.' },
          { t: 'c', q: 'IFC vyvíjí a spravuje organizace…', a: 'buildingSMART International', w: ['Open Geospatial Consortium', 'Česká agentura pro standardizaci', 'Evropská komise'], e: 'OGC spravuje standardy GIS, např. CityGML; obě organizace spolupracují.' },
          { t: 'c', q: 'Online implementací IFD je…', a: 'buildingSMART Data Dictionary (bSDD)', w: ['IFC 4.3', 'CityGML', 'ČSN EN ISO 19650'], e: 'bSDD sjednocuje názvy tříd a vlastností v různých jazycích a klasifikacích.' },
          { t: 'c', q: 'Série ČSN EN ISO 19650 se zabývá…', a: 'správou informací o stavbách s BIM', w: ['metadaty geografických dat', 'kvalitou prostorových dat', 'kalibrací laserových skenerů'], e: 'Definuje role, informační požadavky, CDE a proces předávání informací.' },
          { t: 'c', q: 'Plán realizace BIM zpracovávaný dodavatelem se označuje…', a: 'BEP', w: ['EIR', 'IFC', 'LOD'], e: 'BIM Execution Plan odpovídá na informační požadavky objednatele (EIR).' },
          { t: 'c', q: 'Co přinesla verze IFC 4.3?', a: 'Podporu dopravní infrastruktury', w: ['Podporu rastrových ortofot', 'Nahrazení formátem CityGML', 'Zrušení prostorových vazeb'], e: 'Přibyly silnice, železnice, mosty a přístavy včetně osy trasy (IfcAlignment).' },
          { t: 'tf', q: 'Soubor .ifc je běžně uložen v textovém formátu STEP (ISO 10303-21).', a: true, e: 'Existují i varianty ifcXML a zazipované .ifczip.' },
        ],
      },
      {
        id: 'neb045l3', title: 'CDE a role v týmu', icon: '👥',
        items: [
          { t: 'c', q: 'CDE (Common Data Environment) je…', a: 'společné datové prostředí projektu', w: ['formát výměny dat', 'software pro kreslení', 'úroveň podrobnosti modelu'], e: 'Jediný zdroj pravdy pro všechny informace projektu, s řízením verzí a přístupů.' },
          { t: 'o', q: 'Seřaďte stavy informací v CDE podle ISO 19650', s: ['Rozpracované', 'Sdílené', 'Publikované', 'Archivované'], e: 'Informace jsou nejprve u autora, pak se sdílí ke koordinaci, publikují k použití a archivují.' },
          { t: 'c', q: 'Kdo obvykle koordinuje profesní modely a kontrolu kolizí?', a: 'BIM koordinátor', w: ['Úředně oprávněný zeměměřič', 'Stavební úřad', 'Správce katastru'], e: 'Koordinátor sestavuje federovaný model a řeší kolize mezi profesemi.' },
          { t: 'c', q: 'Detekce kolizí (clash detection) hledá…', a: 'prostorové střety prvků profesí', w: ['chyby v souřadnicích bodů', 'duplicitní soubory v CDE', 'překročení rozpočtu'], e: 'Např. potrubí procházející nosníkem – odhalí se před stavbou, ne na stavbě.' },
          { t: 'c', q: 'Federovaný model je…', a: 'spojení samostatných profesních modelů', w: ['jeden soubor pro všechny profese', 'model schválený státem', 'model pouze pro provoz'], e: 'Každá profese spravuje svůj model; ke koordinaci se modely jen skládají dohromady.' },
          { t: 'tf', q: 'V CDE může každý účastník upravovat modely všech ostatních profesí.', a: false, e: 'Každý model vlastní jeho autor; ostatní ho jen referencují a připomínkují.' },
          { t: 'c', q: 'Informační požadavky na dodavatele stanovuje…', a: 'objednatel v EIR', w: ['dodavatel v BEP', 'geodet v zaměření', 'software CDE'], e: 'EIR říká, co má být dodáno; BEP popisuje, jak toho dodavatel dosáhne.' },
          { t: 'c', q: 'Aby BIM model seděl v S-JTSK a Bpv, musí být definováno…', a: 'georeferencování modelu', w: ['barevné schéma modelu', 'harmonogram stavby', 'klasifikace místností'], e: 'Vztah lokálních souřadnic projektu k S-JTSK a Bpv (v IFC 4 např. IfcMapConversion).' },
        ],
      },
      {
        id: 'neb045l4', title: 'IFC, CityGML a LOD', icon: '🏙️',
        items: [
          { t: 'c', q: 'CityGML je standard organizace…', a: 'OGC', w: ['buildingSMART', 'ČÚZK', 'ISO/TC 59'], e: 'Open Geospatial Consortium; CityGML je výměnný formát pro 3D modely měst.' },
          { t: 'm', q: 'Spojte úroveň LOD (CityGML 2.0) s obsahem', p: [['LOD0', 'Terén a půdorysy'], ['LOD1', 'Blokový model'], ['LOD2', 'Tvary střech'], ['LOD3', 'Architektonický detail fasád'], ['LOD4', 'Interiér budovy']], e: 'LOD0 až LOD4 zvyšují geometrický i sémantický detail; v CityGML 3.0 byl LOD4 zrušen a interiér lze modelovat v kterékoli úrovni.' },
          { t: 'tf', q: 'V CityGML 3.0 byla úroveň LOD4 zrušena a interiér lze modelovat v LOD0–3.', a: true, e: 'Vnitřek a vnějšek se v CityGML 3.0 popisují nezávisle na úrovni podrobnosti.' },
          { t: 'c', q: 'Jak se liší geometrie IFC a CityGML?', a: 'IFC popisuje objemy, CityGML povrchy', w: ['IFC je 2D, CityGML je 3D', 'IFC je rastr, CityGML vektor', 'Liší se jen příponou souboru'], e: 'IFC používá objemová tělesa (vytažení, CSG), CityGML hraniční reprezentaci (B-rep).' },
          { t: 'c', q: 'Level of Development se oproti Level of Detail týká…', a: 'spolehlivosti informací prvku', w: ['jen počtu polygonů', 'barev textur modelu', 'měřítka tisku výkresu'], e: 'Detail popisuje, kolik je v modelu vidět; Development, nakolik se na prvek lze spolehnout.' },
          { t: 'c', q: 'Level of Development LOD 500 znamená…', a: 'ověřený model skutečného provedení', w: ['koncepční studii objemu', 'model pro výrobu dílců', 'první návrh dispozice'], e: 'Stupnice 100–500: od koncepce po ověřený stav skutečného provedení.' },
          { t: 'c', q: 'Level of Information Need (LOIN) popisuje…', a: 'potřebné geometrické i negeometrické informace', w: ['přesnost laserového skeneru', 'počet uživatelů CDE', 'velikost souboru modelu'], e: 'Určuje, jaké informace jsou potřeba pro daný účel a milník – nic navíc (ISO 7817).' },
          { t: 'c', q: 'CityJSON je…', a: 'kódování datového modelu CityGML v JSON', w: ['nová verze IFC', 'rastrový formát DMT', 'webová služba pro ortofota'], e: 'Kompaktnější a snáze zpracovatelné než XML/GML.' },
        ],
      },
      {
        id: 'neb045l5', title: 'Scan-to-BIM', icon: '🔦',
        items: [
          { t: 'o', q: 'Seřaďte kroky scan-to-BIM', s: ['Plánování stanovisek a terčů', 'Skenování a zaměření terčů', 'Registrace a georeference mračen', 'Čištění a segmentace mračna', 'Modelování prvků BIM', 'Kontrola odchylek model–mračno'], e: 'Kvalita modelu stojí na dobré registraci a georeferenci mračen.' },
          { t: 'c', q: 'Proč se terče zaměřují i totální stanicí?', a: 'Aby šlo mračno georeferencovat', w: ['Aby se zvýšila hustota mračna', 'Aby skener měřil barvy', 'Aby se zkrátila doba skenování'], e: 'Terče se známými souřadnicemi v S-JTSK a Bpv převedou mračno do závazného systému a kontrolují registraci.' },
          { t: 'c', q: 'Segmentace mračna bodů znamená…', a: 'rozdělení bodů na plochy a objekty', w: ['zmenšení počtu bodů na polovinu', 'převod mračna do formátu IFC', 'obarvení bodů podle výšky'], e: 'Např. stěny, stropy, sloupy a potrubí – podklad pro modelování prvků.' },
          { t: 'c', q: 'Rovinné plochy (stěny, podlahy) se v mračnu často hledají algoritmem…', a: 'RANSAC', w: ['Dijkstra', 'Kriging', 'Kruskal'], e: 'RANSAC odhadne rovinu robustně i v přítomnosti šumu a jiných objektů.' },
          { t: 'c', q: 'Jak se nejlépe ověřuje přesnost modelu scan-to-BIM?', a: 'Mapou odchylek mezi modelem a mračnem', w: ['Počtem prvků v modelu', 'Velikostí souboru IFC', 'Vizuální kontrolou barev'], e: 'Barevná mapa vzdáleností bodů od ploch modelu ukáže místa, kde model neodpovídá skutečnosti.' },
          { t: 'tf', q: 'Scan-to-BIM je dnes plně automatický a zkušený modelář už není potřeba.', a: false, e: 'Automatizace pomáhá se segmentací, ale interpretace a modelování prvků vyžadují člověka.' },
          { t: 'c', q: 'Hustota skenování se volí podle…', a: 'nejmenšího prvku, který se modeluje', w: ['barvy fasády budovy', 'počtu uživatelů CDE', 'maximálního dosahu skeneru'], e: 'Drobné prvky (např. potrubí) potřebují hustší mračno než hrubá geometrie stěn.' },
          { t: 'c', q: 'Skutečná stěna je vychýlená o 2 cm od svislice. Jak ji modelovat?', a: 'Podle požadavků zadání modelu', w: ['Vždy přesně svisle', 'Stěnu vůbec nemodelovat', 'Jako mračno bez prvků'], e: 'Zadání určí, zda modelovat idealizovaně, nebo skutečnou geometrii s tolerancí.' },
          { t: 'c', q: 'Jak řešit zákryty (stíny) v mračnu bodů?', a: 'Doplnit další stanoviska skeneru', w: ['Zvýšit intenzitu laseru', 'Zmenšit hustotu skenování', 'Chybějící plochy vymyslet'], e: 'Každé místo by mělo být viditelné aspoň z jednoho, ideálně z více stanovisek.' },
        ],
      },
    ],
  },
];
