// Kapitoly podle osnov VUT FAST (Bc.): Matematická kartografie, Kartografie 1, GIS 1,
// Inženýrská geodézie 1, Výuka v terénu. Formát otázek viz js/content/u01-03.js.

export default [
  {
    id: 'mkart', title: 'Matematická kartografie', color: '#b45309', level: 'Bc.', course: '—', sem: '2. ročník · LS',
    desc: 'Referenční plochy, křivky na kouli, klasifikace a zkreslení zobrazení a zobrazení používaná v ČR.',
    lessons: [
      {
        id: 'mkartl1', title: 'Plochy a křivky na kouli', icon: '🌐', gens: ['sphericalExcess'],
        items: [
          { t: 'c', q: 'Jaké referenční plochy se v matematické kartografii postupně používají?', a: 'Elipsoid, koule a rovina', w: ['Geoid, kvazigeoid a rovina', 'Koule, válec a hyperboloid', 'Rovina, kužel a paraboloid'], e: 'Zemi aproximujeme elipsoidem nebo koulí a výsledek zobrazujeme do roviny (případně přes kužel či válec).' },
          { t: 'c', q: 'Ortodroma je na kouli…', a: 'nejkratší spojnice dvou bodů po hlavní kružnici', w: ['křivka protínající poledníky pod stálým úhlem', 'spojnice bodů po rovnoběžce', 'průmět poledníku do roviny rovníku'], e: 'Ortodroma leží na hlavní kružnici, jejíž rovina prochází středem koule.' },
          { t: 'c', q: 'Loxodroma je křivka, která…', a: 'protíná všechny poledníky pod stejným úhlem', w: ['je nejkratší spojnicí dvou bodů', 'vždy prochází oběma póly', 'leží v rovině procházející středem koule'], e: 'Loxodroma (kosoběžka) má stálý azimut – spirálovitě se blíží k pólu. Pro plavbu se stálým kurzem.' },
          { t: 'tf', q: 'Rovnoběžka 50° s. š. je ortodroma.', a: false, e: 'Rovnoběžky (kromě rovníku) jsou vedlejší kružnice – jejich rovina neprochází středem koule.' },
          { t: 'c', q: 'Ve kterém zobrazení se loxodroma zobrazí jako přímka?', a: 'Mercatorově', w: ['Gnómonickém', 'Stereografickém', 'Sansonově'], e: 'Mercatorovo válcové konformní zobrazení bylo navrženo pro námořní navigaci – kurz se odečte přímo z mapy.' },
          { t: 'c', q: 'Součet úhlů sférického trojúhelníku je…', a: 'větší než 180° o sférický exces', w: ['přesně 180°', 'menší než 180° o sférický exces', 'vždy právě 270°'], e: 'Sférický exces ε = P / R² (v radiánech) roste s plochou trojúhelníku.' },
          { t: 'c', q: 'Legendreova věta říká, že malý sférický trojúhelník lze řešit jako rovinný, když…', a: 'každý úhel zmenšíme o třetinu excesu', w: ['každou stranu zkrátíme o exces', 'úhly zvětšíme o celý exces', 'poloměr koule položíme roven 1'], e: 'Rovinný trojúhelník se stejnými stranami má úhly α − ε/3, β − ε/3, γ − ε/3.' },
          { t: 'n', q: 'Jaká je délka oblouku 1° poledníku na kouli o poloměru R = 6 371 km?', a: 111.19, tol: 0.05, dec: 2, unit: 'km', e: 'd = 2πR / 360 = 40 030 km / 360 ≈ 111,19 km.' },
          { t: 'm', q: 'Spojte pojem s popisem', p: [['Hlavní kružnice', 'Rovina prochází středem koule'], ['Loxodroma', 'Stálý azimut'], ['Poledník', 'Spojuje oba póly'], ['Rovník', 'Rovnoběžka se šířkou 0°']], e: 'Nejkratší spojnicí na kouli je ortodroma (oblouk hlavní kružnice), loxodroma protíná poledníky pod stálým úhlem a je delší; poledníkové kružnice jsou hlavní kružnice, z rovnoběžek jen rovník.' },
        ],
      },
      {
        id: 'mkartl2', title: 'Klasifikace zobrazení', icon: '🗂️',
        items: [
          { t: 'c', q: 'Konformní zobrazení nezkresluje…', a: 'úhly', w: ['plochy', 'délky ve všech směrech', 'vzdálenosti od středu'], e: 'Konformní (stejnoúhlé) zobrazení zachová úhly v nekonečně malém okolí bodu – tvary drobných útvarů jsou podobné.' },
          { t: 'c', q: 'Ekvivalentní zobrazení zachovává…', a: 'plochy', w: ['úhly', 'tvary', 'azimuty z libovolného bodu'], e: 'Ekvivalentní (stejnoplochá) zobrazení se hodí např. pro tematické mapy hustoty.' },
          { t: 'tf', q: 'Existuje zobrazení koule do roviny, které je současně konformní i ekvivalentní.', a: false, e: 'Kouli nelze rozvinout do roviny bez zkreslení – konformní a ekvivalentní vlastnost se vylučují.' },
          { t: 'c', q: 'Jak se nazývá zobrazení, které nezkresluje délky v jedné soustavě směrů (např. na polednících)?', a: 'Ekvidistantní', w: ['Konformní', 'Ekvivalentní', 'Gnómonické'], e: 'Ekvidistantní (stejnodélné) zobrazení zachovává délky jen v určitém směru, ne všude.' },
          { t: 'c', q: 'Zobrazení v obecné (šikmé) poloze má osu zobrazovací plochy…', a: 'odkloněnou od zemské osy i od roviny rovníku', w: ['totožnou se zemskou osou', 'ležící v rovině rovníku', 'kolmou k rovině poledníku 0°'], e: 'Normální poloha: osa = zemská osa; příčná (transverzální): osa v rovině rovníku; obecná: jinak.' },
          { t: 'c', q: 'Vyrovnávací (kompenzační) zobrazení…', a: 'zkresluje vše, ale žádnou veličinu příliš', w: ['nezkresluje žádnou veličinu', 'zachovává úhly i plochy', 'lze použít jen pro plány'], e: 'Příkladem je Robinsonovo zobrazení pro mapy světa.' },
          { t: 'c', q: 'Sečné zobrazení má oproti tečnému…', a: 'dvě nezkreslené linie a menší extrémy zkreslení', w: ['žádnou nezkreslenou linii', 'vždy konformní vlastnost', 'větší zkreslení uprostřed území'], e: 'Uprostřed je délkové zkreslení mírně pod 1, na okrajích nad 1 – zkreslení se rozloží rovnoměrněji.' },
          { t: 'm', q: 'Přiřaďte zobrazovací plochu druhu zobrazení', p: [['Rovina', 'Azimutální'], ['Kužel', 'Kuželové'], ['Válec', 'Válcové'], ['Koule (z elipsoidu)', 'Dvojité zobrazení']], e: 'Rovina dává azimutální, kužel kuželové a válec válcové zobrazení; při dvojitém zobrazení se elipsoid nejprve zobrazí na kouli a teprve ta do roviny – tak pracuje Křovákovo zobrazení.' },
        ],
      },
      {
        id: 'mkartl3', title: 'Kartografická zkreslení', icon: '🔍', gens: ['cylDistortion'],
        items: [
          { t: 'c', q: 'Délkové zkreslení m je definováno jako…', a: 'poměr délky v obraze k délce na referenční ploše', w: ['rozdíl délky v obraze a skutečnosti', 'poměr ploch v obraze a na kouli', 'úhel mezi obrazem poledníku a osou X'], e: 'm = ds′ / ds; hodnota 1 znamená, že délka není zkreslena. Často se udává v cm/km.' },
          { t: 'c', q: 'Tissotova indikatrix je…', a: 'elipsa – obraz nekonečně malé kružnice', w: ['kružnice nezkreslených délek', 'síť poledníků a rovnoběžek', 'graf délkového zkreslení podle šířky'], e: 'Poloosy a, b indikatrix jsou extrémní délková zkreslení v hlavních směrech daného bodu.' },
          { t: 'c', q: 'Jaká je Tissotova indikatrix u konformního zobrazení?', a: 'Kružnice (a = b)', w: ['Elipsa s a · b = 1', 'Úsečka', 'Elipsa s b = 0'], e: 'Konformní zobrazení zkresluje délky v bodě ve všech směrech stejně – indikatrix je kružnice, mění se jen její velikost.' },
          { t: 'c', q: 'Plošné zkreslení vypočteme z poloos indikatrix jako…', a: 'P = a · b', w: ['P = a + b', 'P = a / b', 'P = a − b'], e: 'U ekvivalentního zobrazení platí a · b = 1.' },
          { t: 'c', q: 'Délkové zkreslení m = 1,000 1 znamená, že délka 1 km se v obraze…', a: 'prodlouží o 10 cm', w: ['zkrátí o 10 cm', 'prodlouží o 1 m', 'prodlouží o 1 cm'], e: '(m − 1) · 1 000 m = 0,000 1 · 1 000 m = 0,1 m = 10 cm/km.' },
          { t: 'n', q: 'Mercatorovo zobrazení koule: délkové zkreslení je m = 1 / cos φ. Jaké je plošné zkreslení na rovnoběžce φ = 60°?', a: 4, tol: 0.001, dec: 0, unit: '', e: 'Konformní zobrazení: P = m² = (1 / cos 60°)² = 2² = 4. Plochy jsou tu čtyřikrát zvětšené.' },
          { t: 'tf', q: 'Úhlové zkreslení v bodě závisí na rozdílu poloos a a b Tissotovy indikatrix.', a: true, e: 'Když a = b, úhly se nezkreslují; čím víc se a a b liší, tím větší je maximální úhlové zkreslení.' },
          { t: 'm', q: 'Spojte pojem s vlastností Tissotovy indikatrix', p: [['Konformní', 'a = b'], ['Ekvivalentní', 'a · b = 1'], ['Ekvidistantní v polednících', 'Jedna poloosa rovna 1'], ['Plošné zkreslení', 'P = a · b']], e: 'Tissotova indikatrix je obraz nekonečně malé kružnice: konformní zobrazení ji ponechá kružnicí (mění jen velikost), ekvivalentní ji změní v elipsu o stejné ploše.' },
        ],
      },
      {
        id: 'mkartl4', title: 'Jednoduchá a nepravá zobrazení', icon: '🧭',
        items: [
          { t: 'c', q: 'Gnómonická projekce promítá kouli z…', a: 'jejího středu', w: ['protějšího pólu', 'nekonečna', 'bodu na rovníku'], e: 'Hlavní kružnice procházejí středem, proto se všechny ortodromy zobrazí jako přímky.' },
          { t: 'c', q: 'Stereografická projekce (promítání z protějšího bodu koule) je…', a: 'konformní', w: ['ekvivalentní', 'ekvidistantní', 'vyrovnávací'], e: 'Kružnice na kouli se zobrazí opět jako kružnice nebo přímky.' },
          { t: 'c', q: 'Postelovo (azimutální ekvidistantní) zobrazení nezkresluje…', a: 'vzdálenosti a azimuty od středu zobrazení', w: ['plochy v celé mapě', 'úhly v každém bodě', 'loxodromy'], e: 'Používá se např. pro mapy vzdáleností od jednoho místa (letiště, radiostanice).' },
          { t: 'c', q: 'V normálním kuželovém zobrazení se rovnoběžky zobrazí jako…', a: 'soustředné kruhové oblouky', w: ['rovnoběžné přímky', 'elipsy', 'sinusoidy'], e: 'Poledníky jsou přímky sbíhající se do vrcholu kužele.' },
          { t: 'c', q: 'V normálním válcovém zobrazení jsou poledníky…', a: 'rovnoběžné přímky', w: ['přímky sbíhající se v pólu', 'kruhové oblouky', 'elipsy'], e: 'Rovnoběžky jsou přímky kolmé k poledníkům – síť je pravoúhlá.' },
          { t: 'c', q: 'Nepravá zobrazení se liší od jednoduchých tím, že…', a: 'poledníky jsou obecné křivky', w: ['rovnoběžky jsou vždy elipsy', 'nepoužívají žádnou zobrazovací plochu', 'jsou vždy konformní'], e: 'Rovnoběžky mají tvar jako u „vzoru“ (přímky, oblouky), poledníky se ale zakřivují – např. Sansonovo, Mollweidovo, Bonneovo.' },
          { t: 'tf', q: 'Gaussovo zobrazení elipsoidu na kouli je konformní.', a: true, e: 'Používá se např. v Křovákově zobrazení: Besselův elipsoid → Gaussova koule s nezkreslenou rovnoběžkou 49°30′.' },
          { t: 'm', q: 'Spojte zobrazení s jeho vlastností', p: [['Mercatorovo', 'Válcové konformní'], ['Mollweidovo', 'Nepravé válcové stejnoploché'], ['Bonneovo', 'Nepravé kuželové stejnoploché'], ['Lambertovo kuželové', 'Kuželové konformní']], e: 'Mercatorovo zobrazení zachovává úhly, proto se v něm loxodroma zobrazí jako přímka a slouží k navigaci; nepravá zobrazení (Mollweide, Bonne) mají zakřivené poledníky a bývají stejnoplochá.' },
        ],
      },
      {
        id: 'mkartl5', title: 'Zobrazení v ČR', icon: '🇨🇿',
        items: [
          { t: 'c', q: 'Křovákovo zobrazení (S-JTSK) je…', a: 'kuželové konformní v obecné poloze', w: ['válcové konformní v příčné poloze', 'azimutální stejnoploché v normální poloze', 'kuželové ekvidistantní v normální poloze'], e: 'Dvojité zobrazení: Besselův elipsoid → Gaussova koule → kužel v obecné poloze → rovina.' },
          { t: 'c', q: 'Kam směřují kladné osy souřadnic S-JTSK?', a: 'X k jihu, Y k západu', w: ['X k severu, Y k východu', 'X k východu, Y k severu', 'X k západu, Y k jihu'], e: 'Počátek je ve vrcholu kužele, proto jsou souřadnice na území ČR kladné a platí Y < X.' },
          { t: 'c', q: 'Proč Křovák zmenšil poloměr základní rovnoběžky koeficientem 0,999 9?', a: 'Aby vznikly dvě nezkreslené rovnoběžky', w: ['Aby souřadnice vyšly kladné', 'Aby zobrazení bylo ekvivalentní', 'Aby osa X mířila k jihu'], e: 'Zobrazení se stalo sečným – délkové zkreslení je v ČR zhruba od −10 cm/km do +14 cm/km.' },
          { t: 'c', q: 'Gauss-Krügerovo zobrazení (S-42) používá elipsoid…', a: 'Krasovského', w: ['Besselův', 'GRS80', 'Hayfordův'], e: 'S-42 je bývalý vojenský systém; zobrazení je příčné válcové konformní v 6° (případně 3°) poledníkových pásech.' },
          { t: 'c', q: 'Jaké délkové zkreslení má UTM na středním poledníku pásu?', a: '0,999 6', w: ['1,000 0', '0,999 9', '1,000 4'], e: 'Díky zmenšení vznikají dvě nezkreslené linie asi 180 km od středního poledníku.' },
          { t: 'c', q: 'Ve kterých pásech UTM leží Česká republika?', a: '33 a 34', w: ['31 a 32', '3 a 4', '35 a 36'], e: 'Pás 33 má střední poledník 15° v. d., pás 34 poledník 21° v. d. (Pásy 3 a 4 patří k S-42.)' },
          { t: 'c', q: 'Ve kterém zobrazení byly vedeny mapy stabilního katastru?', a: 'Cassini-Soldnerově', w: ['Křovákově', 'Gauss-Krügerově', 'Mercatorově'], e: 'Transverzální válcové ekvidistantní zobrazení se systémy Gusterberg (Čechy) a Svatý Štěpán (Morava a Slezsko).' },
          { t: 'tf', q: 'Pro území protáhlé ve směru poledníku se hodí válcové zobrazení v příčné poloze.', a: true, e: 'Nezkreslená linie (střední poledník) pak prochází podélně územím – proto GK a UTM používají úzké poledníkové pásy.' },
          { t: 'm', q: 'Spojte systém se zobrazením', p: [['S-JTSK', 'Křovákovo'], ['S-42', 'Gauss-Krügerovo'], ['WGS84 (AČR)', 'UTM'], ['Stabilní katastr', 'Cassini-Soldnerovo']], e: 'Křovákovo zobrazení je dvojité konformní kuželové v obecné poloze; Gauss-Krügerovo i UTM jsou příčná válcová konformní zobrazení v poledníkových pásech, UTM navíc s měřítkem 0,9996 na středním poledníku.' },
        ],
      },
    ],
  },

  {
    id: 'kart1', title: 'Kartografie 1', color: '#15803d', level: 'Bc.', course: '—', sem: '2. ročník · LS',
    desc: 'Struktura kartografie, obsah a jazyk mapy, generalizace, kartometrie, státní mapová díla a dějiny kartografie.',
    lessons: [
      {
        id: 'kart1l1', title: 'Kartografie a mapa', icon: '🗺️',
        items: [
          { t: 'c', q: 'Mapa je…', a: 'zmenšený generalizovaný obraz Země v rovině', w: ['nezmenšená fotografie zemského povrchu', 'libovolný náčrt bez měřítka', 'seznam souřadnic podrobných bodů'], e: 'Mapa vzniká podle matematického zákona (zobrazení), je zmenšená, generalizovaná a používá znakový jazyk.' },
          { t: 'c', q: 'Čím se liší plán od mapy?', a: 'Zobrazuje malé území bez vlivu zakřivení Země', w: ['Nemá žádné měřítko', 'Zobrazuje vždy celý stát', 'Vzniká jen z leteckých snímků'], e: 'Plán má velké měřítko a zakřivení Země se u něj zanedbává.' },
          { t: 'c', q: 'Glóbus a reliéfní mapa patří mezi kartografická díla…', a: 'prostorová', w: ['rovinná', 'digitální', 'tematická'], e: 'Dělení děl: rovinná (mapy, plány, atlasy), prostorová (glóbusy, reliéfy), digitální.' },
          { t: 'c', q: 'Atlas je…', a: 'soubor map spojených účelem a koncepcí', w: ['jedna mapa velkého formátu', 'mapa bez legendy', 'soubor náhodně vybraných plánů'], e: 'Mapy v atlasu mají jednotné zpracování – zobrazení, znakový klíč i generalizaci.' },
          { t: 'c', q: 'Topografická mapa na rozdíl od tematické…', a: 'zobrazuje obecně polohopis, výškopis a popis', w: ['znázorňuje jen jeden vybraný jev', 'nemá souřadnicovou síť', 'nesmí obsahovat vrstevnice'], e: 'Tematická mapa klade důraz na zvolené téma (hustota, geologie…) na zjednodušeném topografickém podkladu.' },
          { t: 'tf', q: 'Kartometrie se zabývá měřením na mapách (délek, ploch, úhlů).', a: true, e: 'Patří k ní i hodnocení přesnosti map a oprava o srážku mapového listu.' },
          { t: 'c', q: 'Která disciplína kartografie řeší zobrazení a zkreslení?', a: 'Matematická kartografie', w: ['Tematická kartografie', 'Kartografická polygrafie', 'Dějiny kartografie'], e: 'Matematická kartografie tvoří geometrický základ všech map.' },
          { t: 'm', q: 'Spojte kartografické dílo s druhem', p: [['Glóbus', 'Prostorové'], ['Turistická mapa', 'Rovinné'], ['Mapový portál', 'Digitální'], ['Školní atlas', 'Soubor map']], e: 'Kartografická díla lze dělit podle formy: glóbus je prostorové dílo, mapa rovinné a mapový portál digitální; atlas je soubor map se společnou koncepcí.' },
        ],
      },
      {
        id: 'kart1l2', title: 'Obsah a kompozice mapy', icon: '🖼️', gens: ['scaleToReal', 'realToMap'],
        items: [
          { t: 'c', q: 'Co ohraničuje vnitřní rám mapy?', a: 'Mapové pole', w: ['Legendu', 'Tiráž', 'Celý mapový list'], e: 'Mimo vnitřní rám jsou mimorámové údaje a případně ozdobný (vnější) rám.' },
          { t: 'c', q: 'Který údaj patří mezi mimorámové údaje?', a: 'Tiráž (vydavatel, rok vydání)', w: ['Vrstevnice', 'Názvy obcí v mapovém poli', 'Silniční síť'], e: 'Mimorámové údaje: název, nomenklatura listu, měřítko, legenda, tiráž, schéma kladu listů…' },
          { t: 'c', q: 'Kilometrová síť na mapě je…', a: 'síť rovinných pravoúhlých souřadnic', w: ['síť poledníků a rovnoběžek', 'síť nivelačních pořadů', 'rozdělení státu na katastry'], e: 'Zeměpisná síť (poledníky a rovnoběžky) je něco jiného – na mapě v S-JTSK jsou její čáry obecně křivky.' },
          { t: 'c', q: 'Hlavní kompoziční prvky mapy jsou…', a: 'mapové pole, název, legenda a měřítko', w: ['jen mapové pole', 'vrstevnice, kóty a šrafy', 'body bodového pole a jejich místopisy'], e: 'Doplňují je tiráž, směrovka, případně vedlejší mapy a grafy. Dobrá kompozice je vyvážená.' },
          { t: 'tf', q: 'Grafické měřítko zůstane správné i po zmenšení kopie mapy.', a: true, e: 'Úsečka se zmenší ve stejném poměru jako mapa; číselné měřítko by po kopírování neplatilo.' },
          { t: 'c', q: 'Nomenklatura mapového listu je…', a: 'jednoznačné označení listu v kladu', w: ['seznam místních názvů', 'vysvětlivka znaků', 'údaj o magnetické deklinaci'], e: 'Klad listů určuje rozdělení území na listy, nomenklatura je jejich označení.' },
          { t: 'c', q: 'Topografický obsah mapy tvoří…', a: 'polohopis, výškopis a popis', w: ['legenda, tiráž a rám', 'jen vodstvo a sídla', 'souřadnice a nadmořské výšky bodů bodového pole'], e: 'Polohopis = objekty a jejich poloha; výškopis = tvar terénu; popis = názvy a čísla.' },
          { t: 'm', q: 'Spojte prvek mapy s jeho úlohou', p: [['Legenda', 'Vysvětluje znaky'], ['Tiráž', 'Údaje o vydání'], ['Směrovka', 'Orientace k severu'], ['Měřítko', 'Poměr zmenšení']], e: 'Spolu s mapovým polem a názvem tvoří tyto prvky kompozici mapy; měřítko 1 : 10 000 znamená, že 1 cm v mapě odpovídá 100 m ve skutečnosti.' },
        ],
      },
      {
        id: 'kart1l3', title: 'Kartografický jazyk', icon: '🔣', gens: ['popDensity', 'mapSymbol'],
        items: [
          { t: 'c', q: 'Studnu nebo kótu na mapě vyjádříme znakem…', a: 'bodovým', w: ['liniovým', 'plošným', 'písmovým'], e: 'Bodové znaky zobrazují objekty, jejichž rozměr v měřítku mapy nelze vyjádřit.' },
          { t: 'c', q: 'Vodní tok v malém měřítku vyjádříme znakem…', a: 'liniovým', w: ['bodovým', 'plošným', 'diagramovým'], e: 'Liniový znak vyjadřuje délkový objekt; jeho šířka v mapě nebývá v měřítku.' },
          { t: 'c', q: 'Kartogram vyjadřuje…', a: 'relativní hodnoty vztažené k ploše jednotky', w: ['absolutní hodnoty pomocí diagramů', 'polohu jednotlivých objektů', 'výšky terénu vrstevnicemi'], e: 'Např. hustota zalidnění obcí – plocha jednotky se vybarví podle intervalu hodnot.' },
          { t: 'c', q: 'Kartodiagram vyjadřuje…', a: 'absolutní hodnoty diagramy v územních jednotkách', w: ['relativní hodnoty barvou plochy', 'jen liniové objekty', 'tvar terénu stínováním'], e: 'Např. počet obyvatel obcí jako kruhové diagramy s plochou úměrnou hodnotě.' },
          { t: 'c', q: 'Která grafická proměnná se hodí pro vyjádření množství?', a: 'Velikost znaku', w: ['Tvar znaku', 'Orientace znaku', 'Druh písma'], e: 'Velikost a světlost jsou vnímány jako uspořádané; tvar a barevný tón spíš kvalitativně.' },
          { t: 'tf', q: 'Vrstevnice je čára spojující body se stejnou nadmořskou výškou.', a: true, e: 'Rozlišujeme základní, zdůrazněné a doplňkové vrstevnice.' },
          { t: 'c', q: 'Která metoda vyjádření výškopisu je čistě plastická a neměřitelná?', a: 'Stínování', w: ['Vrstevnice', 'Výškové kóty', 'Barevná hypsometrie po vrstvách'], e: 'Stínování dává dojem reliéfu, ale výšku z něj neodečteme – proto se kombinuje s vrstevnicemi.' },
          { t: 'm', q: 'Spojte metodu tematické kartografie s použitím', p: [['Kartogram', 'Hustota zalidnění'], ['Kartodiagram', 'Počet obyvatel obcí'], ['Izolinie', 'Průměrná teplota'], ['Metoda areálů', 'Výskyt druhu rostliny']], e: 'Kartogram vyjadřuje relativní hodnoty vztažené k ploše, kartodiagram absolutní hodnoty diagramem; izolinie spojují místa se stejnou hodnotou spojitého jevu.' },
        ],
      },
      {
        id: 'kart1l4', title: 'Generalizace a kartometrie', icon: '✂️', gens: ['scaleToReal'],
        items: [
          { t: 'c', q: 'Hlavní příčinou kartografické generalizace je…', a: 'zmenšení měřítka a účel mapy', w: ['chyba dálkoměru', 'srážka papíru', 'volba zobrazení'], e: 'Činitelé generalizace: účel, měřítko, charakter území, kvalita podkladů a grafické možnosti.' },
          { t: 'c', q: 'Vynechání malých rybníků při zmenšení měřítka je generalizace…', a: 'výběrem', w: ['posunem', 'zveličením', 'slučováním'], e: 'Výběr rozhoduje, které objekty v mapě zůstanou podle jejich významu a velikosti.' },
          { t: 'c', q: 'Silnice a železnice vedou těsně vedle sebe. Aby byly obě čitelné, kartograf použije…', a: 'posun (odsunutí)', w: ['výběr', 'zjednodušení', 'klasifikaci'], e: 'Posun mírně mění polohu objektu ve prospěch čitelnosti; důležitější objekt se posouvá méně.' },
          { t: 'c', q: 'Spojení několika blízkých budov v jeden blok je…', a: 'slučování (agregace)', w: ['zveličení', 'výběr', 'posun'], e: 'Slučování nahrazuje skupinu objektů jedním větším celkem.' },
          { t: 'n', q: 'Töpferův zákon výběru: mapa 1 : 25 000 obsahuje 400 objektů. Kolik jich ponecháme v odvozené mapě 1 : 100 000?', a: 200, tol: 0.5, dec: 0, unit: '', e: 'n_F = n_A · √(M_A / M_F) = 400 · √(25 000 / 100 000) = 400 · 0,5 = 200.' },
          { t: 'n', q: 'Grafická přesnost mapy je 0,1 mm. Jaké délce ve skutečnosti odpovídá v mapě 1 : 5 000?', a: 0.5, tol: 0.001, dec: 1, unit: 'm', e: '0,1 mm · 5 000 = 500 mm = 0,5 m. Menší objekty mapa neodliší.' },
          { t: 'tf', q: 'Zveličení znamená zvětšení malého, ale významného objektu, aby byl v mapě vidět.', a: true, e: 'Např. šířka silnice je v mapě malého měřítka mnohem větší, než by odpovídalo skutečnosti.' },
          { t: 'c', q: 'Srážka mapy je…', a: 'změna rozměru mapového listu (papíru)', w: ['sjednocení dvou listů', 'zmenšení měřítka při generalizaci', 'chyba vzniklá zobrazením'], e: 'Při kartometrii se zjistí proměřením rámu nebo sítě a naměřené hodnoty se opraví.' },
        ],
      },
      {
        id: 'kart1l5', title: 'Mapová díla a dějiny', icon: '📜',
        items: [
          { t: 'c', q: 'ZABAGED je…', a: 'digitální topografický model území ČR', w: ['katastrální mapa v digitální podobě', 'síť permanentních stanic GNSS', 'databáze adres a budov'], e: 'Základní báze geografických dat spravuje Zeměměřický úřad (ČÚZK); je podkladem pro Základní mapy ČR.' },
          { t: 'c', q: 'Nejpodrobnější základní mapa ČR (řada ZM) má měřítko…', a: '1 : 10 000', w: ['1 : 5 000', '1 : 2 000', '1 : 25 000'], e: 'Řada Základních map ČR: ZM 10, ZM 25, ZM 50, ZM 100 a menší.' },
          { t: 'c', q: 'SMO-5 je…', a: 'Státní mapa 1 : 5 000 odvozená', w: ['Základní mapa 1 : 50 000', 'vojenská mapa v UTM', 'mapa stabilního katastru'], e: 'SMO-5 kombinuje polohopis katastrální mapy s výškopisem; je v S-JTSK.' },
          { t: 'c', q: 'Autorem první známé mapy Čech (1518) je…', a: 'Mikuláš Klaudyán', w: ['Jan Amos Komenský', 'Kristián Müller', 'Gerhard Mercator'], e: 'Klaudyánova mapa je orientována k jihu a měla sloužit poutníkům.' },
          { t: 'c', q: 'Jan Amos Komenský je autorem známé mapy…', a: 'Moravy', w: ['Čech', 'Slezska', 'Evropy'], e: 'Komenského mapa Moravy vyšla poprvé roku 1627 a byla mnohokrát přetištěna.' },
          { t: 'c', q: 'Kristián (Johann Christoph) Müller vytvořil na počátku 18. století…', a: 'podrobné mapy Moravy a Čech', w: ['první mapu světa v Mercatorově zobrazení', 'stabilní katastr', 'III. vojenské mapování'], e: 'Mapa Moravy (1716) a Čech (1720) vznikly na základě terénního průzkumu – vrchol předtriangulační kartografie.' },
          { t: 'tf', q: 'III. (františko-josefské) vojenské mapování probíhalo v měřítku 1 : 25 000.', a: true, e: 'Bylo podkladem pro speciální mapy 1 : 75 000; opíralo se o triangulaci.' },
          { t: 'o', q: 'Seřaďte vojenská mapování od nejstaršího', s: ['I. (josefské) mapování', 'II. (františkovo) mapování', 'III. (františko-josefské) mapování'], e: 'I. 1763–1787 bez geodetického základu, II. 1806–1869 na triangulaci, III. 1869–1887.' },
          { t: 'c', q: 'Který podklad vzniká z leteckého laserového skenování?', a: 'DMR 5G', w: ['ZM 10', 'SMO-5', 'Müllerova mapa'], e: 'Digitální model reliéfu 5. generace je nepravidelná síť bodů holého terénu.' },
        ],
      },
    ],
  },

  {
    id: 'bea020', title: 'GIS 1', color: '#2563eb', level: 'Bc.', course: 'BEA020', sem: '3. ročník · ZS',
    desc: 'GIS a jeho historie, informační systémy veřejné správy, prostorové databáze a SQL, datové modely a webové služby.',
    lessons: [
      {
        id: 'bea020l1', title: 'Co je GIS', icon: '🧩',
        items: [
          { t: 'c', q: 'GIS je…', a: 'systém pro sběr, správu, analýzu a prezentaci prostorových dat', w: ['program na kreslení technických výkresů', 'databáze bez vazby na polohu', 'síť stanic pro určování polohy'], e: 'Klíčová je vazba dat na polohu a možnost prostorových analýz.' },
          { t: 'c', q: 'Za „otce GIS“ je považován…', a: 'Roger Tomlinson', w: ['John Snow', 'Gerhard Mercator', 'Josef Křovák'], e: 'Tomlinson vedl v 60. letech vývoj Canada Geographic Information System (CGIS).' },
          { t: 'c', q: 'Mapa Johna Snowa (Londýn 1854) je známý příklad…', a: 'rané prostorové analýzy', w: ['prvního satelitního snímku', 'první topografické mapy', 'prvního GIS softwaru'], e: 'Snow vynesl úmrtí na choleru a ukázal jejich koncentraci kolem jedné veřejné pumpy.' },
          { t: 'c', q: 'Které složky tvoří GIS?', a: 'Hardware, software, data, lidé a metody', w: ['Jen software a data', 'Mapy, glóbusy a atlasy', 'Přístroje, stativy a výtyčky'], e: 'Bez lidí a metod je i nejlepší software jen nástroj bez užitku.' },
          { t: 'c', q: 'Hlavní rozdíl GIS oproti CAD je, že GIS…', a: 'pracuje s atributy a prostorovými vztahy', w: ['neumí kreslit linie', 'nepoužívá souřadnice', 'slouží jen pro tisk map'], e: 'CAD je zaměřen na přesnou kresbu a konstrukci; GIS na databázi, topologii a analýzy.' },
          { t: 'tf', q: 'QGIS je otevřený (open source) GIS software.', a: true, e: 'Na rozdíl od komerčního ArcGIS firmy Esri je QGIS volně dostupný.' },
          { t: 'c', q: 'Geografický (topografický) objekt v GIS se popisuje…', a: 'geometrií a atributy', w: ['jen barvou a symbolem', 'jen názvem', 'jen souřadnicí středu listu'], e: 'Geometrie říká „kde“ a jaký tvar, atributy „co“ a „jaké“.' },
          { t: 'm', q: 'Spojte funkci GIS s příkladem', p: [['Sběr dat', 'Zaměření GNSS'], ['Správa dat', 'Uložení do databáze'], ['Analýza', 'Obalová zóna kolem řeky'], ['Prezentace', 'Tisk tematické mapy']], e: 'GIS se popisuje čtyřmi funkcemi: sběr, správa, analýza a prezentace dat; právě analýzy (obalové zóny, překryv vrstev) ho odlišují od pouhého kreslicího programu.' },
        ],
      },
      {
        id: 'bea020l2', title: 'IS veřejné správy', icon: '🏛️',
        items: [
          { t: 'c', q: 'RÚIAN je…', a: 'registr územní identifikace, adres a nemovitostí', w: ['informační systém o půdě', 'registr obyvatel', 'systém plánování tras'], e: 'RÚIAN je jeden ze základních registrů veřejné správy; jeho správcem je ČÚZK.' },
          { t: 'c', q: 'ISKN je…', a: 'informační systém katastru nemovitostí', w: ['registr silničních vozidel', 'systém pro GNSS korekce', 'mapový server Evropské unie'], e: 'Obsahuje geometrické i popisné informace katastru a je provozován ČÚZK.' },
          { t: 'c', q: 'Směrnice INSPIRE vytváří…', a: 'infrastrukturu pro prostorové informace v EU', w: ['jednotný katastr celé EU', 'evropský navigační systém', 'standard pro tisk map'], e: 'Směrnice 2007/2/ES požaduje metadata, síťové služby a interoperabilní data ve 34 tématech.' },
          { t: 'c', q: 'Kolik základních registrů veřejné správy má ČR?', a: '4', w: ['2', '6', '10'], e: 'Registr obyvatel, registr osob, RÚIAN a registr práv a povinností.' },
          { t: 'c', q: 'GeoInfoStrategie je…', a: 'strategie rozvoje infrastruktury pro prostorové informace v ČR', w: ['program pro výpočet GP', 'evropská norma pro metadata', 'mapový portál ČÚZK'], e: 'Cílem je koordinované využívání prostorových dat ve veřejné správě a omezení duplicit.' },
          { t: 'tf', q: 'Digitální technickou mapu (DTM) v ČR vedou kraje.', a: true, e: 'DTM kraje obsahuje dopravní a technickou infrastrukturu a objekty základní prostorové situace.' },
          { t: 'c', q: 'Metadata jsou…', a: 'data o datech (původ, přesnost, aktuálnost)', w: ['data zmenšená generalizací', 'nejpodrobnější data v GIS', 'data bez souřadnic'], e: 'Díky metadatům lze data vyhledat a posoudit, zda se hodí k danému účelu.' },
          { t: 'm', q: 'Spojte systém s obsahem', p: [['ISKN', 'Parcely a vlastnická práva'], ['RÚIAN', 'Adresní místa a stavební objekty'], ['ZABAGED', 'Topografická data'], ['INSPIRE', 'Evropská infrastruktura dat']], e: 'ISKN a RÚIAN spravuje ČÚZK, ZABAGED vytváří Zeměměřický úřad; INSPIRE je směrnice EU, která sjednocuje a zpřístupňuje prostorová data členských států.' },
        ],
      },
      {
        id: 'bea020l3', title: 'Prostorové databáze a SQL', icon: '🗄️',
        items: [
          { t: 'c', q: 'PostGIS je…', a: 'prostorové rozšíření databáze PostgreSQL', w: ['samostatný desktopový GIS', 'formát rastrových dat', 'webová mapová služba'], e: 'Přidává geometrické typy, prostorové funkce (ST_*) a indexy.' },
          { t: 'c', q: 'Která funkce vytvoří obalovou zónu (buffer)?', a: 'ST_Buffer', w: ['ST_Area', 'ST_Within', 'ST_Length'], e: 'ST_Buffer(geom, 50) vrátí polygon všech míst do 50 jednotek od geometrie.' },
          { t: 'c', q: 'Co vrátí dotaz s podmínkou ST_Intersects(a.geom, b.geom)?', a: 'Dvojice objektů, které mají společný bod', w: ['Jen objekty uvnitř jiných', 'Objekty vzdálené přes 1 km', 'Plochu průniku v m²'], e: 'Intersects = geometrie se protínají, dotýkají nebo jedna leží v druhé.' },
          { t: 'c', q: 'Kód EPSG:5514 označuje systém…', a: 'S-JTSK / Křovák East North', w: ['WGS 84 (zeměpisné souřadnice)', 'ETRS89 / UTM 33N', 'Web Mercator'], e: 'Varianta se zápornými souřadnicemi a osami orientovanými na východ a sever. EPSG:4326 je WGS 84.' },
          { t: 'c', q: 'Prostorový index typu R-strom pracuje s…', a: 'minimálními ohraničujícími obdélníky (MBR)', w: ['abecedním pořadím názvů', 'barvami pixelů', 'identifikátory parcel'], e: 'Nejprve se rychle vyberou kandidáti podle MBR (filtr), pak se přesně testují geometrie (upřesnění).' },
          { t: 'tf', q: 'WKT je textový zápis geometrie, např. POINT(16.6 49.2).', a: true, e: 'Well-Known Text; binární obdobou je WKB. Oba definuje standard OGC Simple Features.' },
          { t: 'c', q: 'Cizí klíč v relační databázi…', a: 'odkazuje na primární klíč jiné tabulky', w: ['jednoznačně určuje řádek vlastní tabulky', 'šifruje obsah tabulky', 'je vždy geometrický sloupec'], e: 'Tak se propojí např. tabulka parcel s tabulkou vlastníků.' },
          { t: 'o', q: 'Seřaďte klauzule dotazu SQL v pořadí zápisu', s: ['SELECT', 'FROM', 'WHERE', 'GROUP BY', 'ORDER BY'], e: 'SELECT sloupce FROM tabulky WHERE podmínka GROUP BY seskupení ORDER BY řazení.' },
        ],
      },
      {
        id: 'bea020l4', title: 'Datové modely a topologie', icon: '🔷',
        items: [
          { t: 'c', q: 'Vektorový model reprezentuje objekty pomocí…', a: 'bodů, linií a polygonů', w: ['pravidelné mřížky buněk', 'jen atributových tabulek', 'barevných pixelů'], e: 'Vektor je vhodný pro diskrétní objekty s jasnou hranicí – parcely, budovy, silnice.' },
          { t: 'c', q: 'Rastrový model je vhodný hlavně pro…', a: 'spojité jevy jako výška nebo teplota', w: ['hranice parcel', 'síť potrubí', 'adresní body'], e: 'Rastr je mřížka buněk; jeho přesnost je dána velikostí buňky (rozlišením).' },
          { t: 'c', q: 'Špagetový model se od topologického liší tím, že…', a: 'neukládá vztahy mezi objekty', w: ['neukládá souřadnice', 'je vždy rastrový', 'neumožňuje atributy'], e: 'Ve špagetovém modelu je společná hranice dvou polygonů uložena dvakrát a může se rozejít.' },
          { t: 'c', q: 'Topologie popisuje vlastnosti, které se nemění při…', a: 'spojité deformaci (natažení, ohnutí)', w: ['změně atributů', 'změně barvy symbolu', 'smazání objektu'], e: 'Sousednost, spojitost nebo obsažení zůstanou zachovány i po deformaci „gumové plachty“.' },
          { t: 'c', q: 'Linie končí kousek před jinou linií, se kterou se má spojit. Jde o chybu…', a: 'nedotah (undershoot)', w: ['přetah (overshoot)', 'sliver polygon', 'duplicitní uzel'], e: 'Topologická kontrola s tolerancí takové chyby najde a opraví přichycením (snap).' },
          { t: 'tf', q: 'Úzké mezery a překryty mezi sousedními polygony (sliver) jsou topologické chyby.', a: true, e: 'Vznikají typicky při samostatné digitalizaci sousedních ploch bez sdílené hranice.' },
          { t: 'c', q: 'Model DE-9IM slouží k popisu…', a: 'topologických vztahů dvou geometrií', w: ['komprese rastrových dat', 'transformace souřadnic', 'kódování barev mapy'], e: 'Porovnává vnitřek, hranici a vnějšek obou geometrií (matice 3 × 3).' },
          { t: 'm', q: 'Spojte topologický vztah s příkladem', p: [['Sousednost', 'Dvě parcely se společnou hranicí'], ['Spojitost', 'Úseky silnice propojené v uzlu'], ['Obsažení', 'Budova uvnitř parcely'], ['Disjunkce', 'Dva vzdálené rybníky']], e: 'Topologické vztahy se nemění při spojité deformaci (natažení, ohnutí) a GIS je využívá ke kontrole dat, např. že se sousední parcely nepřekrývají ani mezi nimi nejsou mezery.' },
        ],
      },
      {
        id: 'bea020l5', title: 'Služby, analýzy a DMT', icon: '🌐', gens: ['slopeDeg'],
        items: [
          { t: 'c', q: 'Webová služba WMS vrací…', a: 'obrázek mapy', w: ['vektorové objekty s atributy', 'metadata katalogu', 'surová rastrová data s hodnotami'], e: 'Požadavek GetMap vrátí vykreslený obrázek (PNG, JPEG) pro zadané území a vrstvy.' },
          { t: 'c', q: 'Která služba poskytuje vektorová data včetně atributů?', a: 'WFS', w: ['WMS', 'WMTS', 'CSW'], e: 'Web Feature Service vrací objekty (např. v GML) požadavkem GetFeature.' },
          { t: 'c', q: 'Čím se WMTS liší od WMS?', a: 'Poskytuje předem vygenerované dlaždice', w: ['Vrací vektorová data', 'Neumí měnit měřítko', 'Nepodporuje souřadnicové systémy'], e: 'Dlaždice (tiles) se dají cachovat, proto je WMTS rychlejší pro podkladové mapy.' },
          { t: 'c', q: 'Který požadavek vrací popis schopností služby (vrstvy, systémy, formáty)?', a: 'GetCapabilities', w: ['GetMap', 'GetFeature', 'GetLegend'], e: 'GetCapabilities je první krok při připojení služby do GIS klienta.' },
          { t: 'c', q: 'Fokální funkce mapové algebry počítá hodnotu buňky z…', a: 'hodnot v jejím okolí', w: ['jen hodnoty téže buňky', 'celé zóny stejné kategorie', 'všech buněk rastru'], e: 'Tomlin: lokální (buňka), fokální (okolí, klouzavé okno), zonální (zóna), globální (celý rastr).' },
          { t: 'c', q: 'Delaunayova triangulace pro TIN splňuje podmínku, že…', a: 'kružnice opsaná trojúhelníku neobsahuje jiný bod', w: ['všechny trojúhelníky jsou shodné', 'každý bod má právě 3 sousedy', 'hrany jsou rovnoběžné s osami'], e: 'Tím se maximalizuje nejmenší úhel a vznikají co nejméně protáhlé trojúhelníky.' },
          { t: 'tf', q: 'GRID je model terénu v pravidelné mřížce, TIN v nepravidelné trojúhelníkové síti.', a: true, e: 'TIN lépe vystihne terénní hrany a lokálně hustší body, GRID se snáz analyzuje.' },
          { t: 'c', q: 'Interpolační metoda IDW odhaduje hodnotu jako…', a: 'vážený průměr s váhou klesající se vzdáleností', w: ['hodnotu nejvzdálenějšího bodu', 'aritmetický průměr všech bodů', 'maximum z okolních bodů'], e: 'Inverse Distance Weighting – bližší body mají větší vliv.' },
          { t: 'm', q: 'Spojte službu OGC s obsahem', p: [['WMS', 'Obrázek mapy'], ['WMTS', 'Dlaždice'], ['WFS', 'Vektorové objekty'], ['WCS', 'Rastrová data (coverage)'], ['CSW', 'Katalog metadat']], e: 'Všechny jsou standardy OGC: WMS a WMTS vracejí jen obraz, WFS a WCS skutečná data (vektorová, resp. rastrová) a CSW umožňuje vyhledávat v metadatech.' },
        ],
      },
    ],
  },

  {
    id: 'bea021', title: 'Inženýrská geodézie 1', color: '#a21caf', level: 'Bc.', course: 'BEA021', sem: '3. ročník · ZS',
    desc: 'Rozbory přesnosti, vytyčování základních veličin, metody polohového vytyčení a geodézie ve výstavbě.',
    lessons: [
      {
        id: 'bea021l1', title: 'Model měření a rozbory', icon: '🎯', gens: ['stakeoutAccuracy'],
        items: [
          { t: 'c', q: 'Rozbor přesnosti a priori se provádí…', a: 'před měřením při návrhu metody a přístrojů', w: ['po měření z naměřených hodnot', 'jen u nivelace', 'až při předání stavby'], e: 'Z požadované přesnosti výsledku se odvodí nutná přesnost měření. A posteriori ověřuje dosaženou přesnost.' },
          { t: 'c', q: 'Model měření se skládá z modelu…', a: 'funkčního a stochastického', w: ['rastrového a vektorového', 'polohového a výškového', 'místního a státního'], e: 'Funkční model popisuje vztahy veličin, stochastický jejich přesnost a korelace.' },
          { t: 'c', q: 'Které chyby lze zmenšit opakováním měření a průměrováním?', a: 'Náhodné', w: ['Systematické', 'Hrubé', 'Všechny stejně'], e: 'Systematické chyby se průměrem neodstraní – eliminují se metodou nebo opravami, hrubé chyby kontrolou.' },
          { t: 'n', q: 'Délka byla měřena 9× se střední chybou jednoho měření 3 mm. Jaká je střední chyba průměru?', a: 1, tol: 0.01, dec: 1, unit: 'mm', e: 'σ_průměr = σ / √n = 3 / √9 = 1 mm.' },
          { t: 'c', q: 'Mezní odchylka se z výběrové střední chyby určí jako…', a: 'násobek střední chyby koeficientem u_p', w: ['součet všech oprav', 'polovina střední chyby', 'druhá mocnina střední chyby'], e: 'δ = u_p · σ; koeficient bývá 2 až 3 podle zvolené spolehlivosti.' },
          { t: 'c', q: 'Při polárním vytyčení na delší vzdálenost roste vliv…', a: 'chyby vytyčovaného úhlu', w: ['chyby výšky přístroje', 'chyby teploty na délku 1 m', 'zakřivení Země na úhel'], e: 'Příčná chyba = d · m_ω (v radiánech) – roste lineárně se vzdáleností.' },
          { t: 'tf', q: 'Při vytyčování se chyba podkladu (bodů vytyčovací sítě) projeví ve výsledné poloze bodu.', a: true, e: 'Výsledná chyba = chyba podkladu ⊕ chyba vytyčení; síť proto musí být přesnější než vytyčení.' },
          { t: 'o', q: 'Seřaďte kroky rozboru přesnosti a priori', s: ['Zjistit požadovanou přesnost (toleranci)', 'Zvolit metodu a funkční vztah', 'Aplikovat zákon hromadění chyb', 'Určit nutnou přesnost měření a přístroje'], e: 'Postupuje se od výsledku k měření – opačně než při rozboru a posteriori.' },
        ],
      },
      {
        id: 'bea021l2', title: 'Vytyčení základních veličin', icon: '📐',
        items: [
          { t: 'c', q: 'Při zpřesněném vytyčení úhlu se bod po změření rozdílu Δω posune…', a: 'kolmo k záměře o q = d · Δω', w: ['ve směru záměry o d · Δω', 'o konstantní 1 cm', 'na opačnou stranu záměry o d'], e: 'Nejdřív se bod vytyčí přibližně, úhel se změří ve více skupinách a oprava se odměří kolmo.' },
          { t: 'n', q: 'Vytyčení výšky: čtení na lati na reperu (H = 250,000 m) je 1,532 m. Jaké musí být čtení na lati na bodě s projektovanou výškou 250,800 m?', a: 0.732, tol: 0.0005, dec: 3, unit: 'm', e: 'Horizont přístroje = 250,000 + 1,532 = 251,532 m; čtení = 251,532 − 250,800 = 0,732 m.' },
          { t: 'c', q: 'Přímku prodlužujeme teodolitem ve dvou polohách dalekohledu, aby se vyloučila…', a: 'kolimační chyba', w: ['chyba z refrakce', 'chyba centrace cíle', 'chyba z teploty'], e: 'Z obou poloh vzniknou dva body; správný je jejich střed.' },
          { t: 'c', q: 'Svislici pro vysokou budovu nejpřesněji vytyčíme…', a: 'optickým nebo laserovým provažovačem', w: ['krabicovou libelou', 'pásmem a olovnicí ve větru', 'ručním GNSS'], e: 'Provažovač vytvoří svislou záměru k zenitu (nadiru); u teodolitu se svislice přenáší ve dvou polohách.' },
          { t: 'c', q: 'Rotační laser se na stavbě používá hlavně k vytyčení…', a: 'vodorovné (nebo skloněné) roviny', w: ['polohy lomových bodů', 'svislice', 'směrníků'], e: 'Rotující paprsek vytvoří referenční rovinu, kterou snímá detektor na lati.' },
          { t: 'tf', q: 'Při vytyčení vodorovné délky ve svahu musí geodet vytyčit delší šikmou délku.', a: true, e: 's = d / cos α (α je sklon); totální stanice to přepočítá automaticky.' },
          { t: 'c', q: 'Před vytyčením délky dálkoměrem je nutné zadat…', a: 'teplotu a tlak vzduchu', w: ['barvu hranolu', 'číslo katastrálního území', 'čas východu Slunce'], e: 'Z nich se vypočte atmosférická (fyzikální) oprava délky v ppm.' },
          { t: 'm', q: 'Spojte vytyčovanou veličinu s pomůckou', p: [['Výška', 'Nivelační přístroj a lať'], ['Svislice', 'Provažovač'], ['Vodorovná rovina', 'Rotační laser'], ['Úhel a délka', 'Totální stanice']], e: 'Rotační laser vytvoří vodorovnou (i skloněnou) rovinu, kterou snímá detektor na lati – jeden člověk tak vytyčí výšky na celé stavbě; provažovač přenáší svislici např. do vyšších pater.' },
        ],
      },
      {
        id: 'bea021l3', title: 'Metody polohového vytyčení', icon: '📍', gens: ['polarY', 'intersectionY', 'stakeout'],
        items: [
          { t: 'c', q: 'Vytyčovací prvky polární metody jsou…', a: 'vytyčovaný úhel a vodorovná délka', w: ['dvě délky ze dvou bodů', 'dva úhly ze dvou bodů', 'staničení a kolmice'], e: 'Úhel ω = σ_SP − σ_SO (od orientace), délka d = vzdálenost stanoviska S a bodu P.' },
          { t: 'c', q: 'Protínání vpřed z úhlů je výhodné, když…', a: 'na vytyčovaný bod nelze měřit délku', w: ['je k dispozici jen jeden bod sítě', 'body jsou pod zemí', 'chceme vytyčit výšku'], e: 'Např. pilíř mostu v řece – úhly se vytyčí ze dvou břehových bodů.' },
          { t: 'c', q: 'Nejpříznivější úhel protnutí na určovaném bodě je blízký…', a: '100 gon', w: ['10 gon', '180 gon', '400 gon'], e: 'Při ostrém nebo tupém úhlu protnutí se chyba polohy výrazně zvětšuje.' },
          { t: 'c', q: 'Protínání z délek má obecně…', a: 'dvě řešení symetrická podle spojnice', w: ['vždy jediné řešení', 'žádné řešení', 'nekonečně mnoho řešení'], e: 'Kružnice se protínají ve dvou bodech – správný se vybere podle náčrtu.' },
          { t: 'c', q: 'Volné stanovisko se určí…', a: 'měřením směrů a délek na aspoň dva známé body', w: ['postavením přístroje na bod sítě', 'jen odhadem z mapy', 'jen z výšky přístroje'], e: 'Výhodou je libovolná volba místa s dobrou viditelností; nadbytečná měření dají kontrolu.' },
          { t: 'tf', q: 'Ortogonální (pravoúhlá) metoda vytyčuje body staničením na měřické přímce a kolmicí.', a: true, e: 'Vhodná pro krátké kolmice a body blízko osy, např. u pozemních staveb.' },
          { t: 'o', q: 'Seřaďte postup polárního vytyčení bodu', s: ['Výpočet vytyčovacích prvků ze souřadnic', 'Postavení na stanovisko a orientace', 'Kontrola orientace na další bod', 'Vytyčení úhlu a délky', 'Stabilizace a kontrolní měření'], e: 'Kontrola orientace i kontrolní zaměření vytyčeného bodu jsou nezbytné.' },
        ],
      },
      {
        id: 'bea021l4', title: 'Stavební geodézie', icon: '🏗️',
        items: [
          { t: 'c', q: 'Vytyčovací výkres obsahuje…', a: 'vytyčované body, jejich souřadnice a vazby na síť', w: ['jen barevné vizualizace stavby', 'seznam vlastníků sousedních parcel', 'rozpočet stavby'], e: 'Uvádí i referenční systémy, požadovanou přesnost a údaje o vytyčovací síti.' },
          { t: 'c', q: 'Která norma se zabývá přesností vytyčování staveb?', a: 'ČSN 73 0420', w: ['ČSN 01 3411', 'ČSN EN ISO 9001', 'ČSN 73 6005'], e: 'ČSN 73 0420-1 a -2 stanoví požadavky na přesnost a mezní vytyčovací odchylky.' },
          { t: 'c', q: 'Primární stavební systém tvoří…', a: 'hlavní body a osy stavby', w: ['podrobné osy konstrukčních prvků', 'katastrální hranice', 'body ZABAGED'], e: 'Od primárního systému se odvozuje sekundární systém pro podrobné vytyčení konstrukcí.' },
          { t: 'c', q: 'Stavební lavičky slouží k…', a: 'zajištění os mimo prostor výkopu', w: ['sezení figurantů', 'nivelaci podlahy', 'měření posunů budovy'], e: 'Osy se přenesou na lavičky (hřebíky, zářezy) a lze je obnovit i po výkopu.' },
          { t: 'tf', q: 'Podle stavebního zákona musí vytyčení prostorové polohy stavby provést osoba k tomu oprávněná.', a: true, e: 'Výsledek ověřuje úředně oprávněný zeměměřický inženýr. Dříve zákon 183/2006 Sb., nyní zákon 283/2021 Sb.' },
          { t: 'c', q: 'Kdo obvykle zajišťuje vytyčovací síť a vytyčení prostorové polohy stavby?', a: 'Stavebník (investor)', w: ['Zhotovitel podlah', 'Katastrální úřad', 'Dodavatel oken'], e: 'Podrobné vytyčení a kontrolní měření během výstavby zajišťuje zpravidla zhotovitel.' },
          { t: 'c', q: 'Kontrolní měření na stavbě slouží k…', a: 'ověření souladu provedení s projektem', w: ['výpočtu obsahu parcel', 'zápisu do katastru', 'určení tíhového zrychlení'], e: 'Porovnávají se skutečné rozměry s projektovými a s mezními odchylkami.' },
          { t: 'o', q: 'Seřaďte geodetické práce při výstavbě budovy', s: ['Vybudování vytyčovací sítě', 'Vytyčení prostorové polohy stavby', 'Podrobné vytyčení konstrukcí', 'Kontrolní měření', 'Zaměření skutečného provedení'], e: 'Od celku k detailu; na konci se zaměří skutečný stav pro dokumentaci a případný GP.' },
        ],
      },
      {
        id: 'bea021l5', title: 'Vytyčovací sítě a liniové stavby', icon: '🛣️', gens: ['polarY'],
        items: [
          { t: 'c', q: 'Body vytyčovací sítě se stabilizují…', a: 'mimo dosah stavebních prací', w: ['přímo ve výkopu', 'na lešení', 'na stavebních strojích'], e: 'Síť musí zůstat stabilní po celou dobu stavby; body se chrání a kontrolují.' },
          { t: 'c', q: 'Proč se pro rozlehlé stavby volí místní systém orientovaný podle os stavby?', a: 'Vytyčovací výpočty jsou jednodušší', w: ['S-JTSK je zakázán', 'Místní systém nemá chyby', 'Nemusí se připojit na síť'], e: 'Osy stavby jsou rovnoběžné s osami souřadnic; vazba na S-JTSK se zachová transformačním klíčem.' },
          { t: 'c', q: 'Hlavní body kružnicového oblouku jsou…', a: 'začátek, střed a konec oblouku', w: ['jen vrchol tečen', 'body po 1 m', 'lomové body parcel'], e: 'ZO, SO a KO; k jejich vytyčení se využívá vrchol tečnového polygonu VB.' },
          { t: 'n', q: 'Oblouk o poloměru R = 300 m, úhel odklonu tečen α = 40 gon. Jaká je délka tečny t = R · tg(α/2)?', a: 97.48, tol: 0.01, dec: 2, unit: 'm', e: 't = 300 · tg 20 gon = 300 · 0,324 92 = 97,48 m.' },
          { t: 'c', q: 'Přechodnice (klotoida) má tu vlastnost, že…', a: 'křivost roste lineárně s délkou', w: ['má konstantní poloměr', 'je vždy přímá', 'má nulovou délku'], e: 'Platí A² = R · L; zajišťuje plynulý přechod z přímé do oblouku.' },
          { t: 'tf', q: 'Staničení udává vzdálenost bodu od začátku trasy měřenou po ose.', a: true, e: 'Zapisuje se např. km 1,250 00; příčné profily se vztahují ke staničení.' },
          { t: 'c', q: 'Podrobné body oblouku lze vytyčit…', a: 'pravoúhlými souřadnicemi od tečny', w: ['jen protínáním z délek', 'jen nivelací', 'pouze z vrcholu kužele'], e: 'Další možnosti: z tětivy, polárně ze stanoviska nebo GNSS RTK.' },
          { t: 'm', q: 'Spojte druh sítě s použitím', p: [['Stavební mřížka', 'Pravoúhlé budovy v areálu'], ['Polygonová síť', 'Liniová stavba'], ['Mikrosíť', 'Most nebo tunel'], ['Výšková síť', 'Vytyčení výšek']], e: 'Vytyčovací síť se volí podle tvaru stavby: stavební mřížka pro pravoúhlé areály, polygonový pořad podél liniové stavby a přesná mikrosíť s nucenou centrací pro mosty a tunely.' },
        ],
      },
    ],
  },

  {
    id: 'vyuka', title: 'Výuka v terénu', color: '#475569', level: 'Bc.', course: 'BEA026', sem: '3. ročník · LS',
    desc: 'Praktické postupy z terénních cvičení: rekognoskace, polygon, nivelace, mapování, GP a vytyčení stavby.',
    lessons: [
      {
        id: 'vyukal1', title: 'Rekognoskace a příprava', icon: '🔎', gens: ['bubble', 'station'],
        items: [
          { t: 'c', q: 'Hlavním cílem rekognoskace je…', a: 'vyhledat body a ověřit viditelnost', w: ['zapsat výsledky do katastru', 'vyrovnat síť', 'vytisknout hotovou mapu'], e: 'Zjistí se stav bodů, přístupnost, viditelnost a navrhnou se stanoviska.' },
          { t: 'c', q: 'Podle místopisu má být na místě žulový mezník, našel jsi jen prázdnou jámu. Co uděláš?', a: 'Bod nepoužiješ a zvolíš jiný', w: ['Postavíš se doprostřed jámy', 'Bod odhadneš podle plotu', 'Vložíš kolík a zapíšeš původní souřadnice'], e: 'Zničený bod nelze obnovit odhadem; poškození se ohlásí správci bodového pole.' },
          { t: 'o', q: 'Seřaďte postavení přístroje nad bodem', s: ['Postavit stativ přibližně nad bod', 'Hrubě centrovat (olovnice, laser)', 'Urovnat krabicovou libelu stojnými nohami', 'Urovnat přesnou libelu stavěcími šrouby', 'Docentrovat posunem po hlavě stativu a zkontrolovat libelu'], e: 'Centrace a horizontace se ovlivňují, proto se na konci obě kontrolují.' },
          { t: 'c', q: 'Figurant hlásí, že tyč s hranolem vytáhl na 1,80 m, ale v přístroji je zadáno 1,50 m. Co uděláš?', a: 'Opravíš výšku cíle a dotčené body', w: ['Nic, poloha je správně', 'Odečteš 30 cm od polohy', 'Přeměříš orientaci'], e: 'Výška cíle ovlivní jen výšky bodů; všechny body se špatnou výškou cíle je třeba opravit.' },
          { t: 'tf', q: 'Výtyčka s hranolem musí být při měření svislá podle krabicové libely.', a: true, e: 'Naklonění o 1° při výšce 1,5 m posune hranol o asi 2,6 cm.' },
          { t: 'c', q: 'Proč se před prací kontroluje rektifikace přístrojů?', a: 'Aby se odhalily přístrojové chyby', w: ['Aby se nabily baterie', 'Kvůli vyšší ceně měření', 'Aby šel přístroj rychleji'], e: 'Např. i-chyba nivelačního přístroje se ověří zkouškou ze středu a z konce.' },
          { t: 'c', q: 'Při rekognoskaci zjistíš, že mezi dvěma navrženými body brání výhledu nové oplocení. Co uděláš?', a: 'Navrhneš jinou polohu bodu', w: ['Budeš měřit skrz plot', 'Zkrátíš záměru odhadem', 'Bod vynecháš bez náhrady'], e: 'Právě proto se viditelnost ověřuje před měřením, ne až při něm.' },
          { t: 'm', q: 'Spojte pomůcku s účelem', p: [['Stativ', 'Stabilní podložka přístroje'], ['Trojnožka', 'Upevnění a horizontace'], ['Výtyčka s hranolem', 'Cíl pro dálkoměr'], ['Nivelační podložka', 'Přestavový bod latě']], e: 'Trojnožka se stavěcími šrouby umožňuje přístroj urovnat a vyměnit za cíl bez změny centrace (nucená centrace); nivelační podložka zaručí stálou výšku latě na přestavovém bodě.' },
        ],
      },
      {
        id: 'vyukal2', title: 'Polygon a protínání', icon: '🔺', gens: ['polygonClosure', 'station', 'traverse'],
        items: [
          { t: 'o', q: 'Seřaďte měření osnovy směrů na vrcholu polygonu ve skupině', s: ['I. poloha: záměra na zadní bod', 'I. poloha: záměra na přední bod', 'Proložit dalekohled do II. polohy', 'II. poloha: záměra na přední bod', 'II. poloha: záměra na zadní bod'], e: 'Ve II. poloze se postupuje v opačném pořadí; průměr obou poloh eliminuje osové chyby.' },
          { t: 'c', q: 'Úhlový uzávěr polygonu překročil mezní odchylku. Co uděláš?', a: 'Najdeš chybný vrchol a úhel přeměříš', w: ['Rozdělíš uzávěr rovnoměrně', 'Zvětšíš mezní odchylku', 'Změníš souřadnice koncového bodu'], e: 'Chybný vrchol pomůže najít výpočet pořadu z obou konců – na chybném vrcholu vyjdou z obou výpočtů téměř stejné souřadnice.' },
          { t: 'c', q: 'Figurant hlásí, že musel kvůli projíždějícímu autu uhnout z bodu. Co uděláš?', a: 'Počkáš a záměru změříš znovu', w: ['Změřenou hodnotu ponecháš', 'Opravíš ji odhadem', 'Změníš číslo bodu'], e: 'Každá záměra musí jít na cíl přesně nad bodem – nejisté měření se opakuje.' },
          { t: 'tf', q: 'Délky polygonových stran se měří tam i zpět.', a: true, e: 'Obousměrné měření dává kontrolu a zpřesnění; rozdíl nesmí překročit mezní hodnotu.' },
          { t: 'c', q: 'Proč se u polygonu používá nucená centrace (trojpodstavcová soustava)?', a: 'Omezí chyby z centrace přístroje a cílů', w: ['Zrychlí výpočet uzávěru', 'Nahradí orientaci', 'Odstraní refrakci'], e: 'Přístroj a terče se vyměňují v trojnožkách, které zůstávají na místě.' },
          { t: 'c', q: 'U protínání vpřed vidíš, že úhel na určovaném bodě bude jen asi 20 gon. Co uděláš?', a: 'Zvolíš jinou dvojici daných bodů', w: ['Nic, výsledek bude přesný', 'Budeš měřit jen v I. poloze', 'Zvětšíš výšku cíle'], e: 'Ostrý úhel protnutí výrazně zhoršuje přesnost polohy; ideál je kolem 100 gon.' },
          { t: 'c', q: 'Oboustranně připojený a orientovaný polygon umožňuje kontrolu…', a: 'úhlů i souřadnic', w: ['jen výšek', 'jen úhlů', 'žádnou kontrolu'], e: 'Z orientací na obou koncích vyjde úhlový uzávěr, z koncového bodu souřadnicové uzávěry.' },
          { t: 'm', q: 'Spojte uzávěr s tím, co kontroluje', p: [['Úhlový uzávěr', 'Vrcholové úhly'], ['Souřadnicový uzávěr', 'Úhly i délky'], ['Rozdíl délek tam a zpět', 'Měření jedné strany'], ['Výškový uzávěr', 'Převýšení']], e: 'Úhlový uzávěr lze spočítat jen v pořadu připojeném a orientovaném na obou koncích; souřadnicový (polohový) uzávěr pak odhalí chyby délek i zbytkové úhlové chyby.' },
        ],
      },
      {
        id: 'vyukal3', title: 'Nivelační pořad', icon: '📏', gens: ['levelSetup', 'fieldbook', 'blunder'],
        items: [
          { t: 'o', q: 'Seřaďte práci na jedné nivelační sestavě', s: ['Postavit přístroj uprostřed mezi latě', 'Urovnat krabicovou libelu', 'Zacílit a přečíst lať vzad', 'Zacílit a přečíst lať vpřed', 'Zapsat čtení a spočítat převýšení', 'Zadní lať přechází dopředu'], e: 'Zadní figurant se přesouvá na další přestavový bod, přední lať zůstává na podložce.' },
          { t: 'c', q: 'Figurant hlásí, že během přesunu přístroje omylem zvedl a posunul nivelační podložku. Co uděláš?', a: 'Měříš znovu od posledního pevného bodu', w: ['Podložku vrátíš odhadem', 'Pokračuješ, chyba je malá', 'Opravíš výšku o 1 cm'], e: 'Přestavový bod ztratil výšku – spojitost pořadu je přerušena.' },
          { t: 'c', q: 'Proč se přístroj staví doprostřed mezi latě?', a: 'Aby se vyloučila chyba ze sklonu záměrné přímky', w: ['Aby byla kratší záměra vpřed', 'Aby figurant lépe slyšel', 'Aby se ušetřil čas'], e: 'Stejné délky záměr vyloučí i vliv zakřivení Země a z velké části refrakce.' },
          { t: 'tf', q: 'Při naklonění latě je čtení větší, než by bylo na svislé lati.', a: true, e: 'Proto má lať krabicovou libelu; nejmenší čtení odpovídá svislé poloze.' },
          { t: 'c', q: 'Proč se volí sudý počet sestav v oddílu?', a: 'Vyloučí se rozdíl nul obou latí', w: ['Zkrátí se délka pořadu', 'Není třeba měřit zpět', 'Přístroj se méně zahřeje'], e: 'Latě se střídají vzad a vpřed, takže se jejich indexová chyba při sudém počtu sestav odečte.' },
          { t: 'c', q: 'Rozdíl převýšení oddílu tam a zpět je větší než mezní odchylka. Co uděláš?', a: 'Oddíl přeměříš', w: ['Vezmeš průměr', 'Použiješ jen měření tam', 'Zmenšíš počet sestav ve výpočtu'], e: 'Nesplněný limit znamená chybu v měření – průměrování ji jen zamaskuje.' },
          { t: 'c', q: 'Figurant hlásí, že lať stojí v měkké hlíně a pomalu se boří. Co uděláš?', a: 'Použiješ nivelační podložku', w: ['Budeš číst rychleji', 'Lať podložíš rukou', 'Budeš číst jen vpřed'], e: 'Podložka (žabka) zajišťuje stabilní výšku přestavového bodu.' },
          { t: 'm', q: 'Spojte pojem nivelace s významem', p: [['Záměra vzad', 'Čtení na bodě známé výšky'], ['Záměra vpřed', 'Čtení na určovaném bodě'], ['Přestavový bod', 'Dočasný bod mezi sestavami'], ['Oddíl', 'Úsek mezi dvěma nivelačními body']], e: 'Převýšení sestavy je čtení vzad minus čtení vpřed (Δh = z − p); oddíl se měří tam i zpět a rozdíl obou měření se porovnává s mezní odchylkou.' },
        ],
      },
      {
        id: 'vyukal4', title: 'Mapování a GP', icon: '🗺️', gens: ['station'],
        items: [
          { t: 'o', q: 'Seřaďte postup tvorby účelové mapy', s: ['Rekognoskace a vyhledání bodů', 'Vybudování měřické sítě', 'Podrobné měření s náčrtem', 'Výpočet souřadnic a výšek', 'Kresba polohopisu a vrstevnic'], e: 'Nejdřív síť, pak podrobné body a nakonec kresba – s kontrolami v každém kroku.' },
          { t: 'c', q: 'Měřický náčrt se vyhotovuje…', a: 'v terénu souběžně s měřením', w: ['doma podle paměti', 'až po vyhotovení mapy', 'jen u nivelace'], e: 'Čísla bodů v náčrtu musí souhlasit se zápisníkem nebo registrací.' },
          { t: 'c', q: 'Figurant hlásí, že stojí u rohu budovy, na který z přístroje nevidíš. Co uděláš?', a: 'Změříš ho z jiného stanoviska nebo oměrnými mírami', w: ['Roh vynecháš', 'Odhadneš ho z mapy', 'Změříš blízký strom'], e: 'Neviditelné body se doplní z dalšího stanoviska, excentricky nebo pásmem od zaměřených bodů.' },
          { t: 'c', q: 'Pro výškopis se zaměřují zejména…', a: 'terénní hrany, lomy spádu, vrcholy a údolnice', w: ['jen rohy budov', 'body v pravidelné síti 50 m', 'jen body v silnici'], e: 'Tvar terénu vystihnou charakteristické body a čáry; pravidelná síť je často zbytečně hustá.' },
          { t: 'tf', q: 'Oměrné míry pásmem slouží jako nezávislá kontrola podrobného měření.', a: true, e: 'Rozměry budov a vzdálenosti mezi body se porovnají se souřadnicemi.' },
          { t: 'c', q: 'Po postavení na nové stanovisko je vhodné nejprve…', a: 'zaměřit kontrolně známý bod', w: ['zaměřit nejbližší strom', 'vypnout kompenzátor', 'smazat předchozí data'], e: 'Kontrola orientace odhalí chybně zadané stanovisko nebo pohnutý stativ.' },
          { t: 'c', q: 'Při měření pro geometrický plán se vlastníci…', a: 'přizvou ke zjišťování průběhu hranic', w: ['nepřizývají nikdy', 'musí sami měřit', 'přizvou až k zápisu v katastru'], e: 'Průběh hranice se zjišťuje za účasti vlastníků a označí se v terénu.' },
          { t: 'c', q: 'Kódování bodů v totální stanici usnadňuje…', a: 'automatickou kresbu v programu', w: ['výpočet atmosférické korekce', 'centraci přístroje', 'výpočet úhlového uzávěru'], e: 'Kód určí typ objektu i spojování bodů do linií.' },
        ],
      },
      {
        id: 'vyukal5', title: 'Vytyčení stavby v terénu', icon: '🏗️', gens: ['stakeout', 'bubble'],
        items: [
          { t: 'o', q: 'Seřaďte práce při vytyčení budovy v terénu', s: ['Kontrola bodů vytyčovací sítě', 'Vytyčení hlavních bodů polární metodou', 'Kontrola oměrnými mírami a úhlopříčkami', 'Zajištění os na lavičkách', 'Vyhotovení protokolu o vytyčení'], e: 'Každý vytyčený prvek se kontroluje nezávisle a vše se dokumentuje v protokolu.' },
          { t: 'c', q: 'Po vytyčení čtyř rohů obdélníkové budovy se úhlopříčky liší o 4 cm. Co uděláš?', a: 'Najdeš chybu a body opravíš', w: ['Rozdíl zanedbáš', 'Posuneš jeden roh náhodně', 'Změníš projekt'], e: 'Obdélník má stejné úhlopříčky; rozdíl ukazuje chybu vytyčení nebo výpočtu.' },
          { t: 'c', q: 'Figurant hlásí, že kolík nejde zatlouct přesně na vytyčené místo kvůli kameni. Co uděláš?', a: 'Vytyčíš bod na ose excentricky a zapíšeš', w: ['Kolík zatlučeš vedle bez záznamu', 'Bod vynecháš', 'Změníš souřadnice bodu'], e: 'Dočasně posunutý bod musí být jednoznačně popsán (směr a vzdálenost), jinak dojde k chybě.' },
          { t: 'c', q: 'Výšku ±0,000 (podlaha přízemí) vytyčíš…', a: 'nivelací od výškového bodu', w: ['odhadem od terénu', 'z katastrální mapy', 'z výšky stativu'], e: 'Výška ±0,000 je vztažena k Bpv a projekt ji udává; převádí se z nejbližšího reperu.' },
          { t: 'tf', q: 'Vytyčený bod se kontroluje nezávislým měřením, ideálně z jiného stanoviska.', a: true, e: 'Kontrola ze stejného stanoviska neodhalí chybu v orientaci ani v souřadnicích stanoviska.' },
          { t: 'c', q: 'Figurant hlásí, že bagr stojí na bodě vytyčovací sítě. Co uděláš?', a: 'Ověříš stabilitu bodu z ostatních bodů', w: ['Bod dál bez kontroly používáš', 'Bod smažeš ze seznamu', 'Opravíš souřadnice odhadem'], e: 'Bod mohl být posunut – proto se body sítě během stavby pravidelně kontrolují.' },
          { t: 'c', q: 'Osa liniové stavby se v terénu vyznačuje body…', a: 'v pravidelném staničení a v hlavních bodech', w: ['jen na začátku a konci', 'náhodně podle terénu', 'jen v obloucích'], e: 'Hlavní body (ZO, KO, VB) i body po staničení jsou podkladem pro příčné profily a výškové vytyčení.' },
          { t: 'm', q: 'Spojte kontrolu s odhalenou chybou', p: [['Úhlopříčky obdélníka', 'Chyba pravého úhlu'], ['Kontrola orientace', 'Pootočená osnova'], ['Oměrná míra strany', 'Chyba délky'], ['Nivelace zpět na reper', 'Chyba výšky']], e: 'Úhlopříčky vytyčeného obdélníka musí být shodné, rozdíl prozradí nepravý úhel; obecně má kontrola ověřit výsledek nezávislou cestou, např. nivelací zpět na známý reper.' },
        ],
      },
    ],
  },
];
