// Kapitoly podle osnov VUT FAST – Ing.: Geomatika a aplikovaná geoinformatika (NEB039 + NEB048),
// Právo a oceňování nemovitostí (NZA018 + NEB050), Komplexní projekt a výuka v terénu 4 (NEA043 + NEA038).

export default [
  {
    id: 'neb039', title: 'Geomatika a aplikovaná geoinformatika', color: '#2563eb',
    level: 'Ing.', course: 'NEB039', sem: '1. ročník · LS',
    desc: 'Software a databáze GIS, formáty a standardy geodat, kvalita dat, interpolace, prostorové analýzy a publikování ve 3D a na webu.',
    lessons: [
      {
        id: 'neb039l1', title: 'Software a databáze GIS', icon: '💻',
        items: [
          { t: 'c', q: 'Který GIS software je open source a patří mezi projekty OSGeo?', a: 'QGIS', w: ['ArcGIS Pro', 'MicroStation', 'AutoCAD Map 3D'], e: 'QGIS je šířen pod licencí GNU GPL; ArcGIS Pro je komerční produkt firmy Esri.' },
          { t: 'c', q: 'GRASS GIS je tradičně nejsilnější v oblasti…', a: 'rastrových analýz a modelování', w: ['kreslení výkresů CAD', 'správy katastru', 'sazby atlasů'], e: 'GRASS vznikl v 80. letech jako analytický systém; dnes je dostupný i z QGIS přes Processing.' },
          { t: 'c', q: 'Která knihovna stojí v pozadí čtení a zápisu většiny formátů geodat v QGIS?', a: 'GDAL/OGR', w: ['OpenCV', 'NumPy', 'LAPACK'], e: 'GDAL (rastry) a OGR (vektory) jsou základní převodní vrstvou mnoha GIS programů.' },
          { t: 'c', q: 'Prostorové rozšíření databáze PostgreSQL se jmenuje…', a: 'PostGIS', w: ['SpatiaLite', 'GeoServer', 'MapInfo'], e: 'PostGIS přidává geometrické typy, prostorové indexy a funkce ST_*.' },
          { t: 'c', q: 'K čemu slouží prostorový index (např. R-strom, GiST)?', a: 'k rychlému výběru objektů podle polohy', w: ['ke zvýšení přesnosti souřadnic', 'k transformaci mezi systémy', 'ke kompresi rastrů'], e: 'Index porovná nejprve obalové obdélníky a přesnou geometrii testuje jen u kandidátů.' },
          { t: 'c', q: 'SQL funkce ST_Intersects(a, b) vrací…', a: 'pravdivostní hodnotu, zda se geometrie protínají', w: ['novou geometrii průniku', 'plochu průniku v m²', 'vzdálenost geometrií'], e: 'Predikát vrací true/false; geometrii průniku vrací ST_Intersection.' },
          { t: 'tf', q: 'Relační databáze umožňuje víceuživatelský přístup a řízení transakcí lépe než souborová úložiště typu shapefile.', a: true, e: 'Proto se víceuživatelská GIS data drží v SŘBD (PostgreSQL/PostGIS, Oracle, MS SQL).' },
          { t: 'm', q: 'Spojte nástroj s jeho rolí', p: [['PostGIS', 'Prostorová databáze'], ['PyQGIS', 'Skriptování v QGIS'], ['ArcPy', 'Skriptování v ArcGIS'], ['GeoServer', 'Publikace webových služeb']] },
        ],
      },
      {
        id: 'neb039l2', title: 'Sběr dat a formáty', icon: '📡',
        items: [
          { t: 'c', q: 'Který formát ukládá vektory i rastry do jediného souboru databáze SQLite?', a: 'GeoPackage', w: ['Shapefile', 'GeoTIFF', 'GeoJSON'], e: 'GeoPackage (.gpkg) je standard OGC postavený na SQLite.' },
          { t: 'c', q: 'GeoTIFF je…', a: 'rastr TIFF s georeferenčními značkami', w: ['textový vektorový formát', 'formát mračen bodů', 'webová mapová služba'], e: 'Značky nesou souřadnicový systém a vazbu pixelů na souřadnice; varianta COG je optimalizovaná pro cloud.' },
          { t: 'c', q: 'LAZ je…', a: 'bezeztrátově komprimovaný formát LAS', w: ['ztrátový rastrový formát', 'formát pro metadata', 'textová varianta GeoJSON'], e: 'LAS je standard ASPRS pro mračna bodů; LAZ zmenší soubory několikanásobně bez ztráty informace.' },
          { t: 'c', q: 'Podle RFC 7946 jsou souřadnice v GeoJSON v systému…', a: 'WGS 84 v pořadí délka, šířka', w: ['S-JTSK v pořadí Y, X', 'ETRS89-TM33 v metrech', 'libovolném dle hlavičky'], e: 'Aktuální specifikace GeoJSON nepodporuje deklaraci jiného CRS.' },
          { t: 'c', q: 'Která nevýhoda je typická pro shapefile?', a: 'více souborů a názvy atributů max. 10 znaků', w: ['nepodporuje body', 'neumí atributy', 'je jen pro rastry'], e: 'Shapefile tvoří .shp, .shx, .dbf (+ .prj) a má limit 2 GB na soubor.' },
          { t: 'c', q: 'Který moderní způsob sběru dat dává hustá mračna bodů z jedoucího vozidla?', a: 'mobilní mapovací systém (MMS)', w: ['statická nivelace', 'ortogonální metoda', 'digitalizace rastru'], e: 'MMS kombinuje laserové skenery, kamery, GNSS a inerciální jednotku.' },
          { t: 'tf', q: 'Mračno bodů má blíže k vektorové než k rastrové reprezentaci, protože každý bod nese vlastní souřadnice.', a: true, e: 'Body mají souřadnice X, Y, Z a atributy (intenzita, třída); do rastru se převádí např. při tvorbě DMR.' },
          { t: 'm', q: 'Spojte formát s typem dat', p: [['LAS', 'Mračno bodů'], ['GeoTIFF', 'Rastr'], ['GeoJSON', 'Vektor v textu'], ['CityGML', '3D model města']] },
        ],
      },
      {
        id: 'neb039l3', title: 'Standardy a kvalita dat', icon: '📏',
        items: [
          { t: 'c', q: 'Webová služba WMS vrací klientovi…', a: 'mapu jako obrázek', w: ['vektorové prvky s atributy', 'surová rastrová data', 'metadatové záznamy'], e: 'Vektorové prvky dává WFS, rastrová data (coverage) WCS.' },
          { t: 'c', q: 'Která organizace vydává standardy WMS, WFS a GeoPackage?', a: 'Open Geospatial Consortium (OGC)', w: ['Mezinárodní geodetická asociace', 'Evropská kosmická agentura', 'World Wide Web Consortium'], e: 'OGC spolupracuje s ISO/TC 211, které vydává řadu norem ISO 19100.' },
          { t: 'c', q: 'Norma ISO 19115 se týká…', a: 'metadat geografických informací', w: ['kvality mračen bodů', 'webových mapových služeb', 'kartografických značek'], e: 'Metadata popisují původ, rozsah, souřadnicový systém a kvalitu dat.' },
          { t: 'c', q: 'Směrnice INSPIRE (2007/2/ES) vytváří…', a: 'infrastrukturu prostorových informací v EU', w: ['jednotný evropský katastr', 'evropskou síť GNSS stanic', 'jednotné zobrazení map'], e: 'Požaduje harmonizovaná data, metadata a síťové služby pro vyhledávání, prohlížení a stahování.' },
          { t: 'c', q: 'Který prvek kvality podle ISO 19157 posuzuje, zda v datech nechybějí nebo nepřebývají objekty?', a: 'úplnost', w: ['polohová přesnost', 'časová kvalita', 'tematická přesnost'], e: 'Úplnost sleduje chybějící objekty (omise) a nadbytečné objekty (komise).' },
          { t: 'c', q: 'Překryvy sousedních parcel a „díry“ mezi polygony jsou chybou…', a: 'logické (topologické) konzistence', w: ['časové kvality', 'tematické přesnosti', 'použitelnosti'], e: 'Topologická pravidla odhalí překryvy, mezery a nenavazující linie.' },
          { t: 'tf', q: 'Vysoká přesnost souřadnic zaručuje, že data jsou úplná a aktuální.', a: false, e: 'Prvky kvality jsou nezávislé: přesná data mohou být neúplná nebo zastaralá.' },
          { t: 'm', q: 'Spojte službu OGC s obsahem', p: [['WMS', 'Obrázek mapy'], ['WMTS', 'Předgenerované dlaždice'], ['WFS', 'Vektorové prvky'], ['WCS', 'Rastrová data (coverage)'], ['CSW', 'Katalog metadat']] },
        ],
      },
      {
        id: 'neb039l4', title: 'Interpolace a DMT', icon: '🏔️', gens: ['slopeDeg'],
        items: [
          { t: 'c', q: 'Metoda IDW odhaduje hodnotu jako…', a: 'vážený průměr s vahami podle převrácené vzdálenosti', w: ['průměr všech bodů bez vah', 'hodnotu nejvyššího bodu', 'polynom 5. stupně z celé oblasti'], e: 'Inverse Distance Weighting: váha 1/dᵖ, parametr p řídí vliv blízkých bodů.' },
          { t: 'c', q: 'Kriging vychází z…', a: 'semivariogramu popisujícího prostorovou závislost', w: ['Voronoiových polygonů', 'histogramu výšek', 'pouze nejbližšího bodu'], e: 'Geostatistická metoda, která dává i odhad rozptylu interpolované hodnoty.' },
          { t: 'c', q: 'Parametr semivariogramu „range“ (dosah) udává…', a: 'vzdálenost, za níž body už nejsou korelované', w: ['největší výšku v oblasti', 'počet vstupních bodů', 'velikost výsledného pixelu'], e: 'Nugget popisuje nespojitost u nuly, sill ustálenou hodnotu semivariance.' },
          { t: 'c', q: 'Interpolace IDW nikdy nevytvoří hodnotu…', a: 'mimo rozsah minima a maxima vstupů', w: ['v místě vstupního bodu', 'na okraji oblasti', 'v celém čísle'], e: 'Vážený průměr s kladnými vahami nemůže vybočit z rozsahu vstupních hodnot – vrcholy a dna se „useknou“.' },
          { t: 'c', q: 'Nepravidelná trojúhelníková síť (TIN) se nejčastěji vytváří…', a: 'Delaunayho triangulací', w: ['Fourierovou transformací', 'metodou nejmenších čtverců', 'reklasifikací rastru'], e: 'Delaunayho triangulace maximalizuje nejmenší úhly trojúhelníků; lze ji doplnit o povinné hrany (lomové linie).' },
          { t: 'c', q: 'Rozdíl digitálního modelu povrchu a reliéfu (DMP − DMR) dává…', a: 'výšky objektů nad terénem', w: ['nadmořské výšky terénu', 'sklon svahu', 'převýšení geoidu'], e: 'Normalizovaný model povrchu (nDSM) se používá pro výšky budov a vegetace.' },
          { t: 'tf', q: 'Lomové linie (hrany teras, břehy) se mají do TIN zavádět jako povinné hrany.', a: true, e: 'Jinak triangulace „zaoblí“ ostré terénní tvary.' },
          { t: 'o', q: 'Seřaďte tvorbu DMR z leteckého laserového skenování', s: ['Georeferencování mračna bodů', 'Klasifikace bodů terénu', 'Doplnění lomových linií', 'Interpolace (TIN nebo grid)', 'Kontrola na nezávislých bodech'], e: 'Pro DMR se použijí jen body klasifikované jako terén; přesnost se ověří na kontrolních bodech.' },
        ],
      },
      {
        id: 'neb039l5', title: 'Analýzy, 3D a web', icon: '🧮',
        items: [
          { t: 'c', q: 'Obalová zóna (buffer) kolem vodního toku vymezí…', a: 'území do zadané vzdálenosti od toku', w: ['povodí toku', 'nejkratší cestu k toku', 'rastr sklonů u toku'], e: 'Typicky ochranná pásma, pásma podél toků nebo hlukové zóny.' },
          { t: 'c', q: 'Překryvná operace Intersect (průnik) vrátí…', a: 'jen části společné oběma vrstvám', w: ['sjednocení obou vrstev', 'první vrstvu bez druhé', 'jen hranice polygonů'], e: 'Atributy obou vrstev se v průniku spojí; Union vrací vše, Erase rozdíl.' },
          { t: 'c', q: 'Reklasifikace rastru znamená…', a: 'přiřazení nových hodnot podle intervalů', w: ['změnu velikosti pixelu', 'převod na vektor', 'transformaci souřadnic'], e: 'Např. sklony 0–5° → 1, 5–15° → 2, nad 15° → 3 pro vícekriteriální hodnocení.' },
          { t: 'c', q: 'Fokální operace mapové algebry počítá hodnotu buňky z…', a: 'jejího okolí (plovoucího okna)', w: ['jen téže buňky', 'celé zóny', 'celého rastru'], e: 'Tomlinovo dělení: lokální, fokální, zonální a globální operace.' },
          { t: 'c', q: 'Který standard popisuje 3D modely měst v úrovních detailu LOD?', a: 'CityGML', w: ['GeoTIFF', 'KML 1.0', 'DXF'], e: 'CityGML (OGC) má sémantický model budov, terénu, vegetace a dalších objektů.' },
          { t: 'c', q: '4D prezentace doplňuje prostorový model o…', a: 'časovou složku', w: ['čtvrtou souřadnici výšky', 'atributovou tabulku', 'měřítko mapy'], e: 'Např. vývoj stavby, deformace svahu nebo změny zástavby v čase.' },
          { t: 'tf', q: 'Knihovny Leaflet a OpenLayers slouží k zobrazení map ve webovém prohlížeči.', a: true, e: 'Načítají dlaždice, WMS/WMTS, GeoJSON či vektorové dlaždice.' },
          { t: 'm', q: 'Spojte analýzu s příkladem použití', p: [['Buffer', 'Ochranné pásmo vedení'], ['Intersect', 'Parcely v záplavovém území'], ['Reklasifikace', 'Třídy sklonu svahu'], ['Thiessenovy polygony', 'Oblasti vlivu srážkoměrů']] },
        ],
      },
    ],
  },
  {
    id: 'nza018', title: 'Právo a oceňování nemovitostí', color: '#9a3412',
    level: 'Ing.', course: 'NZA018', sem: '2. ročník · LS',
    desc: 'Nemovité věci a věcná práva podle občanského zákoníku, stavební a správní řízení, vklad do katastru a metody oceňování nemovitostí.',
    lessons: [
      {
        id: 'nza018l1', title: 'Nemovitá věc', icon: '🏠',
        items: [
          { t: 'c', q: 'Který předpis je platným občanským zákoníkem v ČR?', a: 'zákon č. 89/2012 Sb.', w: ['zákon č. 40/1964 Sb.', 'zákon č. 256/2013 Sb.', 'zákon č. 500/2004 Sb.'], e: 'Nový občanský zákoník je účinný od 1. 1. 2014 a nahradil zákon č. 40/1964 Sb.' },
          { t: 'c', q: 'Zásada „superficies solo cedit“ znamená…', a: 'povrch ustupuje půdě', w: ['stavba je vždy samostatná věc', 'kdo staví, ten vlastní', 'pozemek následuje stavbu'], e: 'Stavba je zpravidla součástí pozemku; tuto zásadu obnovil zákon č. 89/2012 Sb.' },
          { t: 'c', q: 'Která stavba NENÍ součástí pozemku?', a: 'stavba dočasná', w: ['rodinný dům na pozemku', 'oplocení zapuštěné v zemi', 'garáž spojená se zemí'], e: 'Podle § 506 obč. zák. jsou součástí pozemku stavby na něm zřízené s výjimkou staveb dočasných.' },
          { t: 'c', q: 'Pozemek a stavba měly k 1. 1. 2014 různé vlastníky. Jaký je dnes vztah stavby k pozemku?', a: 'stavba je samostatnou nemovitou věcí', w: ['stavba se stala součástí pozemku', 'stavba se stala movitou věcí', 'stavba připadla státu'], e: 'Přechodná ustanovení: stavba zůstává samostatnou věcí a vlastníci mají vzájemné předkupní právo.' },
          { t: 'c', q: 'Součástí pozemku je podle obč. zák. také…', a: 'prostor nad povrchem i pod povrchem', w: ['movité věci na pozemku', 'sousední cesta', 'nerosty vyhrazené zákonem'], e: 'Pozemek zahrnuje i prostor nad a pod povrchem; vyhrazené nerosty jsou ve vlastnictví státu podle horního zákona.' },
          { t: 'tf', q: 'Nemovitou věcí může být i podzemní stavba se samostatným účelovým určením.', a: true, e: '§ 498 obč. zák.: nemovitými věcmi jsou pozemky a podzemní stavby se samostatným účelovým určením, práva k nim a práva, která za nemovité věci prohlásí zákon.' },
          { t: 'c', q: 'Vlastnické právo k nemovitosti evidované v katastru se nabývá smlouvou…', a: 'až vkladem do katastru nemovitostí', w: ['již podpisem smlouvy', 'zaplacením kupní ceny', 'předáním klíčů'], e: 'U zapisovaných práv je vklad konstitutivní; právní účinky nastávají k okamžiku podání návrhu na vklad.' },
          { t: 'm', q: 'Spojte předpis s jeho obsahem', p: [['89/2012 Sb.', 'Občanský zákoník'], ['256/2013 Sb.', 'Katastrální zákon'], ['500/2004 Sb.', 'Správní řád'], ['151/1997 Sb.', 'Oceňování majetku']] },
        ],
      },
      {
        id: 'nza018l2', title: 'Práva k cizí věci', icon: '⚖️',
        items: [
          { t: 'c', q: 'Věcná břemena se podle obč. zák. dělí na…', a: 'služebnosti a reálná břemena', w: ['zástavy a nájmy', 'pachty a výpůjčky', 'spoluvlastnictví a SJM'], e: 'Služebnost: vlastník něco trpí nebo se zdrží; reálné břemeno: vlastník něco dává nebo koná.' },
          { t: 'c', q: 'Právo chůze a jízdy přes sousední pozemek ve prospěch každého vlastníka panujícího pozemku je…', a: 'pozemková služebnost', w: ['osobní služebnost', 'reálné břemeno', 'nájemní právo'], e: 'Pozemková služebnost je spojena s panujícím pozemkem a přechází s jeho vlastnictvím.' },
          { t: 'c', q: 'Služebnost bytu či požívací právo zřízené pro konkrétního člověka je služebnost…', a: 'osobní', w: ['pozemková', 'inženýrská', 'nezbytná'], e: 'Osobní služebnost zaniká nejpozději smrtí oprávněné osoby.' },
          { t: 'c', q: 'Právo stavby lze zřídit nejdéle na…', a: '99 let', w: ['30 let', '50 let', 'dobu neurčitou'], e: 'Právo stavby je věcné právo mít stavbu na cizím pozemku; je nemovitou věcí a stavba je jeho součástí.' },
          { t: 'c', q: 'Předkupní právo sjednané jako věcné právo a zapsané do KN…', a: 'působí i vůči dalším nabyvatelům', w: ['platí jen mezi smluvními stranami', 'zaniká prvním převodem', 'nelze zapsat do katastru'], e: 'Věcné předkupní právo zavazuje i právní nástupce povinného.' },
          { t: 'c', q: 'Vydržení vlastnického práva k nemovité věci při řádné držbě trvá…', a: '10 let', w: ['3 roky', '5 let', '30 let'], e: 'Řádné vydržení nemovitosti trvá 10 let, mimořádné vydržení 20 let.' },
          { t: 'tf', q: 'Nemá-li pozemek dostatečné spojení s veřejnou cestou, může soud povolit nezbytnou cestu přes sousední pozemek.', a: true, e: 'Nezbytná cesta se povoluje za úplatu a jen v nezbytném rozsahu.' },
          { t: 'm', q: 'Spojte právo s jeho podstatou', p: [['Služebnost', 'Vlastník musí něco trpět'], ['Reálné břemeno', 'Vlastník musí něco konat'], ['Zástavní právo', 'Zajištění dluhu'], ['Předkupní právo', 'Přednost při koupi']] },
        ],
      },
      {
        id: 'nza018l3', title: 'Spoluvlastnictví a vklad', icon: '📜',
        items: [
          { t: 'c', q: 'O běžné správě společné věci rozhodují spoluvlastníci…', a: 'většinou počítanou podle velikosti podílů', w: ['vždy jednomyslně', 'podle počtu osob', 'losem'], e: 'Podíl určuje míru práv a povinností spoluvlastníka k věci.' },
          { t: 'c', q: 'Nemovitost koupená jedním z manželů za trvání manželství (bez zúžení) spadá zpravidla do…', a: 'společného jmění manželů', w: ['výlučného vlastnictví kupujícího', 'podílového spoluvlastnictví 1/2', 'vlastnictví obce'], e: 'SJM je bezpodílové; v katastru se zapisuje „SJM“ u obou manželů.' },
          { t: 'c', q: 'Které tři způsoby zápisu práv zná katastrální zákon?', a: 'vklad, záznam a poznámka', w: ['vklad, výmaz a oprava', 'návrh, rozhodnutí a odvolání', 'zápis, výpis a snímek'], e: 'Vklad – na základě listin ze soukromoprávních jednání; záznam – z rozhodnutí úřadů apod.; poznámka – informativní údaj.' },
          { t: 'c', q: 'Kdy nejdříve může katastrální úřad provést vklad?', a: 'po 20 dnech od odeslání vyrozumění', w: ['ihned po podání návrhu', 'po 5 dnech od podání', 'po 60 dnech od podání'], e: 'Ochranná lhůta dává dotčeným vlastníkům čas reagovat na podezřelý návrh.' },
          { t: 'c', q: 'Právo zapsané vkladem vzniká s účinky ke dni…', a: 'podání návrhu na vklad', w: ['podpisu smlouvy', 'provedení zápisu', 'vyrozumění účastníků'], e: 'Proto na pořadí podání návrhů záleží.' },
          { t: 'tf', q: 'Kdo za úplatu nabude věcné právo v dobré víře v zápis v katastru, je chráněn, i když zápis neodpovídá skutečnému právnímu stavu.', a: true, e: 'Princip materiální publicity (§ 984 obč. zák.) chrání úplatného nabyvatele v dobré víře.' },
          { t: 'c', q: 'Geometrický plán pro rozdělení pozemku je přílohou listiny, protože…', a: 'vymezuje nově vzniklé pozemky', w: ['nahrazuje kupní smlouvu', 'určuje cenu pozemku', 'je rozhodnutím úřadu'], e: 'GP ověřený ÚOZI a potvrzený KÚ je podkladem pro zápis změny do KN.' },
          { t: 'o', q: 'Seřaďte převod části pozemku', s: ['Zaměření a vyhotovení geometrického plánu', 'Potvrzení GP katastrálním úřadem', 'Uzavření kupní smlouvy s odkazem na GP', 'Podání návrhu na vklad', 'Provedení vkladu po ochranné lhůtě'], e: 'Smlouva musí na potvrzený GP odkazovat, jinak nelze nové pozemky jednoznačně určit.' },
        ],
      },
      {
        id: 'nza018l4', title: 'Stavební a správní řízení', icon: '🏛️',
        items: [
          { t: 'c', q: 'Správní řízení upravuje obecně…', a: 'správní řád – zákon č. 500/2004 Sb.', w: ['občanský soudní řád', 'katastrální vyhláška', 'zákon o obcích'], e: 'Správní řád se použije, nestanoví-li zvláštní zákon (např. stavební) jinak.' },
          { t: 'c', q: 'Obecná lhůta pro odvolání proti rozhodnutí podle správního řádu je…', a: '15 dnů od oznámení', w: ['8 dnů od oznámení', '30 dnů od vydání', '60 dnů od právní moci'], e: 'Odvolání se podává u správního orgánu, který rozhodnutí vydal.' },
          { t: 'c', q: 'Správní orgán má rozhodnout v jednoduchých věcech bez zbytečného odkladu, jinak nejpozději do…', a: '30 dnů', w: ['7 dnů', '90 dnů', '6 měsíců'], e: 'Lhůtu lze u zvlášť složitých případů prodloužit o dalších 30 dnů.' },
          { t: 'c', q: 'Rozhodnutí je v právní moci, když…', a: 'bylo oznámeno a nelze se již odvolat', w: ['bylo podepsáno úředníkem', 'bylo vyvěšeno na webu', 'bylo doručeno jen žadateli'], e: 'Právní moc nastává marným uplynutím odvolací lhůty nebo vzdáním se odvolání.' },
          { t: 'c', q: 'Nový stavební zákon č. 283/2021 Sb. nahradil dřívější územní a stavební řízení…', a: 'jedním řízením o povolení záměru', w: ['ohlášením na obecním úřadě', 'vkladem do katastru', 'znaleckým posudkem'], e: 'Povolení záměru spojuje posouzení umístění i provedení stavby.' },
          { t: 'c', q: 'Proč se vytyčení prostorové polohy stavby svěřuje odborně způsobilému zeměměřiči?', a: 'poloha stavby musí odpovídat povolení', w: ['nahrazuje kolaudaci', 'určuje výši daně', 'nahrazuje projekt'], e: 'Chybně umístěná stavba může zasáhnout cizí pozemek nebo porušit odstupy.' },
          { t: 'tf', q: 'Účastníkem řízení o povolení stavby mohou být i vlastníci sousedních pozemků, jejichž práva mohou být dotčena.', a: true, e: 'Sousedé mohou uplatnit námitky, např. proti odstupu či zastínění.' },
          { t: 'm', q: 'Spojte pojem s předpisem, který ho upravuje', p: [['Superficies solo cedit', 'Občanský zákoník'], ['Povolení záměru', 'Stavební zákon'], ['Odvolání', 'Správní řád'], ['Vklad práva', 'Katastrální zákon']] },
        ],
      },
      {
        id: 'nza018l5', title: 'Oceňování nemovitostí', icon: '💰',
        items: [
          { t: 'c', q: 'Cena obvyklá je cena…', a: 'dosažitelná při prodeji v obvyklém obchodním styku', w: ['vypočtená podle oceňovací vyhlášky', 'zaplacená při dražbě', 'uvedená v daňovém přiznání'], e: 'Nezohledňují se mimořádné okolnosti trhu, osobní poměry stran ani zvláštní obliba.' },
          { t: 'c', q: 'Cena zjištěná je cena…', a: 'určená postupy zákona a oceňovací vyhlášky', w: ['sjednaná mezi stranami', 'odhadnutá realitní kanceláří', 'převzatá z inzerce'], e: 'Administrativní cena podle zákona č. 151/1997 Sb. a vyhlášky č. 441/2013 Sb.' },
          { t: 'c', q: 'Nákladová metoda vychází z…', a: 'reprodukční ceny snížené o opotřebení', w: ['kapitalizace čistého nájmu', 'cen srovnatelných prodejů', 'ceny z pojistné smlouvy'], e: 'Kolik by stálo pořídit stavbu znovu, snížené o fyzické, funkční a ekonomické opotřebení.' },
          { t: 'c', q: 'Výnosová metoda je nejvhodnější pro…', a: 'nájemní dům nebo komerční objekt', w: ['nově postavený rodinný dům', 'lesní cestu', 'kapličku'], e: 'Hodnota plyne z budoucích čistých výnosů, které objekt přináší.' },
          { t: 'n', q: 'Čistý roční výnos z nájmu je 240 000 Kč, míra kapitalizace 6 %. Jaká je výnosová hodnota (věčná renta)?', a: 4000000, tol: 1, dec: 0, unit: 'Kč', e: 'C = V / i = 240 000 / 0,06 = 4 000 000 Kč.' },
          { t: 'n', q: 'Reprodukční cena stavby je 5 000 000 Kč, opotřebení 30 %. Jaká je věcná (nákladová) hodnota?', a: 3500000, tol: 1, dec: 0, unit: 'Kč', e: '5 000 000 · (1 − 0,30) = 3 500 000 Kč.' },
          { t: 'tf', q: 'Seznam znalců vede a o zápisu do něj rozhoduje Ministerstvo spravedlnosti.', a: true, e: 'Podle zákona č. 254/2019 Sb. o znalcích, znaleckých kancelářích a znaleckých ústavech; posudek musí obsahovat znaleckou doložku.' },
          { t: 'm', q: 'Spojte metodu oceňování s jejím základem', p: [['Nákladová', 'Reprodukční cena − opotřebení'], ['Výnosová', 'Kapitalizace výnosů'], ['Porovnávací', 'Srovnatelné prodeje']] },
        ],
      },
    ],
  },
  {
    id: 'nea043', title: 'Komplexní projekt a výuka v terénu 4', color: '#65a30d',
    level: 'Ing.', course: 'NEA043', sem: '2. ročník · ZS',
    desc: 'Geodetický projekt od zadání a rekognoskace přes síť, měření a zpracování po zprávu, spolu s vytyčováním staveb a GNSS v terénu.',
    lessons: [
      {
        id: 'nea043l1', title: 'Zadání a rekognoskace', icon: '📋',
        items: [
          { t: 'c', q: 'Co musí být v projektu jasné ještě před výběrem metod měření?', a: 'požadovaná přesnost a forma výstupu', w: ['barva měřických terčů', 'počet členů týmu na obědě', 'značka kontroléru'], e: 'Z přesnosti a výstupu (výkres, model, mračno) se odvozují metody, přístroje i počet kontrol.' },
          { t: 'c', q: 'Kde získáte souřadnice a stav bodů PBPP před rekognoskací?', a: 'v databázi bodových polí ČÚZK', w: ['v územním plánu obce', 'v katastrální mapě', 'v projektové dokumentaci stavby'], e: 'Geodetické údaje obsahují souřadnice, výšky, místopis a fotografie bodů.' },
          { t: 'c', q: 'Hlavním cílem rekognoskace je…', a: 'ověřit podklady a podmínky přímo v terénu', w: ['vypočítat vyrovnání sítě', 'vyhotovit technickou zprávu', 'vyfakturovat zakázku'], e: 'Ověřuje se existence bodů, přístupnost, viditelnost, zákryty oblohy i bezpečnost.' },
          { t: 'c', q: 'Při rekognoskaci zjistíte, že trigonometrický bod je zničen. Jak postupujete?', a: 'použijete jiné body a zničení ohlásíte', w: ['souřadnice odhadnete z mapy', 'bod ignorujete bez hlášení', 'zastavíte celý projekt'], e: 'Poškození či zničení bodu se ohlásí správci bodového pole (katastrální nebo Zeměměřický úřad); síť se připojí na jiné body.' },
          { t: 'c', q: 'Pro plánování GNSS měření na lokalitě při rekognoskaci sledujete zejména…', a: 'zákryty obzoru a zdroje odrazů', w: ['sklon terénu v procentech', 'druh půdy', 'počet parkovacích míst'], e: 'Stromy, budovy a kovové plochy zhoršují příjem a způsobují multipath.' },
          { t: 'tf', q: 'Rozdělení rolí v týmu (vedoucí, měřiči, zpracovatel, kontrola) patří do projektu před zahájením prací.', a: true, e: 'Jasné role předcházejí dvojí práci i mezerám v kontrole.' },
          { t: 'c', q: 'Co před vstupem na cizí pozemky vyžaduje zákon o zeměměřictví?', a: 'vhodné předchozí oznámení vlastníkovi', w: ['souhlas stavebního úřadu', 'notářsky ověřenou smlouvu', 'nic, vstup je volný bez oznámení'], e: 'Zeměměřič smí vstupovat na nemovitosti v nezbytném rozsahu, musí to však vlastníkovi vhodně oznámit.' },
          { t: 'o', q: 'Seřaďte úvodní fázi komplexního projektu', s: ['Převzetí zadání a sestavení týmu', 'Analýza podkladů a dat', 'Rekognoskace lokality', 'Podrobný projekt měření', 'Stabilizace bodů sítě'], e: 'Projekt měření navazuje na poznatky z rekognoskace; teprve pak se body stabilizují.' },
        ],
      },
      {
        id: 'nea043l2', title: 'Měřická síť a vlícovací body', icon: '📍', gens: ['station'],
        items: [
          { t: 'c', q: 'Pro opakovaná přesná měření posunů je nejvhodnější stabilizace…', a: 'pilíř s nucenou centrací', w: ['dřevěný kolík', 'křída na asfaltu', 'plastová značka'], e: 'Nucená centrace odstraní chybu centrace na úroveň desetin milimetru.' },
          { t: 'c', q: 'Body sítě v zastavěném území se na zpevněných plochách nejčastěji stabilizují…', a: 'měřickými hřeby nebo nastřelovacími značkami', w: ['dřevěnými kolíky', 'betonovými kvádry s trnem', 'litinovými poklopy'], e: 'Hřeby jsou levné, trvanlivé a nepřekážejí provozu.' },
          { t: 'c', q: 'Jak rozmístit body polygonového pořadu nebo sítě?', a: 's dobrou viditelností a pravidelnými délkami stran', w: ['co nejblíže k sobě v řadě', 'jen do rohů zájmového území', 'kamkoli bez ohledu na viditelnost'], e: 'Nevhodná geometrie (krátké strany vedle dlouhých) zhoršuje přesnost.' },
          { t: 'c', q: 'Vlícovací body (GCP) v projektu UAV slouží k…', a: 'georeferencování bloku snímků', w: ['vypočtení doby letu', 'kalibraci baterie dronu', 'určení barvy terénu'], e: 'Určují polohu a měřítko modelu; kontrolní body se do výpočtu nezavádějí.' },
          { t: 'c', q: 'Kontrolní body (check points) se při zpracování fotogrammetrie…', a: 'nepoužijí k výpočtu, jen k ověření přesnosti', w: ['použijí stejně jako vlícovací body', 'smažou před výpočtem', 'měří jen ručním GNSS'], e: 'Nezávislé body dávají poctivý odhad přesnosti výsledného modelu.' },
          { t: 'c', q: 'Jak rozmístit vlícovací body v bloku snímků z dronu?', a: 'po obvodu i uvnitř bloku, rovnoměrně', w: ['všechny do jednoho rohu', 'jen do středu bloku', 'na jednu přímku'], e: 'Rovnoměrné rozložení (i výškové) brání deformaci bloku, zejména jeho „prohnutí“.' },
          { t: 'tf', q: 'Kulové terče jsou vhodné pro spojování mračen z laserového skenování, protože vypadají stejně ze všech směrů.', a: true, e: 'Střed koule se spolehlivě určí fitováním z libovolného stanoviska.' },
          { t: 'm', q: 'Spojte značku s použitím', p: [['Pilíř s nucenou centrací', 'Monitoring posunů'], ['Měřický hřeb', 'Polygon ve městě'], ['Šachovnicový terč', 'Vlícovací bod UAV'], ['Kulový terč', 'Registrace skenů']] },
        ],
      },
      {
        id: 'nea043l3', title: 'Sběr dat v praxi', icon: '🛰️', gens: ['baseline3d'],
        items: [
          { t: 'c', q: 'Pro určení bodů sítě s přesností na milimetry zvolíte GNSS metodu…', a: 'statickou s dlouhou observací', w: ['RTK s 5s observací', 'navigační kódové měření', 'měření telefonem'], e: 'Statická metoda s následným zpracováním vektorů je nejpřesnější.' },
          { t: 'c', q: 'Výšku antény GNSS je nutné měřit k…', a: 'referenčnímu bodu antény (ARP)', w: ['horní hraně krytu antény', 'displeji přijímače', 'hlavě stativu bez podložky'], e: 'Od ARP se uplatní kalibrace fázového centra (PCO/PCV) dané antény.' },
          { t: 'c', q: 'Data z více typů přijímačů převedete pro společné zpracování do formátu…', a: 'RINEX', w: ['LAS', 'DXF', 'GeoTIFF'], e: 'RINEX je výměnný formát GNSS observací nezávislý na výrobci.' },
          { t: 'c', q: 'Síť permanentních stanic GNSS provozovaná ČÚZK se jmenuje…', a: 'CZEPOS', w: ['ZABAGED', 'RÚIAN', 'INSPIRE'], e: 'Poskytuje korekce pro RTK i data pro postprocessing.' },
          { t: 'c', q: 'Proč se při TLS skenuje z více stanovisek s překryvem?', a: 'kvůli zákrytům a spojení mračen', w: ['aby byl sken barevnější', 'aby se šetřila baterie', 'kvůli ochraně osobních údajů'], e: 'Jedno stanovisko nevidí za objekty; překryv nebo terče umožní registraci.' },
          { t: 'c', q: 'Při náletu UAV pro fotogrammetrii se obvykle volí podélný a příčný překryt snímků…', a: 'kolem 80 % a 60–70 %', w: ['kolem 10 % a 5 %', 'přesně 50 % a 50 %', 'žádný, snímky se nepřekrývají'], e: 'Velký překryt zajistí dostatek spojovacích bodů pro výpočet SfM.' },
          { t: 'tf', q: 'Kontrolní měření na známý bod na začátku a na konci měření RTK odhalí chybné nastavení souřadnicového systému.', a: true, e: 'Kontrola na známém bodě je základní ověření správnosti korekcí i transformace.' },
          { t: 'm', q: 'Spojte úlohu s vhodnou technologií', p: [['Síť bodů s mm přesností', 'Statická GNSS'], ['Podrobné body na volném terénu', 'RTK GNSS'], ['Fasáda historické budovy', 'Laserové skenování'], ['Ortofoto staveniště', 'UAV fotogrammetrie']] },
        ],
      },
      {
        id: 'nea043l4', title: 'Stavební systémy a vytyčení', icon: '🏗️', gens: ['stakeout', 'stakeoutAccuracy'],
        items: [
          { t: 'c', q: 'Primární vytyčovací systém stavby tvoří…', a: 'body vytyčovací sítě navázané na S-JTSK a Bpv', w: ['podrobné body bednění', 'kóty v projektu interiéru', 'body katastrální mapy'], e: 'Z primárního systému se odvozuje sekundární – hlavní a podrobné osy objektu.' },
          { t: 'c', q: 'Sekundární systém stavby tvoří především…', a: 'hlavní a podrobné osy objektu', w: ['body PBPP v okolí', 'permanentní stanice GNSS', 'body sítě vyšší geodézie'], e: 'Osy stavby (osnova) vytyčené z primárního systému slouží pro podrobné vytyčení.' },
          { t: 'c', q: 'Jak se běžně kontroluje vytyčený bod?', a: 'nezávislým měřením z jiného stanoviska', w: ['opakovaným čtením stejné hodnoty', 'odhadem od oka', 'kontrolou podpisu na výkrese'], e: 'Kontrola musí být nezávislá – např. oměrné míry mezi body nebo jiná metoda.' },
          { t: 'c', q: 'U objektu s prostorovou skladbou (např. skelet) se výšky podlaží přenášejí…', a: 'svislým měřením od výškového bodu', w: ['odhadem z projektu', 'jen pomocí GNSS', 'z katastrální mapy'], e: 'Používá se ocelové pásmo, přesná nivelace nebo trigonometrie od výškového bodu u stavby.' },
          { t: 'c', q: 'Svislost osy vysoké budovy se přenáší do vyšších podlaží nejčastěji…', a: 'optickým nebo laserovým provažovačem', w: ['měřickým pásmem po fasádě', 'buzolou', 'ruční libelou'], e: 'Provažovač promítne bod ze základní úrovně přes prostupy ve stropech.' },
          { t: 'c', q: 'Zajištění vytyčených os mimo stavební jámu slouží k…', a: 'jejich obnově po zničení při výkopu', w: ['označení hranice pozemku', 'zlepšení signálu GNSS', 'měření hluku'], e: 'Zajišťovací body (lavičky, značky na okolních objektech) umožní osy rychle obnovit.' },
          { t: 'tf', q: 'Chyba vytyčení polární metodou roste s délkou vytyčovací vzdálenosti i při stejné přesnosti úhlu.', a: true, e: 'Příčná chyba = d · m_ω (v radiánech), proto se dlouhé záměry omezují.' },
          { t: 'o', q: 'Seřaďte vytyčení stavby', s: ['Kontrola a doplnění vytyčovací sítě', 'Vytyčení prostorové polohy stavby', 'Zajištění hlavních os', 'Podrobné vytyčení prvků', 'Kontrolní měření a protokol'], e: 'Postupuje se od celku k detailu, každá etapa se kontroluje.' },
        ],
      },
      {
        id: 'nea043l5', title: 'Zpracování, přesnost a zpráva', icon: '📑', gens: ['levelSetup'],
        items: [
          { t: 'c', q: 'Vyrovnání sítě metodou nejmenších čtverců dává kromě souřadnic také…', a: 'odhad jejich přesnosti a oprav měření', w: ['cenu zakázky', 'fotografie bodů', 'počet měřičů v terénu'], e: 'Opravy a střední chyby umožní odhalit hrubé chyby a posoudit splnění kritérií.' },
          { t: 'c', q: 'Jak nejspolehlivěji ověříte přesnost výsledného modelu?', a: 'porovnáním s nezávisle určenými body', w: ['podle hlášení softwaru', 'odhadem zkušeného kolegy', 'podle počtu snímků'], e: 'Rozdíly na kontrolních bodech dávají empirickou střední chybu (RMSE).' },
          { t: 'c', q: 'Ve vyrovnání sítě vyjde jedna oprava zřetelně větší než ostatní. Co uděláte?', a: 'prověříte měření a hledáte hrubou chybu', w: ['výsledek odevzdáte bez změn', 'všechna měření smažete', 'ručně upravíte souřadnice'], e: 'Testy odlehlých měření a kontrola zápisníku odhalí např. chybnou výšku cíle.' },
          { t: 'c', q: 'Co patří do technické zprávy projektu?', a: 'použité metody, přístroje a dosaženou přesnost', w: ['osobní hodnocení členů týmu', 'soukromá data vlastníků', 'surová hesla k serverům'], e: 'Zpráva popisuje podklady, souřadnicový a výškový systém, postup, kontroly a výsledky.' },
          { t: 'c', q: 'Při uzávěru nivelačního pořadu překročí odchylka mezní hodnotu. Správný postup je…', a: 'pořad nebo jeho část přeměřit', w: ['odchylku rozdělit rovnoměrně', 'zmenšit mezní hodnotu', 'vynechat nejhorší sestavu'], e: 'Opravy se rozdělují jen při odchylce v mezích; jinak jde o chybu měření.' },
          { t: 'tf', q: 'Prezentace projektu má vést posluchače od zadání přes postup k výsledkům a jejich přesnosti.', a: true, e: 'Zadavatele zajímá hlavně, zda výsledek splnil požadavky.' },
          { t: 'c', q: 'Proč se odevzdávají i protokoly z měření a výpočtů?', a: 'aby byl výsledek přezkoumatelný', w: ['aby byl soubor větší', 'protože je vyžaduje GDPR', 'aby se nemusela psát zpráva'], e: 'Zadavatel či kontrola musí dohledat vznik každé souřadnice.' },
          { t: 'o', q: 'Seřaďte závěrečnou fázi projektu', s: ['Kontrola a čištění měřených dat', 'Vyrovnání a výpočet souřadnic', 'Posouzení přesnosti na kontrolních bodech', 'Tvorba výstupů', 'Technická zpráva a prezentace'], e: 'Nejprve kvalitní data, pak výpočet, ověření a nakonec dokumentace výsledků.' },
        ],
      },
    ],
  },
];
