// Kapitoly podle osnov VUT FAST – navazující magisterské studium (Ing.), 1. ročník.
// NEA030 Inženýrská geodézie 2, NEA033 Geodézie v podzemních prostorách, NEA034 Katastr nemovitostí 3,
// NEA031 Kartografie 2 – tematická, NEA035 Kosmická geodézie 2. Formát otázek viz u01-03.js.

export default [
  {
    id: 'nea030', title: 'Inženýrská geodézie 2', color: '#b45309', level: 'Ing.', course: 'NEA030', sem: '1. ročník · ZS',
    desc: 'Rozbory přesnosti, vytyčovací sítě a výkresy, dopravní stavby, mosty, památky, průmysl a normy.',
    lessons: [
      {
        id: 'nea030l1', title: 'Rozbory přesnosti', icon: '🎯', gens: ['stakeoutAccuracy', 'errorPropagation'],
        items: [
          { t: 'c', q: 'Rozbor přesnosti před měřením (apriorní) slouží hlavně k…', a: 'návrhu metody a přístrojů', w: ['ověření výsledků po měření', 'výpočtu ceny zakázky', 'vyrovnání naměřených hodnot'], e: 'Z požadované přesnosti (tolerance) se odvodí dovolené chyby jednotlivých měřených veličin.' },
          { t: 'c', q: 'Relativní přesnost vytyčení se týká…', a: 'vzájemné polohy vytyčených bodů', w: ['polohy bodu vůči státní síti', 'přesnosti přístroje z kalibrace', 'výšky bodu v systému Bpv'], e: 'Např. délka mezi dvěma osami nebo rozteč kotevních šroubů – chyba sítě se v ní téměř neuplatní.' },
          { t: 'c', q: 'Celková (absolutní) přesnost vytyčení zahrnuje…', a: 'chybu podkladu i chybu vytyčení', w: ['jen chybu měření délky', 'jen chybu centrace přístroje', 'jen nepřesnost projektu'], e: 'm_celk = √(m_podkladu² + m_vytyčení²) – podkladem je vytyčovací síť.' },
          { t: 'c', q: 'Střední polohová chyba bodu ze středních chyb souřadnic je…', a: 'm_p = √(m_x² + m_y²)', w: ['m_p = m_x + m_y', 'm_p = (m_x + m_y) / 2', 'm_p = m_x · m_y'], e: 'Souřadnicová střední chyba je m_xy = m_p / √2.' },
          { t: 'c', q: 'Mezní odchylka se ze směrodatné odchylky obvykle získá násobením koeficientem…', a: '2', w: ['0,5', '1', '10'], e: 'Interval ±2σ pokrývá při normálním rozdělení asi 95 % případů; pro vyšší spolehlivost se volí 2,5 nebo 3.' },
          { t: 'n', q: 'Polární vytyčení na vzdálenost 100 m, střední chyba úhlu 10 cc. Jaká je příčná chyba vytyčeného bodu?', a: 1.57, tol: 0.01, dec: 2, unit: 'mm', e: 'q = d · m_ω(rad) = 100 000 mm · 10 · π / 2 000 000 ≈ 1,57 mm.' },
          { t: 'tf', q: 'Příčná chyba polárně vytyčeného bodu roste lineárně s délkou záměry.', a: true, e: 'q = d · m_ω – proto se dlouhé záměry při přesném vytyčení omezují.' },
          { t: 'm', q: 'Spojte pojem s významem', p: [['Apriorní rozbor', 'Před měřením – návrh'], ['Aposteriorní rozbor', 'Po měření – z výsledků'], ['Relativní přesnost', 'Vzájemná poloha bodů'], ['Celková přesnost', 'Poloha vůči síti']] },
        ],
      },
      {
        id: 'nea030l2', title: 'Příprava staveb a výkresy', icon: '📐', gens: ['stakeout'],
        items: [
          { t: 'c', q: 'Pro projektování stavby dodává geodet jako podklad hlavně…', a: 'účelovou mapu (polohopis a výškopis)', w: ['výpis z listu vlastnictví', 'geologický průzkum', 'statický výpočet'], e: 'Účelová mapa v potřebné přesnosti je základem pro umístění stavby i výpočet vytyčovacích prvků.' },
          { t: 'c', q: 'Prostorová poloha stavby se vytyčuje od…', a: 'bodů vytyčovací sítě', w: ['odhadem od plotu souseda', 'rohu nejbližší budovy', 'libovolného stromu'], e: 'Vytyčovací síť (primární systém) je stabilizovaná mimo dosah stavebních prací.' },
          { t: 'c', q: 'Podrobné body stavby se vytyčují zpravidla od…', a: 'hlavních bodů a os stavby', w: ['bodů státní nivelace', 'hranic katastrálních území', 'bodů CZEPOS'], e: 'Sekundární (osový) systém na objektu zajišťuje vysokou relativní přesnost podrobného vytyčení.' },
          { t: 'c', q: 'Úroveň ±0,000 na stavebních výkresech obvykle označuje…', a: 'podlahu 1. NP s výškou v Bpv', w: ['nulovou nadmořskou výšku', 'úroveň spodní vody', 'nejnižší bod pozemku'], e: 'Výkres uvádí, jaké nadmořské výšce v Bpv úroveň ±0,000 odpovídá.' },
          { t: 'c', q: 'Vytyčovací výkres je vhodné doplnit hlavně o…', a: 'souřadnice bodů a kontrolní míry', w: ['vizualizaci fasády', 'rozpočet stavby', 'harmonogram dodávek'], e: 'Kontrolní míry (např. oměrné a diagonály) umožňují nezávislou kontrolu vytyčení.' },
          { t: 'tf', q: 'Geodet by měl být zapojen už do přípravy a projektování stavby, ne až do vytyčení.', a: true, e: 'Včasný návrh sítě a rozbor přesnosti předejde nesouladu projektu se skutečností.' },
          { t: 'c', q: 'Dokumentace skutečného provedení stavby obsahuje z geodetické části…', a: 'zaměření dokončené stavby', w: ['původní účelovou mapu', 'návrh vytyčovací sítě', 'kopii katastrální mapy'], e: 'Geodetická část DSPS zachycuje skutečnou polohu stavby a sítí po dokončení.' },
          { t: 'o', q: 'Seřaďte geodetické práce v průběhu stavby', s: ['Mapový podklad pro projekt', 'Vytyčovací výkres a výpočet prvků', 'Vytyčení prostorové polohy stavby', 'Kontrolní měření při výstavbě', 'Zaměření skutečného provedení'], e: 'Geodézie provází stavbu od přípravy až po dokumentaci skutečného stavu.' },
        ],
      },
      {
        id: 'nea030l3', title: 'Vytyčovací sítě', icon: '🕸️', gens: ['errorPropagation'],
        items: [
          { t: 'c', q: 'Pravoúhlá vytyčovací síť rovnoběžná s osami objektů se nazývá…', a: 'stavební (čtvercová) síť', w: ['trigonometrická síť', 'nivelační síť', 'katastrální síť'], e: 'Používá se na rozsáhlých průmyslových areálech; vytyčení se tak zjednoduší na pravoúhlé míry.' },
          { t: 'c', q: 'Místní souřadnicový systém stavby se často volí tak, aby…', a: 'osy byly rovnoběžné s osami stavby', w: ['počátek ležel v Greenwichi', 'osa x mířila k jihu', 'souhlasil se S-JTSK'], e: 'Souřadnice pak přímo odpovídají staničení a odsazení od os objektu.' },
          { t: 'c', q: 'Body vytyčovací sítě se stabilizují…', a: 'trvale a mimo dosah stavby', w: ['dočasně uprostřed výkopu', 'jen barvou na asfalt', 'na pohyblivé mechanizaci'], e: 'Síť musí sloužit po celou dobu výstavby, často i pro sledování posunů.' },
          { t: 'c', q: 'Přesnost navrhované sítě se před měřením posuzuje např. pomocí…', a: 'elips chyb z kovarianční matice', w: ['výšky budov v okolí', 'počtu měřických dnů', 'ceny přístroje'], e: 'Kovarianční matice se spočte z plánovaných měření a jejich vah ještě před jejich pořízením.' },
          { t: 'tf', q: 'Vytyčovací síť se často vyrovnává jako volná nebo s minimem podmínek, aby ji nedeformovaly chyby připojovacích bodů.', a: true, e: 'Pro stavbu je rozhodující vnitřní (relativní) přesnost sítě, ne soulad se státní sítí.' },
          { t: 'c', q: 'Stabilita bodů sítě se během stavby ověřuje…', a: 'opakovaným měřením a porovnáním', w: ['jednorázově před stavbou', 'jen vizuální prohlídkou', 'podle stáří stabilizace'], e: 'Posunutý bod sítě by přenesl chybu do všech bodů od něj vytyčených.' },
          { t: 'c', q: 'Síť pro rozsáhlou liniovou stavbu se dnes obvykle zakládá…', a: 'kombinací GNSS a terestrie', w: ['jen pásmem a úhloměrem', 'jen z leteckých snímků', 'z katastrální mapy'], e: 'GNSS dává rámec na velké vzdálenosti, terestrie zhušťuje a zajistí vysokou lokální přesnost.' },
          { t: 'm', q: 'Spojte typ sítě s jeho využitím', p: [['Stavební síť', 'Průmyslový areál s pravoúhlou zástavbou'], ['Polygonová síť', 'Pořady podél liniové stavby'], ['Síť GNSS', 'Rozsáhlé území bez přímé viditelnosti'], ['Trilaterační síť', 'Síť určená jen měřením délek']] },
        ],
      },
      {
        id: 'nea030l4', title: 'Dopravní stavby', icon: '🛤️', gens: ['arcLength'],
        items: [
          { t: 'c', q: 'Přechodnice se vkládá mezi přímou a kruhový oblouk, aby…', a: 'se křivost měnila plynule', w: ['se zkrátila délka trasy', 'se zjednodušilo vytyčení', 'se zvětšil poloměr oblouku'], e: 'Plynulá změna křivosti znamená plynulý nárůst odstředivého zrychlení.' },
          { t: 'c', q: 'Klotoida je křivka, jejíž křivost roste…', a: 'lineárně s délkou oblouku', w: ['kvadraticky s délkou', 'exponenciálně s délkou', 'nijak – je konstantní'], e: 'Křivost 1/r = l / A² – na začátku 0, na konci přechodnice 1/R.' },
          { t: 'c', q: 'Parametr klotoidy A, poloměr R a délka přechodnice L splňují…', a: 'A² = R · L', w: ['A = R · L', 'A² = R / L', 'A = R + L'], e: 'Parametr A má rozměr délky; volí se podle návrhové rychlosti.' },
          { t: 'n', q: 'Přechodnice (klotoida) délky L = 100 m navazuje na kruhový oblouk R = 400 m. Jaký je parametr A?', a: 200, tol: 0.5, dec: 0, unit: 'm', e: 'A = √(R · L) = √(400 · 100) = 200 m.' },
          { t: 'c', q: 'Výškové (zakružovací) oblouky se na silnicích a železnicích navrhují obvykle jako…', a: 'kružnicové oblouky', w: ['klotoidy', 'kubické paraboly', 'lomené čáry'], e: 'Výškový oblouk zaobluje lom sklonů nivelety; vytyčuje se pořadnicemi od tečen.' },
          { t: 'c', q: 'Normální rozchod železniční koleje je…', a: '1 435 mm', w: ['1 520 mm', '1 000 mm', '1 668 mm'], e: '1 520 mm je široký rozchod (např. Ukrajina), 1 000 mm metrový úzký rozchod.' },
          { t: 'c', q: 'Převýšení koleje v oblouku slouží ke…', a: 'kompenzaci odstředivého zrychlení', w: ['zlepšení odvodnění tratě', 'snížení hluku z provozu', 'zkrácení brzdné dráhy'], e: 'Vnější kolejnice je výš; převýšení se na přechodnici mění plynule (vzestupnice).' },
          { t: 'tf', q: 'Staničení udává vzdálenost bodu od počátku trasy měřenou podél její osy.', a: true, e: 'Zapisuje se např. 2,345 60 km; podrobné body se vytyčují ve staničení a kolmém odsazení.' },
          { t: 'c', q: 'Prostorová poloha koleje se dnes efektivně měří…', a: 'měřicím vozíkem s totální stanicí', w: ['jen pásmem po pražcích', 'nivelační latí po metru', 'z katastrální mapy'], e: 'Vozík měří rozchod a převýšení, stanice nebo GNSS jeho polohu vůči zajišťovacím bodům.' },
        ],
      },
      {
        id: 'nea030l5', title: 'Mosty, památky a průmysl', icon: '🌉', gens: ['stakeoutAccuracy'],
        items: [
          { t: 'c', q: 'Při letmé betonáži mostu se geodeticky sleduje hlavně…', a: 'výšková poloha lamel s nadvýšením', w: ['teplota betonu v lamelách', 'barva pohledového betonu', 'hmotnost bednění'], e: 'Projekt předepisuje nadvýšení, které vyrovná průhyb od vlastní tíhy a dotvarování betonu.' },
          { t: 'tf', q: 'Přesná měření na ocelových mostech se kvůli teplotním deformacím plánují ráno nebo za zatažené oblohy.', a: true, e: 'Jednostranné oslunění konstrukci ohýbá a měření by zachytilo dočasný stav.' },
          { t: 'c', q: 'Při zaměření historického objektu se dnes nejčastěji kombinuje…', a: 'laserové skenování a fotogrammetrie', w: ['jen pásmo a olovnice', 'jen GNSS v režimu RTK', 'jen katastrální mapa'], e: 'Mračno bodů zachytí nepravidelné tvary, snímky dodají texturu a detail.' },
          { t: 'c', q: 'Pasportizace objektu před rekonstrukcí znamená…', a: 'zdokumentování skutečného stavu', w: ['vydání stavebního povolení', 'výpočet ceny rekonstrukce', 'vytyčení nových základů'], e: 'Staré budovy se od původních výkresů často liší; projekt rekonstrukce proto vychází ze zaměření.' },
          { t: 'c', q: 'Rektifikace strojního zařízení znamená…', a: 'uvedení do předepsané polohy', w: ['výměnu opotřebených dílů', 'kalibraci délkoměru', 'natření ochranným nátěrem'], e: 'Geodet změří odchylky od projektované geometrie a montážníci je postupně odstraní.' },
          { t: 'c', q: 'Laserový tracker typicky měří na odražeč typu…', a: 'SMR (kulový reflektor)', w: ['kruhový hranol 360°', 'odrazná fólie', 'nivelační lať'], e: 'Střed kulového reflektoru je vždy ve stejné vzdálenosti od dosedací plochy – měří se tak body na povrchu.' },
          { t: 'c', q: 'Metoda záměrné přímky slouží k určení…', a: 'příčných odchylek od přímky', w: ['nadmořských výšek bodů', 'délky dané přímky', 'azimutu dané přímky'], e: 'Používá se např. pro přímost jeřábových drah nebo osy strojů.' },
          { t: 'tf', q: 'Norma ČSN 73 0420-2 obsahuje mezní vytyčovací odchylky pro různé druhy staveb.', a: true, e: 'Část 1 stanoví základní požadavky a postup, část 2 vytyčovací odchylky.' },
          { t: 'm', q: 'Spojte normu s jejím obsahem', p: [['ČSN 73 0420-1', 'Přesnost vytyčování – základní požadavky'], ['ČSN 73 0420-2', 'Vytyčovací odchylky'], ['ČSN 73 0405', 'Měření posunů stavebních objektů'], ['ČSN ISO 4463', 'Měřické metody ve výstavbě']] },
        ],
      },
    ],
  },

  {
    id: 'nea033', title: 'Geodézie v podzemních prostorách', color: '#78716c', level: 'Ing.', course: 'NEA033', sem: '1. ročník · LS',
    desc: 'Důlní měřictví, gyroteodolit, orientace podzemí, důlní mapy, poddolování, tunely a hornické předpisy.',
    lessons: [
      {
        id: 'nea033l1', title: 'Specifika podzemí', icon: '⛏️',
        items: [
          { t: 'c', q: 'Důlní měřictví se zabývá…', a: 'měřením a dokumentací v dolech', w: ['výhradně měřením tíže', 'evidencí pozemků', 'tvorbou turistických map'], e: 'Zahrnuje orientaci a připojení podzemí, vedení ražeb, důlní mapy i sledování vlivů na povrch.' },
          { t: 'c', q: 'Body v důlních chodbách se často stabilizují…', a: 've stropě jako stropní značky', w: ['v počvě dřevěnými kolíky', 'přímo na kolejích', 'jen křídou na ostění'], e: 'Počva je poškozována dopravou; na stropní bod se přístroj centruje olovnicí.' },
          { t: 'c', q: 'Počva je v hornické terminologii…', a: 'spodní plocha důlního díla', w: ['horní plocha důlního díla', 'boční stěna chodby', 'svislé důlní dílo'], e: 'Horní plocha je strop, boční plochy jsou boky.' },
          { t: 'm', q: 'Spojte hornický pojem s významem', p: [['Jáma', 'Svislé dílo z povrchu'], ['Štola', 'Vodorovné dílo s ústím na povrch'], ['Počva', 'Spodní plocha díla'], ['Strop', 'Horní plocha díla']] },
          { t: 'tf', q: 'V dolech s nebezpečím výbuchu metanu se smějí používat jen přístroje v nevýbušném provedení.', a: true, e: 'Běžná elektronika by mohla jiskrou zapálit výbušnou atmosféru.' },
          { t: 'c', q: 'Polygonové pořady v podzemí bývají obvykle…', a: 'vybíhavé s krátkými stranami', w: ['uzavřené s dlouhými stranami', 'nahrazené měřením GNSS', 'bez nutnosti orientace'], e: 'Pořad postupuje s ražbou; chyby se kumulují, a proto se kontroluje opakováním a gyroskopickou orientací.' },
          { t: 'c', q: 'Proč nelze v podzemí použít GNSS?', a: 'Signál družic neprojde horninou', w: ['Přijímače nesnesou vlhkost', 'Chybí tam S-JTSK', 'Je tam příliš velká tíže'], e: 'Poloha se proto do podzemí převádí terestricky – jámami, štolami a gyroteodolitem.' },
          { t: 'c', q: 'Magnetická orientace se v dolech používá jen omezeně, protože…', a: 'ji ruší ocel a ložiska rud', w: ['v podzemí není magnetické pole', 'buzola nemá dost dílků', 'je zakázána zákonem'], e: 'Výztuž, kolejiště a stroje vytvářejí lokální magnetické anomálie.' },
        ],
      },
      {
        id: 'nea033l2', title: 'Gyroteodolit', icon: '🌀',
        items: [
          { t: 'c', q: 'Na jakém principu gyroteodolit najde sever?', a: 'Setrvačník se vlivem rotace Země staví k poledníku', w: ['Magnetická střelka ukáže k pólu', 'Přístroj přijímá signál z družic', 'Dalekohled se zaměří na Polárku'], e: 'Rychle rotující setrvačník se zavěšením kmitá kolem roviny poledníku.' },
          { t: 'c', q: 'Gyroteodolit určuje směr…', a: 'astronomického poledníku', w: ['magnetického poledníku', 'osy x systému S-JTSK', 'poledníku Ferro'], e: 'Výsledkem je astronomický azimut; pro směrník v S-JTSK je třeba další opravy.' },
          { t: 'c', q: 'Astronomický azimut z gyroteodolitu se na směrník v S-JTSK převede hlavně opravou o…', a: 'meridiánovou konvergenci', w: ['atmosférickou refrakci', 'srážku k elipsoidu', 'excentricitu cíle'], e: 'Přesněji je třeba uvážit i tížnicovou odchylku (Laplaceova oprava).' },
          { t: 'c', q: 'Kmity gyroskopu kolem poledníku se vyhodnocují např. metodou…', a: 'reverzních bodů', w: ['Gaussovy eliminace', 'nejmenší délky', 'dvojího zenitu'], e: 'Poloha rovnovážného směru se odvodí z obratů kmitů; další možností je metoda průchodů.' },
          { t: 'c', q: 'S rostoucí zeměpisnou šířkou přesnost gyroskopu klesá, protože…', a: 'vodorovná složka rotace Země klesá s cos φ', w: ['roste tížnicová odchylka', 'klesá teplota vzduchu', 'roste magnetická deklinace'], e: 'Směrující moment je úměrný ω · cos φ; u pólů je gyroteodolit nepoužitelný.' },
          { t: 'tf', q: 'Kalibrace gyroteodolitu se provádí na základně se známým azimutem před i po měření v podzemí.', a: true, e: 'Určí se přístrojová konstanta a zkontroluje její stálost během měření.' },
          { t: 'tf', q: 'Gyroteodolit potřebuje k orientaci přímou viditelnost na body na povrchu.', a: false, e: 'Právě proto se hodí do podzemí – azimut určí samostatně z rotace Země.' },
          { t: 'o', q: 'Seřaďte kroky gyroskopické orientace strany v podzemí', s: ['Kalibrace na povrchové základně', 'Měření na orientované straně v podzemí', 'Opětovná kalibrace na povrchu', 'Výpočet směrníku s opravami'], e: 'Kalibrace před a po měření odhalí změnu přístrojové konstanty.' },
        ],
      },
      {
        id: 'nea033l3', title: 'Orientace a připojení podzemí', icon: '🧭',
        items: [
          { t: 'c', q: 'Orientace podzemí znamená…', a: 'převod směrníku z povrchu do podzemí', w: ['určení počtu pater dolu', 'výpočet objemu vytěžené horniny', 'měření teploty v jámě'], e: 'Spolu se souřadnicemi se tak podzemní síť připojí k systému na povrchu.' },
          { t: 'c', q: 'Hlavní slabinou orientace jednou jámou dvěma olovnicemi je…', a: 'velmi krátká spojnice olovnic', w: ['příliš velká hmotnost závaží', 'nemožnost měřit délky', 'chybějící výškové připojení'], e: 'Spojnice má jen několik metrů, ale přenáší se z ní orientace pro celý podzemní pořad.' },
          { t: 'c', q: 'Kmity olovnice v jámě se tlumí…', a: 'ponořením závaží do oleje či vody', w: ['přivázáním k výztuži jámy', 'zkrácením drátu na 1 m', 'přidáním magnetu'], e: 'Zbývající kyv se případně vyhodnotí odečítáním krajních poloh.' },
          { t: 'c', q: 'Při orientaci jednou jámou se nahoře i dole měří…', a: 'připojovací trojúhelník', w: ['nivelační pořad', 'výšky hvězd', 'zenitové úhly do jámy'], e: 'Trojúhelník stanovisko–olovnice–olovnice se volí velmi štíhlý, s malým úhlem u stanoviska.' },
          { t: 'c', q: 'Orientace dvěma jámami je přesnější, protože…', a: 'olovnice jsou mnohem dál od sebe', w: ['jámy jsou vždy mělčí', 'nepotřebuje měřit úhly', 'odpadá výškové připojení'], e: 'Mezi jámami se v podzemí vede pořad a spojnice olovnic má délku stovek metrů.' },
          { t: 'c', q: 'Výškové připojení svislou jámou se provádí např….', a: 'měřením délky pásmem či dálkoměrem', w: ['geometrickou nivelací z povrchu', 'odhadem podle hloubky klece', 'magnetickým hloubkoměrem'], e: 'Délka měřená podél jámy se opravuje o teplotu a u pásma i o protažení vlastní tíhou.' },
          { t: 'tf', q: 'Podzemí přístupné štolou lze připojit běžným polygonovým pořadem z povrchu.', a: true, e: 'Štola má ústí na povrchu, takže pořad může plynule pokračovat do podzemí.' },
          { t: 'o', q: 'Seřaďte kroky orientace jednou jámou', s: ['Spuštění dvou olovnic do jámy', 'Uklidnění olovnic', 'Připojovací měření na povrchu a v podzemí', 'Výpočet směrníku a souřadnic v podzemí'], e: 'Olovnice jsou společnými body obou částí – nahoře mají souřadnice, dole se z nich orientuje pořad.' },
        ],
      },
      {
        id: 'nea033l4', title: 'Důlní mapy a poddolování', icon: '🗺️',
        items: [
          { t: 'c', q: 'Důlní mapy jsou součástí…', a: 'důlně měřické dokumentace', w: ['katastrálního operátu', 'státního mapového díla ZM 10', 'územního plánu obce'], e: 'Dokumentují důlní díla, ložiska a stav dobývání a musí se průběžně doplňovat.' },
          { t: 'c', q: 'Poddolování se na povrchu projeví hlavně…', a: 'poklesovou kotlinou', w: ['zvednutím terénu', 'změnou magnetického pole', 'vznikem nových pramenů'], e: 'Nad vyrubaným prostorem vzniká mísovitá sníženina, jejíž okraje sahají za hranu porubu.' },
          { t: 'c', q: 'Hranici území ovlivněného poddolováním vymezuje…', a: 'úhel vlivu (mezní úhel)', w: ['úhel sklonu jámy', 'azimut porubu', 'zenitová vzdálenost'], e: 'Z okraje vyrubaného prostoru se úhlem vlivu vynese hranice poklesové kotliny na povrch.' },
          { t: 'c', q: 'Poměr maximálního poklesu k mocnosti vyrubané sloje se nazývá…', a: 'součinitel poklesu', w: ['úhel vlivu', 'průrazová chyba', 'koeficient refrakce'], e: 'Závisí hlavně na způsobu dobývání – u zakládání je menší než při řízeném závalu.' },
          { t: 'tf', q: 'Pokles povrchu nad vydobytými slojemi může dosáhnout i několika metrů.', a: true, e: 'Např. na Karvinsku vznikly velké poklesy a zatopené poklesové kotliny.' },
          { t: 'c', q: 'Poklesy nad poddolovaným územím se dnes sledují…', a: 'nivelací, GNSS a také InSAR', w: ['jen pohledem z letadla', 'jen katastrální mapou', 'jen měřením tíže'], e: 'Opakovaná nivelace pozorovacích stanic je přesná, InSAR pokryje plošně velké území.' },
          { t: 'c', q: 'Stavby na poddolovaném území kromě poklesu nejvíce poškozují…', a: 'vodorovná přetvoření a náklon', w: ['změny teploty vzduchu', 'magnetické bouře', 'kolísání tíže'], e: 'Tahy a tlaky v terénu trhají základy, náklon ohrožuje vysoké stavby.' },
          { t: 'm', q: 'Spojte deformační veličinu s popisem', p: [['Pokles', 'Svislý posun bodu'], ['Náklon', 'Rozdíl poklesů na jednotku délky'], ['Poměrné přetvoření', 'Protažení či zkrácení na jednotku délky'], ['Zakřivení', 'Ohyb povrchu v kotlině']] },
        ],
      },
      {
        id: 'nea033l5', title: 'Tunely a předpisy', icon: '🚇',
        items: [
          { t: 'c', q: 'Nová rakouská tunelovací metoda (NRTM) využívá…', a: 'nosnou schopnost okolní horniny', w: ['výhradně ocelový štít', 'zmrazování celého masivu', 'hloubení z povrchu'], e: 'Primární ostění (stříkaný beton, kotvy) nechá horninu spolupůsobit; o dalším postupu rozhoduje monitoring.' },
          { t: 'c', q: 'U ražby metodou NRTM se geodeticky sleduje hlavně…', a: 'konvergence (deformace) výrubu', w: ['nadmořská výška portálu', 'magnetická deklinace', 'hustota horniny'], e: '3D měření odrazných terčů na ostění ukazuje, zda se deformace ustalují.' },
          { t: 'c', q: 'TBM je…', a: 'plnoprofilový razicí stroj', w: ['metoda hloubení z povrchu', 'typ gyroteodolitu', 'geotechnický snímač tlaku'], e: 'Tunnel Boring Machine razí celý profil najednou a za sebou osazuje segmentové ostění.' },
          { t: 'c', q: 'Polohu a sklon štítu TBM během ražby určuje…', a: 'navigační systém s totální stanicí', w: ['obsluha odhadem', 'magnetická buzola', 'ruční nivelační přístroj'], e: 'Automatická stanice sleduje terče na stroji a porovnává polohu s projektovanou osou.' },
          { t: 'c', q: 'Která složka průrazové chyby tunelu je nejméně kritická?', a: 'podélná', w: ['příčná', 'výšková', 'všechny jsou stejně kritické'], e: 'Podélná chyba jen mírně změní délku tunelu; příčná a výšková se projeví zalomením osy.' },
          { t: 'tf', q: 'Osa tunelu se v podzemí vytyčuje z polygonového pořadu, který postupuje s ražbou.', a: true, e: 'Pořad se připojuje na portálové body a pravidelně kontroluje, např. gyroskopicky.' },
          { t: 'c', q: 'Zákon č. 61/1988 Sb. upravuje…', a: 'hornickou činnost a báňskou správu', w: ['zeměměřictví a katastr', 'územní plánování', 'ochranu přírody'], e: 'Celý název: o hornické činnosti, výbušninách a o státní báňské správě.' },
          { t: 'c', q: 'Za důlně měřickou činnost v organizaci odpovídá…', a: 'hlavní důlní měřič', w: ['závodní lékař', 'ÚOZI pro katastr', 'stavbyvedoucí'], e: 'Musí mít předepsanou kvalifikaci a jeho činnost podléhá dozoru báňských úřadů.' },
          { t: 'o', q: 'Seřaďte geodetické práce při stavbě tunelu', s: ['Nadzemní síť s portálovými body', 'Připojení a orientace u portálů', 'Vedení ražby podle osy', 'Průraz a určení průrazové chyby', 'Zaměření skutečného stavu'], e: 'Nadzemní síť zajistí, aby se ražby z obou portálů setkaly v tolerancích.' },
        ],
      },
    ],
  },

  {
    id: 'nea034', title: 'Katastr nemovitostí 3', color: '#0369a1', level: 'Ing.', course: 'NEA034', sem: '1. ročník · LS',
    desc: 'Ověřování a druhy geometrických plánů, poskytování údajů, DKM a KMD, vytyčení hranic a opravy chyb.',
    lessons: [
      {
        id: 'nea034l1', title: 'Ověřování GP', icon: '✅', gens: ['areaQuad'],
        items: [
          { t: 'c', q: 'Ověřením GP úředně oprávněný zeměměřický inženýr potvrzuje, že…', a: 'plán odpovídá předpisům i přesností', w: ['vlastníci s plánem souhlasí', 'změna je už zapsána v KN', 'pozemek nemá žádné zástavy'], e: 'ÚOZI ověřuje náležitosti a přesnost výsledku, nikoli právní vztahy.' },
          { t: 'c', q: 'Geometrický plán potvrzuje…', a: 'katastrální úřad', w: ['úředně oprávněný inženýr', 'obecní úřad', 'notář'], e: 'Potvrzení vyjadřuje souhlas s očíslováním parcel; bez něj nelze GP pro zápis použít.' },
          { t: 'c', q: 'Úřední oprávnění k ověřování výsledků zeměměřických činností uděluje…', a: 'Český úřad zeměměřický a katastrální', w: ['katastrální úřad pro kraj', 'Česká komora architektů', 'Ministerstvo pro místní rozvoj'], e: 'Podmínkou je vzdělání, praxe a úspěšná zkouška odborné způsobilosti.' },
          { t: 'c', q: 'Před zpracováním GP si zhotovitel od katastrálního úřadu vyžádá mimo jiné…', a: 'číslo záznamu podrobného měření změn', w: ['číslo listu vlastnictví kupujícího', 'kopii kupní smlouvy', 'územní rozhodnutí'], e: 'Číslo ZPMZ jednoznačně identifikuje dokumentaci výsledků měření.' },
          { t: 'c', q: 'Zkratka SGI znamená…', a: 'soubor geodetických informací', w: ['soubor geografických informací', 'státní geodetický index', 'systém grafické identifikace'], e: 'SGI obsahuje katastrální mapu a souřadnice; SPI (soubor popisných informací) údaje o vlastnících a parcelách.' },
          { t: 'tf', q: 'Ověřený GP lze jako podklad pro zápis do KN použít i bez potvrzení katastrálním úřadem.', a: false, e: 'GP musí být ověřen ÚOZI i potvrzen katastrálním úřadem.' },
          { t: 'c', q: 'Výměra nově vytvořené parcely se v GP počítá z…', a: 'souřadnic lomových bodů', w: ['odměření na papírové mapě', 'odhadu podle ortofota', 'výměry v listu vlastnictví'], e: 'Z měřených souřadnic se určí výměra Gaussovým (L’Huilierovým) vzorcem.' },
          { t: 'm', q: 'Spojte kód kvality podrobného bodu se střední souřadnicovou chybou', p: [['KK 3', '0,14 m'], ['KK 4', '0,26 m'], ['KK 5', '0,50 m']] },
        ],
      },
      {
        id: 'nea034l2', title: 'Druhy GP a složité GP', icon: '📄',
        items: [
          { t: 'c', q: 'Který GP se zpracovává pro novou budovu na pozemku?', a: 'GP pro vyznačení budovy', w: ['GP pro rozdělení pozemku', 'GP pro opravu geometrického určení', 'GP pro doplnění parcel'], e: 'Budova se do KN zapisuje na podkladě GP a listiny (např. kolaudace, souhlas).' },
          { t: 'c', q: 'GP pro vymezení rozsahu věcného břemene k části pozemku…', a: 'nevytváří novou parcelu', w: ['vždy vytvoří novou parcelu', 'mění výměru pozemku', 'ruší původní parcelu'], e: 'Vymezí se jen dotčená část pozemku, parcela zůstává beze změny.' },
          { t: 'c', q: 'Parcela vzniklá rozdělením pozemku dostane…', a: 'nové parcelní číslo, např. 123/2', w: ['stejné číslo jako původní', 'číslo listu vlastnictví', 'číslo záznamu ZPMZ'], e: 'Nové parcely se označují lomeným číslem odvozeným od kmenového čísla.' },
          { t: 'c', q: 'Složitý GP typicky vzniká, když…', a: 'změna zasahuje mnoho parcel a vlastníků', w: ['se mění jen číslo popisné', 'jde o jedinou malou budovu', 'se opravuje překlep v LV'], e: 'Např. liniové stavby, kde se dělí desítky pozemků a zároveň slučují díly.' },
          { t: 'c', q: 'Výkaz dosavadního a nového stavu údajů katastru je součástí…', a: 'geometrického plánu', w: ['listu vlastnictví', 'vytyčovacího protokolu', 'kupní smlouvy'], e: 'Výkaz a srovnávací sestavení parcel propojuje staré a nové parcely a jejich výměry.' },
          { t: 'tf', q: 'Samotný GP stačí k zápisu změny vlastnictví do katastru.', a: false, e: 'GP je jen technický podklad; změna práv se zapisuje na základě listiny (smlouvy, rozhodnutí), jejíž je GP součástí.' },
          { t: 'c', q: 'GP pro opravu geometrického a polohového určení se zpracovává při…', a: 'opravě chyby v katastrální mapě', w: ['prodeji celého pozemku', 'dědickém řízení', 'změně druhu pozemku'], e: 'Opravuje se chybně zobrazená hranice na základě původních výsledků měření.' },
          { t: 'o', q: 'Seřaďte postup zpracování GP', s: ['Vyžádání čísla ZPMZ a podkladů z KÚ', 'Zjišťování průběhu hranic a měření', 'Výpočty a vyhotovení GP', 'Ověření ÚOZI', 'Potvrzení katastrálním úřadem'], e: 'Potvrzení je posledním krokem, teprve pak se GP připojí k listině.' },
        ],
      },
      {
        id: 'nea034l3', title: 'Poskytování údajů a ISKN', icon: '💾',
        items: [
          { t: 'c', q: 'ISKN je…', a: 'informační systém katastru nemovitostí', w: ['integrovaný systém kartografie', 'mezinárodní standard katastru', 'interní seznam katastrálních notářů'], e: 'Centrální systém, ve kterém katastrální úřady vedou údaje o nemovitostech a právech.' },
          { t: 'c', q: 'Bezplatné nahlížení do KN přes internet umožňuje aplikace…', a: 'Nahlížení do katastru nemovitostí', w: ['CZEPOS', 'Registr obyvatel', 'Datová schránka'], e: 'Informativně ukazuje mapu, parcely, vlastníky i stav řízení.' },
          { t: 'c', q: 'Kdo vede katastr nemovitostí na území kraje?', a: 'katastrální úřad s pracovišti', w: ['krajský úřad', 'obecní úřad s rozšířenou působností', 'Zeměměřický úřad'], e: 'Katastrálních úřadů je 14 (pro každý kraj), výkon zajišťují katastrální pracoviště.' },
          { t: 'tf', q: 'Katastr nemovitostí je veřejný seznam – nahlížet do něj a pořizovat výpisy může kdokoli.', a: true, e: 'Omezení platí jen pro některé údaje (např. přehled vlastnictví k osobě).' },
          { t: 'c', q: 'Výměnný formát dat katastru se označuje…', a: 'VFK', w: ['DXF', 'SHP', 'LAS'], e: 'Textový formát s popisnými i geometrickými daty KN pro další zpracování.' },
          { t: 'c', q: 'Který základní registr je těsně propojen s katastrem?', a: 'RÚIAN', w: ['CZEPOS', 'ZABAGED', 'DMR 5G'], e: 'Registr územní identifikace, adres a nemovitostí přebírá údaje o parcelách a budovách z ISKN.' },
          { t: 'c', q: 'Výřez mapy a seznam souřadnic pro zaměření se poskytují jako…', a: 'podklady pro zeměměřické činnosti', w: ['výpis z listu vlastnictví', 'snímek pozemkové knihy', 'informace o ceně pozemku'], e: 'Poskytují se ověřovatelům a zhotovitelům výsledků zeměměřických činností.' },
          { t: 'm', q: 'Spojte část listu vlastnictví s obsahem', p: [['Část A', 'Vlastník a jiný oprávněný'], ['Část B', 'Nemovitosti'], ['Část C', 'Omezení vlastnického práva'], ['Část E', 'Nabývací tituly']] },
        ],
      },
      {
        id: 'nea034l4', title: 'DKM, KMD a obnova map', icon: '🗺️',
        items: [
          { t: 'c', q: 'Digitální katastrální mapa (DKM) vzniká hlavně z…', a: 'výsledků přesného měření', w: ['vektorizace sáhových map', 'leteckého snímkování', 'odhadu podle ortofota'], e: 'Lomové body mají souřadnice v S-JTSK se zpravidla nejvyšší přesností (kód kvality 3).' },
          { t: 'c', q: 'Katastrální mapa digitalizovaná (KMD) vzniká hlavně…', a: 'přepracováním analogových map', w: ['novým mapováním v terénu', 'leteckým laserovým skenováním', 'měřením všech bodů GNSS'], e: 'Rastr mapy se transformuje do S-JTSK a vektorizuje; body mají nižší přesnost.' },
          { t: 'c', q: 'Mapy stabilního katastru mají měřítko…', a: '1 : 2 880', w: ['1 : 2 000', '1 : 5 000', '1 : 1 000'], e: 'Sáhové měřítko: 1 palec na mapě = 40 sáhů ve skutečnosti.' },
          { t: 'tf', q: 'Souřadnice lomových bodů v KMD mají stejnou přesnost jako v DKM.', a: false, e: 'Body KMD pocházejí z digitalizace grafické mapy, a mají proto vyšší (horší) kódy kvality.' },
          { t: 'c', q: 'Obnova katastrálního operátu může proběhnout…', a: 'novým mapováním nebo přepracováním', w: ['jen revizí listů vlastnictví', 'jen na žádost vlastníka', 'pouze leteckým snímkováním'], e: 'Třetí možností je obnova na podkladě výsledků pozemkových úprav.' },
          { t: 'c', q: 'Hlavním přínosem nahrazení starší mapy KM-D mapou DKM nebo KMD je…', a: 'jednotná vektorová mapa v S-JTSK', w: ['zrušení listů vlastnictví', 'změna vlastnických práv', 'nahrazení katastru ortofotem'], e: 'Mapa se převede do jednotného vektorového tvaru s kódy kvality bodů.' },
          { t: 'tf', q: 'Při převodu do KMD se evidovaná výměra parcely automaticky nepřepočítává z nové mapy.', a: true, e: 'Výměra se mění až např. na podkladě GP nebo opravy chyby z přesnějšího měření.' },
          { t: 'm', q: 'Spojte typ katastrální mapy s popisem', p: [['DKM', 'Z přesného měření'], ['KMD', 'Z přepracování sáhových map'], ['KM-D', 'Starší digitalizace k nahrazení'], ['Analogová mapa', 'Na fólii nebo papíře']] },
        ],
      },
      {
        id: 'nea034l5', title: 'Vytyčení hranic a opravy', icon: '🚩', gens: ['stakeout'],
        items: [
          { t: 'c', q: 'Hranice pozemku se vytyčuje podle…', a: 'geometrického určení v katastru', w: ['přání objednatele', 'průběhu stávajícího plotu', 'hranice na ortofotu'], e: 'Vytyčuje se hranice evidovaná v KN, případně z dokumentace výsledků původního měření.' },
          { t: 'c', q: 'K vytyčení hranice je třeba přizvat…', a: 'vlastníky dotčených pozemků', w: ['starostu obce', 'pracovníka katastrálního úřadu', 'notáře'], e: 'Vlastníci mají být včas vyrozuměni, aby se mohli vytyčení zúčastnit.' },
          { t: 'c', q: 'Výsledkem vytyčení hranice je…', a: 'protokol o vytyčení hranice', w: ['geometrický plán', 'výpis z listu vlastnictví', 'rozhodnutí katastrálního úřadu'], e: 'Protokol obsahuje náčrt, způsob označení bodů a vyjádření účastníků.' },
          { t: 'tf', q: 'Vytyčením hranice pozemku se mění vlastnické právo.', a: false, e: 'Vytyčení jen vyznačí v terénu průběh hranice evidovaný v katastru.' },
          { t: 'c', q: 'Nesouhlasí-li soused s vytyčenou hranicí…', a: 'uvede se to v protokolu', w: ['vytyčení se zruší', 'hranici posune ÚOZI', 'katastrální úřad změní mapu'], e: 'Spor o vlastnictví hranice řeší soud; geodet vytyčuje evidovaný stav.' },
          { t: 'c', q: 'Vytyčené lomové body se označují…', a: 'trvalým způsobem (mezník, kolík)', w: ['jen sprejem na trávu', 'pouze v náčrtu', 'provázkem mezi stromy'], e: 'Označení se provede, pokud s ním vlastník souhlasí a je to technicky možné.' },
          { t: 'c', q: 'Opravu chyby v údajích katastru provádí…', a: 'katastrální úřad, i z moci úřední', w: ['ÚOZI bez dalšího řízení', 'soud v každém případě', 'obecní úřad'], e: 'O opravě se vede řízení; podnět může dát i vlastník.' },
          { t: 'c', q: 'Chybou v geometrickém určení nemovitosti je, když…', a: 'mapa neodpovídá původnímu měření', w: ['vlastník prodá pozemek', 'se změní druh pozemku', 'se pozemek zastaví'], e: 'Oprava se provede na podkladě GP pro opravu geometrického a polohového určení.' },
          { t: 'o', q: 'Seřaďte postup vytyčení hranice pozemku', s: ['Získání podkladů z katastrálního úřadu', 'Výpočet vytyčovacích prvků', 'Vytyčení a označení bodů za účasti vlastníků', 'Kontrolní měření', 'Sepsání protokolu o vytyčení'], e: 'Kontrola musí být nezávislá; protokol pak podepisují přítomní vlastníci.' },
        ],
      },
    ],
  },

  {
    id: 'nea031', title: 'Kartografie 2 – tematická', color: '#be185d', level: 'Ing.', course: 'NEA031', sem: '1. ročník · ZS',
    desc: 'Kompozice a generalizace, vyjadřovací prostředky, metody tematické kartografie, klasifikace dat, barvy a atlasy.',
    lessons: [
      {
        id: 'nea031l1', title: 'Kompozice a generalizace', icon: '🧩',
        items: [
          { t: 'c', q: 'Tematická mapa zobrazuje…', a: 'vybraný jev na topografickém podkladu', w: ['jen výškopis území', 'jen hranice katastru', 'úplný topografický obsah'], e: 'Téma (např. hustota zalidnění) je v popředí, podklad slouží k orientaci.' },
          { t: 'c', q: 'Základní kompoziční prvky mapy jsou…', a: 'mapové pole, název, legenda, měřítko', w: ['jen mapové pole a rám', 'jen název a tiráž', 'jen legenda a logo'], e: 'Doplňkové prvky jsou např. tiráž, směrovka, vedlejší mapy a grafy.' },
          { t: 'c', q: 'Topografický podklad tematické mapy má být…', a: 'potlačený, aby nepřebíjel téma', w: ['co nejvýraznější', 'vždy barevný', 'zcela vynechán'], e: 'Podklad se kreslí světle a generalizovaně, aby vynikl tematický obsah.' },
          { t: 'c', q: 'Legenda tematické mapy musí být…', a: 'úplná a shodná se znaky v mapě', w: ['co nejkratší bez ohledu na obsah', 'jen v anglickém jazyce', 'umístěna mimo list mapy'], e: 'Každý znak v mapě musí být vysvětlen, a to ve stejné podobě.' },
          { t: 'tf', q: 'Tiráž mapy obsahuje údaje o autorovi, vydavateli, zdrojích dat a datu vydání.', a: true, e: 'Umožňuje posoudit aktuálnost a věrohodnost mapy.' },
          { t: 'c', q: 'Při zmenšení měřítka se sídla z ploch obvykle převedou na…', a: 'bodové znaky', w: ['izolinie', 'liniové znaky', 'kartodiagramy'], e: 'Jde o změnu dimenze objektu – typickou generalizační operaci.' },
          { t: 'c', q: 'Kartografická generalizace je…', a: 'výběr a zjednodušení obsahu mapy', w: ['změna kartografického zobrazení', 'převod mapy do rastru', 'tisk mapy ve více barvách'], e: 'Odvíjí se od měřítka, účelu mapy a charakteru zobrazovaného jevu.' },
          { t: 'm', q: 'Spojte generalizační operaci s popisem', p: [['Výběr', 'Vypuštění méně významných objektů'], ['Zjednodušení', 'Odstranění drobných zákrutů'], ['Zveličení', 'Zvětšení malého důležitého objektu'], ['Odsun', 'Posunutí kvůli čitelnosti'], ['Sloučení', 'Spojení blízkých objektů']] },
        ],
      },
      {
        id: 'nea031l2', title: 'Vyjadřovací prostředky', icon: '🎨',
        items: [
          { t: 'c', q: 'Mezi Bertinovy vizuální proměnné patří…', a: 'velikost, tvar, barva, světlost', w: ['měřítko, zobrazení, rámec', 'autor, rok, vydavatel', 'šířka, délka, výška papíru'], e: 'Dále orientace a textura (struktura výplně); každá se hodí pro jiný typ dat.' },
          { t: 'c', q: 'Pro kvantitativní (poměrová) data je nejvhodnější proměnná…', a: 'velikost', w: ['tvar', 'barevný tón', 'orientace'], e: 'Velikost intuitivně vyjadřuje „více“ a „méně“, tón a tvar ne.' },
          { t: 'c', q: 'Kvalitativní (nominální) data se nejlépe vyjádří…', a: 'barevným tónem nebo tvarem', w: ['velikostí znaku', 'světlostí barvy', 'tloušťkou čáry'], e: 'Kategorie nemají pořadí, proto se odlišují rovnocennými prostředky.' },
          { t: 'tf', q: 'Světlost barvy vyjadřuje intuitivně pořadí – tmavší znamená více.', a: true, e: 'Proto se v kartogramu používají stupnice od světlé k tmavé.' },
          { t: 'c', q: 'Bodové znaky (signatury) mohou být…', a: 'geometrické, symbolické a obrázkové', w: ['jen kruhové', 'jen písmenné zkratky', 'jen trojrozměrné'], e: 'Geometrické se nejlépe porovnávají velikostí, obrázkové jsou nejsrozumitelnější.' },
          { t: 'c', q: 'Liniové znaky se v tematické mapě používají hlavně pro…', a: 'toky, hranice a komunikace', w: ['hustotu zalidnění', 'rozlohu lesů', 'nadmořské výšky vrcholů'], e: 'Tloušťka čáry může vyjadřovat i kvantitu (např. intenzitu dopravy).' },
          { t: 'c', q: 'Znakový klíč mapy je…', a: 'soubor znaků a jejich významů', w: ['heslo k mapovému serveru', 'měřítko mapy', 'rastr pro tisk'], e: 'V mapě se prezentuje legendou; musí být jednoznačný a srozumitelný.' },
          { t: 'm', q: 'Spojte úroveň měření dat s příkladem', p: [['Nominální', 'Druh půdy'], ['Ordinální', 'Stupeň ohrožení'], ['Intervalová', 'Teplota ve °C'], ['Poměrová', 'Počet obyvatel']] },
        ],
      },
      {
        id: 'nea031l3', title: 'Metody tematické kartografie', icon: '🗾', gens: ['popDensity'],
        items: [
          { t: 'c', q: 'Kartogram zobrazuje…', a: 'relativní hodnoty v plošných jednotkách', w: ['absolutní hodnoty diagramy', 'spojitý jev izoliniemi', 'polohu jednotlivých objektů'], e: 'Např. hustota zalidnění, podíl lesů – hodnoty vztažené k ploše nebo počtu.' },
          { t: 'tf', q: 'V kartogramu je správné vyjádřit absolutní počet obyvatel obcí.', a: false, e: 'Absolutní hodnoty patří do kartodiagramu; v kartogramu by velké obce vypadaly zkresleně.' },
          { t: 'c', q: 'Kartodiagram vyjadřuje…', a: 'absolutní hodnoty diagramy', w: ['jen relativní hodnoty', 'spojitý jev izoliniemi', 'výskyt jevu areálem'], e: 'Diagramy (sloupce, kruhy, výsečové grafy) se umisťují do jednotek.' },
          { t: 'c', q: 'Bodová (tečková) metoda znázorňuje…', a: 'rozmístění jevu tečkami s pevnou vahou', w: ['hustotu barevnou stupnicí', 'průměry v okresech', 'pohyb obyvatel šipkami'], e: 'Každá tečka představuje stejné množství (např. 100 obyvatel) a umisťuje se do místa výskytu.' },
          { t: 'c', q: 'Izolinie jsou vhodné pro jevy…', a: 'spojité, jako teplota či srážky', w: ['nespojité, jako počet škol', 'kvalitativní, jako druh půdy', 'liniové, jako silnice'], e: 'Izolinie spojují místa se stejnou hodnotou – izotermy, izohyety, vrstevnice.' },
          { t: 'c', q: 'Dasymetrická metoda zpřesňuje kartogram tím, že…', a: 'vyloučí neobydlené plochy', w: ['zvětší všechny jednotky', 'nahradí barvy tečkami', 'zruší hranice jednotek'], e: 'Hodnoty se vztáhnou jen k obydleným částem (bez lesů, vod), takže lépe odpovídají skutečnosti.' },
          { t: 'c', q: 'Anamorfóza (kartogram s deformací) mění…', a: 'velikost území podle hodnoty', w: ['barvu podle nadmořské výšky', 'měřítko podle šířky', 'hranice podle katastru'], e: 'Např. státy zvětšené úměrně počtu obyvatel.' },
          { t: 'm', q: 'Spojte metodu s vhodným tématem', p: [['Kartogram', 'Hustota zalidnění'], ['Kartodiagram', 'Počet obyvatel okresů'], ['Izolinie', 'Průměrná roční teplota'], ['Metoda areálů', 'Výskyt chráněného druhu'], ['Bodová metoda', 'Rozmístění obyvatel']] },
        ],
      },
      {
        id: 'nea031l4', title: 'Klasifikace a barvy', icon: '🌈',
        items: [
          { t: 'c', q: 'Klasifikace ekvidistantními intervaly…', a: 'dělí rozsah dat na stejně široké třídy', w: ['dává do tříd stejný počet jednotek', 'hledá mezery v datech', 'používá jen dvě třídy'], e: 'Šířka třídy = (max − min) / počet tříd; nevhodná pro výrazně nesouměrná data.' },
          { t: 'c', q: 'Klasifikace kvantily…', a: 'dává do tříd stejný počet jednotek', w: ['dělí rozsah na stejné intervaly', 'minimalizuje rozptyl uvnitř tříd', 'vychází ze směrodatné odchylky'], e: 'Mapa působí vyváženě, ale podobné hodnoty mohou skončit v různých třídách.' },
          { t: 'c', q: 'Metoda přirozených zlomů (Jenks)…', a: 'minimalizuje rozptyl uvnitř tříd', w: ['dělí rozsah na stejné intervaly', 'dává do tříd stejný počet jednotek', 'volí meze náhodně'], e: 'Hranice tříd leží v „mezerách“ mezi shluky hodnot.' },
          { t: 'n', q: 'Hodnoty v kartogramu jsou od 20 do 180 obyv./km². Jaká je šířka třídy při 4 ekvidistantních třídách?', a: 40, tol: 0.01, dec: 0, unit: 'obyv./km²', e: '(180 − 20) / 4 = 40 – třídy 20–60, 60–100, 100–140, 140–180.' },
          { t: 'c', q: 'Pro data kolem kritické hodnoty (např. přírůstek a úbytek) se hodí…', a: 'divergentní dvoubarevná stupnice', w: ['sekvenční jednobarevná stupnice', 'kvalitativní paleta tónů', 'duhová spektrální stupnice'], e: 'Střed stupnice (nula) je světlý, kladné a záporné hodnoty sytí dvě různé barvy.' },
          { t: 'c', q: 'Sekvenční barevná stupnice v kartogramu…', a: 'mění světlost od světlé po tmavou', w: ['střídá kontrastní barevné tóny', 'používá jen černou a bílou', 'mění barvu náhodně'], e: 'Nejnižší třída je nejsvětlejší, nejvyšší nejtmavší.' },
          { t: 'tf', q: 'Duhová (spektrální) stupnice je pro kvantitativní kartogram vždy nejlepší volbou.', a: false, e: 'Tóny duhy nemají přirozené pořadí a čtenáři s poruchou barvocitu je špatně rozliší.' },
          { t: 'c', q: 'Kartogram mívá obvykle…', a: '4 až 7 tříd', w: ['2 třídy', '15 až 20 tříd', 'přes 30 tříd'], e: 'Více tříd lidské oko v ploše spolehlivě nerozliší.' },
        ],
      },
      {
        id: 'nea031l5', title: 'Dynamika, písmo a atlasy', icon: '📚',
        items: [
          { t: 'c', q: 'Časoprostorovou dynamiku jevu lze v mapě vyjádřit…', a: 'sérií map, animací či šipkami', w: ['jen jedinou statickou mapou', 'jen změnou měřítka', 'jen tiráží mapy'], e: 'Série map ukazuje stavy, animace průběh a pohybové znaky přesuny.' },
          { t: 'c', q: 'Metoda pohybových znaků (vektorů) zobrazuje…', a: 'směr a intenzitu přesunů', w: ['hustotu zalidnění', 'nadmořskou výšku', 'druhy půd'], e: 'Např. migrace, dopravní proudy; šířka šipky vyjadřuje objem.' },
          { t: 'c', q: 'Kartogram změny zobrazuje…', a: 'rozdíl hodnot mezi dvěma obdobími', w: ['změnu měřítka mapy', 'počet změn v legendě', 'změnu zobrazení'], e: 'Typicky s divergentní stupnicí pro nárůst a pokles.' },
          { t: 'c', q: 'Názvy vodních toků a ploch se v mapách tradičně píší…', a: 'modře a skloněným písmem', w: ['červeně a verzálkami', 'černě a tučně', 'zeleně a stojatým písmem'], e: 'Barva a řez písma pomáhají odlišit kategorie popisu (hydrografie, sídla, terén).' },
          { t: 'c', q: 'Popis plošného objektu (např. pohoří) se umisťuje…', a: 'prostrkaně přes plochu objektu', w: ['vždy do levého horního rohu', 'jen do legendy', 'mimo mapové pole'], e: 'Rozložení popisu naznačuje rozsah a průběh objektu.' },
          { t: 'tf', q: 'Popis bodového objektu se přednostně umisťuje vpravo nahoru od znaku.', a: true, e: 'Když tam není místo, volí se další polohy podle ustálených pravidel.' },
          { t: 'c', q: 'Atlas je…', a: 'soubor map s jednotnou koncepcí', w: ['jediná nástěnná mapa', 'rastr ortofota', 'katalog přístrojů'], e: 'Mapy atlasu spojuje účel, obsah a jednotné zpracování (měřítka, znaky, barvy).' },
          { t: 'o', q: 'Seřaďte postup tvorby tematické mapy', s: ['Stanovení účelu a uživatele', 'Sběr a zpracování dat', 'Volba metody a klasifikace', 'Návrh kompozice a znaků', 'Kontrola a vydání'], e: 'Účel mapy určuje všechna další rozhodnutí – od dat po grafiku.' },
        ],
      },
    ],
  },

  {
    id: 'nea035', title: 'Kosmická geodézie 2', color: '#312e81', level: 'Ing.', course: 'NEA035', sem: '1. ročník · LS',
    desc: 'Nebeské souřadnice a čas, pohyby zemské osy, astronomické určování, VLBI, SLR, DORIS, gravitační mise a InSAR.',
    lessons: [
      {
        id: 'nea035l1', title: 'Vesmír a nebeské souřadnice', icon: '🔭',
        items: [
          { t: 'c', q: 'Astronomická jednotka (au) je přibližně…', a: '149,6 milionu km', w: ['9,46 bilionu km', '384 400 km', '3,26 milionu km'], e: 'Střední vzdálenost Země–Slunce; 384 400 km je vzdálenost Měsíce, 9,46 bilionu km světelný rok.' },
          { t: 'c', q: 'Parsek je vzdálenost, ze které…', a: 'je roční paralaxa 1″', w: ['světlo letí jeden rok', 'je Slunce vidět pod 1°', 'je Země vidět pod 1′'], e: 'Poloměr zemské dráhy (1 au) je odtud vidět pod úhlem 1″.' },
          { t: 'c', q: '1 parsek je přibližně…', a: '3,26 světelného roku', w: ['1 světelný rok', '206 265 km', '0,5 světelného roku'], e: '1 pc ≈ 206 265 au ≈ 3,26 ly.' },
          { t: 'c', q: 'Obzorníkové souřadnice hvězdy jsou…', a: 'azimut a výška', w: ['rektascenze a deklinace', 'hodinový úhel a deklinace', 'ekliptikální délka a šířka'], e: 'Závisí na místě a čase pozorování; místo výšky se používá i zenitová vzdálenost z = 90° − h.' },
          { t: 'c', q: 'Rektascenze se měří od…', a: 'jarního bodu', w: ['místního poledníku', 'severního světového pólu', 'podzimního bodu'], e: 'Rektascenze a deklinace (2. rovníková soustava) nezávisí na rotaci Země.' },
          { t: 'c', q: 'Hodinový úhel t, místní hvězdný čas s a rektascenze α spojuje vztah…', a: 't = s − α', w: ['t = α − s', 't = s + α', 't = s · α'], e: 'Hvězdný čas je hodinový úhel jarního bodu; hvězda s α = s právě kulminuje (t = 0).' },
          { t: 'tf', q: 'Výška světového pólu nad obzorem je rovna astronomické šířce pozorovatele.', a: true, e: 'Proto šlo šířku přibližně určit z výšky Polárky.' },
          { t: 'm', q: 'Spojte souřadnicovou soustavu se souřadnicemi', p: [['Obzorníková', 'A, h'], ['1. rovníková', 't, δ'], ['2. rovníková', 'α, δ'], ['Ekliptikální', 'λ, β']] },
        ],
      },
      {
        id: 'nea035l2', title: 'Čas a pohyby zemské osy', icon: '⏳',
        items: [
          { t: 'c', q: 'Hvězdný den je kratší než střední sluneční den asi o…', a: '3 min 56 s', w: ['4 h', '56 s', '12 min'], e: 'Země za den urazí asi 1° po dráze kolem Slunce a musí se pootočit o kousek víc.' },
          { t: 'c', q: 'Čas UT1 je odvozen ze…', a: 'skutečné rotace Země', w: ['sítě atomových hodin', 'pohybu Měsíce', 'hodin družic GPS'], e: 'Rotace Země je nepravidelná, proto UT1 nerovnoměrně ubíhá vůči atomovému času.' },
          { t: 'c', q: 'Rozdíl TAI − UTC v současnosti činí…', a: '37 s', w: ['18 s', '19 s', '0 s'], e: 'Od roku 2017; GPS − UTC = 18 s a TAI − GPS = 19 s.' },
          { t: 'c', q: 'Přestupná sekunda se do UTC vkládá, aby…', a: '|UT1 − UTC| nepřekročilo 0,9 s', w: ['GPS a UTC byly shodné', 'TAI zůstal konstantní', 'hvězdný čas byl roven UTC'], e: 'UTC tak ubíhá atomovými sekundami, ale drží se rotace Země.' },
          { t: 'tf', q: 'Rotace Země je dokonale rovnoměrná, takže délka dne je konstantní.', a: false, e: 'Délka dne kolísá o milisekundy (atmosféra, oceány, slapy, jádro).' },
          { t: 'tf', q: 'Precese je způsobena působením Slunce a Měsíce na zploštělou Zemi.', a: true, e: 'Slapové síly se snaží „narovnat“ rovníkovou výduť do roviny ekliptiky – osa proto opisuje kužel.' },
          { t: 'm', q: 'Spojte jev s jeho periodou', p: [['Precese', '≈ 25 800 let'], ['Hlavní člen nutace', '18,6 roku'], ['Chandlerův pohyb pólu', '≈ 433 dní'], ['Hvězdný den', '23 h 56 min 4 s']] },
          { t: 'c', q: 'Parametry orientace Země (pohyb pólu, UT1 − UTC) publikuje…', a: 'IERS', w: ['IGS', 'EUREF', 'ČÚZK'], e: 'International Earth Rotation and Reference Systems Service kombinuje VLBI, SLR, GNSS a DORIS.' },
          { t: 'c', q: 'Okamžitý pól se od konvenčního pólu vzdaluje řádově o…', a: 'jednotky metrů', w: ['desítky kilometrů', 'milimetry', 'stovky metrů'], e: 'Desetiny úhlové vteřiny odpovídají na povrchu Země několika metrům.' },
        ],
      },
      {
        id: 'nea035l3', title: 'Zdánlivé polohy a astronomické určování', icon: '✨',
        items: [
          { t: 'c', q: 'Roční paralaxa nejbližší hvězdy (Proxima Centauri) je asi…', a: '0,77″', w: ['7,7″', '0,077″', '77″'], e: 'Vzdálenost je tedy asi 1 / 0,77 ≈ 1,3 pc ≈ 4,2 světelného roku.' },
          { t: 'c', q: 'Roční aberace je způsobena…', a: 'pohybem Země a konečnou rychlostí světla', w: ['ohybem světla v atmosféře', 'precesí zemské osy', 'vlastním pohybem hvězdy'], e: 'Poměr rychlosti Země (≈ 30 km/s) a rychlosti světla dává posun až asi 20,5″.' },
          { t: 'c', q: 'Konstanta roční aberace je přibližně…', a: '20,5″', w: ['0,77″', '8,8″', '60″'], e: '8,8″ je sluneční paralaxa, 0,77″ paralaxa Proximy.' },
          { t: 'c', q: 'Astronomická refrakce…', a: 'zvětšuje zdánlivou výšku hvězdy', w: ['zmenšuje zdánlivou výšku hvězdy', 'nemá na výšku vliv', 'mění jen azimut hvězdy'], e: 'V zenitu je nulová, u obzoru dosahuje asi 35′ – proto se nízké hvězdy nepozorují.' },
          { t: 'c', q: 'Vlastní pohyb hvězdy je…', a: 'její skutečný pohyb po obloze', w: ['odraz pohybu Země kolem Slunce', 'důsledek refrakce', 'důsledek rotace Země'], e: 'Hvězdné katalogy proto udávají polohu k epoše spolu s vlastním pohybem.' },
          { t: 'c', q: 'Pro astronomické určení azimutu se tradičně pozoruje Polárka, protože…', a: 'je blízko pólu a pohybuje se pomalu', w: ['je nejjasnější hvězdou oblohy', 'leží přesně v zenitu', 'nemá žádnou paralaxu'], e: 'Její azimut se v čase mění pomalu, takže chyba v čase má malý vliv.' },
          { t: 'tf', q: 'K astronomickému určení zeměpisné délky je nutné znát přesný čas.', a: true, e: 'Délka je rozdíl místního a greenwichského hvězdného času; chyba 1 s času dává 15″ délky.' },
          { t: 'n', q: 'Hvězda s deklinací δ = 40° kulminuje jižně od zenitu se zenitovou vzdáleností z = 9,5°. Jaká je astronomická šířka?', a: 49.5, tol: 0.01, dec: 2, unit: '°', e: 'Při horní kulminaci jižně od zenitu je z = φ − δ, tedy φ = δ + z = 40° + 9,5° = 49,5°.' },
          { t: 'c', q: 'Moderním přístrojem pro určení astronomických souřadnic je…', a: 'digitální zenitová kamera', w: ['nivelační přístroj', 'gyroteodolit', 'laserový skener'], e: 'Snímkuje hvězdy kolem zenitu kamerou CCD a z polohy tížnice určí Φ a Λ.' },
        ],
      },
      {
        id: 'nea035l4', title: 'VLBI, SLR a DORIS', icon: '📡', gens: ['pseudorange'],
        items: [
          { t: 'c', q: 'VLBI pozoruje…', a: 'rádiové signály vzdálených kvasarů', w: ['laserové odrazy od družic', 'signály družic GPS', 'viditelné světlo hvězd'], e: 'Kvasary jsou tak daleko, že představují prakticky nehybné body – základ rámce ICRF.' },
          { t: 'c', q: 'Základní měřenou veličinou VLBI je…', a: 'zpoždění příchodu signálu mezi anténami', w: ['Dopplerův posun kmitočtu', 'doba letu laserového pulzu', 'tíhové zrychlení'], e: 'Ze zpoždění na dlouhých základnách se určí délka základny i orientace Země.' },
          { t: 'c', q: 'Parametr, který spolehlivě určuje jen VLBI, je…', a: 'UT1 (rotace Země vůči kvasarům)', w: ['výška geoidu nad elipsoidem', 'hmotnost Země', 'polohový rozdíl dvou GNSS bodů'], e: 'Družicové techniky nemají vazbu na inerciální prostor kvasarů, proto UT1 samy neurčí.' },
          { t: 'c', q: 'SLR (Satellite Laser Ranging) měří…', a: 'dobu letu pulzu k družici a zpět', w: ['fázi signálu z kvasaru', 'Dopplerův posun rádiového signálu', 'gradient tíhového pole'], e: 'Družice nesou koutové odražeče, pozemní stanice vysílá krátké laserové pulzy.' },
          { t: 'n', q: 'Laserový pulz se od družice vrátil za 40,000 ms. Jaká je vzdálenost družice? (c = 299 792 458 m/s)', a: 5996, tol: 1, dec: 0, unit: 'km', e: 'd = c · t / 2 = 299 792,458 km/s · 0,040 s / 2 ≈ 5 996 km.' },
          { t: 'c', q: 'Družice LAGEOS jsou…', a: 'pasivní koule s koutovými odražeči', w: ['aktivní družice s radarem', 'navigační družice GNSS', 'geostacionární meteodružice'], e: 'Hustá kovová koule na vysoké dráze má stabilní, dobře modelovatelnou dráhu.' },
          { t: 'c', q: 'Systém DORIS je založen na…', a: 'Dopplerově posunu signálu pozemních majáků', w: ['laserovém měření z Měsíce', 'interferometrii kvasarů', 'měření tíže gradiometrem'], e: 'Majáky vysílají na zemi, přijímač je na družici (např. altimetrické mise).' },
          { t: 'tf', q: 'SLR je nejdůležitější technikou pro určení počátku (geocentra) ITRF.', a: true, e: 'Dráhy družic LAGEOS jsou citlivé na těžiště Země; VLBI geocentrum určit nedokáže.' },
          { t: 'm', q: 'Spojte techniku s jejím principem', p: [['VLBI', 'Rádiové vlny z kvasarů'], ['SLR', 'Laserové pulzy k družici'], ['DORIS', 'Dopplerův posun z majáků'], ['GNSS', 'Kódová a fázová měření z družic']] },
        ],
      },
      {
        id: 'nea035l5', title: 'Altimetrie, gravitační mise a InSAR', icon: '🛰️', gens: ['orbitPeriod'],
        items: [
          { t: 'c', q: 'Družicová altimetrie měří…', a: 'výšku družice nad hladinou oceánu', w: ['tíhové zrychlení na dráze', 'zpoždění signálu z kvasaru', 'posuny pevniny radarem'], e: 'Z přesné dráhy a naměřené výšky se odvodí výška hladiny moře a přes ni i geoid.' },
          { t: 'c', q: 'Mise GRACE určovala tíhové pole z…', a: 'změn vzdálenosti dvou družic', w: ['gradiometru na palubě', 'altimetru nad oceány', 'laserových odrazů z Měsíce'], e: 'Dvojice družic letí za sebou a mikrovlnně měří vzájemnou vzdálenost (low-low SST).' },
          { t: 'c', q: 'Hlavním přístrojem mise GOCE byl…', a: 'gradiometr', w: ['altimetr', 'radar se syntetickou aperturou', 'laserový odražeč'], e: 'Gradiometr měřil druhé derivace tíhového potenciálu – detailní statický geoid.' },
          { t: 'c', q: 'Družice CHAMP určovala tíhové pole hlavně…', a: 'sledováním dráhy z družic GPS', w: ['měřením vzdálenosti dvou družic', 'gradiometrií', 'altimetrií nad oceány'], e: 'High-low SST: nízká družice je sledována vysoko letícími družicemi GPS.' },
          { t: 'tf', q: 'GRACE umožnila sledovat v čase změny zásob vody a úbytek ledovců.', a: true, e: 'Měsíční modely tíhového pole ukazují přesuny hmot, např. tání Grónska.' },
          { t: 'c', q: 'InSAR určuje deformace povrchu z…', a: 'fázových rozdílů radarových snímků', w: ['barev optických snímků', 'doby letu laseru', 'změn tíže na povrchu'], e: 'Fázový rozdíl dvou snímků téhož území vyjadřuje změnu vzdálenosti k radaru.' },
          { t: 'c', q: 'Diferenční InSAR měří posun ve směru…', a: 'záměry radaru (LOS)', w: ['vždy jen svislém', 'severu a jihu', 'kolmém k dráze letu'], e: 'Kombinací vzestupné a sestupné dráhy lze posun rozložit do více složek.' },
          { t: 'c', q: 'Družice Sentinel-1 nesou radar v pásmu…', a: 'C', w: ['L', 'X', 'Ka'], e: 'Pásmo C (≈ 5,6 cm) je kompromisem mezi citlivostí a průnikem vegetací.' },
          { t: 'o', q: 'Seřaďte kroky zpracování diferenčního InSAR', s: ['Pořízení dvou snímků SAR', 'Koregistrace snímků', 'Tvorba interferogramu', 'Odečtení vlivu topografie (DMR)', 'Rozbalení fáze a převod na posun'], e: 'Po odečtení topografie zbývá fáze deformace, atmosféry a šumu.' },
        ],
      },
    ],
  },
];
